In [1]:
# import nbformat
# from google.colab import files

# nb_path = "/content/drive/MyDrive/Colab Notebooks/MS4_YOLO_combined_original_plus_augmented_fft_cp.ipynb"   # change to your notebook name

# nb = nbformat.read(nb_path, as_version=4)

# # 🔥 Remove widget metadata ONLY
# if "widgets" in nb["metadata"]:
#     del nb["metadata"]["widgets"]

# nbformat.write(nb, nb_path)

# print("✅ Cleaned notebook (outputs preserved)")

# files.download(nb_path)

# YOLO Sweep Winner: Final Retrain

**Configuration source:** W&B Bayesian sweep `zzovt4eb`, winning run `volcanic-sweep-2`.

Sweep mAP50 = 0.6697 (in 20 epochs). This notebook retrains the same hyperparameter combination for 50 epochs to push the final number higher.

**Winning hyperparameters:**
- `lr0=0.000173`, `weight_decay=7.2e-5`
- `box=12`, `cls=0.515`, `dfl=1.29` (loss weights)
- `mosaic=0.325`, `copy_paste=0.0086`, `close_mosaic=29` (augmentation)
- `optimizer=AdamW`, `imgsz=1024`, `batch=8`, `seed=42`

Pulled from the leaderboard at https://wandb.ai/rpatel9/hair-follicle-density-estimation-209b-MS4_sweep/sweeps/zzovt4eb

In [2]:
# Install dependencies (no-op if already installed)
import subprocess, sys
for pkg in ['ultralytics', 'albumentations', 'opencv-python', 'scipy', 'scikit-learn', 'tqdm']:
    try:
        __import__(pkg.replace('-', '_').split('[')[0])
    except ImportError:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', pkg], check=False)

In [3]:
import os
import shutil
import random
import yaml
import json
import xml.etree.ElementTree as ET
from dataclasses import dataclass, replace
from typing import List, Dict, Any, Optional, Tuple
from collections import Counter
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw
from tqdm.auto import tqdm

from ultralytics import YOLO
from torchvision.ops import box_iou
from scipy.optimize import linear_sum_assignment
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

In [4]:
# Mount Google Drive (Colab only) or use local data on Lambda/Mac
import os
IS_COLAB = os.path.exists('/content') and 'COLAB_GPU' in os.environ

if IS_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    # Copy data from Drive to runtime
    if not os.path.exists('/content/data/Images'):
        os.system('cp -r /content/drive/MyDrive/data /content/')
else:
    print(f'Not in Colab — using local data at {os.path.expanduser("~/hair-follicle-density-estimation-209b/data")}')

Not in Colab — using local data at /home/ubuntu/hair-follicle-density-estimation-209b/data

##  Configuration

In [5]:
from dataclasses import dataclass, replace, field
import os

def _default_data_paths():
    candidates = [
        '/content/data',
        os.path.expanduser('~/hair-follicle-density-estimation-209b/data'),
        'data', '../data',
    ]
    for base in candidates:
        if os.path.exists(os.path.join(base, 'Images')):
            return base
    return '/content/data'

def _default_drive_dir():
    if os.path.exists('/content/drive/MyDrive'):
        return '/content/drive/MyDrive/yolo_follicle_sweep_winner'
    repo = os.path.expanduser('~/hair-follicle-density-estimation-209b')
    if os.path.exists(repo):
        return os.path.join(repo, 'MS4/checkpoints/yolo_sweep_winner_runs')
    return 'MS4/checkpoints/yolo_sweep_winner_runs'

_DATA_BASE = _default_data_paths()
_DRIVE_DIR = _default_drive_dir()

@dataclass
class Config:
    image_dir: str = field(default_factory=lambda: os.path.join(_DATA_BASE, 'Images'))
    annot_dir: str = field(default_factory=lambda: os.path.join(_DATA_BASE, 'Annotations'))
    split_dir: str = field(default_factory=lambda: os.path.join(_DATA_BASE, 'ImageSets', 'Main'))
    yolo_root: str = '/tmp/yolo_follicle_dataset'
    drive_dir: str = field(default_factory=lambda: _DRIVE_DIR)
    run_name: str = 'yolo_sweep_winner_50ep'
    pretrained_model_name: str = 'yolo11m.pt'
    class_names: Optional[List[str]] = None

    image_size: int = 1024
    epochs: int = 50
    batch: int = 8
    workers: int = 2
    seed: int = 42
    patience: int = 25

    map_conf_threshold: float = 0.001
    val_iou_threshold: float = 0.70
    max_det: int = 1000

    use_light_manual_balancer: bool = True
    balance_target_classes: tuple = (2, 3)
    paste_buffer_px: int = 10
    paste_attempts: int = 40
    min_crop_area: int = 16
    feather_ksize: int = 15
    undersize_pastes_per_image: int = 1
    abnormal_pastes_per_image: int = 2

    add_fft_edge_augmented_copy: bool = True
    rebuild_dataset: bool = True
    fft_edge_replace_prob: float = 0.25

common_cfg = Config()
if common_cfg.class_names is None:
    common_cfg.class_names = ['premium', 'single', 'undersize', 'abnormal']

label2id = {name: i for i, name in enumerate(common_cfg.class_names)}
id2label = {i: name for name, i in label2id.items()}
CLASS_NAMES = common_cfg.class_names

def set_seed(seed: int = 42):
    import random
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)

set_seed(common_cfg.seed)
os.makedirs(common_cfg.drive_dir, exist_ok=True)
print(f'image_dir: {common_cfg.image_dir}')
print(f'drive_dir: {common_cfg.drive_dir}')
print(f'label2id: {label2id}')

image_dir: /home/ubuntu/hair-follicle-density-estimation-209b/data/Images
drive_dir: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs
label2id: {'premium': 0, 'single': 1, 'undersize': 2, 'abnormal': 3}

## Train/validation split

In [6]:
def read_split_txt(path: str) -> List[str]:
    with open(path) as f:
        return [line.strip() for line in f.readlines() if line.strip()]

train_files = read_split_txt(os.path.join(common_cfg.split_dir, "train.txt"))
val_files = read_split_txt(os.path.join(common_cfg.split_dir, "val.txt"))

print("train:", len(train_files))
print("val:", len(val_files))
print("example train file stem:", train_files[0] if train_files else None)

train: 992
val: 330
example train file stem: 220106_A207_2

## VOC parsing, YOLO box utilities, YAML creation, and sanity checks

In [7]:
def find_image_path(image_dir: str, stem: str) -> Optional[str]:
    for ext in [".jpg", ".jpeg", ".png", ".JPG", ".JPEG", ".PNG"]:
        p = os.path.join(image_dir, stem + ext)
        if os.path.exists(p):
            return p
    return None


def clip_box_xyxy(box, width, height):
    x1, y1, x2, y2 = box
    x1 = max(0.0, min(float(x1), width - 1))
    y1 = max(0.0, min(float(y1), height - 1))
    x2 = max(0.0, min(float(x2), width - 1))
    y2 = max(0.0, min(float(y2), height - 1))
    return [x1, y1, x2, y2]


def is_valid_xyxy(box):
    box = np.asarray(box, dtype=float)
    x1, y1, x2, y2 = box
    return np.isfinite(box).all() and (x2 > x1) and (y2 > y1)


def xyxy_to_yolo(box, width, height):
    x1, y1, x2, y2 = box
    cx = ((x1 + x2) / 2.0) / width
    cy = ((y1 + y2) / 2.0) / height
    bw = (x2 - x1) / width
    bh = (y2 - y1) / height
    return [cx, cy, bw, bh]


def parse_voc_xml(xml_path: str, label2id: Dict[str, int]) -> Dict[str, Any]:
    tree = ET.parse(xml_path)
    root = tree.getroot()
    filename = root.findtext("filename")
    size = root.find("size")

    width = int(size.findtext("width")) if size is not None and size.findtext("width") else None
    height = int(size.findtext("height")) if size is not None and size.findtext("height") else None

    objects = []
    for obj in root.findall("object"):
        label_name = obj.findtext("name") or obj.findtext("class")
        if label_name is None:
            continue
        label_name = label_name.strip()
        if label_name not in label2id:
            print(f"Skipping unknown class {label_name} in {xml_path}")
            continue

        bnd = obj.find("bndbox")
        if bnd is None:
            continue

        x1 = float(bnd.findtext("xmin"))
        y1 = float(bnd.findtext("ymin"))
        x2 = float(bnd.findtext("xmax"))
        y2 = float(bnd.findtext("ymax"))

        # Fix inverted coordinates if present
        x1, x2 = sorted([x1, x2])
        y1, y2 = sorted([y1, y2])

        box = [x1, y1, x2, y2]
        if width is not None and height is not None:
            box = clip_box_xyxy(box, width, height)

        if not is_valid_xyxy(box):
            continue

        objects.append({
            "class_name": label_name,
            "class_id": label2id[label_name],
            "bbox_xyxy": box,
        })

    return {"filename": filename, "width": width, "height": height, "objects": objects}

def yolo_to_xyxy(box, width, height):
    """Convert normalized YOLO cx cy w h to absolute xyxy."""
    cx, cy, bw, bh = box
    cx *= width
    cy *= height
    bw *= width
    bh *= height
    return [cx - bw / 2, cy - bh / 2, cx + bw / 2, cy + bh / 2]


def safe_yolo_line(cls_id: int, box_xyxy, w: int, h: int) -> Optional[str]:
    box = clip_box_xyxy(box_xyxy, w, h)
    if not is_valid_xyxy(box):
        return None
    vals = xyxy_to_yolo(box, w, h)
    vals = [min(max(float(v), 0.0), 1.0) for v in vals]
    if vals[2] <= 0 or vals[3] <= 0:
        return None
    return f"{cls_id} " + " ".join(f"{v:.6f}" for v in vals)


def reset_dir(path: str):
    if os.path.exists(path):
        shutil.rmtree(path)
    os.makedirs(path, exist_ok=True)


def create_yolo_data_yaml(cfg: Config):
    data_yaml = {
        "path": cfg.yolo_root,
        "train": "images/train",
        "val": "images/val",
        "names": id2label,
    }
    yaml_path = os.path.join(cfg.yolo_root, "data.yaml")
    with open(yaml_path, "w") as f:
        yaml.safe_dump(data_yaml, f, sort_keys=False)
    print(yaml_path)
    print(open(yaml_path).read())
    return yaml_path


def summarize_yolo_labels(label_dir: str):
    counts = Counter()
    bad_rows = []
    files = list(Path(label_dir).glob("*.txt"))
    for lab in files:
        with open(lab) as f:
            for row_idx, line in enumerate(f):
                parts = line.strip().split()
                if not parts:
                    continue
                if len(parts) != 5:
                    bad_rows.append((str(lab), row_idx, line.strip(), "wrong column count"))
                    continue
                cls = int(float(parts[0]))
                vals = list(map(float, parts[1:]))
                if cls not in id2label:
                    bad_rows.append((str(lab), row_idx, line.strip(), "bad class id"))
                if any(v < 0 or v > 1 for v in vals):
                    bad_rows.append((str(lab), row_idx, line.strip(), "box value outside 0..1"))
                if vals[2] <= 0 or vals[3] <= 0:
                    bad_rows.append((str(lab), row_idx, line.strip(), "non-positive width/height"))
                counts[cls] += 1
    return counts, bad_rows


def print_label_summary(cfg: Config):
    for split in ["train", "val"]:
        counts, bad = summarize_yolo_labels(os.path.join(cfg.yolo_root, "labels", split))
        print("", split)
        print({id2label[k]: v for k, v in sorted(counts.items())})
        print("bad rows:", len(bad))
        if bad[:5]:
            print(bad[:5])


def draw_yolo_label_file(image_path, label_path, id2label, color="green"):
    image = Image.open(image_path).convert("RGB")
    W, H = image.size
    draw = ImageDraw.Draw(image)
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue
                cls = int(parts[0])
                box = list(map(float, parts[1:]))
                x1, y1, x2, y2 = yolo_to_xyxy(box, W, H)
                draw.rectangle([x1, y1, x2, y2], outline=color, width=2)
                draw.text((x1, y1), id2label[cls], fill=color)
    return image

## Baseline dataset builder

In [8]:
def convert_split_to_yolo_clean(split_name: str, stems: List[str], cfg: Config):
    """Baseline conversion: original RGB images + original VOC boxes only."""
    img_out = os.path.join(cfg.yolo_root, "images", split_name)
    lab_out = os.path.join(cfg.yolo_root, "labels", split_name)
    os.makedirs(img_out, exist_ok=True)
    os.makedirs(lab_out, exist_ok=True)

    skipped = []
    invalid = []
    class_counter = Counter()
    box_counter = 0

    for stem in tqdm(stems, desc=f"Creating baseline {split_name} set"):
        xml_path = os.path.join(cfg.annot_dir, stem + ".xml")
        img_path = find_image_path(cfg.image_dir, stem)

        if not os.path.exists(xml_path) or img_path is None:
            skipped.append(stem)
            continue

        image = Image.open(img_path).convert("RGB")
        W, H = image.size
        parsed = parse_voc_xml(xml_path, label2id)

        out_img_path = os.path.join(img_out, os.path.basename(img_path))
        shutil.copy2(img_path, out_img_path)

        out_label_path = os.path.join(lab_out, stem + ".txt")
        lines = []
        for obj in parsed["objects"]:
            line = safe_yolo_line(obj["class_id"], obj["bbox_xyxy"], W, H)
            if line is None:
                invalid.append((stem, obj))
                continue
            lines.append(line)
            class_counter[obj["class_id"]] += 1
            box_counter += 1

        with open(out_label_path, "w") as f:
            f.write("\n".join(lines))

    return {
        "split": split_name,
        "images": len(stems) - len(skipped),
        "skipped": skipped,
        "invalid": invalid,
        "boxes": box_counter,
        "class_counter": dict(class_counter),
    }


def create_baseline_dataset(cfg: Config, train_files: List[str], val_files: List[str]):
    """Create baseline YOLO dataset without image enhancement or manual copy-paste."""
    if cfg.rebuild_dataset or not os.path.exists(cfg.yolo_root):
        reset_dir(cfg.yolo_root)
        train_stats = convert_split_to_yolo_clean("train", train_files, cfg)
        val_stats = convert_split_to_yolo_clean("val", val_files, cfg)
    else:
        train_stats = val_stats = None
    yaml_path = create_yolo_data_yaml(cfg)
    print("train_stats:", train_stats)
    print("val_stats:", val_stats)
    print_label_summary(cfg)
    return yaml_path, train_stats, val_stats

## Enhanced image preprocessing

In [9]:
def apply_enhancement(img_bgr: np.ndarray) -> np.ndarray:
    """
    Follicle-friendly enhancement:
    1. CLAHE on luminance for local contrast
    2. Canny edge detail blended lightly
    3. FFT high-pass detail blended lightly

    Returns a 3-channel BGR uint8 image.
    """
    if img_bgr is None:
        raise ValueError("apply_enhancement received None image")

    # CLAHE on luminance
    lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)
    L, A, B = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    L_eq = clahe.apply(L)

    # Edge enhancement
    edges = cv2.Canny(L_eq, threshold1=40, threshold2=120)
    edges_blur = cv2.GaussianBlur(edges, (3, 3), 0)

    # FFT high-pass enhancement on luminance
    f = np.fft.fft2(L_eq.astype(np.float32))
    fshift = np.fft.fftshift(f)
    rows, cols = L_eq.shape
    crow, ccol = rows // 2, cols // 2
    radius = max(4, min(rows, cols) // 18)

    mask = np.ones((rows, cols), np.float32)
    cv2.circle(mask, (ccol, crow), radius, 0, thickness=-1)

    fshift_hp = fshift * mask
    img_back = np.fft.ifft2(np.fft.ifftshift(fshift_hp))
    hp = np.abs(img_back)
    hp = cv2.normalize(hp, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    # Blend: keep subtle to avoid creating artificial objects
    L_enh = cv2.addWeighted(L_eq, 1.00, edges_blur, 0.15, 0)
    L_enh = cv2.addWeighted(L_enh, 0.90, hp, 0.10, 0)
    L_enh = np.clip(L_enh, 0, 255).astype(np.uint8)

    enhanced_lab = cv2.merge([L_enh, A, B])
    enhanced_bgr = cv2.cvtColor(enhanced_lab, cv2.COLOR_LAB2BGR)
    return enhanced_bgr

## Enhanced training augmentation builder

This builder keeps original training images, adds copy-paste + FFT/edge-enhanced augmented training copies, and keeps validation images untouched.

In [10]:

def is_overlapping(new_box, existing_boxes, buffer=10):
    """Return True when new_box overlaps or is too close to any existing box."""
    nx1, ny1, nx2, ny2 = map(float, new_box)
    for ex1, ey1, ex2, ey2 in existing_boxes:
        if not (
            nx2 + buffer < ex1 or
            nx1 - buffer > ex2 or
            ny2 + buffer < ey1 or
            ny1 - buffer > ey2
        ):
            return True
    return False


def make_feather_mask(h: int, w: int, feather_ksize: int = 15) -> np.ndarray:
    """Create a soft rectangular alpha mask so pasted crops do not have hard borders."""
    k = int(feather_ksize)
    if k % 2 == 0:
        k += 1
    k = max(3, k)

    margin = max(2, k // 2)
    mask = np.zeros((h, w), dtype=np.float32)
    cv2.rectangle(
        mask,
        (margin, margin),
        (max(margin, w - margin - 1), max(margin, h - margin - 1)),
        1.0,
        -1,
    )
    mask = cv2.GaussianBlur(mask, (k, k), 0)
    mask = np.clip(mask, 0.0, 1.0)
    return mask[:, :, None]


def match_crop_brightness(crop_bgr: np.ndarray, background_roi_bgr: np.ndarray) -> np.ndarray:
    """Lightly match crop luminance to the target background ROI to reduce pasted-patch artifacts."""
    crop_lab = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2LAB).astype(np.float32)
    bg_lab = cv2.cvtColor(background_roi_bgr, cv2.COLOR_BGR2LAB).astype(np.float32)

    crop_mean = crop_lab[:, :, 0].mean()
    bg_mean = bg_lab[:, :, 0].mean()
    shift = np.clip(bg_mean - crop_mean, -20, 20)
    crop_lab[:, :, 0] = np.clip(crop_lab[:, :, 0] + shift, 0, 255)
    return cv2.cvtColor(crop_lab.astype(np.uint8), cv2.COLOR_LAB2BGR)


def random_light_crop_transform(crop_bgr: np.ndarray) -> np.ndarray:
    """Small scale and flip only. Avoid extreme transforms because YOLO handles rotation separately."""
    crop = crop_bgr.copy()
    if random.random() < 0.5:
        crop = cv2.flip(crop, 1)
    if random.random() < 0.25:
        crop = cv2.flip(crop, 0)

    scale = random.uniform(0.85, 1.15)
    h, w = crop.shape[:2]
    nw, nh = max(2, int(w * scale)), max(2, int(h * scale))
    crop = cv2.resize(crop, (nw, nh), interpolation=cv2.INTER_LINEAR)
    return crop


def feather_blend_paste(img_bgr: np.ndarray, crop_bgr: np.ndarray, x1: int, y1: int, feather_ksize: int = 15) -> np.ndarray:
    """Paste crop into image using brightness matching and Gaussian feather alpha blending."""
    ch, cw = crop_bgr.shape[:2]
    roi = img_bgr[y1:y1 + ch, x1:x1 + cw]
    if roi.shape[:2] != (ch, cw):
        return img_bgr

    crop_adj = match_crop_brightness(crop_bgr, roi)
    alpha = make_feather_mask(ch, cw, feather_ksize)
    blended = (alpha * crop_adj.astype(np.float32) + (1 - alpha) * roi.astype(np.float32)).astype(np.uint8)
    img_bgr[y1:y1 + ch, x1:x1 + cw] = blended
    return img_bgr


def write_yolo_sample(img_bgr: np.ndarray, yolo_lines: List[str], out_img_dir: str, out_lab_dir: str, sample_name: str):
    """Write one image and its YOLO label file using a shared sample name."""
    cv2.imwrite(os.path.join(out_img_dir, sample_name + ".jpg"), img_bgr)
    with open(os.path.join(out_lab_dir, sample_name + ".txt"), "w") as f:
        f.write("\n".join(yolo_lines))


def objects_to_yolo_lines(objects: List[Dict[str, Any]], w: int, h: int):
    """Convert parsed VOC objects to YOLO lines and clipped xyxy boxes."""
    yolo_lines = []
    boxes = []
    invalid = []
    counts = Counter()

    for obj in objects:
        box = clip_box_xyxy(obj["bbox_xyxy"], w, h)
        line = safe_yolo_line(obj["class_id"], box, w, h)
        if line is None:
            invalid.append(obj)
            continue
        yolo_lines.append(line)
        boxes.append(box)
        counts[obj["class_id"]] += 1

    return yolo_lines, boxes, counts, invalid


def build_minority_crop_bank(train_files: List[str], cfg: Config) -> Dict[int, List[np.ndarray]]:
    """
    Build minority crop bank from ORIGINAL images only.
    This avoids creating synthetic crops from already FFT/edge-enhanced images.
    """
    bank = {cls_id: [] for cls_id in cfg.balance_target_classes}

    for stem in tqdm(train_files, desc="Banking original minority crops: undersize + abnormal only"):
        img_path = find_image_path(cfg.image_dir, stem)
        xml_path = os.path.join(cfg.annot_dir, stem + ".xml")
        if img_path is None or not os.path.exists(xml_path):
            continue

        img = cv2.imread(img_path)
        if img is None:
            continue
        h, w = img.shape[:2]

        parsed = parse_voc_xml(xml_path, label2id)
        for obj in parsed["objects"]:
            cls_id = obj["class_id"]
            if cls_id not in bank:
                continue

            x1, y1, x2, y2 = map(int, clip_box_xyxy(obj["bbox_xyxy"], w, h))
            crop = img[y1:y2, x1:x2]
            if crop.size == 0:
                continue
            if crop.shape[0] * crop.shape[1] < cfg.min_crop_area:
                continue
            bank[cls_id].append(crop)

    print("Minority crop bank:", {id2label[k]: len(v) for k, v in bank.items()})
    return bank


def create_copy_paste_image_from_original(
    img_bgr: np.ndarray,
    base_boxes: List[List[float]],
    base_yolo_lines: List[str],
    bank: Dict[int, List[np.ndarray]],
    cfg: Config,
):
    """
    Apply light manual copy-paste directly to the ORIGINAL image.
    FFT/edge enhancement, if used, should happen AFTER this step.
    """
    aug_img = img_bgr.copy()
    h, w = aug_img.shape[:2]
    existing_boxes = [list(b) for b in base_boxes]
    yolo_lines = list(base_yolo_lines)
    synthetic_counts = Counter()

    paste_counts_by_class = {
        2: cfg.undersize_pastes_per_image,
        3: cfg.abnormal_pastes_per_image,
    }

    if not cfg.use_light_manual_balancer:
        return aug_img, yolo_lines, synthetic_counts

    for cls_id in cfg.balance_target_classes:
        cls_bank = bank.get(cls_id, [])
        if not cls_bank:
            continue
        n_pastes = paste_counts_by_class.get(cls_id, 1)

        for _ in range(n_pastes):
            crop = random_light_crop_transform(random.choice(cls_bank))
            ch, cw = crop.shape[:2]
            if ch < 2 or cw < 2 or ch >= h or cw >= w:
                continue

            for _attempt in range(cfg.paste_attempts):
                nx1 = random.randint(0, max(0, w - cw - 1))
                ny1 = random.randint(0, max(0, h - ch - 1))
                new_box = [nx1, ny1, nx1 + cw, ny1 + ch]

                if is_overlapping(new_box, existing_boxes, buffer=cfg.paste_buffer_px):
                    continue

                aug_img = feather_blend_paste(aug_img, crop, nx1, ny1, feather_ksize=cfg.feather_ksize)
                existing_boxes.append(new_box)
                line = safe_yolo_line(cls_id, new_box, w, h)
                if line is not None:
                    yolo_lines.append(line)
                    synthetic_counts[cls_id] += 1
                break

    return aug_img, yolo_lines, synthetic_counts


def convert_val_to_yolo_original(files: List[str], cfg: Config):
    """
    Validation set is kept intact: no FFT, no edge enhancement, no manual copy-paste.
    This measures performance on the real original image distribution.
    """
    out_img_dir = os.path.join(cfg.yolo_root, "images", "val")
    out_lab_dir = os.path.join(cfg.yolo_root, "labels", "val")
    os.makedirs(out_img_dir, exist_ok=True)
    os.makedirs(out_lab_dir, exist_ok=True)

    counts = Counter()
    missing, invalid = [], []

    for stem in tqdm(files, desc="Creating original val set"):
        img_path = find_image_path(cfg.image_dir, stem)
        xml_path = os.path.join(cfg.annot_dir, stem + ".xml")
        if img_path is None or not os.path.exists(xml_path):
            missing.append(stem)
            continue

        img = cv2.imread(img_path)
        if img is None:
            missing.append(stem)
            continue
        h, w = img.shape[:2]

        parsed = parse_voc_xml(xml_path, label2id)
        yolo_lines, _, obj_counts, bad = objects_to_yolo_lines(parsed["objects"], w, h)
        invalid.extend([(stem, obj) for obj in bad])
        counts.update(obj_counts)

        # Keep original validation image unchanged.
        cv2.imwrite(os.path.join(out_img_dir, stem + ".jpg"), img)
        with open(os.path.join(out_lab_dir, stem + ".txt"), "w") as f:
            f.write("\n".join(yolo_lines))

    return counts, missing, invalid


def convert_train_to_yolo_original_plus_augmented(files: List[str], cfg: Config, bank: Dict[int, List[np.ndarray]]):
    """
    Training dataset construction:
      1. Start from original image.
      2. Apply copy-paste on original image.
      3. Save only ONE full image per source image:
           - copy-pasted image if minority paste succeeds
           - otherwise original image
      4. Randomly apply FFT/edge enhancement to some saved train images IN PLACE.
      5. Do not create duplicate _cp or _fft images.
    """

    out_img_dir = os.path.join(cfg.yolo_root, "images", "train")
    out_lab_dir = os.path.join(cfg.yolo_root, "labels", "train")
    os.makedirs(out_img_dir, exist_ok=True)
    os.makedirs(out_lab_dir, exist_ok=True)

    total_counts = Counter()
    original_counts = Counter()
    synthetic_counts = Counter()

    missing, invalid = [], []

    num_images_written = 0
    num_copypaste_success = 0
    num_copypaste_failed = 0
    num_fft_replaced = 0

    # probability of replacing saved train image with FFT/edge version
    fft_edge_prob = getattr(cfg, "fft_edge_replace_prob", 0.30)

    saved_image_paths = []

    for stem in tqdm(files, desc="Creating train set: one image per source, CP first"):
        img_path = find_image_path(cfg.image_dir, stem)
        xml_path = os.path.join(cfg.annot_dir, stem + ".xml")

        if img_path is None or not os.path.exists(xml_path):
            missing.append(stem)
            continue

        img = cv2.imread(img_path)
        if img is None:
            missing.append(stem)
            continue

        h, w = img.shape[:2]

        parsed = parse_voc_xml(xml_path, label2id)
        base_yolo_lines, base_boxes, obj_counts, bad = objects_to_yolo_lines(parsed["objects"], w, h)

        invalid.extend([(stem, obj) for obj in bad])
        original_counts.update(obj_counts)

        # Try copy-paste on original image
        cp_img, cp_yolo_lines, added_counts = create_copy_paste_image_from_original(
            img_bgr=img,
            base_boxes=base_boxes,
            base_yolo_lines=base_yolo_lines,
            bank=bank,
            cfg=cfg,
        )

        if sum(added_counts.values()) > 0:
            final_img = cp_img
            final_yolo_lines = cp_yolo_lines

            final_counts = Counter(obj_counts)
            final_counts.update(added_counts)

            synthetic_counts.update(added_counts)
            num_copypaste_success += 1
        else:
            final_img = img
            final_yolo_lines = base_yolo_lines
            final_counts = Counter(obj_counts)
            num_copypaste_failed += 1

        # Save exactly one full image per original source image
        sample_name = stem
        write_yolo_sample(
            img_bgr=final_img,
            yolo_lines=final_yolo_lines,
            out_img_dir=out_img_dir,
            out_lab_dir=out_lab_dir,
            sample_name=sample_name,
        )

        saved_image_paths.append(os.path.join(out_img_dir, sample_name + ".jpg"))

        total_counts.update(final_counts)
        num_images_written += 1

    # Randomly replace some saved train images with FFT/edge-enhanced versions
    if getattr(cfg, "add_fft_edge_augmented_copy", True):
        for img_file in saved_image_paths:
            if random.random() < fft_edge_prob:
                img = cv2.imread(img_file)
                if img is None:
                    continue

                enhanced = apply_enhancement(img)

                # Replace image in place.
                # Label file stays unchanged.
                cv2.imwrite(img_file, enhanced)
                num_fft_replaced += 1

    train_stats = {
        "split": "train",
        "images_written": num_images_written,
        "copypaste_success_images": num_copypaste_success,
        "copypaste_failed_original_images": num_copypaste_failed,
        "fft_edge_replaced_images": num_fft_replaced,
        "fft_edge_replace_prob": fft_edge_prob,
        "original_box_counts": dict(original_counts),
        "synthetic_added_box_counts": dict(synthetic_counts),
        "total_box_counts_written": dict(total_counts),
        "missing": missing,
        "invalid": invalid,
    }

    print("Original train counts:", {id2label[k]: v for k, v in sorted(original_counts.items())})
    print("Synthetic minority additions:", {id2label[k]: v for k, v in sorted(synthetic_counts.items())})
    print("Total written train counts:", {id2label[k]: v for k, v in sorted(total_counts.items())})
    print("Images written:", num_images_written)
    print("Copy-paste success images:", num_copypaste_success)
    print("Copy-paste failed / original kept:", num_copypaste_failed)
    print("FFT/edge images replaced in place:", num_fft_replaced)

    return train_stats

def create_enhanced_dataset_light_balancer(cfg: Config, train_files: List[str], val_files: List[str]):
    """
    Enhanced experiment dataset:
      - train: original images + copy-paste images + FFT/edge-enhanced copy-paste images
      - val: original images only, no enhancement and no balancing

    Returns the same 3 items as create_baseline_dataset for cleaner experiment orchestration.
    """
    if cfg.rebuild_dataset:
        reset_dir(cfg.yolo_root)

    for d in ["images/train", "labels/train", "images/val", "labels/val"]:
        os.makedirs(os.path.join(cfg.yolo_root, d), exist_ok=True)

    bank = build_minority_crop_bank(train_files, cfg)
    train_stats = convert_train_to_yolo_original_plus_augmented(train_files, cfg, bank)
    val_counts, val_missing, val_invalid = convert_val_to_yolo_original(val_files, cfg)

    val_stats = {
        "split": "val",
        "images": len(val_files) - len(val_missing),
        "class_counter": dict(val_counts),
        "missing": val_missing,
        "invalid": val_invalid,
        "note": "Validation kept original-only: no FFT, no edge enhancement, no copy-paste.",
    }

    print("\nEnhanced experiment dataset policy:")
    print("  train = original + copy-paste + FFT/edge-enhanced copy-paste augmentation")
    print("  val   = original only")
    print("Val class counts:", {id2label[k]: v for k, v in sorted(val_counts.items())})
    print("Missing train/val:", len(train_stats["missing"]), len(val_missing))
    print("Invalid train/val boxes:", len(train_stats["invalid"]), len(val_invalid))

    yaml_path = create_yolo_data_yaml(cfg)
    print_label_summary(cfg)
    return yaml_path, train_stats, val_stats

## Build datasets

In [11]:
# Build BOTH datasets: baseline (vanilla VOC->YOLO) and enhanced (FFT/edge preprocessing + copy-paste augmentation)
# Both will be trained with the same sweep-winner hyperparameters for a fair comparison.

import tempfile
DATASET_BASE = '/tmp' if not os.path.exists('/content') else '/content'

baseline_cfg = replace(
    common_cfg,
    yolo_root=f'{DATASET_BASE}/yolo_follicle_dataset_baseline',
    run_name='yolo_sweep_winner_baseline_50ep',
    use_light_manual_balancer=False,
)

enhanced_cfg = replace(
    common_cfg,
    yolo_root=f'{DATASET_BASE}/yolo_follicle_dataset_enhanced',
    run_name='yolo_sweep_winner_enhanced_50ep',
    use_light_manual_balancer=True,
)

print(f'Baseline yolo_root: {baseline_cfg.yolo_root}')
print(f'Enhanced yolo_root: {enhanced_cfg.yolo_root}')
print(f'Output dir: {common_cfg.drive_dir}')

baseline_yaml_path, baseline_train_stats, baseline_val_stats = create_baseline_dataset(
    baseline_cfg, train_files, val_files
)

enhanced_yaml_path, enhanced_train_stats, enhanced_val_stats = create_enhanced_dataset_light_balancer(
    enhanced_cfg, train_files, val_files
)

experiment_registry = {
    'baseline': {'cfg': baseline_cfg, 'yaml_path': baseline_yaml_path},
    'enhanced_balanced': {'cfg': enhanced_cfg, 'yaml_path': enhanced_yaml_path},
}

Baseline yolo_root: /tmp/yolo_follicle_dataset_baseline
Enhanced yolo_root: /tmp/yolo_follicle_dataset_enhanced
Output dir: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs

Creating baseline train set:   0%|          | 0/992 [00:00<?, ?it/s]

Creating baseline val set:   0%|          | 0/330 [00:00<?, ?it/s]

/tmp/yolo_follicle_dataset_baseline/data.yaml
path: /tmp/yolo_follicle_dataset_baseline
train: images/train
val: images/val
names:
  0: premium
  1: single
  2: undersize
  3: abnormal

train_stats: {'split': 'train', 'images': 992, 'skipped': [], 'invalid': [], 'boxes': 12224, 'class_counter': {0: 8065, 2: 917, 1: 2820, 3: 422}}
val_stats: {'split': 'val', 'images': 330, 'skipped': [], 'invalid': [], 'boxes': 4227, 'class_counter': {3: 153, 0: 2884, 1: 942, 2: 248}}
 train
{'premium': 8065, 'single': 2820, 'undersize': 917, 'abnormal': 422}
bad rows: 0
 val
{'premium': 2884, 'single': 942, 'undersize': 248, 'abnormal': 153}
bad rows: 0

Banking original minority crops: undersize + abnormal only:   0%|          | 0/992 [00:00<?, ?it/s]

Minority crop bank: {'undersize': 917, 'abnormal': 421}

Creating train set: one image per source, CP first:   0%|          | 0/992 [00:00<?, ?it/s]

Original train counts: {'premium': 8065, 'single': 2820, 'undersize': 917, 'abnormal': 422}
Synthetic minority additions: {'undersize': 991, 'abnormal': 1968}
Total written train counts: {'premium': 8065, 'single': 2820, 'undersize': 1908, 'abnormal': 2390}
Images written: 992
Copy-paste success images: 992
Copy-paste failed / original kept: 0
FFT/edge images replaced in place: 247

Creating original val set:   0%|          | 0/330 [00:00<?, ?it/s]

Enhanced experiment dataset policy:
  train = original + copy-paste + FFT/edge-enhanced copy-paste augmentation
  val   = original only
Val class counts: {'premium': 2884, 'single': 942, 'undersize': 248, 'abnormal': 153}
Missing train/val: 0 0
Invalid train/val boxes: 0 0
/tmp/yolo_follicle_dataset_enhanced/data.yaml
path: /tmp/yolo_follicle_dataset_enhanced
train: images/train
val: images/val
names:
  0: premium
  1: single
  2: undersize
  3: abnormal

 train
{'premium': 8065, 'single': 2820, 'undersize': 1908, 'abnormal': 2390}
bad rows: 0
 val
{'premium': 2884, 'single': 942, 'undersize': 248, 'abnormal': 153}
bad rows: 0

## Sample preview for both datasets

In [12]:
# Preview skipped for headless run
print('Skipping dataset preview')

Skipping dataset preview

# Model training, validation, and plotting helpers

In [13]:
def get_run_paths(cfg: Config):
    run_dir = os.path.join(cfg.drive_dir, cfg.run_name)
    best_path = os.path.join(run_dir, "weights", "best.pt")
    os.makedirs(run_dir, exist_ok=True)
    return run_dir, best_path


def make_train_kwargs(cfg: Config, yaml_path: str, enhanced: bool = False):
    """Training kwargs for the sweep-winner config (W&B run volcanic-sweep-2 from sweep zzovt4eb).

    All hyperparameters below were chosen by Bayesian optimization targeting mAP50(B)
    over 13+ trials. Loss weights and augmentation values are the exact winning combo.
    """
    common = dict(
        data=yaml_path,
        imgsz=cfg.image_size,
        epochs=cfg.epochs,
        batch=cfg.batch,

        # Loss weights (from sweep winner: volcanic-sweep-2)
        box=12.0,
        cls=0.5150205061041268,
        dfl=1.291618724666412,

        # Optimizer (from sweep winner)
        optimizer="AdamW",
        lr0=0.00017277992070938698,
        weight_decay=7.20056409483377e-05,
        patience=cfg.patience,

        # Augmentation (from sweep winner)
        mosaic=0.3246607118043379,
        copy_paste=0.008596619193078536,
        close_mosaic=29,

        # Reproducibility / saving
        seed=cfg.seed,
        workers=cfg.workers,
        project=cfg.drive_dir,
        name=cfg.run_name,
        exist_ok=True,
        # Save every epoch checkpoint so we can compare Hungarian-eval IoU across epochs
        save_period=1,
    )
    return common


def train_or_load_yolo(cfg: Config, yaml_path: str, enhanced: bool = False):
    run_dir, best_path = get_run_paths(cfg)
    train_kwargs = make_train_kwargs(cfg, yaml_path, enhanced=enhanced)
    print(json.dumps({k: str(v) for k, v in train_kwargs.items() if k != "data"}, indent=2))

    if os.path.exists(best_path):
        print(f"Existing best checkpoint found: {best_path}")
        print("Loading it instead of retraining.")
        model = YOLO(best_path)
    else:
        print("Training new model...")
        model = YOLO(cfg.pretrained_model_name)
        model.train(**train_kwargs)
        model = YOLO(best_path)
    print("Model ready:", best_path)
    return model, run_dir, best_path


def validate_yolo_model(model, cfg: Config, yaml_path: str, run_dir: str, experiment_name: str):
    val_results = model.val(
        data=yaml_path,
        imgsz=cfg.image_size,
        conf=cfg.map_conf_threshold,
        iou=cfg.val_iou_threshold,
        max_det=cfg.max_det,
        plots=True,
        verbose=True,
    )

    summary = {
        "experiment": experiment_name,
        "run_name": cfg.run_name,
        "imgsz": cfg.image_size,
        "conf_for_mAP": cfg.map_conf_threshold,
        "nms_iou": cfg.val_iou_threshold,
        "max_det": cfg.max_det,
    }
    try:
        summary.update({
            "precision": float(val_results.box.mp),
            "recall": float(val_results.box.mr),
            "mAP50": float(val_results.box.map50),
            "mAP50_95": float(val_results.box.map),
        })
    except Exception as e:
        print("Could not extract metrics automatically:", e)

    summary_df = pd.DataFrame([summary])
    display(summary_df)

    metrics_path = os.path.join(run_dir, f"{experiment_name}_validation_summary.csv")
    summary_df.to_csv(metrics_path, index=False)
    print("Saved metrics to:", metrics_path)
    return val_results, summary_df


def plot_training_curves(run_dir: str):
    results_csv = os.path.join(run_dir, "results.csv")
    if not os.path.exists(results_csv):
        print(f"No training curves found at {results_csv}")
        return
    df = pd.read_csv(results_csv)
    df.columns = [c.strip() for c in df.columns]
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    if "train/box_loss" in df.columns:
        axes[0,0].plot(df["epoch"], df["train/box_loss"], label="train")
    if "val/box_loss" in df.columns:
        axes[0,0].plot(df["epoch"], df["val/box_loss"], label="val")
    axes[0,0].set_title("Box loss"); axes[0,0].legend(); axes[0,0].set_xlabel("epoch")
    if "train/cls_loss" in df.columns:
        axes[0,1].plot(df["epoch"], df["train/cls_loss"], label="train")
    if "val/cls_loss" in df.columns:
        axes[0,1].plot(df["epoch"], df["val/cls_loss"], label="val")
    axes[0,1].set_title("Cls loss"); axes[0,1].legend(); axes[0,1].set_xlabel("epoch")
    if "metrics/mAP50(B)" in df.columns:
        axes[1,0].plot(df["epoch"], df["metrics/mAP50(B)"])
        axes[1,0].set_title("mAP50"); axes[1,0].set_xlabel("epoch")
    if "metrics/mAP50-95(B)" in df.columns:
        axes[1,1].plot(df["epoch"], df["metrics/mAP50-95(B)"])
        axes[1,1].set_title("mAP50-95"); axes[1,1].set_xlabel("epoch")
    plt.tight_layout(); plt.show()

## Experiment 1: Baseline + sweep-winner hyperparameters

In [14]:
baseline_model, baseline_run_dir, baseline_best_path = train_or_load_yolo(
    baseline_cfg,
    baseline_yaml_path,
    enhanced=False,
)

baseline_val_results, baseline_summary_df = validate_yolo_model(
    baseline_model,
    baseline_cfg,
    baseline_yaml_path,
    baseline_run_dir,
    experiment_name='baseline',
)

plot_training_curves(baseline_run_dir)

{
  "imgsz": "1024",
  "epochs": "50",
  "batch": "8",
  "box": "12.0",
  "cls": "0.5150205061041268",
  "dfl": "1.291618724666412",
  "optimizer": "AdamW",
  "lr0": "0.00017277992070938698",
  "weight_decay": "7.20056409483377e-05",
  "patience": "25",
  "mosaic": "0.3246607118043379",
  "copy_paste": "0.008596619193078536",
  "close_mosaic": "29",
  "seed": "42",
  "workers": "2",
  "project": "/home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs",
  "name": "yolo_sweep_winner_baseline_50ep",
  "exist_ok": "True",
  "save_period": "1"
}
Existing best checkpoint found: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_baseline_50ep/weights/best.pt
Loading it instead of retraining.

Model ready: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_baseline_50ep/weights/best.pt

Ultralytics 8.4.48 🚀 Python-3.10.12 torch-2.11.0+cu130 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)

YOLO11m summary (fused): 126 layers, 20,033,116 parameters, 0 gradients, 67.7 GFLOPs

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2832.0±531.9 MB/s, size: 99.0 KB)

val: Scanning /tmp/yolo_follicle_dataset_baseline/labels/val... 149 images, 0 backgrounds, 0 corrupt: 45% ━━━━━─────── 149/330 441.6it/s 0.1s<0.4s

val: Scanning /tmp/yolo_follicle_dataset_baseline/labels/val... 301 images, 0 backgrounds, 0 corrupt: 91% ━━━━━━━━━━╸─ 301/330 758.3it/s 0.2s<0.0s

val: Scanning /tmp/yolo_follicle_dataset_baseline/labels/val... 330 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 330/330 1.5Kit/s 0.2s

val: New cache created: /tmp/yolo_follicle_dataset_baseline/labels/val.cache

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 1.6s/it 0.5s<32.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 1.3s/it 1.4s<24.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 1.2s/it 2.3s<21.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 1.0s/it 3.1s<17.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 2.7it/s 3.3s<5.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 4.0it/s 3.4s<3.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 4.8it/s 3.5s<2.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 5.5it/s 3.7s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 5.4it/s 3.9s<2.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 5.8it/s 4.0s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 5.8it/s 4.2s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 6.2it/s 4.3s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 6.4it/s 4.5s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 6.5it/s 4.6s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 6.6it/s 4.8s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 6.7it/s 4.9s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 6.1it/s 5.1s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 5.9it/s 5.3s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 6.1it/s 5.5s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 6.3it/s 5.6s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.7it/s 5.7s

                   all        330       4227      0.668      0.628      0.654      0.396

               premium        330       2884      0.844       0.76      0.844      0.534

                single        307        942      0.766      0.779      0.823      0.561

             undersize        161        248      0.574      0.637      0.584      0.308

              abnormal        103        153      0.487      0.335      0.365      0.182

Speed: 2.2ms preprocess, 5.4ms inference, 0.0ms loss, 4.3ms postprocess per image

Results saved to /home/ubuntu/hair-follicle-density-estimation-209b/MS4/runs/detect/val

,experiment,run_name,imgsz,conf_for_mAP,nms_iou,max_det,precision,recall,mAP50,mAP50_95
0,baseline,yolo_sweep_winner_baseline_50ep,1024,0.001,0.7,1000,0.667715,0.627749,0.653825,0.396445

Saved metrics to: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_baseline_50ep/baseline_validation_summary.csv

## Experiment 2: Enhanced (FFT/edge preprocessing + copy-paste) + sweep-winner hyperparameters

In [15]:
enhanced_model, enhanced_run_dir, enhanced_best_path = train_or_load_yolo(
    enhanced_cfg,
    enhanced_yaml_path,
    enhanced=True,
)

enhanced_val_results, enhanced_summary_df = validate_yolo_model(
    enhanced_model,
    enhanced_cfg,
    enhanced_yaml_path,
    enhanced_run_dir,
    experiment_name='enhanced_balanced',
)

plot_training_curves(enhanced_run_dir)

{
  "imgsz": "1024",
  "epochs": "50",
  "batch": "8",
  "box": "12.0",
  "cls": "0.5150205061041268",
  "dfl": "1.291618724666412",
  "optimizer": "AdamW",
  "lr0": "0.00017277992070938698",
  "weight_decay": "7.20056409483377e-05",
  "patience": "25",
  "mosaic": "0.3246607118043379",
  "copy_paste": "0.008596619193078536",
  "close_mosaic": "29",
  "seed": "42",
  "workers": "2",
  "project": "/home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs",
  "name": "yolo_sweep_winner_enhanced_50ep",
  "exist_ok": "True",
  "save_period": "1"
}
Training new model...

Ultralytics 8.4.48 🚀 Python-3.10.12 torch-2.11.0+cu130 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)

engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=12.0, cache=False, cfg=None, classes=None, close_mosaic=29, cls=0.5150205061041268, cls_pw=0.0, compile=False, conf=None, copy_paste=0.008596619193078536, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/tmp/yolo_follicle_dataset_enhanced/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.291618724666412, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1024, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.00017277992070938698, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11m.pt, momentum=0.937, mosaic=0.3246607118043379, multi_scale=0.0, name=yolo_sweep_winner_enhanced_50ep, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=25, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep, save_frames=False, save_json=False, save_period=1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=7.20056409483377e-05, workers=2, workspace=None

Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments

  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]

  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]

  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]

  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]

  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]

  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]

  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]

  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]

  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]

  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]

 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]

 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 13                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]

 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']

 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 16                  -1  1    542720  ultralytics.nn.modules.block.C3k2            [1024, 256, 1, True]

 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]

 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 19                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]

 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]

 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]

 22                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]

 23        [16, 19, 22]  1   1414108  ultralytics.nn.modules.head.Detect           [4, 16, None, [256, 512, 512]]

YOLO11m summary: 232 layers, 20,056,092 parameters, 20,056,076 gradients, 68.2 GFLOPs

Transferred 643/649 items from pretrained weights

Freezing layer 'model.23.dfl.conv.weight'

AMP: running Automatic Mixed Precision (AMP) checks...

AMP: checks passed ✅

train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4221.8±1304.2 MB/s, size: 194.7 KB)

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 142 images, 0 backgrounds, 0 corrupt: 14% ━╸────────── 142/992 425.6it/s 0.1s<2.0s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 293 images, 0 backgrounds, 0 corrupt: 30% ━━━╸──────── 293/992 745.1it/s 0.2s<0.9s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 446 images, 0 backgrounds, 0 corrupt: 45% ━━━━━─────── 446/992 979.8it/s 0.3s<0.6s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 599 images, 0 backgrounds, 0 corrupt: 60% ━━━━━━━───── 599/992 1.1Kit/s 0.4s<0.3s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 755 images, 0 backgrounds, 0 corrupt: 76% ━━━━━━━━━─── 755/992 1.3Kit/s 0.5s<0.2s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 908 images, 0 backgrounds, 0 corrupt: 92% ━━━━━━━━━━╸─ 908/992 1.3Kit/s 0.6s<0.1s

train: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/train... 992 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 992/992 1.5Kit/s 0.7s

train: New cache created: /tmp/yolo_follicle_dataset_enhanced/labels/train.cache

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2917.4±1905.7 MB/s, size: 187.2 KB)

val: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/val... 143 images, 0 backgrounds, 0 corrupt: 43% ━━━━━─────── 143/330 424.0it/s 0.1s<0.4s

val: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/val... 294 images, 0 backgrounds, 0 corrupt: 89% ━━━━━━━━━━╸─ 294/330 749.6it/s 0.2s<0.0s

val: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/val... 330 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 330/330 1.5Kit/s 0.2s

val: New cache created: /tmp/yolo_follicle_dataset_enhanced/labels/val.cache

optimizer: AdamW(lr=0.00017277992070938698, momentum=0.937) with parameter groups 106 weight(decay=0.0), 113 weight(decay=7.20056409483377e-05), 112 bias(decay=0.0)

Plotting labels to /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/labels.jpg...

Image sizes 1024 train, 1024 val
Using 2 dataloader workers
Logging results to /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/50        10G      3.548      4.589       1.97        151       1024: 0% ──────────── 0/124  3.5s

       1/50        10G      3.733      4.529      1.945        133       1024: 1% ──────────── 1/124 1.6it/s 3.7s<1:17

       1/50        10G       3.86       4.56      1.996        104       1024: 2% ──────────── 2/124 2.3it/s 3.9s<53.2s

       1/50        10G      3.805      4.578      1.965        114       1024: 2% ──────────── 3/124 3.3it/s 4.1s<36.4s

       1/50        10G       3.77      4.581       1.92        197       1024: 3% ──────────── 4/124 3.9it/s 4.3s<30.5s

       1/50        10G      3.754      4.583      1.921        136       1024: 4% ──────────── 5/124 4.5it/s 4.5s<26.6s

       1/50        10G      3.755      4.597        1.9        177       1024: 5% ╸─────────── 6/124 4.9it/s 4.6s<24.0s

       1/50      10.1G      3.747      4.595      1.895        138       1024: 6% ╸─────────── 7/124 4.6it/s 4.9s<25.5s

       1/50      10.1G      3.729       4.52      1.859        131       1024: 6% ╸─────────── 8/124 4.9it/s 5.1s<23.5s

       1/50      10.1G      3.684      4.394      1.798        164       1024: 7% ╸─────────── 9/124 5.2it/s 5.3s<22.2s

       1/50      10.1G      3.646      4.241      1.759        162       1024: 8% ╸─────────── 10/124 5.4it/s 5.4s<21.2s

       1/50      10.1G      3.605      4.111      1.726        164       1024: 9% ━─────────── 11/124 5.5it/s 5.6s<20.5s

       1/50      10.1G      3.552      4.003      1.697        129       1024: 10% ━─────────── 12/124 5.6it/s 5.8s<20.0s

       1/50      10.1G      3.515       3.91      1.674        137       1024: 10% ━─────────── 13/124 5.7it/s 5.9s<19.6s

       1/50      10.1G      3.492      3.832      1.665        101       1024: 11% ━─────────── 14/124 5.7it/s 6.1s<19.2s

       1/50      10.1G      3.466      3.755      1.647        136       1024: 12% ━─────────── 15/124 5.7it/s 6.3s<19.0s

       1/50      10.1G       3.46      3.685      1.628        129       1024: 13% ━╸────────── 16/124 5.8it/s 6.5s<18.7s

       1/50      10.1G      3.435      3.625      1.612        125       1024: 14% ━╸────────── 17/124 5.8it/s 6.6s<18.6s

       1/50      10.1G      3.437      3.568      1.599        156       1024: 15% ━╸────────── 18/124 5.8it/s 6.8s<18.4s

       1/50      10.1G      3.399      3.509      1.586        101       1024: 15% ━╸────────── 19/124 5.8it/s 7.0s<18.2s

       1/50      10.1G      3.393      3.454      1.574         95       1024: 16% ━╸────────── 20/124 5.7it/s 7.2s<18.2s

       1/50      10.1G      3.366      3.398      1.559        118       1024: 17% ━━────────── 21/124 5.7it/s 7.3s<18.1s

       1/50      10.1G      3.351      3.343      1.544        111       1024: 18% ━━────────── 22/124 5.7it/s 7.5s<17.8s

       1/50      10.1G      3.325      3.288      1.533        146       1024: 19% ━━────────── 23/124 5.7it/s 7.7s<17.6s

       1/50      10.1G      3.304      3.238      1.527        109       1024: 19% ━━────────── 24/124 5.8it/s 7.8s<17.4s

       1/50      10.1G      3.301      3.197      1.517        119       1024: 20% ━━────────── 25/124 5.8it/s 8.0s<17.1s

       1/50      10.1G      3.286      3.145      1.506        152       1024: 21% ━━╸───────── 26/124 5.8it/s 8.2s<17.0s

       1/50      10.1G      3.264      3.102      1.498        123       1024: 22% ━━╸───────── 27/124 6.1it/s 8.3s<15.8s

       1/50      10.1G       3.26      3.068      1.493        118       1024: 23% ━━╸───────── 28/124 6.0it/s 8.5s<15.9s

       1/50      10.1G       3.25      3.029      1.485        164       1024: 23% ━━╸───────── 29/124 6.3it/s 8.7s<15.1s

       1/50      10.1G      3.239      2.985      1.479        131       1024: 24% ━━╸───────── 30/124 6.1it/s 8.8s<15.3s

       1/50      10.1G      3.232      2.957      1.473        116       1024: 25% ━━━───────── 31/124 6.4it/s 9.0s<14.6s

       1/50      10.1G      3.222      2.929      1.467        113       1024: 26% ━━━───────── 32/124 6.2it/s 9.1s<14.9s

       1/50      10.1G      3.211        2.9      1.459        164       1024: 27% ━━━───────── 33/124 6.4it/s 9.3s<14.2s

       1/50      10.1G      3.204      2.874      1.456        147       1024: 27% ━━━───────── 34/124 6.2it/s 9.5s<14.5s

       1/50      10.1G      3.191       2.85      1.453        123       1024: 28% ━━━───────── 35/124 6.4it/s 9.6s<13.8s

       1/50      10.1G      3.192      2.826      1.449        160       1024: 29% ━━━───────── 36/124 6.2it/s 9.8s<14.1s

       1/50      10.1G      3.187      2.799      1.442        203       1024: 30% ━━━╸──────── 37/124 6.3it/s 9.9s<13.7s

       1/50      10.1G      3.173      2.771      1.437        107       1024: 31% ━━━╸──────── 38/124 6.2it/s 10.1s<13.9s

       1/50      10.1G      3.161      2.744      1.429        157       1024: 31% ━━━╸──────── 39/124 6.4it/s 10.3s<13.3s

       1/50      10.1G      3.157       2.72      1.426        146       1024: 32% ━━━╸──────── 40/124 6.2it/s 10.4s<13.6s

       1/50      10.1G      3.152      2.703      1.423        120       1024: 33% ━━━╸──────── 41/124 6.4it/s 10.6s<13.0s

       1/50      10.1G      3.146      2.683       1.42        121       1024: 34% ━━━━──────── 42/124 6.2it/s 10.7s<13.2s

       1/50      10.1G      3.143      2.663      1.419        112       1024: 35% ━━━━──────── 43/124 6.4it/s 10.9s<12.7s

       1/50      10.1G      3.132      2.639      1.413        145       1024: 35% ━━━━──────── 44/124 6.2it/s 11.1s<12.9s

       1/50      10.1G      3.123      2.618      1.407        172       1024: 36% ━━━━──────── 45/124 6.4it/s 11.2s<12.3s

       1/50      10.1G      3.118        2.6      1.406        117       1024: 37% ━━━━──────── 46/124 6.2it/s 11.4s<12.6s

       1/50      10.1G      3.114      2.582      1.403        134       1024: 38% ━━━━╸─────── 47/124 6.4it/s 11.5s<12.0s

       1/50      10.1G      3.102      2.562      1.397        170       1024: 39% ━━━━╸─────── 48/124 6.1it/s 11.7s<12.4s

       1/50      10.1G      3.103      2.548      1.393        115       1024: 40% ━━━━╸─────── 49/124 6.3it/s 11.9s<11.9s

       1/50      10.1G      3.101      2.532      1.392        121       1024: 40% ━━━━╸─────── 50/124 6.1it/s 12.0s<12.1s

       1/50      10.1G      3.089      2.511      1.387        129       1024: 41% ━━━━╸─────── 51/124 6.4it/s 12.2s<11.4s

       1/50      10.1G      3.085      2.493      1.383        142       1024: 42% ━━━━━─────── 52/124 6.2it/s 12.4s<11.7s

       1/50      10.1G      3.079      2.482      1.379        111       1024: 43% ━━━━━─────── 53/124 6.3it/s 12.5s<11.2s

       1/50      10.1G      3.071      2.469      1.374        148       1024: 44% ━━━━━─────── 54/124 6.1it/s 12.7s<11.5s

       1/50      10.1G      3.057      2.454      1.369        123       1024: 44% ━━━━━─────── 55/124 6.2it/s 12.8s<11.1s

       1/50      10.1G      3.051      2.439      1.365        156       1024: 45% ━━━━━─────── 56/124 6.0it/s 13.0s<11.4s

       1/50      10.1G      3.043      2.423      1.362        139       1024: 46% ━━━━━╸────── 57/124 6.1it/s 13.2s<11.0s

       1/50      10.1G       3.04      2.412      1.358        178       1024: 47% ━━━━━╸────── 58/124 5.9it/s 13.4s<11.2s

       1/50      10.1G      3.035      2.401      1.356        127       1024: 48% ━━━━━╸────── 59/124 6.1it/s 13.5s<10.6s

       1/50      10.1G       3.03      2.388      1.353        128       1024: 48% ━━━━━╸────── 60/124 6.0it/s 13.7s<10.7s

       1/50      10.1G      3.026      2.377      1.349        235       1024: 49% ━━━━━╸────── 61/124 6.2it/s 13.8s<10.2s

       1/50      10.1G      3.019      2.368      1.347        153       1024: 50% ━━━━━━────── 62/124 5.9it/s 14.0s<10.4s

       1/50      10.1G      3.015      2.357      1.343        196       1024: 51% ━━━━━━────── 63/124 6.1it/s 14.2s<9.9s

       1/50      10.1G      3.011      2.345      1.339        141       1024: 52% ━━━━━━────── 64/124 6.0it/s 14.4s<10.1s

       1/50      10.1G      3.013      2.337      1.338        140       1024: 52% ━━━━━━────── 65/124 6.2it/s 14.5s<9.5s

       1/50      10.1G      3.009      2.332      1.336        124       1024: 53% ━━━━━━────── 66/124 6.0it/s 14.7s<9.7s

       1/50      10.1G      3.002      2.321      1.333        170       1024: 54% ━━━━━━────── 67/124 6.2it/s 14.8s<9.2s

       1/50      10.1G      2.996      2.311       1.33        136       1024: 55% ━━━━━━╸───── 68/124 6.1it/s 15.0s<9.2s

       1/50      10.1G      2.988      2.299      1.326        171       1024: 56% ━━━━━━╸───── 69/124 6.3it/s 15.2s<8.8s

       1/50      10.1G       2.98      2.287      1.323        121       1024: 56% ━━━━━━╸───── 70/124 6.1it/s 15.3s<8.8s

       1/50      10.1G      2.973      2.277       1.32        139       1024: 57% ━━━━━━╸───── 71/124 6.3it/s 15.5s<8.4s

       1/50      10.1G      2.964      2.266      1.316        128       1024: 58% ━━━━━━╸───── 72/124 6.0it/s 15.7s<8.7s

       1/50      10.1G      2.958      2.257      1.314        119       1024: 59% ━━━━━━━───── 73/124 6.1it/s 15.8s<8.3s

       1/50      10.1G      2.951      2.247      1.312        127       1024: 60% ━━━━━━━───── 74/124 6.0it/s 16.0s<8.3s

       1/50      10.1G      2.948      2.238      1.309        109       1024: 60% ━━━━━━━───── 75/124 6.2it/s 16.2s<7.9s

       1/50      10.1G       2.94      2.227      1.306        107       1024: 61% ━━━━━━━───── 76/124 6.0it/s 16.3s<8.0s

       1/50      10.1G      2.933      2.219      1.303        128       1024: 62% ━━━━━━━───── 77/124 6.3it/s 16.5s<7.5s

       1/50      10.1G      2.926      2.211      1.301        180       1024: 63% ━━━━━━━╸──── 78/124 6.1it/s 16.7s<7.6s

       1/50      10.1G      2.921      2.202      1.298        163       1024: 64% ━━━━━━━╸──── 79/124 6.1it/s 16.8s<7.3s

       1/50      10.1G      2.912      2.192      1.295        124       1024: 65% ━━━━━━━╸──── 80/124 6.2it/s 17.0s<7.1s

       1/50      10.1G      2.909      2.185      1.293        134       1024: 65% ━━━━━━━╸──── 81/124 6.0it/s 17.2s<7.2s

       1/50      10.1G      2.904      2.175      1.292        127       1024: 66% ━━━━━━━╸──── 82/124 6.1it/s 17.3s<6.9s

       1/50      10.1G      2.901      2.167       1.29        167       1024: 67% ━━━━━━━━──── 83/124 6.2it/s 17.5s<6.6s

       1/50      10.1G      2.899      2.162       1.29        127       1024: 68% ━━━━━━━━──── 84/124 6.0it/s 17.7s<6.7s

       1/50      10.1G      2.895      2.154      1.287        159       1024: 69% ━━━━━━━━──── 85/124 6.1it/s 17.8s<6.4s

       1/50      10.1G      2.889      2.146      1.285        151       1024: 69% ━━━━━━━━──── 86/124 6.2it/s 18.0s<6.1s

       1/50      10.1G      2.885       2.14      1.283        132       1024: 70% ━━━━━━━━──── 87/124 6.0it/s 18.1s<6.2s

       1/50      10.1G      2.881      2.133      1.282        113       1024: 71% ━━━━━━━━╸─── 88/124 6.1it/s 18.3s<5.9s

       1/50      10.1G      2.878      2.125       1.28        171       1024: 72% ━━━━━━━━╸─── 89/124 6.3it/s 18.5s<5.6s

       1/50      10.1G      2.875      2.119      1.278        125       1024: 73% ━━━━━━━━╸─── 90/124 6.1it/s 18.6s<5.6s

       1/50      10.1G      2.871      2.112      1.276        193       1024: 73% ━━━━━━━━╸─── 91/124 6.1it/s 18.8s<5.4s

       1/50      10.1G      2.865      2.103      1.274        123       1024: 74% ━━━━━━━━╸─── 92/124 6.2it/s 18.9s<5.1s

       1/50      10.1G      2.859      2.096      1.272        124       1024: 75% ━━━━━━━━━─── 93/124 6.1it/s 19.1s<5.1s

       1/50      10.1G      2.855       2.09       1.27        140       1024: 76% ━━━━━━━━━─── 94/124 6.3it/s 19.3s<4.8s

       1/50      10.1G      2.853      2.083      1.269        141       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 19.4s<4.5s

       1/50      10.1G      2.848      2.077      1.266        160       1024: 77% ━━━━━━━━━─── 96/124 6.2it/s 19.6s<4.5s

       1/50      10.1G      2.843      2.071      1.265        148       1024: 78% ━━━━━━━━━─── 97/124 6.3it/s 19.7s<4.3s

       1/50      10.1G       2.84      2.065      1.264        123       1024: 79% ━━━━━━━━━─── 98/124 6.4it/s 19.9s<4.1s

       1/50      10.1G      2.837      2.059      1.263        108       1024: 80% ━━━━━━━━━╸── 99/124 6.2it/s 20.1s<4.1s

       1/50      10.1G      2.833      2.054      1.262        157       1024: 81% ━━━━━━━━━╸── 100/124 6.2it/s 20.2s<3.9s

       1/50      10.1G      2.827      2.047      1.261        114       1024: 81% ━━━━━━━━━╸── 101/124 6.4it/s 20.4s<3.6s

       1/50      10.1G      2.824      2.043      1.259        143       1024: 82% ━━━━━━━━━╸── 102/124 6.1it/s 20.6s<3.6s

       1/50      10.1G      2.819      2.035      1.258        147       1024: 83% ━━━━━━━━━╸── 103/124 6.2it/s 20.7s<3.4s

       1/50      10.1G      2.817      2.031      1.257        129       1024: 84% ━━━━━━━━━━── 104/124 6.4it/s 20.9s<3.1s

       1/50      10.1G      2.812      2.026      1.255        123       1024: 85% ━━━━━━━━━━── 105/124 6.2it/s 21.0s<3.1s

       1/50      10.1G      2.809      2.022      1.254        157       1024: 85% ━━━━━━━━━━── 106/124 6.3it/s 21.2s<2.9s

       1/50      10.1G      2.805      2.018      1.252        152       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 21.3s<2.6s

       1/50      10.1G      2.802      2.013      1.251        112       1024: 87% ━━━━━━━━━━── 108/124 6.2it/s 21.5s<2.6s

       1/50      10.1G      2.798      2.007       1.25        108       1024: 88% ━━━━━━━━━━╸─ 109/124 6.3it/s 21.7s<2.4s

       1/50      10.1G      2.794      2.002      1.249        126       1024: 89% ━━━━━━━━━━╸─ 110/124 6.5it/s 21.8s<2.2s

       1/50      10.1G      2.789      1.997      1.248        121       1024: 90% ━━━━━━━━━━╸─ 111/124 6.2it/s 22.0s<2.1s

       1/50      10.1G      2.784      1.992      1.246        155       1024: 90% ━━━━━━━━━━╸─ 112/124 6.4it/s 22.1s<1.9s

       1/50      10.1G      2.782      1.987      1.245        126       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 22.3s<1.7s

       1/50      10.1G      2.779      1.982      1.244        117       1024: 92% ━━━━━━━━━━━─ 114/124 6.3it/s 22.5s<1.6s

       1/50      10.1G      2.777      1.977      1.242        151       1024: 93% ━━━━━━━━━━━─ 115/124 6.3it/s 22.6s<1.4s

       1/50      10.1G      2.771      1.972      1.241        107       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 22.8s<1.2s

       1/50      10.1G      2.768      1.968       1.24        144       1024: 94% ━━━━━━━━━━━─ 117/124 6.2it/s 22.9s<1.1s

       1/50      10.1G      2.764      1.963      1.239        134       1024: 95% ━━━━━━━━━━━─ 118/124 6.4it/s 23.1s<0.9s

       1/50      10.1G      2.761      1.957      1.238        110       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 23.2s<0.8s

       1/50      10.1G      2.757      1.953      1.238        119       1024: 97% ━━━━━━━━━━━╸ 120/124 6.2it/s 23.4s<0.6s

       1/50      10.1G      2.752      1.949      1.237        118       1024: 98% ━━━━━━━━━━━╸ 121/124 6.3it/s 23.6s<0.5s

       1/50      10.1G      2.751      1.946      1.236        105       1024: 98% ━━━━━━━━━━━╸ 122/124 6.3it/s 23.7s<0.3s

       1/50      10.1G      2.749      1.942      1.235         93       1024: 99% ━━━━━━━━━━━╸ 123/124 6.2it/s 23.9s<0.2s

       1/50      10.1G      2.749      1.942      1.235         93       1024: 100% ━━━━━━━━━━━━ 124/124 5.2it/s 23.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 3.5s/it 1.0s<1:10

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 2.7it/s 1.2s<7.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 4.3it/s 1.3s<4.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 5.4it/s 1.4s<3.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 5.7it/s 1.6s<2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 6.6it/s 1.7s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.0it/s 1.8s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 7.5it/s 1.9s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 7.7it/s 2.1s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 7.9it/s 2.2s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.0it/s 2.3s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.2it/s 2.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.2it/s 2.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.2it/s 2.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.2it/s 2.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.3it/s 2.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.2it/s 3.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.3it/s 3.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.2it/s 3.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.3it/s 3.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.8it/s 4.4s

                   all        330       4227      0.407      0.408      0.363      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/50      10.1G       2.12       1.41      1.078        116       1024: 0% ──────────── 0/124  0.2s

       2/50      10.1G      2.166      1.332      1.082        101       1024: 1% ──────────── 1/124 1.9it/s 0.3s<1:04

       2/50      10.1G      2.235      1.395      1.098        123       1024: 2% ──────────── 2/124 3.0it/s 0.5s<40.5s

       2/50      10.1G      2.269      1.402      1.107        125       1024: 2% ──────────── 3/124 4.0it/s 0.7s<30.3s

       2/50      10.1G      2.315        1.4      1.109        108       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.8s

       2/50      10.1G      2.347      1.409      1.098        138       1024: 4% ──────────── 5/124 5.1it/s 1.0s<23.3s

       2/50      10.1G      2.377      1.422      1.099        126       1024: 5% ╸─────────── 6/124 5.4it/s 1.1s<21.7s

       2/50      10.1G      2.378      1.409      1.116        119       1024: 6% ╸─────────── 7/124 5.8it/s 1.3s<20.1s

       2/50      10.1G       2.36      1.409       1.11        133       1024: 6% ╸─────────── 8/124 5.8it/s 1.5s<20.0s

       2/50      10.1G      2.363      1.404      1.108        121       1024: 7% ╸─────────── 9/124 6.1it/s 1.6s<18.8s

       2/50      10.1G      2.384      1.415      1.109        162       1024: 8% ╸─────────── 10/124 6.3it/s 1.8s<18.0s

       2/50      10.1G      2.402      1.411      1.105        121       1024: 9% ━─────────── 11/124 6.5it/s 1.9s<17.4s

       2/50      10.1G      2.385      1.402      1.096        106       1024: 10% ━─────────── 12/124 6.1it/s 2.1s<18.3s

       2/50      10.1G      2.372      1.385      1.088        158       1024: 10% ━─────────── 13/124 6.2it/s 2.2s<17.8s

       2/50      10.1G      2.374       1.38       1.08        217       1024: 11% ━─────────── 14/124 6.3it/s 2.4s<17.5s

       2/50      10.1G      2.372      1.373      1.079        159       1024: 12% ━─────────── 15/124 6.4it/s 2.6s<17.1s

       2/50      10.1G      2.364      1.365      1.075        108       1024: 13% ━╸────────── 16/124 6.2it/s 2.7s<17.5s

       2/50      10.1G      2.368      1.367      1.077        112       1024: 14% ━╸────────── 17/124 6.4it/s 2.9s<16.7s

       2/50      10.1G      2.363      1.367      1.079        165       1024: 15% ━╸────────── 18/124 6.5it/s 3.0s<16.3s

       2/50      10.1G      2.363      1.363      1.076        144       1024: 15% ━╸────────── 19/124 6.6it/s 3.2s<15.9s

       2/50      10.1G       2.36      1.358      1.078        122       1024: 16% ━╸────────── 20/124 6.4it/s 3.3s<16.3s

       2/50      10.1G      2.366      1.363      1.082        116       1024: 17% ━━────────── 21/124 6.5it/s 3.5s<15.8s

       2/50      10.1G      2.359      1.359      1.082        153       1024: 18% ━━────────── 22/124 6.6it/s 3.6s<15.4s

       2/50      10.1G      2.356      1.358      1.084        108       1024: 19% ━━────────── 23/124 6.6it/s 3.8s<15.3s

       2/50      10.1G      2.352      1.358      1.082        136       1024: 19% ━━────────── 24/124 6.3it/s 4.0s<15.7s

       2/50      10.1G      2.358       1.36      1.085        104       1024: 20% ━━────────── 25/124 6.5it/s 4.1s<15.3s

       2/50      10.1G      2.366      1.361       1.09        150       1024: 21% ━━╸───────── 26/124 6.6it/s 4.2s<14.9s

       2/50      10.1G      2.372      1.362       1.09        140       1024: 22% ━━╸───────── 27/124 6.7it/s 4.4s<14.5s

       2/50      10.1G       2.37      1.356      1.089        171       1024: 23% ━━╸───────── 28/124 6.4it/s 4.6s<15.1s

       2/50      10.1G      2.372      1.356      1.088        139       1024: 23% ━━╸───────── 29/124 6.4it/s 4.7s<14.8s

       2/50      10.1G      2.364      1.357      1.088        146       1024: 24% ━━╸───────── 30/124 6.5it/s 4.9s<14.4s

       2/50      10.1G      2.365      1.357      1.089        112       1024: 25% ━━━───────── 31/124 6.6it/s 5.0s<14.1s

       2/50      10.1G      2.361      1.358      1.091        121       1024: 26% ━━━───────── 32/124 6.3it/s 5.2s<14.5s

       2/50      10.1G      2.359      1.359       1.09        110       1024: 27% ━━━───────── 33/124 6.5it/s 5.3s<14.0s

       2/50      10.1G      2.356      1.357      1.091        117       1024: 27% ━━━───────── 34/124 6.6it/s 5.5s<13.6s

       2/50      10.1G      2.359      1.356      1.091        179       1024: 28% ━━━───────── 35/124 6.7it/s 5.6s<13.3s

       2/50      10.1G      2.357      1.352      1.091        129       1024: 29% ━━━───────── 36/124 6.4it/s 5.8s<13.7s

       2/50      10.1G       2.37      1.359      1.092        128       1024: 30% ━━━╸──────── 37/124 6.5it/s 6.0s<13.4s

       2/50      10.1G      2.366      1.357       1.09        157       1024: 31% ━━━╸──────── 38/124 6.5it/s 6.1s<13.3s

       2/50      10.1G      2.362      1.355      1.091        112       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.3s<13.2s

       2/50      10.1G      2.355      1.352      1.091        120       1024: 32% ━━━╸──────── 40/124 6.2it/s 6.4s<13.5s

       2/50      10.1G      2.349      1.352      1.088        137       1024: 33% ━━━╸──────── 41/124 6.3it/s 6.6s<13.1s

       2/50      10.1G      2.351      1.354       1.09        101       1024: 34% ━━━━──────── 42/124 6.4it/s 6.7s<12.9s

       2/50      10.1G      2.365      1.358      1.093        108       1024: 35% ━━━━──────── 43/124 6.4it/s 6.9s<12.7s

       2/50      10.1G      2.364      1.357      1.092        116       1024: 35% ━━━━──────── 44/124 6.1it/s 7.1s<13.1s

       2/50      10.1G      2.363      1.358      1.091        117       1024: 36% ━━━━──────── 45/124 6.2it/s 7.2s<12.8s

       2/50      10.1G      2.357      1.356       1.09        143       1024: 37% ━━━━──────── 46/124 6.2it/s 7.4s<12.5s

       2/50      10.1G      2.363      1.359       1.09        183       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.5s<12.0s

       2/50      10.1G      2.352      1.354      1.089        111       1024: 39% ━━━━╸─────── 48/124 6.2it/s 7.7s<12.3s

       2/50      10.1G      2.353      1.356      1.088        154       1024: 40% ━━━━╸─────── 49/124 6.3it/s 7.9s<11.9s

       2/50      10.1G      2.348      1.356      1.086        144       1024: 40% ━━━━╸─────── 50/124 6.4it/s 8.0s<11.6s

       2/50      10.1G      2.346      1.357      1.086         97       1024: 41% ━━━━╸─────── 51/124 6.5it/s 8.2s<11.2s

       2/50      10.1G      2.345      1.356      1.085        168       1024: 42% ━━━━━─────── 52/124 6.3it/s 8.3s<11.5s

       2/50      10.1G      2.349      1.358      1.085        169       1024: 43% ━━━━━─────── 53/124 6.5it/s 8.5s<11.0s

       2/50      10.1G      2.348      1.357      1.083        101       1024: 44% ━━━━━─────── 54/124 6.6it/s 8.6s<10.6s

       2/50      10.1G      2.341      1.354      1.081        118       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.8s<10.3s

       2/50      10.1G      2.335      1.353       1.08        118       1024: 45% ━━━━━─────── 56/124 6.3it/s 9.0s<10.7s

       2/50      10.1G      2.332      1.351       1.08        116       1024: 46% ━━━━━╸────── 57/124 6.5it/s 9.1s<10.3s

       2/50      10.1G      2.333      1.352      1.082        133       1024: 47% ━━━━━╸────── 58/124 6.5it/s 9.3s<10.1s

       2/50      10.1G       2.33      1.351      1.081        109       1024: 48% ━━━━━╸────── 59/124 6.6it/s 9.4s<9.8s

       2/50      10.1G      2.329      1.353      1.081        121       1024: 48% ━━━━━╸────── 60/124 6.4it/s 9.6s<10.1s

       2/50      10.1G      2.327      1.354       1.08        115       1024: 49% ━━━━━╸────── 61/124 6.5it/s 9.7s<9.6s

       2/50      10.1G      2.325      1.355       1.08        153       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.9s<9.4s

       2/50      10.1G      2.327      1.355       1.08        121       1024: 51% ━━━━━━────── 63/124 6.7it/s 10.0s<9.2s

       2/50      10.1G      2.323      1.356      1.079        140       1024: 52% ━━━━━━────── 64/124 6.7it/s 10.2s<9.0s

       2/50      10.1G      2.323      1.355      1.078        161       1024: 52% ━━━━━━────── 65/124 6.4it/s 10.3s<9.2s

       2/50      10.1G      2.326      1.355      1.078        154       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.5s<8.9s

       2/50      10.1G      2.328      1.355      1.079        114       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.6s<8.6s

       2/50      10.1G       2.33      1.353      1.079        154       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.8s<8.4s

       2/50      10.1G      2.325       1.35      1.078        148       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.9s<8.2s

       2/50      10.1G      2.325      1.348      1.078        119       1024: 56% ━━━━━━╸───── 70/124 6.3it/s 11.1s<8.5s

       2/50      10.1G       2.33      1.349      1.078        179       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 11.3s<8.2s

       2/50      10.1G      2.326      1.347      1.076        195       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.4s<7.9s

       2/50      10.1G      2.328       1.35      1.077        121       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.6s<7.7s

       2/50      10.1G      2.324      1.349      1.077        142       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.7s<7.4s

       2/50      10.1G      2.319      1.348      1.075        153       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.9s<7.6s

       2/50      10.1G      2.318      1.344      1.074        117       1024: 61% ━━━━━━━───── 76/124 6.5it/s 12.0s<7.4s

       2/50      10.1G      2.316      1.343      1.075        114       1024: 62% ━━━━━━━───── 77/124 6.6it/s 12.2s<7.1s

       2/50      10.1G      2.316      1.345      1.076        116       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.3s<6.9s

       2/50      10.1G      2.318      1.348      1.077        124       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.5s<6.7s

       2/50      10.1G      2.321      1.347      1.077        129       1024: 65% ━━━━━━━╸──── 80/124 6.4it/s 12.6s<6.8s

       2/50      10.1G      2.319      1.345      1.078        135       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.8s<6.5s

       2/50      10.1G      2.318      1.344      1.077        127       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.9s<6.3s

       2/50      10.1G      2.317      1.343      1.076        164       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 13.1s<6.1s

       2/50      10.1G      2.314      1.339      1.075        143       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 13.2s<5.9s

       2/50      10.1G      2.311      1.337      1.075        110       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 13.4s<6.0s

       2/50      10.1G      2.312      1.336      1.077        125       1024: 69% ━━━━━━━━──── 86/124 6.5it/s 13.5s<5.9s

       2/50      10.1G      2.312      1.335      1.077        129       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.7s<5.6s

       2/50      10.1G       2.31      1.334      1.077        128       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.8s<5.4s

       2/50      10.1G      2.309      1.334      1.077        178       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 14.0s<5.2s

       2/50      10.1G      2.309      1.338      1.077        107       1024: 73% ━━━━━━━━╸─── 90/124 6.4it/s 14.2s<5.3s

       2/50      10.1G      2.307      1.337      1.076        175       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 14.3s<5.2s

       2/50      10.1G      2.307      1.337      1.076        116       1024: 74% ━━━━━━━━╸─── 92/124 6.4it/s 14.5s<5.0s

       2/50      10.1G      2.306      1.337      1.076        133       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.6s<4.7s

       2/50      10.1G      2.303      1.335      1.075        116       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.8s<4.5s

       2/50      10.1G      2.302      1.335      1.075        141       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.9s<4.5s

       2/50      10.1G        2.3      1.333      1.074        116       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 15.1s<4.3s

       2/50      10.1G      2.297      1.331      1.074        128       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 15.2s<4.1s

       2/50      10.1G      2.296      1.331      1.073        177       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.4s<3.9s

       2/50      10.1G      2.295      1.329      1.072        137       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.5s<3.7s

       2/50      10.1G      2.293      1.329      1.073        115       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.7s<3.7s

       2/50      10.1G      2.291      1.327      1.072        152       1024: 81% ━━━━━━━━━╸── 101/124 6.4it/s 15.8s<3.6s

       2/50      10.1G      2.286      1.325      1.072        114       1024: 82% ━━━━━━━━━╸── 102/124 6.5it/s 16.0s<3.4s

       2/50      10.1G      2.285      1.325      1.071        197       1024: 83% ━━━━━━━━━╸── 103/124 6.6it/s 16.1s<3.2s

       2/50      10.1G      2.285      1.323      1.072        106       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 16.3s<3.0s

       2/50      10.1G      2.282      1.323      1.071        144       1024: 85% ━━━━━━━━━━── 105/124 6.3it/s 16.5s<3.0s

       2/50      10.1G      2.284      1.323      1.071        121       1024: 85% ━━━━━━━━━━── 106/124 6.5it/s 16.6s<2.8s

       2/50      10.1G       2.28      1.321       1.07        149       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.8s<2.6s

       2/50      10.1G      2.278      1.319      1.069        167       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.9s<2.4s

       2/50      10.1G      2.276      1.319      1.069        119       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 17.1s<2.2s

       2/50      10.1G      2.274      1.317      1.068        178       1024: 89% ━━━━━━━━━━╸─ 110/124 6.4it/s 17.2s<2.2s

       2/50      10.1G      2.277      1.318      1.069        118       1024: 90% ━━━━━━━━━━╸─ 111/124 6.6it/s 17.4s<2.0s

       2/50      10.1G      2.279      1.318      1.069        142       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.5s<1.8s

       2/50      10.1G       2.28      1.318      1.069        139       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.7s<1.6s

       2/50      10.1G      2.281      1.318      1.069        109       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.8s<1.5s

       2/50      10.1G      2.283      1.318       1.07        111       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 18.0s<1.4s

       2/50      10.1G       2.28      1.316      1.069        171       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 18.1s<1.2s

       2/50      10.1G      2.278      1.315      1.068        195       1024: 94% ━━━━━━━━━━━─ 117/124 6.5it/s 18.3s<1.1s

       2/50      10.1G       2.28      1.315      1.069        109       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 18.4s<0.9s

       2/50      10.1G      2.278      1.314      1.069        104       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.6s<0.7s

       2/50      10.1G      2.277      1.313      1.068        163       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.7s<0.6s

       2/50      10.1G      2.278      1.314      1.069        145       1024: 98% ━━━━━━━━━━━╸ 121/124 6.4it/s 18.9s<0.5s

       2/50      10.1G      2.277      1.313      1.069        171       1024: 98% ━━━━━━━━━━━╸ 122/124 6.5it/s 19.0s<0.3s

       2/50      10.1G      2.275      1.313      1.069        154       1024: 99% ━━━━━━━━━━━╸ 123/124 6.6it/s 19.2s<0.2s

       2/50      10.1G      2.275      1.313      1.069        154       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 19.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.8it/s 0.1s<7.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.7it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.4it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.6it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 7.8it/s 1.0s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.0it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.1it/s 1.2s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.2it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.6s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.3it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.2it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.2it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.3it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.3it/s 2.2s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.3it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.4it/s 2.5s

                   all        330       4227      0.437      0.486       0.46      0.263

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/50      10.1G      1.872      1.209     0.9876        142       1024: 0% ──────────── 0/124  0.1s

       3/50      10.1G       2.06      1.204     0.9976        149       1024: 1% ──────────── 1/124 2.1it/s 0.3s<60.0s

       3/50      10.1G      2.001      1.207      1.007        112       1024: 2% ──────────── 2/124 3.4it/s 0.4s<36.1s

       3/50      10.1G      2.026      1.198      1.009        142       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.6s

       3/50      10.1G      2.096      1.198      1.013        189       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.8s

       3/50      10.1G      2.103      1.217      1.017        118       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.8s

       3/50      10.1G      2.108      1.217      1.026        140       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.0s

       3/50      10.1G      2.128      1.227      1.034        121       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

       3/50      10.1G      2.102      1.214      1.039        125       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.5s

       3/50      10.1G      2.135      1.211      1.038        153       1024: 7% ╸─────────── 9/124 6.1it/s 1.5s<18.8s

       3/50      10.1G      2.153      1.217      1.042        121       1024: 8% ╸─────────── 10/124 6.3it/s 1.7s<18.2s

       3/50      10.1G      2.176      1.223      1.045        142       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.5s

       3/50      10.1G      2.163      1.212      1.047        105       1024: 10% ━─────────── 12/124 6.6it/s 2.0s<17.0s

       3/50      10.1G      2.177      1.213      1.052        122       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.6s

       3/50      10.1G      2.185      1.206      1.055        131       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.3s

       3/50      10.1G      2.202      1.206       1.06        138       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<16.9s

       3/50      10.1G      2.195      1.209      1.059        131       1024: 13% ━╸────────── 16/124 6.5it/s 2.6s<16.7s

       3/50      10.1G      2.192      1.209      1.062        151       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.3s

       3/50      10.1G      2.204      1.213      1.064        120       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

       3/50      10.1G      2.209      1.212      1.067        141       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

       3/50      10.1G      2.217      1.216      1.067        110       1024: 16% ━╸────────── 20/124 6.8it/s 3.2s<15.3s

       3/50      10.1G      2.209      1.216      1.066        191       1024: 17% ━━────────── 21/124 6.5it/s 3.3s<15.9s

       3/50      10.1G      2.203      1.212      1.063        131       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.4s

       3/50      10.1G      2.201      1.214      1.063        107       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

       3/50      10.1G      2.203      1.211      1.062        108       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.8s

       3/50      10.1G      2.209      1.212      1.065        130       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

       3/50      10.1G      2.209      1.211       1.06        191       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.4s

       3/50      10.1G      2.209      1.211      1.058        137       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.9s

       3/50      10.1G      2.209      1.209      1.058        116       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.5s

       3/50      10.1G      2.206      1.209      1.057        101       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

       3/50      10.1G      2.212      1.209      1.058        139       1024: 24% ━━╸───────── 30/124 6.8it/s 4.7s<13.9s

       3/50      10.1G      2.208      1.208      1.055        197       1024: 25% ━━━───────── 31/124 6.8it/s 4.8s<13.7s

       3/50      10.1G      2.221      1.215      1.055        180       1024: 26% ━━━───────── 32/124 6.8it/s 5.0s<13.6s

       3/50      10.1G      2.218      1.216      1.057        121       1024: 27% ━━━───────── 33/124 6.5it/s 5.2s<14.1s

       3/50      10.1G      2.221      1.219      1.057        116       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.7s

       3/50      10.1G      2.223      1.221      1.061        105       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

       3/50      10.1G      2.218      1.226      1.061        127       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

       3/50      10.1G       2.22      1.225      1.061        118       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

       3/50      10.1G      2.223      1.224      1.059        140       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

       3/50      10.1G      2.221      1.223      1.057        124       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.2s

       3/50      10.1G      2.219      1.221      1.056        143       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

       3/50      10.1G      2.218      1.222      1.057        112       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.6s

       3/50      10.1G      2.223      1.226      1.061        111       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

       3/50      10.1G       2.22      1.223      1.059        140       1024: 35% ━━━━──────── 43/124 6.7it/s 6.7s<12.2s

       3/50      10.1G      2.219      1.223      1.059        124       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

       3/50      10.1G      2.218      1.222      1.059        107       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

       3/50      10.1G      2.217      1.219       1.06        124       1024: 37% ━━━━──────── 46/124 6.5it/s 7.1s<12.0s

       3/50      10.1G      2.214      1.217       1.06        149       1024: 38% ━━━━╸─────── 47/124 6.6it/s 7.3s<11.7s

       3/50      10.1G      2.213       1.22      1.059        111       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.4s

       3/50      10.1G      2.205      1.216      1.057        125       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.1s

       3/50      10.1G      2.204      1.215      1.056        175       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

       3/50      10.1G      2.198      1.213      1.055        135       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.8s

       3/50      10.1G      2.197      1.212      1.055        133       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.0s<10.6s

       3/50      10.1G      2.201      1.215      1.055        147       1024: 43% ━━━━━─────── 53/124 6.4it/s 8.2s<11.1s

       3/50      10.1G        2.2      1.213      1.057        135       1024: 44% ━━━━━─────── 54/124 6.5it/s 8.3s<10.8s

       3/50      10.1G      2.201      1.212      1.056        122       1024: 44% ━━━━━─────── 55/124 6.6it/s 8.5s<10.5s

       3/50      10.1G      2.202      1.212      1.056        181       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.6s<10.2s

       3/50      10.1G      2.204      1.212      1.056        171       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

       3/50      10.1G      2.204      1.211      1.056        104       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.8s

       3/50      10.1G      2.204      1.212      1.055        216       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.1s<9.6s

       3/50      10.1G      2.202      1.212      1.054        193       1024: 48% ━━━━━╸────── 60/124 6.4it/s 9.2s<9.9s

       3/50      10.1G      2.201      1.211      1.054        131       1024: 49% ━━━━━╸────── 61/124 6.5it/s 9.4s<9.7s

       3/50      10.1G      2.201      1.212      1.055        109       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.5s<9.4s

       3/50      10.1G        2.2      1.212      1.054        118       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

       3/50      10.1G      2.196      1.212      1.053        163       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<8.9s

       3/50      10.1G      2.194       1.21      1.052        149       1024: 52% ━━━━━━────── 65/124 6.7it/s 10.0s<8.9s

       3/50      10.1G      2.191      1.209      1.052        144       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.1s<8.8s

       3/50      10.1G      2.194       1.21      1.051        130       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

       3/50      10.1G      2.197      1.212      1.051        191       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.4s<8.6s

       3/50      10.1G      2.195      1.211      1.051        148       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

       3/50      10.1G      2.196      1.211      1.051        155       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.2s

       3/50      10.1G      2.197      1.211      1.051        127       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<8.0s

       3/50      10.1G      2.198      1.209       1.05        136       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.0s<7.8s

       3/50      10.1G      2.199       1.21       1.05        146       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.2s<7.6s

       3/50      10.1G      2.201      1.214      1.052        108       1024: 60% ━━━━━━━───── 74/124 6.5it/s 11.4s<7.7s

       3/50      10.1G      2.201      1.214      1.051        121       1024: 60% ━━━━━━━───── 75/124 6.6it/s 11.5s<7.4s

       3/50      10.1G      2.198      1.212       1.05        126       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.2s

       3/50      10.1G      2.199      1.213      1.051        179       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.8s<7.0s

       3/50      10.1G      2.202      1.215      1.051        139       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

       3/50      10.1G      2.202      1.214      1.049        199       1024: 64% ━━━━━━━╸──── 79/124 6.8it/s 12.1s<6.6s

       3/50      10.1G      2.202      1.213       1.05        157       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.2s<6.5s

       3/50      10.1G      2.203      1.212       1.05        118       1024: 65% ━━━━━━━╸──── 81/124 6.5it/s 12.4s<6.6s

       3/50      10.1G      2.201      1.212       1.05        141       1024: 66% ━━━━━━━╸──── 82/124 6.5it/s 12.6s<6.4s

       3/50      10.1G      2.205      1.214      1.051        137       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.7s<6.3s

       3/50      10.1G      2.203      1.214       1.05        139       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.9s<6.0s

       3/50      10.1G      2.205      1.216      1.052        116       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.8s

       3/50      10.1G      2.203      1.214      1.051        145       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.6s

       3/50      10.1G      2.203      1.214      1.051        165       1024: 70% ━━━━━━━━──── 87/124 6.8it/s 13.3s<5.5s

       3/50      10.1G      2.201      1.213      1.051        122       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.6s

       3/50      10.1G      2.197      1.213       1.05        131       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

       3/50      10.1G      2.196      1.211       1.05        170       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

       3/50      10.1G      2.196      1.212       1.05        117       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

       3/50      10.1G      2.194      1.211      1.049        213       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.1s<4.7s

       3/50      10.1G      2.192      1.212      1.049        113       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.2s<4.6s

       3/50      10.1G      2.189      1.212      1.049        147       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

       3/50      10.1G      2.191      1.212      1.048        152       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

       3/50      10.1G      2.188       1.21      1.047        125       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.7s<4.3s

       3/50      10.1G      2.189      1.211      1.048        131       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

       3/50      10.1G      2.187       1.21      1.047        166       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

       3/50      10.1G      2.189       1.21      1.048        128       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.1s<3.7s

       3/50      10.1G      2.188       1.21      1.047        172       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.3s<3.6s

       3/50      10.1G      2.189      1.209      1.048         99       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.4s<3.4s

       3/50      10.1G      2.188      1.209      1.047        181       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

       3/50      10.1G      2.189      1.208      1.047        150       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

       3/50      10.1G       2.19      1.208      1.047        147       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.9s<3.1s

       3/50      10.1G      2.188      1.206      1.046         91       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

       3/50      10.1G      2.189      1.208      1.047        135       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

       3/50      10.1G      2.188      1.207      1.046        138       1024: 86% ━━━━━━━━━━── 107/124 6.8it/s 16.3s<2.5s

       3/50      10.1G      2.188      1.207      1.046        109       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.5s<2.3s

       3/50      10.1G      2.188      1.205      1.046        136       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.6s<2.2s

       3/50      10.1G      2.187      1.205      1.046        129       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

       3/50      10.1G      2.186      1.205      1.046        108       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

       3/50      10.1G      2.186      1.206      1.047        103       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.1s<1.8s

       3/50      10.1G      2.184      1.204      1.046        131       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.2s<1.7s

       3/50      10.1G      2.181      1.203      1.045        100       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

       3/50      10.1G      2.182      1.202      1.045        166       1024: 93% ━━━━━━━━━━━─ 115/124 6.8it/s 17.5s<1.3s

       3/50      10.1G      2.181      1.201      1.045        141       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.7s<1.2s

       3/50      10.1G      2.182      1.202      1.047        104       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.8s<1.0s

       3/50      10.1G      2.184      1.203      1.047        126       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

       3/50      10.1G      2.184      1.203      1.047        137       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

       3/50      10.1G      2.183      1.203      1.047        132       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.3s<0.6s

       3/50      10.1G      2.182      1.202      1.046        141       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.5s

       3/50      10.1G      2.181      1.202      1.046        131       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.6s<0.3s

       3/50      10.1G      2.179      1.203      1.046        126       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.7s<0.1s

       3/50      10.1G      2.179      1.203      1.046        126       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.2it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.4it/s 0.4s<3.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.3it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.5it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 1.0s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.1it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.3it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.5it/s 2.5s

                   all        330       4227      0.546      0.512      0.512      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/50      10.1G      2.162      1.273      1.068        115       1024: 0% ──────────── 0/124  0.1s

       4/50      10.1G      2.248      1.206       1.06        150       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.5s

       4/50      10.1G      2.249      1.218      1.062        119       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.6s

       4/50      10.1G       2.23      1.213      1.067        109       1024: 2% ──────────── 3/124 4.2it/s 0.6s<28.6s

       4/50      10.1G      2.184      1.203      1.063        150       1024: 3% ──────────── 4/124 5.0it/s 0.7s<23.8s

       4/50      10.1G      2.173      1.182      1.051        145       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.3s

       4/50      10.1G      2.177       1.17      1.034        146       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

       4/50      10.1G      2.147      1.151      1.025        102       1024: 6% ╸─────────── 7/124 6.3it/s 1.2s<18.6s

       4/50      10.1G      2.177      1.173      1.036        132       1024: 6% ╸─────────── 8/124 6.5it/s 1.3s<17.9s

       4/50      10.1G      2.157      1.153      1.027        151       1024: 7% ╸─────────── 9/124 6.6it/s 1.5s<17.4s

       4/50      10.1G      2.162      1.151      1.028        127       1024: 8% ╸─────────── 10/124 6.7it/s 1.6s<17.0s

       4/50      10.1G      2.164      1.148      1.026        148       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

       4/50      10.1G      2.143      1.142      1.023        142       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.5s

       4/50      10.1G      2.147      1.148       1.02        132       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.9s

       4/50      10.1G      2.143      1.144      1.022        142       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.5s

       4/50      10.1G      2.145      1.144      1.023        151       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.2s

       4/50      10.1G      2.143       1.14       1.02        174       1024: 13% ━╸────────── 16/124 6.8it/s 2.5s<16.0s

       4/50      10.1G      2.139      1.132      1.022        112       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.7s

       4/50      10.1G       2.13      1.133      1.022        161       1024: 15% ━╸────────── 18/124 6.8it/s 2.8s<15.6s

       4/50      10.1G      2.138      1.128      1.024        159       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.2s

       4/50      10.1G       2.13      1.125      1.024        130       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.0s

       4/50      10.1G      2.125      1.122      1.023        134       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

       4/50      10.1G      2.125      1.125      1.021        149       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.3s

       4/50      10.1G       2.13      1.127      1.021        151       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

       4/50      10.1G      2.117      1.124      1.017        200       1024: 19% ━━────────── 24/124 6.6it/s 3.7s<15.0s

       4/50      10.1G      2.117      1.124      1.018        132       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.7s

       4/50      10.1G      2.118       1.12      1.022        119       1024: 21% ━━╸───────── 26/124 6.8it/s 4.0s<14.5s

       4/50      10.1G      2.117      1.122      1.022        113       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<15.0s

       4/50      10.1G      2.108      1.119       1.02        120       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.5s

       4/50      10.1G      2.104      1.117      1.018        145       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

       4/50      10.1G      2.101      1.115      1.017        166       1024: 24% ━━╸───────── 30/124 6.7it/s 4.6s<14.0s

       4/50      10.1G      2.097      1.118      1.017        168       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

       4/50      10.1G      2.097      1.118      1.019        136       1024: 26% ━━━───────── 32/124 6.8it/s 4.9s<13.6s

       4/50      10.1G      2.098       1.12      1.018        145       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

       4/50      10.1G      2.094      1.118      1.018        126       1024: 27% ━━━───────── 34/124 6.8it/s 5.2s<13.2s

       4/50      10.1G      2.097      1.121       1.02        121       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.7s

       4/50      10.1G      2.098      1.122       1.02        125       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.3s

       4/50      10.1G      2.097      1.122       1.02        119       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

       4/50      10.1G       2.09       1.12       1.02        137       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.8s<13.0s

       4/50      10.1G      2.088      1.121       1.02        146       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.0s<12.7s

       4/50      10.1G      2.083      1.121       1.02        120       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.1s<12.6s

       4/50      10.1G      2.092      1.127      1.021        135       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.5s

       4/50      10.1G      2.093      1.127      1.022        122       1024: 34% ━━━━──────── 42/124 6.7it/s 6.4s<12.2s

       4/50      10.1G       2.09      1.125      1.021        139       1024: 35% ━━━━──────── 43/124 6.4it/s 6.6s<12.6s

       4/50      10.1G      2.091      1.126      1.023        142       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.4s

       4/50      10.1G       2.09      1.125      1.021        147       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<12.0s

       4/50      10.1G      2.084      1.124      1.021        114       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

       4/50      10.1G      2.087      1.123      1.021        132       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.2s<11.4s

       4/50      10.1G      2.082      1.123       1.02        156       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

       4/50      10.1G      2.082      1.124      1.022        132       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.0s

       4/50      10.1G      2.085      1.124      1.023        105       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.6s<10.8s

       4/50      10.1G      2.081      1.124      1.023        101       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.2s

       4/50      10.1G       2.08      1.125      1.022        218       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

       4/50      10.1G       2.08      1.123      1.024        113       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

       4/50      10.1G      2.078      1.123      1.023        116       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

       4/50      10.1G      2.081      1.122      1.023        185       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.2s

       4/50      10.1G      2.082      1.122      1.022        142       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.5s<10.0s

       4/50      10.1G      2.081      1.121      1.023        130       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.8s

       4/50      10.1G      2.077       1.12      1.022        118       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.6s

       4/50      10.1G      2.073      1.118       1.02        142       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.0s<9.9s

       4/50      10.1G      2.073      1.116       1.02        113       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

       4/50      10.1G      2.072      1.115       1.02        147       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.5s

       4/50      10.1G      2.079      1.118      1.022        174       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.2s

       4/50      10.1G      2.076      1.117      1.021        127       1024: 51% ━━━━━━────── 63/124 6.8it/s 9.6s<9.0s

       4/50      10.1G      2.079      1.117      1.021        106       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.7s<8.8s

       4/50      10.1G      2.077      1.116      1.021        131       1024: 52% ━━━━━━────── 65/124 6.9it/s 9.9s<8.6s

       4/50      10.1G      2.081      1.117      1.021        160       1024: 53% ━━━━━━────── 66/124 6.9it/s 10.0s<8.4s

       4/50      10.1G      2.083      1.118      1.022        117       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.2s<8.7s

       4/50      10.1G       2.08      1.115      1.022        117       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.3s<8.3s

       4/50      10.1G      2.081      1.114      1.022        130       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

       4/50      10.1G       2.08      1.114      1.021        184       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.6s<8.0s

       4/50      10.1G      2.078      1.114      1.021        118       1024: 57% ━━━━━━╸───── 71/124 6.8it/s 10.8s<7.7s

       4/50      10.1G      2.081      1.114      1.021        131       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 10.9s<7.7s

       4/50      10.1G      2.082      1.115      1.022        102       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

       4/50      10.1G       2.08      1.115      1.021        141       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.2s<7.4s

       4/50      10.1G       2.08      1.115      1.022        136       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.4s<7.6s

       4/50      10.1G      2.081      1.118      1.022        124       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.5s<7.3s

       4/50      10.1G       2.08      1.118      1.023        111       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.7s<7.0s

       4/50      10.1G      2.074      1.116      1.022        144       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.8s<6.8s

       4/50      10.1G      2.077      1.118      1.023        119       1024: 64% ━━━━━━━╸──── 79/124 6.8it/s 12.0s<6.6s

       4/50      10.1G      2.074      1.117      1.024        107       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.1s<6.5s

       4/50      10.1G      2.073      1.117      1.024        118       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.3s<6.3s

       4/50      10.1G      2.074      1.116      1.024        160       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.4s<6.1s

       4/50      10.1G      2.075      1.116      1.024        153       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.6s<6.3s

       4/50      10.1G      2.073      1.115      1.023        115       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.7s<6.0s

       4/50      10.1G      2.074      1.115      1.023        120       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.9s<5.8s

       4/50      10.1G      2.071      1.114      1.022        100       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.0s<5.6s

       4/50      10.1G      2.069      1.112      1.021        154       1024: 70% ━━━━━━━━──── 87/124 6.8it/s 13.2s<5.5s

       4/50      10.1G       2.07      1.112      1.022        110       1024: 71% ━━━━━━━━╸─── 88/124 6.8it/s 13.3s<5.3s

       4/50      10.1G      2.067      1.111      1.021        136       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.2s

       4/50      10.1G      2.065       1.11      1.021        154       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.6s<5.1s

       4/50      10.1G      2.065       1.11       1.02        138       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.8s<5.1s

       4/50      10.1G      2.063       1.11       1.02        120       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 13.9s<4.8s

       4/50      10.1G      2.068      1.111       1.02        143       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

       4/50      10.1G      2.069      1.113      1.021        134       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.2s<4.4s

       4/50      10.1G      2.074      1.114      1.021        144       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 14.4s<4.3s

       4/50      10.1G      2.073      1.114      1.021        133       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.5s<4.2s

       4/50      10.1G      2.075      1.115       1.02        138       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.0s

       4/50      10.1G      2.074      1.115       1.02        129       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.8s<3.9s

       4/50      10.1G      2.074      1.115       1.02        147       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.0s<3.9s

       4/50      10.1G      2.075      1.115      1.021        147       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.1s<3.6s

       4/50      10.1G      2.074      1.114       1.02        161       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.3s<3.4s

       4/50      10.1G      2.075      1.114       1.02        128       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.4s<3.3s

       4/50      10.1G      2.074      1.113       1.02        119       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.6s<3.1s

       4/50      10.1G      2.076      1.114       1.02        141       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.7s<2.9s

       4/50      10.1G      2.078      1.115       1.02        187       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 15.9s<2.8s

       4/50      10.1G       2.08      1.116      1.021        118       1024: 85% ━━━━━━━━━━── 106/124 6.9it/s 16.0s<2.6s

       4/50      10.1G      2.082      1.116      1.021        107       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.2s<2.6s

       4/50      10.1G      2.083      1.117      1.022        111       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.3s<2.4s

       4/50      10.1G      2.085      1.117      1.022        171       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.5s<2.2s

       4/50      10.1G      2.087      1.119      1.023        104       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.6s<2.1s

       4/50      10.1G      2.085      1.118      1.023        119       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.8s<1.9s

       4/50      10.1G      2.084      1.117      1.023        148       1024: 90% ━━━━━━━━━━╸─ 112/124 6.9it/s 16.9s<1.7s

       4/50      10.1G      2.084      1.119      1.022        134       1024: 91% ━━━━━━━━━━╸─ 113/124 6.9it/s 17.0s<1.6s

       4/50      10.1G      2.085       1.12      1.023        102       1024: 92% ━━━━━━━━━━━─ 114/124 6.9it/s 17.2s<1.4s

       4/50      10.1G      2.083       1.12      1.022        165       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.4s<1.4s

       4/50      10.1G      2.084      1.121      1.022        130       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.5s<1.2s

       4/50      10.1G      2.085      1.121      1.022        145       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.7s<1.0s

       4/50      10.1G      2.084      1.122      1.022        113       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.8s<0.9s

       4/50      10.1G      2.084      1.121      1.022        112       1024: 96% ━━━━━━━━━━━╸ 119/124 6.8it/s 17.9s<0.7s

       4/50      10.1G      2.083       1.12      1.022        163       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.1s<0.6s

       4/50      10.1G      2.083      1.119      1.022        177       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.2s<0.4s

       4/50      10.1G      2.082      1.119      1.021        151       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.4s<0.3s

       4/50      10.1G      2.082       1.12      1.022        143       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.6s<0.2s

       4/50      10.1G      2.082       1.12      1.022        143       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.3it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.1it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.582      0.531      0.548      0.313

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/50      10.1G      2.012      1.072      1.045        145       1024: 0% ──────────── 0/124  0.1s

       5/50      10.1G      2.131      1.177      1.086        121       1024: 1% ──────────── 1/124 2.1it/s 0.3s<58.8s

       5/50      10.1G      2.138      1.197      1.073        152       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.5s

       5/50      10.1G      2.144      1.176      1.066        154       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.6s

       5/50      10.1G      2.131      1.155      1.052        173       1024: 3% ──────────── 4/124 5.2it/s 0.7s<22.9s

       5/50      10.1G      2.113      1.136      1.042        160       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.8s

       5/50      10.1G      2.097      1.145      1.028        229       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.6s

       5/50      10.1G       2.06       1.12      1.023        133       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.6s

       5/50      10.1G      2.035      1.105      1.015        122       1024: 6% ╸─────────── 8/124 6.2it/s 1.3s<18.8s

       5/50      10.1G      2.024      1.092      1.014        139       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

       5/50      10.1G      2.023      1.081      1.013        119       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.4s

       5/50      10.1G      2.016      1.075      1.014        128       1024: 9% ━─────────── 11/124 6.7it/s 1.8s<16.9s

       5/50      10.1G      2.004      1.082      1.014        117       1024: 10% ━─────────── 12/124 6.8it/s 1.9s<16.6s

       5/50      10.1G      2.007      1.084      1.013        138       1024: 10% ━─────────── 13/124 6.8it/s 2.1s<16.3s

       5/50      10.1G      2.013      1.086      1.011        120       1024: 11% ━─────────── 14/124 6.9it/s 2.2s<16.0s

       5/50      10.1G      2.005      1.085      1.008        162       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.6s

       5/50      10.1G          2      1.086      1.008        122       1024: 13% ━╸────────── 16/124 6.5it/s 2.5s<16.6s

       5/50      10.1G      2.018       1.09      1.015        120       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.4s

       5/50      10.1G      2.022      1.093      1.017        100       1024: 15% ━╸────────── 18/124 6.7it/s 2.8s<15.9s

       5/50      10.1G      2.032      1.092      1.019        148       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

       5/50      10.1G      2.032      1.094      1.017        184       1024: 16% ━╸────────── 20/124 6.8it/s 3.1s<15.3s

       5/50      10.1G      2.035      1.097      1.018        124       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.1s

       5/50      10.1G      2.049      1.096       1.02        152       1024: 18% ━━────────── 22/124 6.9it/s 3.4s<14.9s

       5/50      10.1G      2.043      1.095      1.018        180       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.9s

       5/50      10.1G      2.032      1.088      1.014        146       1024: 19% ━━────────── 24/124 6.5it/s 3.7s<15.3s

       5/50      10.1G      2.028      1.084      1.014        132       1024: 20% ━━────────── 25/124 6.5it/s 3.9s<15.1s

       5/50      10.1G      2.024      1.081      1.012        164       1024: 21% ━━╸───────── 26/124 6.6it/s 4.0s<14.8s

       5/50      10.1G      2.021      1.077       1.01        154       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.4s

       5/50      10.1G      2.028      1.079      1.011        160       1024: 23% ━━╸───────── 28/124 6.8it/s 4.3s<14.2s

       5/50      10.1G      2.034      1.082      1.011        143       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

       5/50      10.1G      2.039      1.084       1.01        168       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

       5/50      10.1G      2.043      1.083       1.01        142       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.6s

       5/50      10.1G      2.044      1.087      1.009        178       1024: 26% ━━━───────── 32/124 6.4it/s 5.0s<14.4s

       5/50      10.1G      2.041      1.086       1.01        175       1024: 27% ━━━───────── 33/124 6.5it/s 5.1s<13.9s

       5/50      10.1G      2.048      1.093      1.012         92       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

       5/50      10.1G      2.044      1.092      1.013        118       1024: 28% ━━━───────── 35/124 6.6it/s 5.4s<13.5s

       5/50      10.1G      2.038      1.091       1.01        121       1024: 29% ━━━───────── 36/124 6.6it/s 5.6s<13.3s

       5/50      10.1G      2.034      1.091       1.01        122       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

       5/50      10.1G       2.04      1.093      1.011        135       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.7s

       5/50      10.1G      2.037      1.092      1.011        134       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

       5/50      10.1G      2.039       1.09      1.011        181       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

       5/50      10.1G      2.038      1.087      1.009        116       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.4s

       5/50      10.1G      2.037      1.087      1.008        158       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.3s

       5/50      10.1G      2.039      1.088      1.007        113       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

       5/50      10.1G      2.043      1.088      1.009        151       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

       5/50      10.1G      2.041      1.085      1.008        150       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

       5/50      10.1G      2.042      1.087      1.009        146       1024: 37% ━━━━──────── 46/124 6.9it/s 7.0s<11.4s

       5/50      10.1G      2.045      1.088      1.011        116       1024: 38% ━━━━╸─────── 47/124 6.6it/s 7.2s<11.7s

       5/50      10.1G      2.049      1.087      1.011        132       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.5s

       5/50      10.1G      2.054      1.086      1.013        154       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

       5/50      10.1G      2.052      1.085      1.015        118       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

       5/50      10.1G      2.051      1.082      1.014        130       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.7s

       5/50      10.1G      2.051      1.082      1.012        153       1024: 42% ━━━━━─────── 52/124 6.8it/s 7.9s<10.5s

       5/50      10.1G      2.053      1.082      1.014        141       1024: 43% ━━━━━─────── 53/124 6.9it/s 8.1s<10.4s

       5/50      10.1G      2.052      1.083      1.013        171       1024: 44% ━━━━━─────── 54/124 6.9it/s 8.2s<10.2s

       5/50      10.1G      2.054      1.085      1.014        169       1024: 44% ━━━━━─────── 55/124 6.6it/s 8.4s<10.5s

       5/50      10.1G      2.051      1.083      1.014        117       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.5s<10.2s

       5/50      10.1G      2.043      1.081      1.014        111       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

       5/50      10.1G      2.045      1.083      1.014        116       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.8s

       5/50      10.1G      2.046      1.084      1.013        131       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.5s

       5/50      10.1G      2.053      1.085      1.013        142       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.1s<9.4s

       5/50      10.1G      2.055      1.087      1.014        140       1024: 49% ━━━━━╸────── 61/124 6.9it/s 9.3s<9.2s

       5/50      10.1G      2.053      1.086      1.015        112       1024: 50% ━━━━━━────── 62/124 6.9it/s 9.4s<9.0s

       5/50      10.1G      2.048      1.087      1.015        142       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.3s

       5/50      10.1G      2.045      1.086      1.015        127       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.7s<9.0s

       5/50      10.1G      2.042      1.083      1.015        100       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<8.9s

       5/50      10.1G      2.039      1.081      1.014        134       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.0s<8.7s

       5/50      10.1G       2.04       1.08      1.013        209       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.2s<8.5s

       5/50      10.1G      2.041       1.08      1.014        127       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.3s<8.3s

       5/50      10.1G      2.037      1.079      1.013        151       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

       5/50      10.1G      2.036      1.078      1.014        105       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.6s<8.1s

       5/50      10.1G      2.033      1.078      1.014        183       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.8s<8.3s

       5/50      10.1G       2.03      1.078      1.013        111       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

       5/50      10.1G      2.031      1.078      1.015        113       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

       5/50      10.1G      2.029      1.077      1.015        173       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.2s<7.4s

       5/50      10.1G      2.026      1.075      1.014        118       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

       5/50      10.1G      2.029      1.075      1.015        119       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.5s<7.1s

       5/50      10.1G      2.025      1.074      1.015         83       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

       5/50      10.1G      2.029      1.076      1.016        138       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.8s<6.7s

       5/50      10.1G       2.03      1.077      1.016        135       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.0s<6.9s

       5/50      10.1G      2.031      1.077      1.015        194       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.1s<6.6s

       5/50      10.1G      2.035      1.077      1.015        108       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.3s<6.4s

       5/50      10.1G      2.035      1.078      1.016         99       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.4s<6.2s

       5/50      10.1G      2.033      1.077      1.015        118       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.6s<6.0s

       5/50      10.1G      2.034      1.079      1.015        119       1024: 68% ━━━━━━━━──── 84/124 6.9it/s 12.7s<5.8s

       5/50      10.1G      2.032      1.079      1.015        112       1024: 69% ━━━━━━━━──── 85/124 6.9it/s 12.9s<5.7s

       5/50      10.1G      2.029      1.079      1.015        162       1024: 69% ━━━━━━━━──── 86/124 6.9it/s 13.0s<5.5s

       5/50      10.1G      2.028      1.078      1.015        153       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.2s<5.7s

       5/50      10.1G      2.031      1.079      1.015        114       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.3s<5.5s

       5/50      10.1G       2.03      1.078      1.015        119       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.5s<5.3s

       5/50      10.1G      2.027      1.077      1.015        117       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.6s<5.2s

       5/50      10.1G      2.028      1.079      1.015        124       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.8s<4.9s

       5/50      10.1G      2.024      1.078      1.015        108       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 13.9s<4.7s

       5/50      10.1G      2.026      1.079      1.015        145       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

       5/50      10.1G      2.025       1.08      1.015        108       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.2s<4.4s

       5/50      10.1G      2.024      1.079      1.015        138       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.4s<4.5s

       5/50      10.1G      2.024       1.08      1.015        131       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.5s<4.2s

       5/50      10.1G      2.025      1.081      1.015        130       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.0s

       5/50      10.1G      2.027      1.081      1.015        149       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.8s<3.8s

       5/50      10.1G      2.026       1.08      1.014        132       1024: 80% ━━━━━━━━━╸── 99/124 6.8it/s 15.0s<3.7s

       5/50      10.1G      2.026       1.08      1.014        161       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.1s<3.5s

       5/50      10.1G      2.026       1.08      1.014        145       1024: 81% ━━━━━━━━━╸── 101/124 6.9it/s 15.3s<3.4s

       5/50      10.1G      2.026       1.08      1.014        154       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.4s<3.2s

       5/50      10.1G      2.027      1.079      1.013        182       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.6s<3.2s

       5/50      10.1G      2.028      1.079      1.013        198       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.7s<3.0s

       5/50      10.1G      2.026      1.079      1.013        150       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.8s

       5/50      10.1G      2.026      1.078      1.013        149       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.0s<2.7s

       5/50      10.1G      2.026      1.078      1.012        127       1024: 86% ━━━━━━━━━━── 107/124 6.8it/s 16.2s<2.5s

       5/50      10.1G      2.023      1.077      1.012        136       1024: 87% ━━━━━━━━━━── 108/124 6.9it/s 16.3s<2.3s

       5/50      10.1G      2.024      1.078      1.012        121       1024: 88% ━━━━━━━━━━╸─ 109/124 6.9it/s 16.5s<2.2s

       5/50      10.1G      2.023      1.078      1.012        144       1024: 89% ━━━━━━━━━━╸─ 110/124 6.9it/s 16.6s<2.0s

       5/50      10.1G      2.022      1.077      1.011        131       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.8s<2.0s

       5/50      10.1G      2.022      1.077      1.011        113       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 16.9s<1.8s

       5/50      10.1G      2.021      1.076      1.012        116       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.1s<1.6s

       5/50      10.1G      2.022      1.077      1.012        138       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.2s<1.5s

       5/50      10.1G      2.023      1.077      1.013        205       1024: 93% ━━━━━━━━━━━─ 115/124 6.8it/s 17.4s<1.3s

       5/50      10.1G      2.025       1.08      1.013         94       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.5s<1.2s

       5/50      10.1G      2.024      1.081      1.013        148       1024: 94% ━━━━━━━━━━━─ 117/124 6.9it/s 17.6s<1.0s

       5/50      10.1G      2.023      1.079      1.012        164       1024: 95% ━━━━━━━━━━━─ 118/124 6.9it/s 17.8s<0.9s

       5/50      10.1G      2.022      1.079      1.012        137       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.0s<0.8s

       5/50      10.1G       2.02      1.079      1.012        124       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.1s<0.6s

       5/50      10.1G      2.021       1.08      1.012         95       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.2s<0.4s

       5/50      10.1G      2.023       1.08      1.013        145       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.4s<0.3s

       5/50      10.1G      2.022      1.079      1.012        146       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.5s<0.1s

       5/50      10.1G      2.022      1.079      1.012        146       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.615      0.548      0.569       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/50      10.1G      2.219      1.042      1.048        123       1024: 0% ──────────── 0/124  0.1s

       6/50      10.1G      1.967     0.9986      1.003        109       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.0s

       6/50      10.1G      2.004      1.036     0.9921        168       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.3s

       6/50      10.1G      2.046      1.051      1.008        122       1024: 2% ──────────── 3/124 4.2it/s 0.6s<29.0s

       6/50      10.1G      2.031      1.044      1.008        107       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.6s

       6/50      10.1G      2.052      1.061      1.002        142       1024: 4% ──────────── 5/124 5.4it/s 0.9s<22.0s

       6/50      10.1G       1.99      1.061     0.9946        103       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.2s

       6/50      10.1G      1.967      1.053     0.9876        188       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<19.0s

       6/50      10.1G      1.988      1.059     0.9903        184       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.2s

       6/50      10.1G      2.001      1.077      1.001        143       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.6s

       6/50      10.1G      1.993      1.087      1.005        144       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.2s

       6/50      10.1G      1.983       1.08      1.004        123       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<17.8s

       6/50      10.1G      1.985      1.073      1.007        127       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.2s

       6/50      10.1G      1.961      1.061     0.9984        142       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.8s

       6/50      10.1G      1.947      1.064     0.9934        121       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.5s

       6/50      10.1G       1.95      1.063     0.9906        164       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.2s

       6/50      10.1G      1.964      1.066     0.9968        113       1024: 13% ━╸────────── 16/124 6.8it/s 2.5s<15.9s

       6/50      10.1G      1.968      1.068     0.9996        125       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.7s

       6/50      10.1G      1.965      1.063     0.9991        129       1024: 15% ━╸────────── 18/124 6.8it/s 2.8s<15.5s

       6/50      10.1G      1.963       1.06     0.9981        129       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.4s

       6/50      10.1G      1.967       1.06     0.9987        116       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.0s

       6/50      10.1G      1.961      1.058      0.995        156       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

       6/50      10.1G      1.979      1.063     0.9969        164       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

       6/50      10.1G      1.968      1.054      0.994        147       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

       6/50      10.1G      1.973      1.054     0.9953        113       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.9s

       6/50      10.1G      1.965      1.052     0.9944        158       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.7s

       6/50      10.1G      1.965       1.05     0.9946        120       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.5s

       6/50      10.1G      1.956      1.045     0.9914        164       1024: 22% ━━╸───────── 27/124 6.4it/s 4.2s<15.2s

       6/50      10.1G      1.958      1.047     0.9913        141       1024: 23% ━━╸───────── 28/124 6.4it/s 4.4s<14.9s

       6/50      10.1G      1.955      1.044     0.9885        174       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.5s

       6/50      10.1G      1.959      1.043      0.988        150       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.2s

       6/50      10.1G      1.961      1.043     0.9881        139       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.9s

       6/50      10.1G      1.954      1.037      0.987        117       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.7s

       6/50      10.1G      1.952      1.036     0.9844        166       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.5s

       6/50      10.1G      1.949      1.033      0.983        120       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.3s

       6/50      10.1G      1.944      1.033     0.9822        110       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.7s

       6/50      10.1G      1.942      1.033     0.9816        125       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.5s

       6/50      10.1G      1.936       1.03     0.9805        191       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.7s<13.2s

       6/50      10.1G      1.931      1.029     0.9785        166       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

       6/50      10.1G      1.931      1.027     0.9788        120       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.0s<12.7s

       6/50      10.1G      1.937      1.029     0.9787        111       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.2s<12.4s

       6/50      10.1G      1.944      1.035     0.9796        112       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.2s

       6/50      10.1G      1.942      1.035     0.9811         92       1024: 34% ━━━━──────── 42/124 6.9it/s 6.5s<12.0s

       6/50      10.1G      1.948      1.036     0.9832        115       1024: 35% ━━━━──────── 43/124 6.6it/s 6.6s<12.4s

       6/50      10.1G      1.951      1.038     0.9837        131       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

       6/50      10.1G      1.958      1.042     0.9857        140       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<12.0s

       6/50      10.1G      1.954      1.045     0.9872        108       1024: 37% ━━━━──────── 46/124 6.5it/s 7.1s<11.9s

       6/50      10.1G      1.955      1.049     0.9875        112       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.2s<11.6s

       6/50      10.1G      1.955      1.048     0.9887        161       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.3s

       6/50      10.1G      1.958      1.049     0.9884        130       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.1s

       6/50      10.1G      1.956      1.047     0.9878        117       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

       6/50      10.1G      1.956      1.048     0.9889        119       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.3s

       6/50      10.1G      1.959       1.05     0.9916        111       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

       6/50      10.1G      1.959      1.051     0.9934        109       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

       6/50      10.1G      1.961      1.053     0.9937        156       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.5s

       6/50      10.1G       1.96      1.053     0.9934        106       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.4s<10.2s

       6/50      10.1G      1.963      1.052     0.9931        149       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.2s

       6/50      10.1G      1.964      1.053     0.9926        170       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.7s<10.1s

       6/50      10.1G      1.968      1.056     0.9941        152       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

       6/50      10.1G      1.966      1.055     0.9938        124       1024: 48% ━━━━━╸────── 59/124 6.3it/s 9.1s<10.3s

       6/50      10.1G      1.967      1.054     0.9939        130       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.2s<9.8s

       6/50      10.1G      1.968      1.053     0.9952        118       1024: 49% ━━━━━╸────── 61/124 6.5it/s 9.4s<9.7s

       6/50      10.1G      1.971      1.054     0.9942        144       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.5s<9.3s

       6/50      10.1G      1.972      1.055     0.9942        126       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

       6/50      10.1G      1.972      1.055     0.9944        132       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<9.0s

       6/50      10.1G      1.972      1.056     0.9942        150       1024: 52% ━━━━━━────── 65/124 6.7it/s 10.0s<8.8s

       6/50      10.1G      1.974      1.058     0.9943        119       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.6s

       6/50      10.1G      1.975      1.057     0.9959        124       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.3s<8.8s

       6/50      10.1G      1.974       1.06      0.996        145       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.5s

       6/50      10.1G      1.976       1.06     0.9957        145       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.6s<8.3s

       6/50      10.1G      1.979       1.06      0.996        133       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.1s

       6/50      10.1G      1.978      1.061      0.996        128       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

       6/50      10.1G      1.979      1.063     0.9961        152       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.0s<7.7s

       6/50      10.1G      1.976      1.063     0.9966        104       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

       6/50      10.1G      1.982      1.065     0.9972        126       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

       6/50      10.1G      1.982      1.067     0.9967        163       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.5s<7.5s

       6/50      10.1G      1.983      1.066     0.9969        132       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

       6/50      10.1G      1.985       1.07     0.9977        130       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

       6/50      10.1G      1.987       1.07     0.9976        140       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.9s

       6/50      10.1G      1.988       1.07      0.997        146       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.7s

       6/50      10.1G      1.988       1.07     0.9967        195       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.2s<6.6s

       6/50      10.1G      1.988      1.069     0.9965        175       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

       6/50      10.1G      1.988      1.068     0.9965        126       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

       6/50      10.1G      1.989      1.067     0.9959        175       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.7s<6.4s

       6/50      10.1G      1.989      1.065      0.996        148       1024: 68% ━━━━━━━━──── 84/124 6.4it/s 12.8s<6.2s

       6/50      10.1G      1.988      1.065     0.9955        114       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 13.0s<6.0s

       6/50      10.1G       1.99      1.065     0.9965        126       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.8s

       6/50      10.1G      1.993      1.067     0.9967        125       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.5s

       6/50      10.1G      1.993      1.068     0.9964        154       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.3s

       6/50      10.1G      1.992      1.067     0.9963        155       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.2s

       6/50      10.1G      1.995      1.068     0.9968        130       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.7s<5.0s

       6/50      10.1G      2.002       1.07     0.9984        114       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.9s<5.1s

       6/50      10.1G      2.007      1.073          1        102       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.0s<4.9s

       6/50      10.1G       2.01      1.074          1        123       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.2s<4.7s

       6/50      10.1G      2.009      1.074      1.001        134       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.3s<4.5s

       6/50      10.1G      2.011      1.074          1        156       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.5s<4.3s

       6/50      10.1G      2.011      1.074          1        186       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.6s<4.1s

       6/50      10.1G       2.01      1.072     0.9998        100       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.8s<4.0s

       6/50      10.1G       2.01      1.071          1        139       1024: 79% ━━━━━━━━━─── 98/124 6.9it/s 14.9s<3.8s

       6/50      10.1G       2.01      1.071          1        145       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.1s<3.8s

       6/50      10.1G       2.01       1.07          1        130       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.2s<3.6s

       6/50      10.1G      2.012      1.071      1.001        126       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.4s<3.4s

       6/50      10.1G      2.012      1.071          1        163       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

       6/50      10.1G      2.012      1.071      1.001         99       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.7s<3.1s

       6/50      10.1G       2.01       1.07          1        188       1024: 84% ━━━━━━━━━━── 104/124 6.9it/s 15.8s<2.9s

       6/50      10.1G      2.009      1.069          1        115       1024: 85% ━━━━━━━━━━── 105/124 6.9it/s 16.0s<2.8s

       6/50      10.1G      2.008      1.068          1        144       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.1s<2.7s

       6/50      10.1G      2.008      1.069     0.9996        142       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.3s<2.6s

       6/50      10.1G      2.007      1.068     0.9996        115       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

       6/50      10.1G      2.005      1.067     0.9995        112       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

       6/50      10.1G      2.007      1.067     0.9991        152       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

       6/50      10.1G      2.007      1.067     0.9994        124       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.9s<1.9s

       6/50      10.1G      2.006      1.065     0.9988        171       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.0s<1.8s

       6/50      10.1G      2.006      1.064      0.999        125       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.2s<1.6s

       6/50      10.1G      2.007      1.064      0.999        111       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.3s<1.5s

       6/50      10.1G      2.008      1.063     0.9987        161       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.5s<1.4s

       6/50      10.1G      2.005      1.063     0.9984        130       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.6s<1.2s

       6/50      10.1G      2.006      1.063     0.9995        107       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.0s

       6/50      10.1G      2.006      1.064     0.9993        136       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

       6/50      10.1G      2.005      1.063     0.9988        105       1024: 96% ━━━━━━━━━━━╸ 119/124 6.8it/s 18.1s<0.7s

       6/50      10.1G      2.005      1.063     0.9988        171       1024: 97% ━━━━━━━━━━━╸ 120/124 6.9it/s 18.2s<0.6s

       6/50      10.1G      2.007      1.062     0.9986        154       1024: 98% ━━━━━━━━━━━╸ 121/124 6.9it/s 18.3s<0.4s

       6/50      10.1G      2.006      1.063     0.9986        127       1024: 98% ━━━━━━━━━━━╸ 122/124 6.9it/s 18.5s<0.3s

       6/50      10.1G      2.007      1.062     0.9986        109       1024: 99% ━━━━━━━━━━━╸ 123/124 6.6it/s 18.7s<0.2s

       6/50      10.1G      2.007      1.062     0.9986        109       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.5it/s 0.4s<3.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.3it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.601      0.556      0.574      0.341

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/50      10.1G       1.79     0.9445     0.9406        124       1024: 0% ──────────── 0/124  0.1s

       7/50      10.1G      1.788       0.95     0.9485        120       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.0s

       7/50      10.1G      1.896     0.9667      0.975        151       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.6s

       7/50      10.1G      1.938     0.9946     0.9779        134       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.6s

       7/50      10.1G      1.982      1.005     0.9854        159       1024: 3% ──────────── 4/124 5.2it/s 0.7s<22.9s

       7/50      10.1G      1.936     0.9985     0.9861        112       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.7s

       7/50      10.1G      1.933     0.9805     0.9824        153       1024: 5% ╸─────────── 6/124 6.1it/s 1.0s<19.4s

       7/50      10.1G      1.942     0.9875     0.9791        127       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.5s

       7/50      10.1G      1.974          1     0.9866        151       1024: 6% ╸─────────── 8/124 6.2it/s 1.3s<18.8s

       7/50      10.1G      1.964      0.995     0.9927        137       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

       7/50      10.1G      1.988     0.9949      0.996        135       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.4s

       7/50      10.1G      2.002     0.9928      1.005        102       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.2s

       7/50      10.1G      1.998     0.9904      1.006        109       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<17.1s

       7/50      10.1G      1.986     0.9827      1.001        173       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.7s

       7/50      10.1G      2.016     0.9983      1.008        109       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.3s

       7/50      10.1G      2.004      1.002      1.008        154       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.9s

       7/50      10.1G       1.99      1.004      1.007        113       1024: 13% ━╸────────── 16/124 6.5it/s 2.5s<16.6s

       7/50      10.1G      1.988      1.007      1.009         94       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.4s

       7/50      10.1G      2.004      1.009      1.014        125       1024: 15% ━╸────────── 18/124 6.6it/s 2.8s<16.0s

       7/50      10.1G       1.99      1.009      1.009        171       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

       7/50      10.1G      1.986      1.007      1.006        194       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.5s

       7/50      10.1G      1.983      1.007      1.007        121       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

       7/50      10.1G      1.985      1.005      1.006        161       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

       7/50      10.1G      1.974      1.002      1.003        132       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.9s

       7/50      10.1G      1.979      1.001      1.005        142       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

       7/50      10.1G      1.986      1.008      1.005        154       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

       7/50      10.1G      1.994      1.009      1.006        145       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

       7/50      10.1G      1.994      1.006      1.006        131       1024: 22% ━━╸───────── 27/124 6.8it/s 4.2s<14.4s

       7/50      10.1G      1.997      1.006      1.009        117       1024: 23% ━━╸───────── 28/124 6.8it/s 4.3s<14.1s

       7/50      10.1G      1.989      1.002      1.008        132       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.1s

       7/50      10.1G      1.983      1.001      1.007         99       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

       7/50      10.1G      1.982     0.9987      1.006        123       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.4s

       7/50      10.1G      1.988      1.003      1.007        151       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.2s

       7/50      10.1G      1.987      1.004      1.006        123       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

       7/50      10.1G      1.982      1.003      1.005        142       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

       7/50      10.1G      1.983      1.002      1.004        114       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

       7/50      10.1G      1.977      1.001      1.004        156       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.0s

       7/50      10.1G      1.972     0.9988      1.001        150       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<12.9s

       7/50      10.1G      1.968     0.9987      1.003         99       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.7s

       7/50      10.1G      1.965          1      1.003        128       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

       7/50      10.1G      1.967      1.002      1.003        119       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.7s

       7/50      10.1G      1.973      1.004      1.002        131       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.4s

       7/50      10.1G      1.978      1.008      1.003        173       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

       7/50      10.1G      1.978      1.009      1.003         99       1024: 35% ━━━━──────── 43/124 6.8it/s 6.6s<12.0s

       7/50      10.1G       1.98      1.012      1.005        143       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

       7/50      10.1G      1.981      1.013      1.004        127       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

       7/50      10.1G      1.979      1.014      1.002        117       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.4s

       7/50      10.1G      1.976      1.013      1.001        115       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.9s

       7/50      10.1G      1.978      1.012      1.002        148       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.5s

       7/50      10.1G      1.973      1.014      1.002         94       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

       7/50      10.1G      1.972      1.016      1.001        150       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

       7/50      10.1G       1.97      1.014          1        143       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.7s

       7/50      10.1G      1.971      1.014      1.001        107       1024: 42% ━━━━━─────── 52/124 6.8it/s 7.9s<10.5s

       7/50      10.1G      1.977      1.017      1.002        155       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.5s

       7/50      10.1G      1.978      1.018      1.002        159       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

       7/50      10.1G      1.976      1.018      1.002        159       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

       7/50      10.1G      1.982      1.019      1.003        105       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

       7/50      10.1G      1.982      1.021      1.001        170       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

       7/50      10.1G      1.981       1.02          1        144       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.8s<9.8s

       7/50      10.1G      1.979      1.021     0.9996        156       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

       7/50      10.1G       1.98      1.021     0.9989        205       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

       7/50      10.1G      1.978       1.02     0.9989        140       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.5s

       7/50      10.1G      1.981      1.023     0.9996        137       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.3s

       7/50      10.1G      1.981      1.024     0.9996        121       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.6s<9.5s

       7/50      10.1G      1.979      1.023     0.9996        123       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.2s

       7/50      10.1G      1.976      1.025     0.9989        158       1024: 52% ━━━━━━────── 65/124 6.5it/s 9.9s<9.1s

       7/50      10.1G      1.977      1.027     0.9987        183       1024: 53% ━━━━━━────── 66/124 6.5it/s 10.1s<8.9s

       7/50      10.1G      1.978      1.029          1        118       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.2s<8.6s

       7/50      10.1G      1.976      1.027          1        103       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.4s<8.4s

       7/50      10.1G      1.974      1.026     0.9997        135       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.5s<8.2s

       7/50      10.1G      1.972      1.025     0.9986        117       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

       7/50      10.1G      1.971      1.027     0.9984        166       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.8s<8.2s

       7/50      10.1G      1.968      1.026     0.9975        108       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

       7/50      10.1G      1.973      1.028      0.998        127       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.8s

       7/50      10.1G      1.978       1.03          1        138       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

       7/50      10.1G      1.978       1.03          1        116       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

       7/50      10.1G      1.978      1.029          1        121       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.2s

       7/50      10.1G       1.98       1.03          1        221       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.7s<7.0s

       7/50      10.1G      1.977      1.029     0.9994        126       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

       7/50      10.1G      1.975       1.03     0.9989        111       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.1s<7.0s

       7/50      10.1G      1.977       1.03     0.9987        150       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.7s

       7/50      10.1G      1.976      1.031     0.9984        107       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.3s<6.5s

       7/50      10.1G      1.973      1.029     0.9975        145       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

       7/50      10.1G      1.974       1.03     0.9971        152       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.6s<6.1s

       7/50      10.1G      1.976      1.029     0.9966        131       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

       7/50      10.1G      1.974      1.028     0.9958        119       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.9s<5.7s

       7/50      10.1G      1.975      1.028     0.9961        136       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

       7/50      10.1G      1.975      1.028     0.9957        167       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.2s<5.7s

       7/50      10.1G      1.972      1.025     0.9945        125       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.5s

       7/50      10.1G      1.971      1.025      0.994        164       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.3s

       7/50      10.1G       1.97      1.023     0.9934        159       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

       7/50      10.1G       1.97      1.024     0.9934        119       1024: 73% ━━━━━━━━╸─── 91/124 6.8it/s 13.8s<4.9s

       7/50      10.1G      1.971      1.025     0.9943        126       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

       7/50      10.1G      1.974      1.025     0.9949        133       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

       7/50      10.1G      1.971      1.023     0.9946        101       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

       7/50      10.1G       1.97      1.023     0.9941        154       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.4s<4.5s

       7/50      10.1G      1.969      1.024     0.9939        136       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.2s

       7/50      10.1G      1.974      1.026     0.9949        130       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.0s

       7/50      10.1G      1.974      1.026     0.9945        157       1024: 79% ━━━━━━━━━─── 98/124 6.6it/s 14.9s<3.9s

       7/50      10.1G      1.973      1.025     0.9947        146       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.1s<3.8s

       7/50      10.1G      1.975      1.025     0.9944        137       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.2s<3.6s

       7/50      10.1G      1.975      1.025     0.9946        128       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.3s<3.5s

       7/50      10.1G      1.975      1.025     0.9945        131       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

       7/50      10.1G      1.975      1.025     0.9946        149       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

       7/50      10.1G      1.977      1.027     0.9957        107       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.8s<3.1s

       7/50      10.1G      1.977      1.029     0.9957        164       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

       7/50      10.1G      1.977      1.028     0.9956        172       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.1s<2.7s

       7/50      10.1G      1.977      1.028     0.9955        102       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.3s<2.6s

       7/50      10.1G      1.979      1.029     0.9965        141       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.4s<2.4s

       7/50      10.1G      1.979      1.028     0.9965        174       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.6s<2.3s

       7/50      10.1G      1.981      1.028     0.9965        187       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.7s<2.1s

       7/50      10.1G      1.982      1.029     0.9967        124       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.9s<2.0s

       7/50      10.1G      1.983      1.029     0.9972        128       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.0s<1.8s

       7/50      10.1G      1.985      1.029     0.9979        126       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.2s<1.7s

       7/50      10.1G      1.985      1.029     0.9981        124       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

       7/50      10.1G      1.985      1.028     0.9982        144       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

       7/50      10.1G      1.985      1.028     0.9981        127       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.6s<1.2s

       7/50      10.1G      1.985      1.028     0.9985        109       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.0s

       7/50      10.1G      1.984      1.027     0.9979        189       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 17.9s<0.9s

       7/50      10.1G      1.984      1.028     0.9975        140       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.1s<0.8s

       7/50      10.1G      1.984      1.028     0.9985        115       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.2s<0.6s

       7/50      10.1G      1.983      1.028     0.9981        117       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.5s

       7/50      10.1G      1.981      1.028     0.9979        116       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

       7/50      10.1G      1.984      1.029     0.9987        110       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

       7/50      10.1G      1.984      1.029     0.9987        110       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.5it/s 0.4s<3.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.3it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.7it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.5it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.7it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 7.9it/s 1.0s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.0it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.1it/s 1.2s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.2it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.6s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.5it/s 2.5s

                   all        330       4227      0.549      0.563      0.566      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/50      10.1G      1.782      1.024     0.9954        148       1024: 0% ──────────── 0/124  0.1s

       8/50      10.1G      1.844      1.033     0.9854        131       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:01

       8/50      10.1G      1.876      1.047     0.9735        119       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.1s

       8/50      10.1G      1.875      1.041       0.96        114       1024: 2% ──────────── 3/124 4.2it/s 0.6s<29.1s

       8/50      10.1G      1.839      1.013     0.9533        142       1024: 3% ──────────── 4/124 5.0it/s 0.8s<24.1s

       8/50      10.1G      1.853       1.02      0.956        124       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.5s

       8/50      10.1G       1.85      1.017     0.9655        116       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<19.9s

       8/50      10.1G      1.874      1.031     0.9637        154       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

       8/50      10.1G      1.867      1.021     0.9613        151       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.2s

       8/50      10.1G      1.882       1.01     0.9704        118       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.6s

       8/50      10.1G      1.898      1.008     0.9797        121       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.2s

       8/50      10.1G      1.893      1.011     0.9775        159       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.8s

       8/50      10.1G      1.872     0.9998     0.9735        115       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.4s

       8/50      10.1G      1.885       1.01     0.9824        112       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

       8/50      10.1G      1.905      1.013     0.9829        157       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.7s

       8/50      10.1G      1.891      1.004     0.9754        168       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.4s

       8/50      10.1G      1.901      1.005      0.974        140       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

       8/50      10.1G      1.915      1.011     0.9741        197       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<15.9s

       8/50      10.1G      1.919      1.007      0.975        117       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.8s

       8/50      10.1G      1.926      1.009     0.9775         91       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.3s

       8/50      10.1G       1.93      1.003     0.9799        125       1024: 16% ━╸────────── 20/124 6.6it/s 3.2s<15.8s

       8/50      10.1G      1.927      1.009     0.9782        130       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.5s

       8/50      10.1G      1.925      1.008     0.9789         99       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.1s

       8/50      10.1G      1.926      1.006     0.9792        125       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

       8/50      10.1G      1.931      1.004     0.9805        145       1024: 19% ━━────────── 24/124 6.8it/s 3.8s<14.7s

       8/50      10.1G      1.931      1.006     0.9824        132       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.8s

       8/50      10.1G      1.923     0.9982     0.9787        137       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

       8/50      10.1G      1.928     0.9987     0.9786        155       1024: 22% ━━╸───────── 27/124 6.4it/s 4.2s<15.1s

       8/50      10.1G      1.925     0.9991     0.9778        140       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.8s

       8/50      10.1G      1.932      1.002     0.9766        124       1024: 23% ━━╸───────── 29/124 6.5it/s 4.5s<14.6s

       8/50      10.1G      1.932     0.9972     0.9744        163       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.3s

       8/50      10.1G       1.94      1.001     0.9754        120       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<14.0s

       8/50      10.1G      1.942     0.9995     0.9746        166       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.8s

       8/50      10.1G      1.947     0.9993     0.9745        192       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.6s

       8/50      10.1G      1.954      1.001     0.9766        129       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

       8/50      10.1G      1.956      1.009     0.9795        112       1024: 28% ━━━───────── 35/124 6.4it/s 5.4s<13.8s

       8/50      10.1G      1.954      1.005      0.978        155       1024: 29% ━━━───────── 36/124 6.4it/s 5.6s<13.7s

       8/50      10.1G      1.956      1.006     0.9783        151       1024: 30% ━━━╸──────── 37/124 6.4it/s 5.8s<13.5s

       8/50      10.1G      1.954      1.006     0.9774        136       1024: 31% ━━━╸──────── 38/124 6.4it/s 5.9s<13.3s

       8/50      10.1G      1.949      1.008     0.9775        128       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.1s<12.9s

       8/50      10.1G       1.95      1.008      0.978        120       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.6s

       8/50      10.1G      1.948      1.005     0.9772        136       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.4s

       8/50      10.1G      1.948      1.004     0.9758        153       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.4s

       8/50      10.1G      1.951      1.003     0.9768        129       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.7s

       8/50      10.1G      1.951      1.004     0.9769        134       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

       8/50      10.1G      1.951      1.005     0.9772        159       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<11.9s

       8/50      10.1G      1.953      1.008     0.9773        118       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

       8/50      10.1G      1.949      1.005     0.9779        124       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.4s

       8/50      10.1G       1.95      1.008     0.9774        149       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.3s

       8/50      10.1G      1.951      1.009     0.9767        188       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.6s<11.4s

       8/50      10.1G      1.948      1.007     0.9757        126       1024: 40% ━━━━╸─────── 50/124 6.5it/s 7.7s<11.4s

       8/50      10.1G      1.949      1.008      0.975        172       1024: 41% ━━━━╸─────── 51/124 6.1it/s 7.9s<12.0s

       8/50      10.1G      1.946      1.007     0.9749        125       1024: 42% ━━━━━─────── 52/124 6.2it/s 8.1s<11.7s

       8/50      10.1G      1.946      1.009      0.975        106       1024: 43% ━━━━━─────── 53/124 6.3it/s 8.2s<11.2s

       8/50      10.1G      1.951      1.012      0.975        107       1024: 44% ━━━━━─────── 54/124 6.5it/s 8.4s<10.8s

       8/50      10.1G       1.95       1.01      0.976        130       1024: 44% ━━━━━─────── 55/124 6.6it/s 8.5s<10.5s

       8/50      10.1G      1.954      1.011     0.9773        114       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.7s<10.3s

       8/50      10.1G      1.955       1.01     0.9771        128       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

       8/50      10.1G      1.955      1.009      0.977        149       1024: 47% ━━━━━╸────── 58/124 6.7it/s 9.0s<9.8s

       8/50      10.1G      1.959      1.009     0.9772        140       1024: 48% ━━━━━╸────── 59/124 6.3it/s 9.2s<10.3s

       8/50      10.1G       1.96      1.009     0.9767        153       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.3s<9.9s

       8/50      10.1G      1.961      1.011     0.9774        111       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

       8/50      10.1G      1.959       1.01     0.9765        111       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.6s<9.3s

       8/50      10.1G       1.96       1.01     0.9779        122       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

       8/50      10.1G      1.959      1.009     0.9791        127       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.9s<9.0s

       8/50      10.1G      1.958      1.009     0.9789        185       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.0s<9.0s

       8/50      10.1G      1.961      1.009     0.9791        148       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.7s

       8/50      10.1G      1.957      1.009     0.9786        117       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.4s<9.0s

       8/50      10.1G      1.957       1.01     0.9781        163       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.5s<8.6s

       8/50      10.1G      1.956      1.009     0.9781        155       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.7s<8.3s

       8/50      10.1G      1.958      1.009     0.9781        123       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.8s<8.1s

       8/50      10.1G      1.957      1.008     0.9777        175       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 11.0s<8.0s

       8/50      10.1G      1.958      1.008      0.979        158       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.8s

       8/50      10.1G      1.959      1.008     0.9787        105       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.3s<7.7s

       8/50      10.1G      1.961      1.008     0.9788        173       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

       8/50      10.1G       1.96      1.007      0.979        112       1024: 60% ━━━━━━━───── 75/124 6.3it/s 11.6s<7.8s

       8/50      10.1G      1.958      1.006     0.9793        161       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.7s<7.4s

       8/50      10.1G      1.959      1.008     0.9796        201       1024: 62% ━━━━━━━───── 77/124 6.5it/s 11.9s<7.2s

       8/50      10.1G      1.957      1.007     0.9787        180       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 12.0s<7.0s

       8/50      10.1G      1.956      1.006     0.9784        111       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.2s<6.7s

       8/50      10.1G      1.957      1.006     0.9783        149       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.3s<6.6s

       8/50      10.1G      1.955      1.005     0.9781        123       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.5s<6.4s

       8/50      10.1G      1.953      1.005      0.978        138       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

       8/50      10.1G      1.953      1.004     0.9783        123       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.8s<6.4s

       8/50      10.1G      1.953      1.005     0.9782        157       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 13.0s<6.2s

       8/50      10.1G      1.952      1.006     0.9785        124       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.1s<5.9s

       8/50      10.1G      1.951      1.006     0.9785        155       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.2s<5.7s

       8/50      10.1G      1.949      1.004     0.9783        139       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.4s<5.6s

       8/50      10.1G      1.948      1.003     0.9785        125       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.6s<5.4s

       8/50      10.1G       1.95      1.002     0.9782        142       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.7s<5.3s

       8/50      10.1G       1.95      1.002     0.9787        160       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.9s<5.1s

       8/50      10.1G      1.951      1.002     0.9786        138       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 14.0s<5.2s

       8/50      10.1G      1.952      1.002     0.9795        107       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.2s<4.9s

       8/50      10.1G      1.952      1.002     0.9798        127       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.3s<4.7s

       8/50      10.1G       1.95      1.001     0.9796        116       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.5s<4.5s

       8/50      10.1G      1.948     0.9989     0.9788        173       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.6s<4.3s

       8/50      10.1G      1.947     0.9973     0.9789        115       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.8s<4.2s

       8/50      10.1G      1.949     0.9978     0.9795        171       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.9s<4.0s

       8/50      10.1G      1.947      0.999      0.979        156       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.1s<3.9s

       8/50      10.1G       1.95          1       0.98        116       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.2s<3.9s

       8/50      10.1G       1.95     0.9999       0.98        129       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.4s<3.7s

       8/50      10.1G      1.948     0.9997     0.9791        115       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

       8/50      10.1G      1.948     0.9982     0.9791        141       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.7s<3.3s

       8/50      10.1G      1.951     0.9989     0.9806        116       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.8s<3.2s

       8/50      10.1G      1.949     0.9986     0.9805        143       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 16.0s<3.0s

       8/50      10.1G       1.95     0.9986     0.9804        200       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.1s<2.8s

       8/50      10.1G      1.951     0.9983     0.9804        159       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.3s<2.7s

       8/50      10.1G       1.95     0.9982       0.98        148       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.4s<2.6s

       8/50      10.1G      1.949     0.9985     0.9797        174       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.6s<2.4s

       8/50      10.1G      1.952     0.9994       0.98        115       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.7s<2.2s

       8/50      10.1G      1.953     0.9997     0.9806        121       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.9s<2.1s

       8/50      10.1G      1.951     0.9984     0.9796        159       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 17.0s<1.9s

       8/50      10.1G      1.951     0.9995       0.98        115       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.2s<1.8s

       8/50      10.1G      1.949     0.9986     0.9796        143       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.3s<1.6s

       8/50      10.1G      1.947     0.9966     0.9794        111       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.5s<1.5s

       8/50      10.1G      1.948     0.9972       0.98        121       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.6s<1.4s

       8/50      10.1G      1.949     0.9973     0.9809        132       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.8s<1.2s

       8/50      10.1G       1.95     0.9985     0.9811         96       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.9s<1.1s

       8/50      10.1G       1.95     0.9986     0.9815        110       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.1s<0.9s

       8/50      10.1G      1.951     0.9988     0.9818        109       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.2s<0.7s

       8/50      10.1G      1.952     0.9993     0.9815        131       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.4s<0.6s

       8/50      10.1G      1.952     0.9993     0.9816        109       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.5s<0.4s

       8/50      10.1G      1.952     0.9994     0.9819        140       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.7s<0.3s

       8/50      10.1G      1.952     0.9996     0.9822        131       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 18.9s<0.2s

       8/50      10.1G      1.952     0.9996     0.9822        131       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227       0.61      0.558      0.583      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/50      10.1G      2.185     0.9814      1.023        157       1024: 0% ──────────── 0/124  0.1s

       9/50      10.1G      1.991     0.9375     0.9965        119       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.8s

       9/50      10.1G      1.964     0.9449     0.9842        124       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.9s

       9/50      10.1G      1.964      0.955     0.9764        118       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.9s

       9/50      10.1G      2.019      1.002     0.9847        208       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.6s

       9/50      10.1G      2.023      1.009     0.9881        144       1024: 4% ──────────── 5/124 5.4it/s 0.9s<22.0s

       9/50      10.1G      2.009     0.9958     0.9804        182       1024: 5% ╸─────────── 6/124 5.8it/s 1.0s<20.3s

       9/50      10.1G      1.997     0.9904     0.9802        128       1024: 6% ╸─────────── 7/124 5.8it/s 1.2s<20.2s

       9/50      10.1G      2.008      1.004     0.9779        145       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<19.0s

       9/50      10.1G       2.03      1.012     0.9886        115       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.2s

       9/50      10.1G      2.023      1.008     0.9886        157       1024: 8% ╸─────────── 10/124 6.5it/s 1.7s<17.6s

       9/50      10.1G      2.011      1.003     0.9874        129       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.1s

       9/50      10.1G       1.99     0.9919     0.9817        133       1024: 10% ━─────────── 12/124 6.7it/s 2.0s<16.8s

       9/50      10.1G      1.979     0.9865     0.9812        104       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

       9/50      10.1G      1.981     0.9878     0.9771        152       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.3s

       9/50      10.1G      1.987     0.9901     0.9766        111       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<16.9s

       9/50      10.1G      1.998     0.9931     0.9767        122       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.4s

       9/50      10.1G      1.984     0.9872     0.9744        103       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<16.1s

       9/50      10.1G      1.993      0.992     0.9784        154       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.8s

       9/50      10.1G      1.988     0.9866      0.978        127       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

       9/50      10.1G      1.983      0.986     0.9782        148       1024: 16% ━╸────────── 20/124 6.8it/s 3.2s<15.4s

       9/50      10.1G      1.981     0.9839      0.977        118       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

       9/50      10.1G      1.988     0.9861     0.9819        138       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.1s

       9/50      10.1G      1.978     0.9874     0.9808        114       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

       9/50      10.1G      1.972     0.9822      0.981        130       1024: 19% ━━────────── 24/124 6.6it/s 3.8s<15.2s

       9/50      10.1G      1.973     0.9823     0.9811        143       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<14.9s

       9/50      10.1G      1.969     0.9818     0.9793        226       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

       9/50      10.1G      1.969     0.9887     0.9822        104       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.4s

       9/50      10.1G      1.967     0.9875     0.9812        167       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.2s

       9/50      10.1G      1.967     0.9873     0.9807        147       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.1s

       9/50      10.1G      1.959     0.9837     0.9795        130       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

       9/50      10.1G      1.955     0.9837      0.979        112       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.5s

       9/50      10.1G       1.96     0.9857     0.9791        118       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.1s

       9/50      10.1G      1.966     0.9889     0.9785        202       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

       9/50      10.1G      1.969     0.9901     0.9807        129       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

       9/50      10.1G      1.969     0.9913     0.9817        103       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.2s

       9/50      10.1G      1.968     0.9902     0.9793        230       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

       9/50      10.1G      1.971     0.9891     0.9799        130       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.9s

       9/50      10.1G       1.97     0.9917     0.9813        154       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.7s

       9/50      10.1G      1.969     0.9918     0.9807        144       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.0s<13.2s

       9/50      10.1G      1.972     0.9917     0.9817        127       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

       9/50      10.1G      1.972     0.9932     0.9837        138       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

       9/50      10.1G      1.965     0.9888     0.9816        119       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

       9/50      10.1G      1.964     0.9884     0.9808        166       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

       9/50      10.1G      1.959     0.9882       0.98        154       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

       9/50      10.1G      1.963     0.9891     0.9808        147       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

       9/50      10.1G      1.963     0.9884     0.9791        209       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

       9/50      10.1G      1.964     0.9909     0.9807        159       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.9s

       9/50      10.1G      1.962     0.9899     0.9807        110       1024: 39% ━━━━╸─────── 48/124 6.5it/s 7.4s<11.7s

       9/50      10.1G      1.967      0.991     0.9808        178       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.5s<11.4s

       9/50      10.1G       1.96     0.9876     0.9789        132       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.1s

       9/50      10.1G      1.963       0.99     0.9787        191       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.9s

       9/50      10.1G      1.959     0.9888     0.9775        123       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

       9/50      10.1G      1.957     0.9881     0.9772        153       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

       9/50      10.1G      1.956     0.9877     0.9766        132       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

       9/50      10.1G      1.958     0.9899     0.9769        144       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.7s

       9/50      10.1G      1.954     0.9892     0.9759        137       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

       9/50      10.1G      1.955     0.9913     0.9785        102       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

       9/50      10.1G      1.952     0.9905     0.9774        119       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

       9/50      10.1G      1.956     0.9926     0.9783        106       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

       9/50      10.1G      1.953     0.9922     0.9777         95       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.2s<9.5s

       9/50      10.1G       1.95     0.9918     0.9774         99       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.3s

       9/50      10.1G      1.947     0.9932     0.9777        109       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

       9/50      10.1G      1.948     0.9928     0.9773        180       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

       9/50      10.1G      1.946     0.9914      0.978        125       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

       9/50      10.1G      1.946     0.9917     0.9787        132       1024: 52% ━━━━━━────── 65/124 6.7it/s 9.9s<8.8s

       9/50      10.1G      1.945     0.9907     0.9784        140       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

       9/50      10.1G      1.954     0.9932     0.9799        141       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.2s<8.5s

       9/50      10.1G      1.954     0.9941     0.9799        117       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.3s

       9/50      10.1G      1.954     0.9934     0.9793        125       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

       9/50      10.1G      1.955     0.9936     0.9804        120       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<7.9s

       9/50      10.1G      1.958     0.9948     0.9805        179       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.8s<8.1s

       9/50      10.1G      1.959     0.9952     0.9809        157       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.9s

       9/50      10.1G      1.964     0.9972     0.9814        164       1024: 59% ━━━━━━━───── 73/124 6.5it/s 11.1s<7.8s

       9/50      10.1G       1.96     0.9956     0.9804        141       1024: 60% ━━━━━━━───── 74/124 6.6it/s 11.3s<7.6s

       9/50      10.1G      1.961     0.9951     0.9815        106       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

       9/50      10.1G      1.958     0.9938      0.981        111       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.1s

       9/50      10.1G      1.955     0.9924     0.9814        130       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

       9/50      10.1G      1.955     0.9922     0.9815        154       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

       9/50      10.1G      1.954     0.9903     0.9807        139       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.1s<7.0s

       9/50      10.1G      1.952     0.9901     0.9804        142       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.7s

       9/50      10.1G      1.958     0.9913      0.981        146       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.3s<6.5s

       9/50      10.1G      1.956     0.9889     0.9803        147       1024: 66% ━━━━━━━╸──── 82/124 6.6it/s 12.5s<6.3s

       9/50      10.1G      1.958     0.9887      0.981        128       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.6s<6.1s

       9/50      10.1G      1.958     0.9882     0.9807        152       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 12.8s<5.9s

       9/50      10.1G      1.957     0.9879     0.9806        149       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.9s<5.8s

       9/50      10.1G      1.957     0.9873     0.9805        142       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.1s<5.6s

       9/50      10.1G      1.959     0.9896     0.9814        107       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.8s

       9/50      10.1G      1.959     0.9899     0.9811        151       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.4s<5.6s

       9/50      10.1G       1.96     0.9911     0.9819        122       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

       9/50      10.1G      1.962     0.9918     0.9818        133       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

       9/50      10.1G      1.961     0.9922     0.9823        139       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

       9/50      10.1G       1.96     0.9931     0.9817        130       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

       9/50      10.1G      1.959     0.9922     0.9819        133       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

       9/50      10.1G      1.959      0.991      0.982        133       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

       9/50      10.1G      1.958      0.991     0.9815        143       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

       9/50      10.1G       1.96     0.9916     0.9815        131       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.6s<4.3s

       9/50      10.1G      1.961     0.9932     0.9817        118       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

       9/50      10.1G      1.962     0.9947     0.9814        183       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

       9/50      10.1G      1.964     0.9973     0.9821        123       1024: 80% ━━━━━━━━━╸── 99/124 6.6it/s 15.1s<3.8s

       9/50      10.1G      1.966     0.9979      0.982        202       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.2s<3.6s

       9/50      10.1G      1.972     0.9993      0.984        104       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.4s<3.4s

       9/50      10.1G      1.972     0.9993     0.9835        167       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

       9/50      10.1G      1.974     0.9983      0.984        139       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

       9/50      10.1G      1.971     0.9969     0.9831        129       1024: 84% ━━━━━━━━━━── 104/124 6.4it/s 15.8s<3.1s

       9/50      10.1G      1.974     0.9988     0.9839        131       1024: 85% ━━━━━━━━━━── 105/124 6.5it/s 16.0s<2.9s

       9/50      10.1G      1.974     0.9995     0.9844         89       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.1s<2.7s

       9/50      10.1G      1.973     0.9991     0.9842        165       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.3s<2.5s

       9/50      10.1G      1.974     0.9992     0.9847        150       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

       9/50      10.1G      1.971     0.9991     0.9845        125       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.6s<2.2s

       9/50      10.1G       1.97     0.9978     0.9844        140       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

       9/50      10.1G      1.971     0.9978     0.9842        175       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

       9/50      10.1G      1.972     0.9971     0.9841        117       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.0s<1.8s

       9/50      10.1G      1.971     0.9965     0.9841        161       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.7s

       9/50      10.1G       1.97     0.9966     0.9841        154       1024: 92% ━━━━━━━━━━━─ 114/124 6.6it/s 17.3s<1.5s

       9/50      10.1G       1.97     0.9969     0.9845        114       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

       9/50      10.1G      1.969     0.9972     0.9844        153       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.6s<1.2s

       9/50      10.1G      1.969     0.9966     0.9845        114       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.8s<1.0s

       9/50      10.1G       1.97     0.9966      0.984        148       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

       9/50      10.1G      1.971     0.9964     0.9847        126       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

       9/50      10.1G      1.972     0.9964     0.9845        191       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.3s<0.6s

       9/50      10.1G       1.97     0.9958     0.9839        145       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.4s<0.5s

       9/50      10.1G       1.97     0.9954     0.9843        122       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.6s<0.3s

       9/50      10.1G      1.967     0.9946     0.9842        140       1024: 99% ━━━━━━━━━━━╸ 123/124 6.6it/s 18.7s<0.2s

       9/50      10.1G      1.967     0.9946     0.9842        140       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.3it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.645      0.531      0.572      0.341

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/50      10.1G      2.087      1.037      1.042        162       1024: 0% ──────────── 0/124  0.1s

      10/50      10.1G      2.101      1.063      1.005        157       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.8s

      10/50      10.1G      2.081      1.013     0.9988        102       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      10/50      10.1G       1.99     0.9669     0.9866        134       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.2s

      10/50      10.1G      2.016     0.9875     0.9816        112       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.9s

      10/50      10.1G      2.002     0.9929     0.9804        135       1024: 4% ──────────── 5/124 5.4it/s 0.9s<21.9s

      10/50      10.1G      1.994     0.9792     0.9707        133       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.2s

      10/50      10.1G       1.97     0.9807     0.9714        128       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      10/50      10.1G      1.968     0.9761     0.9699        169       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.5s

      10/50      10.1G      1.971      0.981     0.9708        152       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<17.9s

      10/50      10.1G      1.983     0.9851     0.9674        167       1024: 8% ╸─────────── 10/124 6.5it/s 1.7s<17.5s

      10/50      10.1G      1.974     0.9858     0.9659        187       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      10/50      10.1G      1.968     0.9786     0.9643        148       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.3s

      10/50      10.1G      1.961     0.9817      0.964        111       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.9s

      10/50      10.1G      1.957      0.986     0.9621        133       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      10/50      10.1G       1.94     0.9854     0.9592        177       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.6s

      10/50      10.1G      1.933     0.9837     0.9551        148       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.4s

      10/50      10.1G      1.937     0.9846     0.9556        147       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<16.0s

      10/50      10.1G       1.93     0.9788      0.956        120       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.8s

      10/50      10.1G      1.933     0.9768     0.9538        115       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.3s

      10/50      10.1G      1.934     0.9807     0.9563        144       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<15.9s

      10/50      10.1G      1.948     0.9804     0.9585        122       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.5s

      10/50      10.1G      1.935     0.9752     0.9571        129       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.2s

      10/50      10.1G      1.931     0.9716     0.9568        117       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

      10/50      10.1G       1.93     0.9701     0.9576        168       1024: 19% ━━────────── 24/124 6.8it/s 3.8s<14.8s

      10/50      10.1G      1.931     0.9727     0.9599        116       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

      10/50      10.1G      1.927     0.9674     0.9604        133       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.4s

      10/50      10.1G      1.925     0.9683     0.9618        118       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<15.0s

      10/50      10.1G      1.928     0.9718     0.9618        141       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.8s

      10/50      10.1G      1.927     0.9708     0.9612        128       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.4s

      10/50      10.1G      1.923     0.9701      0.961        126       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

      10/50      10.1G      1.929      0.971     0.9611        147       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

      10/50      10.1G      1.921     0.9657     0.9602        108       1024: 26% ━━━───────── 32/124 6.8it/s 5.0s<13.6s

      10/50      10.1G      1.918     0.9659     0.9599        159       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      10/50      10.1G      1.916     0.9653     0.9624        104       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.2s

      10/50      10.1G      1.915     0.9635     0.9629        104       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.6s

      10/50      10.1G      1.912     0.9623     0.9632        150       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.5s

      10/50      10.1G      1.913     0.9642     0.9631        163       1024: 30% ━━━╸──────── 37/124 6.5it/s 5.8s<13.4s

      10/50      10.1G      1.909     0.9631     0.9623        148       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.0s

      10/50      10.1G      1.907     0.9604     0.9625        113       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.0s<12.7s

      10/50      10.1G      1.908     0.9615     0.9623        172       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.2s<12.5s

      10/50      10.1G      1.905     0.9642     0.9627        126       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.3s

      10/50      10.1G      1.912     0.9676     0.9636        143       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.1s

      10/50      10.1G      1.909     0.9652     0.9627        131       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.6s

      10/50      10.1G      1.914     0.9649     0.9613        206       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

      10/50      10.1G      1.914      0.964     0.9609        185       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<11.9s

      10/50      10.1G      1.925     0.9674      0.962        121       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      10/50      10.1G      1.923     0.9667     0.9623        122       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.2s<11.4s

      10/50      10.1G      1.921     0.9647     0.9623        128       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      10/50      10.1G      1.924     0.9646      0.963        124       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.0s

      10/50      10.1G      1.923     0.9628     0.9624        132       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      10/50      10.1G      1.923     0.9622     0.9647        160       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.9s<11.3s

      10/50      10.1G      1.922      0.961     0.9638        193       1024: 42% ━━━━━─────── 52/124 6.5it/s 8.0s<11.0s

      10/50      10.1G      1.924     0.9596     0.9648        129       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.7s

      10/50      10.1G      1.923     0.9593     0.9639        126       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.5s

      10/50      10.1G      1.922     0.9575     0.9635        161       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.4s<10.3s

      10/50      10.1G      1.923     0.9606     0.9646        126       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      10/50      10.1G      1.927     0.9617      0.966        123       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.8s

      10/50      10.1G      1.926      0.961     0.9672        130       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.7s

      10/50      10.1G      1.925     0.9605     0.9668        108       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.0s

      10/50      10.1G      1.922     0.9586     0.9662        122       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

      10/50      10.1G      1.922     0.9588      0.965        198       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.5s

      10/50      10.1G      1.924     0.9599     0.9644        209       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.3s

      10/50      10.1G      1.927     0.9611     0.9648        113       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.6s<9.0s

      10/50      10.1G      1.924     0.9588     0.9634        162       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.8s<8.9s

      10/50      10.1G      1.922     0.9568     0.9623        166       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      10/50      10.1G      1.922     0.9587     0.9629        116       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.5s

      10/50      10.1G       1.92     0.9575     0.9622        156       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.3s<8.8s

      10/50      10.1G      1.919      0.956     0.9612        125       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.5s

      10/50      10.1G      1.916     0.9537     0.9607        122       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.6s<8.3s

      10/50      10.1G      1.919     0.9532     0.9608        150       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.7s<8.0s

      10/50      10.1G      1.922     0.9533     0.9604        126       1024: 57% ━━━━━━╸───── 71/124 6.8it/s 10.8s<7.8s

      10/50      10.1G      1.926     0.9542     0.9624        106       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.7s

      10/50      10.1G      1.927     0.9538     0.9631        115       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.1s<7.5s

      10/50      10.1G      1.927     0.9535     0.9636        125       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

      10/50      10.1G      1.926     0.9523     0.9634        119       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.5s<7.6s

      10/50      10.1G      1.929     0.9528     0.9629        148       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.6s<7.3s

      10/50      10.1G      1.927     0.9503     0.9628        126       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      10/50      10.1G      1.931     0.9548      0.964        107       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.9s

      10/50      10.1G      1.933     0.9557     0.9635        131       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.0s<6.7s

      10/50      10.1G      1.933     0.9546     0.9639        107       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.2s<6.5s

      10/50      10.1G      1.936     0.9563     0.9646        137       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.3s<6.3s

      10/50      10.1G      1.938     0.9581     0.9664        116       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.5s<6.2s

      10/50      10.1G      1.944     0.9599      0.968        123       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.7s<6.3s

      10/50      10.1G      1.945     0.9609     0.9676        164       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.8s<6.1s

      10/50      10.1G      1.948     0.9609     0.9673        182       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 13.0s<6.0s

      10/50      10.1G      1.948     0.9608     0.9674        141       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.8s

      10/50      10.1G       1.95     0.9608     0.9669        174       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.6s

      10/50      10.1G      1.951     0.9608     0.9672        120       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.4s

      10/50      10.1G      1.949     0.9598     0.9662        148       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.2s

      10/50      10.1G      1.948     0.9588     0.9662        127       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.7s<5.1s

      10/50      10.1G      1.949     0.9573     0.9666        106       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 13.9s<5.2s

      10/50      10.1G       1.95     0.9579     0.9668        136       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.0s<4.9s

      10/50      10.1G      1.951     0.9576     0.9677        122       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      10/50      10.1G      1.949     0.9578     0.9677        127       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.3s<4.6s

      10/50      10.1G      1.951     0.9579     0.9682        134       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.5s<4.4s

      10/50      10.1G      1.954     0.9602     0.9693        124       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.6s<4.2s

      10/50      10.1G      1.955       0.96     0.9685        137       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.8s<4.0s

      10/50      10.1G      1.957     0.9607     0.9689        140       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.9s<3.8s

      10/50      10.1G      1.959     0.9615     0.9698        112       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.1s<3.9s

      10/50      10.1G      1.957     0.9617     0.9703        116       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.2s<3.7s

      10/50      10.1G      1.954      0.961     0.9695        104       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.4s<3.5s

      10/50      10.1G      1.956     0.9625     0.9696        161       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.5s<3.3s

      10/50      10.1G      1.955      0.962     0.9701        112       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.7s<3.1s

      10/50      10.1G      1.957     0.9621     0.9704        140       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.8s<3.0s

      10/50      10.1G      1.956     0.9617     0.9704        164       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.0s<2.8s

      10/50      10.1G      1.955     0.9615     0.9701        155       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.1s<2.7s

      10/50      10.1G      1.954     0.9614     0.9702        146       1024: 86% ━━━━━━━━━━── 107/124 6.3it/s 16.3s<2.7s

      10/50      10.1G      1.954     0.9611     0.9701        152       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.5s<2.5s

      10/50      10.1G      1.956     0.9622     0.9707        121       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.6s<2.3s

      10/50      10.1G      1.955     0.9609     0.9704        136       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.8s<2.1s

      10/50      10.1G      1.954      0.961     0.9702        161       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.9s<2.0s

      10/50      10.1G      1.952       0.96     0.9696        104       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.1s<1.8s

      10/50      10.1G      1.951      0.959     0.9694        130       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.6s

      10/50      10.1G       1.95     0.9587     0.9691        166       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.3s<1.5s

      10/50      10.1G      1.949     0.9584     0.9689        152       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.5s<1.4s

      10/50      10.1G      1.952     0.9598      0.969        154       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.7s<1.2s

      10/50      10.1G      1.951     0.9594     0.9695        111       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.1s

      10/50      10.1G      1.951     0.9603     0.9695        162       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      10/50      10.1G      1.951     0.9607     0.9696        171       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.1s<0.7s

      10/50      10.1G       1.95     0.9598     0.9696        119       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.3s<0.6s

      10/50      10.1G      1.951     0.9603     0.9702        121       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.4s<0.4s

      10/50      10.1G       1.95     0.9606     0.9702        134       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.6s<0.3s

      10/50      10.1G      1.949     0.9598     0.9698        144       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 18.7s<0.2s

      10/50      10.1G      1.949     0.9598     0.9698        144       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.8it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227       0.56      0.601      0.591      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/50      10.1G      1.681     0.8991      0.902        114       1024: 0% ──────────── 0/124  0.1s

      11/50      10.1G      1.685      0.962     0.9375        132       1024: 1% ──────────── 1/124 1.9it/s 0.3s<1:03

      11/50      10.1G      1.729     0.9478     0.9384        197       1024: 2% ──────────── 2/124 3.4it/s 0.4s<36.0s

      11/50      10.1G      1.733     0.9264     0.9294        163       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.5s

      11/50      10.1G       1.76     0.9179       0.93        145       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.4s

      11/50      10.1G      1.778     0.9245      0.931        116       1024: 4% ──────────── 5/124 5.7it/s 0.9s<21.0s

      11/50      10.1G      1.789     0.9147     0.9435        104       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.6s

      11/50      10.1G      1.792     0.9196     0.9441        161       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.7s

      11/50      10.1G      1.798     0.9176     0.9485        121       1024: 6% ╸─────────── 8/124 6.2it/s 1.4s<18.8s

      11/50      10.1G      1.783     0.9149     0.9439        132       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

      11/50      10.1G      1.812     0.9189     0.9459        187       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.5s

      11/50      10.1G      1.819     0.9282     0.9552        144       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.1s

      11/50      10.1G      1.845     0.9465     0.9667        128       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.8s

      11/50      10.1G      1.853     0.9484     0.9657        154       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      11/50      10.1G      1.849      0.946     0.9635        153       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.3s

      11/50      10.1G      1.872     0.9527     0.9662        146       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.9s

      11/50      10.1G      1.876     0.9484     0.9711        120       1024: 13% ━╸────────── 16/124 6.5it/s 2.6s<16.6s

      11/50      10.1G      1.877     0.9464     0.9703        108       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      11/50      10.1G      1.881     0.9435     0.9715        122       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<15.9s

      11/50      10.1G      1.876     0.9437     0.9741        149       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      11/50      10.1G      1.867     0.9378     0.9726        123       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.4s

      11/50      10.1G      1.881      0.941     0.9744        161       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      11/50      10.1G      1.876     0.9357     0.9743        114       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.2s

      11/50      10.1G      1.873     0.9354      0.974        110       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

      11/50      10.1G      1.875     0.9354     0.9746        148       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.4s

      11/50      10.1G      1.877     0.9364     0.9725        169       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      11/50      10.1G      1.875     0.9355     0.9715        117       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.9s

      11/50      10.1G       1.88     0.9413     0.9736        120       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.6s

      11/50      10.1G      1.882     0.9416      0.972        173       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.4s

      11/50      10.1G      1.881     0.9404     0.9708        120       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.1s

      11/50      10.1G      1.871     0.9344     0.9681        122       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

      11/50      10.1G      1.867     0.9295     0.9698        102       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.5s

      11/50      10.1G      1.888     0.9354     0.9733        135       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.2s

      11/50      10.1G      1.881     0.9332     0.9711        141       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

      11/50      10.1G      1.881     0.9332     0.9721        104       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

      11/50      10.1G      1.876     0.9326     0.9726        146       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

      11/50      10.1G      1.875     0.9326     0.9719        172       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

      11/50      10.1G      1.874     0.9342     0.9704        125       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.7s<13.2s

      11/50      10.1G      1.874     0.9356     0.9713        110       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

      11/50      10.1G      1.865     0.9317     0.9694        127       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.0s<13.3s

      11/50      10.1G       1.87     0.9337     0.9713        107       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.8s

      11/50      10.1G      1.872     0.9339     0.9702        196       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

      11/50      10.1G      1.877     0.9358     0.9706        115       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      11/50      10.1G      1.877     0.9342     0.9711        125       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.0s

      11/50      10.1G       1.88     0.9353      0.971        125       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

      11/50      10.1G      1.875     0.9323     0.9692        139       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

      11/50      10.1G      1.879     0.9325     0.9693        130       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      11/50      10.1G      1.876     0.9304     0.9687        159       1024: 38% ━━━━╸─────── 47/124 6.3it/s 7.3s<12.2s

      11/50      10.1G      1.876     0.9282     0.9685        157       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.4s<11.8s

      11/50      10.1G      1.877      0.932     0.9689        123       1024: 40% ━━━━╸─────── 49/124 6.5it/s 7.6s<11.5s

      11/50      10.1G      1.878     0.9322     0.9697        132       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.2s

      11/50      10.1G       1.88     0.9322     0.9686        150       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<10.9s

      11/50      10.1G      1.878     0.9321     0.9685        111       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      11/50      10.1G      1.876     0.9317     0.9673        115       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

      11/50      10.1G      1.873     0.9307     0.9671        117       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      11/50      10.1G      1.874     0.9315     0.9663        160       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.7s

      11/50      10.1G      1.873     0.9313      0.966        132       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      11/50      10.1G      1.878     0.9332     0.9658        170       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.1s

      11/50      10.1G      1.886     0.9372     0.9662        129       1024: 47% ━━━━━╸────── 58/124 6.6it/s 8.9s<9.9s

      11/50      10.1G      1.886     0.9359     0.9678        158       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.7s

      11/50      10.1G      1.892     0.9374     0.9681        151       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

      11/50      10.1G      1.893     0.9402     0.9677        141       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

      11/50      10.1G      1.897     0.9444     0.9689        122       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.5s<9.3s

      11/50      10.1G      1.895      0.945     0.9693        114       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.7s<9.6s

      11/50      10.1G      1.895     0.9442     0.9704        104       1024: 52% ━━━━━━────── 64/124 6.4it/s 9.8s<9.3s

      11/50      10.1G      1.899      0.947     0.9709        133       1024: 52% ━━━━━━────── 65/124 6.5it/s 10.0s<9.0s

      11/50      10.1G      1.899     0.9472     0.9702        164       1024: 53% ━━━━━━────── 66/124 6.4it/s 10.2s<9.1s

      11/50      10.1G      1.899     0.9465     0.9701        136       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

      11/50      10.1G      1.901     0.9479     0.9693        207       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.5s<8.6s

      11/50      10.1G      1.903     0.9481     0.9694        134       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

      11/50      10.1G      1.905     0.9491     0.9688        179       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.8s<8.2s

      11/50      10.1G      1.908       0.95     0.9692        147       1024: 57% ━━━━━━╸───── 71/124 6.3it/s 10.9s<8.4s

      11/50      10.1G      1.907      0.949     0.9695        118       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.1s<8.0s

      11/50      10.1G      1.909     0.9503     0.9697        120       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.7s

      11/50      10.1G      1.907     0.9484     0.9688        141       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

      11/50      10.1G      1.907     0.9483     0.9692        156       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.5s<7.3s

      11/50      10.1G      1.909     0.9503     0.9689        162       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.7s<7.2s

      11/50      10.1G       1.91     0.9515     0.9687        169       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.8s<7.0s

      11/50      10.1G      1.912     0.9523     0.9696         96       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 12.0s<6.9s

      11/50      10.1G      1.916      0.953     0.9708        103       1024: 64% ━━━━━━━╸──── 79/124 6.3it/s 12.2s<7.2s

      11/50      10.1G      1.914     0.9527     0.9701        128       1024: 65% ━━━━━━━╸──── 80/124 6.3it/s 12.3s<6.9s

      11/50      10.1G      1.914     0.9521     0.9701        136       1024: 65% ━━━━━━━╸──── 81/124 6.5it/s 12.5s<6.6s

      11/50      10.1G      1.915     0.9517     0.9696        148       1024: 66% ━━━━━━━╸──── 82/124 6.6it/s 12.6s<6.4s

      11/50      10.1G      1.914     0.9513     0.9692        143       1024: 67% ━━━━━━━━──── 83/124 6.6it/s 12.8s<6.2s

      11/50      10.1G      1.915     0.9512     0.9693        114       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 12.9s<6.0s

      11/50      10.1G      1.915     0.9504      0.969        144       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.8s

      11/50      10.1G      1.914     0.9495     0.9692        107       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.2s<5.6s

      11/50      10.1G      1.914     0.9498      0.969        125       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.4s<5.7s

      11/50      10.1G      1.915     0.9508     0.9693        158       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.5s

      11/50      10.1G      1.915     0.9507      0.969        151       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.7s<5.3s

      11/50      10.1G      1.916     0.9496     0.9689        143       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

      11/50      10.1G      1.915     0.9492     0.9689        137       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 14.0s<4.9s

      11/50      10.1G      1.917     0.9495     0.9693        146       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.1s<4.7s

      11/50      10.1G      1.918     0.9503     0.9698        166       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.3s<4.6s

      11/50      10.1G      1.919     0.9516     0.9704        137       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      11/50      10.1G       1.92     0.9527     0.9709        157       1024: 77% ━━━━━━━━━─── 95/124 6.3it/s 14.6s<4.6s

      11/50      10.1G      1.921     0.9519     0.9724        124       1024: 77% ━━━━━━━━━─── 96/124 6.4it/s 14.7s<4.4s

      11/50      10.1G       1.92     0.9514     0.9717        137       1024: 78% ━━━━━━━━━─── 97/124 6.5it/s 14.9s<4.1s

      11/50      10.1G      1.921     0.9517     0.9721         99       1024: 79% ━━━━━━━━━─── 98/124 6.5it/s 15.0s<4.0s

      11/50      10.1G       1.92      0.951      0.972        122       1024: 80% ━━━━━━━━━╸── 99/124 6.6it/s 15.2s<3.8s

      11/50      10.1G       1.92     0.9506     0.9719        105       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.4s<3.7s

      11/50      10.1G      1.919      0.951     0.9716        158       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

      11/50      10.1G       1.92     0.9506     0.9718        133       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.6s<3.3s

      11/50      10.1G      1.921     0.9509     0.9723        123       1024: 83% ━━━━━━━━━╸── 103/124 6.3it/s 15.8s<3.3s

      11/50      10.1G      1.921     0.9515     0.9725         98       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 16.0s<3.1s

      11/50      10.1G      1.919     0.9507     0.9723        115       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.1s<2.9s

      11/50      10.1G      1.919     0.9498      0.972        170       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.3s<2.7s

      11/50      10.1G      1.918     0.9502     0.9722         92       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.4s<2.6s

      11/50      10.1G      1.916      0.949     0.9715        127       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.6s<2.4s

      11/50      10.1G      1.917     0.9486     0.9719        116       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.7s<2.2s

      11/50      10.1G      1.916     0.9482     0.9719        127       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.9s<2.1s

      11/50      10.1G      1.914     0.9489     0.9717        160       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 17.0s<2.0s

      11/50      10.1G      1.916     0.9495      0.972        163       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.2s<1.9s

      11/50      10.1G      1.916     0.9497     0.9724        125       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.3s<1.7s

      11/50      10.1G      1.914     0.9481     0.9717        107       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.5s<1.5s

      11/50      10.1G      1.913     0.9481     0.9714        114       1024: 93% ━━━━━━━━━━━─ 115/124 6.6it/s 17.6s<1.4s

      11/50      10.1G      1.913     0.9481      0.971        150       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.8s<1.2s

      11/50      10.1G      1.913     0.9476     0.9708        143       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.9s<1.0s

      11/50      10.1G      1.913     0.9483     0.9706        138       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.1s<0.9s

      11/50      10.1G      1.915     0.9485     0.9704         99       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.2s<0.8s

      11/50      10.1G      1.914     0.9486      0.971         93       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.4s<0.6s

      11/50      10.1G      1.914     0.9474     0.9707        133       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.5s<0.5s

      11/50      10.1G      1.913     0.9477     0.9711        106       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.7s<0.3s

      11/50      10.1G      1.912     0.9479     0.9711        118       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.8s<0.1s

      11/50      10.1G      1.912     0.9479     0.9711        118       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.8it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.639      0.547       0.59      0.359

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/50      10.1G      2.116     0.9181     0.9994        105       1024: 0% ──────────── 0/124  0.1s

      12/50      10.1G      1.943     0.9495     0.9865        112       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      12/50      10.1G      1.924     0.9475      0.977        156       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.3s

      12/50      10.1G      1.915     0.9539      0.987        124       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.2s

      12/50      10.1G      1.907     0.9578     0.9789        135       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.3s

      12/50      10.1G      1.867     0.9289     0.9753        112       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.6s

      12/50      10.1G      1.851     0.9356     0.9644        131       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<19.9s

      12/50      10.1G       1.81     0.9154      0.958        102       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.2s

      12/50      10.1G      1.831     0.9264     0.9678        127       1024: 6% ╸─────────── 8/124 6.2it/s 1.4s<18.7s

      12/50      10.1G      1.816     0.9189     0.9659        135       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

      12/50      10.1G      1.815     0.9165     0.9591        169       1024: 8% ╸─────────── 10/124 6.5it/s 1.7s<17.5s

      12/50      10.1G      1.804     0.9072     0.9533        163       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      12/50      10.1G      1.804     0.9043     0.9522        103       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.6s

      12/50      10.1G      1.793     0.8956     0.9458        189       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

      12/50      10.1G      1.811     0.8932     0.9468        113       1024: 11% ━─────────── 14/124 6.5it/s 2.3s<16.8s

      12/50      10.1G      1.798     0.8861     0.9407        146       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.4s

      12/50      10.1G      1.795     0.8904     0.9405        152       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.2s

      12/50      10.1G      1.784     0.8853      0.939        169       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<15.9s

      12/50      10.1G      1.774     0.8772     0.9358        122       1024: 15% ━╸────────── 18/124 6.8it/s 2.9s<15.7s

      12/50      10.1G      1.773     0.8739     0.9385        122       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.2s

      12/50      10.1G      1.779      0.874     0.9382        152       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.0s

      12/50      10.1G      1.779     0.8839     0.9408        110       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

      12/50      10.1G      1.778     0.8812     0.9379        167       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.3s

      12/50      10.1G      1.783     0.8809      0.939        114       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

      12/50      10.1G      1.796     0.8874     0.9408        161       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.8s

      12/50      10.1G      1.793     0.8871     0.9419        135       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

      12/50      10.1G      1.785     0.8835     0.9411        128       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.4s

      12/50      10.1G       1.79     0.8847     0.9439        130       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<15.0s

      12/50      10.1G      1.787     0.8844     0.9467        128       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      12/50      10.1G      1.789     0.8879     0.9464        116       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

      12/50      10.1G      1.789     0.8879     0.9446        174       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      12/50      10.1G      1.783     0.8881     0.9435        115       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

      12/50      10.1G       1.79     0.8928      0.946        136       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.7s

      12/50      10.1G      1.793     0.8917     0.9441        117       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.7s

      12/50      10.1G       1.79     0.8908     0.9437        136       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

      12/50      10.1G      1.789     0.8903     0.9428        135       1024: 28% ━━━───────── 35/124 6.3it/s 5.5s<14.1s

      12/50      10.1G      1.792     0.8913     0.9443        125       1024: 29% ━━━───────── 36/124 6.4it/s 5.6s<13.8s

      12/50      10.1G      1.796     0.8936     0.9439        218       1024: 30% ━━━╸──────── 37/124 6.5it/s 5.8s<13.4s

      12/50      10.1G      1.792     0.8897     0.9427        117       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.1s

      12/50      10.1G      1.787     0.8873     0.9421        124       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.1s<12.8s

      12/50      10.1G      1.791     0.8896     0.9443        157       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.7s

      12/50      10.1G      1.794     0.8894     0.9445        120       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.4s<12.4s

      12/50      10.1G      1.796     0.8924     0.9457        159       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

      12/50      10.1G      1.802     0.8946     0.9457        122       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.7s

      12/50      10.1G      1.808     0.8969     0.9468        161       1024: 35% ━━━━──────── 44/124 6.4it/s 6.8s<12.5s

      12/50      10.1G       1.81     0.8963     0.9477        157       1024: 36% ━━━━──────── 45/124 6.5it/s 7.0s<12.2s

      12/50      10.1G      1.813     0.8992     0.9497        118       1024: 37% ━━━━──────── 46/124 6.6it/s 7.1s<11.9s

      12/50      10.1G      1.814     0.8995     0.9516        107       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      12/50      10.1G      1.816     0.8996     0.9526        135       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.4s

      12/50      10.1G      1.818     0.9009     0.9528        117       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.1s

      12/50      10.1G      1.822     0.9045     0.9534        193       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      12/50      10.1G      1.819     0.9032     0.9524        134       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.3s

      12/50      10.1G      1.818     0.9025      0.952        161       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      12/50      10.1G      1.821     0.9029     0.9533        146       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.7s

      12/50      10.1G      1.819     0.9002     0.9524        129       1024: 44% ━━━━━─────── 54/124 6.6it/s 8.3s<10.5s

      12/50      10.1G      1.818     0.9007     0.9525        153       1024: 44% ━━━━━─────── 55/124 6.6it/s 8.5s<10.5s

      12/50      10.1G      1.816     0.9005     0.9524        105       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.6s<10.2s

      12/50      10.1G      1.816     0.9006      0.952        131       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

      12/50      10.1G      1.818     0.9017     0.9522        133       1024: 47% ━━━━━╸────── 58/124 6.6it/s 8.9s<10.0s

      12/50      10.1G      1.815     0.9012     0.9512        175       1024: 48% ━━━━━╸────── 59/124 6.2it/s 9.1s<10.6s

      12/50      10.1G      1.815     0.9015     0.9516        125       1024: 48% ━━━━━╸────── 60/124 6.4it/s 9.3s<10.1s

      12/50      10.1G      1.816     0.9035     0.9515        126       1024: 49% ━━━━━╸────── 61/124 6.5it/s 9.4s<9.7s

      12/50      10.1G      1.824     0.9056     0.9518        134       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.6s<9.4s

      12/50      10.1G      1.825     0.9056     0.9517        163       1024: 51% ━━━━━━────── 63/124 6.6it/s 9.7s<9.2s

      12/50      10.1G      1.825     0.9053     0.9515        108       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.9s<8.9s

      12/50      10.1G      1.827     0.9056     0.9528        108       1024: 52% ━━━━━━────── 65/124 6.5it/s 10.0s<9.0s

      12/50      10.1G       1.83     0.9061     0.9536        132       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.8s

      12/50      10.1G      1.829     0.9062     0.9525        161       1024: 54% ━━━━━━────── 67/124 6.3it/s 10.4s<9.0s

      12/50      10.1G      1.829     0.9063     0.9524        115       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.5s<8.6s

      12/50      10.1G      1.828     0.9061     0.9517        106       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.7s<8.3s

      12/50      10.1G      1.827     0.9059      0.952        146       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.8s<8.1s

      12/50      10.1G      1.827     0.9043     0.9518        126       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      12/50      10.1G      1.826     0.9062     0.9514        138       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.7s

      12/50      10.1G      1.826     0.9071     0.9511         99       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      12/50      10.1G      1.824     0.9068     0.9515        128       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

      12/50      10.1G      1.824     0.9074     0.9513        148       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.6s<7.7s

      12/50      10.1G      1.824     0.9078     0.9504        158       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.7s<7.4s

      12/50      10.1G      1.825     0.9078     0.9502        152       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.9s<7.1s

      12/50      10.1G      1.825     0.9071     0.9504        123       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      12/50      10.1G      1.827     0.9065     0.9501        121       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.2s<6.7s

      12/50      10.1G      1.826     0.9063     0.9509        132       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.3s<6.5s

      12/50      10.1G      1.827     0.9054     0.9511        149       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.4s<6.3s

      12/50      10.1G      1.829     0.9064     0.9518        126       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.6s<6.2s

      12/50      10.1G      1.834     0.9071     0.9526        120       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.8s<6.3s

      12/50      10.1G      1.834     0.9067     0.9525        148       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.2s

      12/50      10.1G      1.835     0.9074     0.9533        131       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.1s<5.9s

      12/50      10.1G      1.835     0.9085     0.9539        142       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      12/50      10.1G       1.84     0.9092     0.9548        122       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.4s<5.5s

      12/50      10.1G      1.844     0.9112     0.9557        159       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.5s<5.3s

      12/50      10.1G      1.846     0.9119     0.9561        124       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.7s<5.2s

      12/50      10.1G      1.847     0.9114     0.9562        114       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.8s<5.0s

      12/50      10.1G      1.848     0.9116     0.9559        113       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 14.0s<5.1s

      12/50      10.1G      1.848     0.9116     0.9561        136       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.1s<4.9s

      12/50      10.1G      1.849     0.9117     0.9567        120       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.3s<4.7s

      12/50      10.1G      1.847     0.9106      0.957        105       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      12/50      10.1G      1.848     0.9107     0.9573        146       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.6s<4.4s

      12/50      10.1G      1.849     0.9117     0.9572        177       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.7s<4.2s

      12/50      10.1G      1.851     0.9122     0.9577        113       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.9s<4.0s

      12/50      10.1G      1.852     0.9122     0.9576        106       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

      12/50      10.1G      1.852     0.9117     0.9572        150       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.2s<3.9s

      12/50      10.1G      1.853     0.9118     0.9571        131       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.3s<3.7s

      12/50      10.1G      1.856     0.9124     0.9585        133       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

      12/50      10.1G       1.86     0.9123      0.959        165       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      12/50      10.1G       1.86     0.9129      0.959        169       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.8s<3.1s

      12/50      10.1G      1.861     0.9136     0.9592        112       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.9s<3.0s

      12/50      10.1G      1.863     0.9142     0.9599        118       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.1s<2.8s

      12/50      10.1G      1.866     0.9143     0.9608        107       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      12/50      10.1G      1.867     0.9147     0.9609        152       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.4s<2.7s

      12/50      10.1G      1.867     0.9142     0.9604        180       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.6s<2.5s

      12/50      10.1G      1.868     0.9147       0.96        187       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.7s<2.3s

      12/50      10.1G      1.871     0.9154     0.9603        160       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.9s<2.1s

      12/50      10.1G      1.872     0.9161     0.9603        143       1024: 90% ━━━━━━━━━━╸─ 111/124 6.6it/s 17.0s<2.0s

      12/50      10.1G      1.876     0.9181     0.9607        149       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.2s<1.8s

      12/50      10.1G      1.875     0.9174     0.9608        105       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.3s<1.6s

      12/50      10.1G      1.877     0.9173     0.9613        157       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.5s<1.5s

      12/50      10.1G      1.878     0.9187     0.9622        116       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.6s<1.4s

      12/50      10.1G      1.876     0.9177     0.9625        128       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.8s<1.2s

      12/50      10.1G      1.879     0.9179     0.9626        120       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.9s<1.1s

      12/50      10.1G      1.878     0.9178     0.9623        204       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 18.1s<0.9s

      12/50      10.1G      1.878     0.9182     0.9623        132       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.2s<0.7s

      12/50      10.1G      1.876     0.9172     0.9618        152       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.4s<0.6s

      12/50      10.1G      1.876     0.9173     0.9624        102       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.5s<0.5s

      12/50      10.1G      1.876     0.9165     0.9625        123       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.7s<0.3s

      12/50      10.1G      1.875     0.9165     0.9628        144       1024: 99% ━━━━━━━━━━━╸ 123/124 6.3it/s 18.9s<0.2s

      12/50      10.1G      1.875     0.9165     0.9628        144       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.632      0.594      0.615      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/50      10.1G      1.861      1.002     0.9223        144       1024: 0% ──────────── 0/124  0.1s

      13/50      10.1G      1.847     0.9637     0.9566        109       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.8s

      13/50      10.1G      1.977      1.049     0.9913        123       1024: 2% ──────────── 2/124 3.3it/s 0.5s<36.9s

      13/50      10.1G      1.966      1.035      1.001        121       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.7s

      13/50      10.1G      1.908     0.9837     0.9873        108       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.4s

      13/50      10.1G      1.896     0.9736     0.9714        163       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.2s

      13/50      10.1G      1.901      0.975     0.9781        143       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

      13/50      10.1G      1.874     0.9516     0.9727        130       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.8s

      13/50      10.1G      1.875     0.9608     0.9728        106       1024: 6% ╸─────────── 8/124 6.0it/s 1.4s<19.3s

      13/50      10.1G      1.869     0.9619     0.9672        202       1024: 7% ╸─────────── 9/124 6.2it/s 1.5s<18.5s

      13/50      10.1G      1.862     0.9557     0.9677        142       1024: 8% ╸─────────── 10/124 6.4it/s 1.7s<17.8s

      13/50      10.1G      1.855     0.9426     0.9718         98       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.4s

      13/50      10.1G      1.862     0.9343     0.9743        124       1024: 10% ━─────────── 12/124 6.6it/s 2.0s<17.0s

      13/50      10.1G      1.874     0.9361     0.9782        136       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.7s

      13/50      10.1G      1.861     0.9397     0.9798        113       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.4s

      13/50      10.1G      1.867     0.9397     0.9803        132       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<17.0s

      13/50      10.1G      1.859     0.9354     0.9759        144       1024: 13% ━╸────────── 16/124 6.4it/s 2.6s<16.7s

      13/50      10.1G      1.869     0.9362     0.9769        139       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.4s

      13/50      10.1G      1.875      0.934     0.9757        156       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.1s

      13/50      10.1G      1.875     0.9308     0.9766        106       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      13/50      10.1G      1.874     0.9285     0.9727        212       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.5s

      13/50      10.1G       1.86     0.9213     0.9697        120       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      13/50      10.1G      1.863     0.9241     0.9714        125       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      13/50      10.1G      1.861     0.9196     0.9716        147       1024: 19% ━━────────── 23/124 6.3it/s 3.7s<16.1s

      13/50      10.1G      1.861     0.9166     0.9712        126       1024: 19% ━━────────── 24/124 6.4it/s 3.8s<15.6s

      13/50      10.1G      1.866     0.9134     0.9704        175       1024: 20% ━━────────── 25/124 6.5it/s 4.0s<15.2s

      13/50      10.1G      1.866     0.9095     0.9686        146       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.9s

      13/50      10.1G      1.858     0.9065     0.9663        136       1024: 22% ━━╸───────── 27/124 6.7it/s 4.3s<14.5s

      13/50      10.1G      1.856     0.9047     0.9664        108       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      13/50      10.1G      1.863     0.9044     0.9652        112       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

      13/50      10.1G       1.87     0.9081      0.967         91       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      13/50      10.1G      1.872     0.9075     0.9665        107       1024: 25% ━━━───────── 31/124 6.3it/s 4.9s<14.7s

      13/50      10.1G      1.871     0.9079     0.9671        169       1024: 26% ━━━───────── 32/124 6.3it/s 5.0s<14.5s

      13/50      10.1G      1.871     0.9066     0.9652        146       1024: 27% ━━━───────── 33/124 6.3it/s 5.2s<14.4s

      13/50      10.1G      1.873     0.9065     0.9635        192       1024: 27% ━━━───────── 34/124 6.4it/s 5.3s<14.0s

      13/50      10.1G      1.878     0.9067     0.9615        242       1024: 28% ━━━───────── 35/124 6.5it/s 5.5s<13.7s

      13/50      10.1G       1.88     0.9067     0.9625        106       1024: 29% ━━━───────── 36/124 6.6it/s 5.6s<13.3s

      13/50      10.1G      1.877      0.905     0.9607        148       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.8s<13.1s

      13/50      10.1G      1.882     0.9078     0.9612        129       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

      13/50      10.1G      1.886     0.9112     0.9599        235       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.4s

      13/50      10.1G      1.889      0.913     0.9609        115       1024: 32% ━━━╸──────── 40/124 6.4it/s 6.3s<13.0s

      13/50      10.1G      1.893     0.9137     0.9602        170       1024: 33% ━━━╸──────── 41/124 6.5it/s 6.4s<12.7s

      13/50      10.1G      1.893     0.9157       0.96        107       1024: 34% ━━━━──────── 42/124 6.6it/s 6.6s<12.5s

      13/50      10.1G      1.891     0.9152     0.9596        118       1024: 35% ━━━━──────── 43/124 6.7it/s 6.7s<12.2s

      13/50      10.1G       1.89     0.9127     0.9594        119       1024: 35% ━━━━──────── 44/124 6.7it/s 6.9s<12.0s

      13/50      10.1G      1.895     0.9149     0.9599        164       1024: 36% ━━━━──────── 45/124 6.7it/s 7.0s<11.8s

      13/50      10.1G        1.9     0.9135     0.9598        145       1024: 37% ━━━━──────── 46/124 6.6it/s 7.2s<11.7s

      13/50      10.1G      1.902     0.9141     0.9615        162       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<12.1s

      13/50      10.1G      1.896     0.9142     0.9614        117       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.5s<11.8s

      13/50      10.1G      1.895     0.9131     0.9609        161       1024: 40% ━━━━╸─────── 49/124 6.4it/s 7.6s<11.6s

      13/50      10.1G      1.893     0.9113     0.9616        143       1024: 40% ━━━━╸─────── 50/124 6.4it/s 7.8s<11.5s

      13/50      10.1G      1.892     0.9118      0.962        171       1024: 41% ━━━━╸─────── 51/124 6.6it/s 7.9s<11.1s

      13/50      10.1G      1.892     0.9096     0.9626        125       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.1s<10.8s

      13/50      10.1G      1.888     0.9057     0.9607        155       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.8s

      13/50      10.1G      1.892     0.9047     0.9607        193       1024: 44% ━━━━━─────── 54/124 6.6it/s 8.4s<10.5s

      13/50      10.1G      1.892     0.9032     0.9605        132       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.6s<10.9s

      13/50      10.1G      1.892     0.9026     0.9605        104       1024: 45% ━━━━━─────── 56/124 6.4it/s 8.7s<10.6s

      13/50      10.1G       1.89     0.9027     0.9599        123       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.9s<10.2s

      13/50      10.1G      1.893     0.9027     0.9599        115       1024: 47% ━━━━━╸────── 58/124 6.5it/s 9.0s<10.1s

      13/50      10.1G      1.894      0.902      0.959        127       1024: 48% ━━━━━╸────── 59/124 6.6it/s 9.2s<9.8s

      13/50      10.1G      1.895     0.9019      0.959        155       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.3s<9.6s

      13/50      10.1G      1.892     0.9013     0.9585        153       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.5s<9.5s

      13/50      10.1G      1.893     0.9021     0.9589        146       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.6s<9.4s

      13/50      10.1G      1.892     0.9026     0.9577        123       1024: 51% ━━━━━━────── 63/124 6.2it/s 9.8s<9.8s

      13/50      10.1G       1.89     0.9013     0.9578        122       1024: 52% ━━━━━━────── 64/124 6.3it/s 10.0s<9.5s

      13/50      10.1G       1.89     0.9015     0.9579        150       1024: 52% ━━━━━━────── 65/124 6.4it/s 10.1s<9.2s

      13/50      10.1G      1.892     0.9033     0.9605         99       1024: 53% ━━━━━━────── 66/124 6.4it/s 10.3s<9.0s

      13/50      10.1G      1.889     0.9019     0.9591        133       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.4s<8.7s

      13/50      10.1G      1.889     0.9004     0.9589        129       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.6s<8.4s

      13/50      10.1G      1.884     0.8994     0.9578        132       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.7s<8.2s

      13/50      10.1G      1.885     0.8989     0.9574        212       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.9s<8.0s

      13/50      10.1G      1.884     0.8983      0.957        118       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 11.0s<8.2s

      13/50      10.1G      1.882     0.8971     0.9568        125       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.2s<8.0s

      13/50      10.1G      1.883     0.8962     0.9564        160       1024: 59% ━━━━━━━───── 73/124 6.5it/s 11.3s<7.8s

      13/50      10.1G      1.882     0.8972     0.9559        178       1024: 60% ━━━━━━━───── 74/124 6.5it/s 11.5s<7.7s

      13/50      10.1G      1.882      0.897     0.9561        126       1024: 60% ━━━━━━━───── 75/124 6.6it/s 11.6s<7.4s

      13/50      10.1G      1.883      0.897     0.9565        167       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.8s<7.2s

      13/50      10.1G      1.881     0.8962     0.9552        157       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.9s<7.0s

      13/50      10.1G      1.879     0.8961     0.9551        150       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.1s<6.8s

      13/50      10.1G      1.877     0.8959     0.9544        179       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.2s<7.0s

      13/50      10.1G      1.875     0.8951      0.954        116       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.4s<6.7s

      13/50      10.1G      1.875      0.895     0.9539        113       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.5s<6.5s

      13/50      10.1G      1.874     0.8942     0.9538        115       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.7s<6.3s

      13/50      10.1G      1.872     0.8946     0.9537        133       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.8s<6.1s

      13/50      10.1G      1.876     0.8949     0.9544        137       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 13.0s<5.9s

      13/50      10.1G      1.876      0.896     0.9547        120       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 13.1s<5.7s

      13/50      10.1G      1.875     0.8961     0.9547        118       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.3s<5.6s

      13/50      10.1G      1.876     0.8973     0.9548        139       1024: 70% ━━━━━━━━──── 87/124 6.3it/s 13.5s<5.9s

      13/50      10.1G      1.875     0.8969     0.9551        137       1024: 71% ━━━━━━━━╸─── 88/124 6.4it/s 13.6s<5.7s

      13/50      10.1G      1.876      0.898     0.9553        104       1024: 72% ━━━━━━━━╸─── 89/124 6.5it/s 13.8s<5.4s

      13/50      10.1G      1.877     0.8982     0.9561        141       1024: 73% ━━━━━━━━╸─── 90/124 6.5it/s 13.9s<5.2s

      13/50      10.1G      1.876     0.8979     0.9559        179       1024: 73% ━━━━━━━━╸─── 91/124 6.6it/s 14.1s<5.0s

      13/50      10.1G      1.878     0.8979     0.9565        126       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.2s<4.8s

      13/50      10.1G      1.876     0.8966     0.9563        136       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.4s<4.7s

      13/50      10.1G      1.876     0.8957     0.9556        137       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.5s<4.5s

      13/50      10.1G      1.876     0.8958     0.9551        175       1024: 77% ━━━━━━━━━─── 95/124 6.3it/s 14.7s<4.6s

      13/50      10.1G      1.879     0.8984     0.9566        120       1024: 77% ━━━━━━━━━─── 96/124 6.4it/s 14.8s<4.4s

      13/50      10.1G      1.879     0.8975     0.9568        134       1024: 78% ━━━━━━━━━─── 97/124 6.4it/s 15.0s<4.2s

      13/50      10.1G      1.877     0.8964     0.9565        177       1024: 79% ━━━━━━━━━─── 98/124 6.4it/s 15.2s<4.1s

      13/50      10.1G      1.876     0.8962     0.9563        119       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.3s<3.9s

      13/50      10.1G      1.877     0.8966     0.9565        161       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.5s<3.7s

      13/50      10.1G      1.876     0.8974     0.9569        139       1024: 81% ━━━━━━━━━╸── 101/124 6.5it/s 15.6s<3.6s

      13/50      10.1G      1.876     0.8979     0.9572        131       1024: 82% ━━━━━━━━━╸── 102/124 6.4it/s 15.8s<3.4s

      13/50      10.1G      1.876     0.8985     0.9575        116       1024: 83% ━━━━━━━━━╸── 103/124 6.1it/s 16.0s<3.4s

      13/50      10.1G      1.877     0.8983     0.9578        141       1024: 84% ━━━━━━━━━━── 104/124 6.2it/s 16.1s<3.2s

      13/50      10.1G      1.877      0.898     0.9577        132       1024: 85% ━━━━━━━━━━── 105/124 6.4it/s 16.3s<3.0s

      13/50      10.1G      1.876     0.8969     0.9576        134       1024: 85% ━━━━━━━━━━── 106/124 6.5it/s 16.4s<2.8s

      13/50      10.1G      1.874     0.8964     0.9574        129       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.6s<2.6s

      13/50      10.1G      1.874     0.8964     0.9572        159       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.7s<2.4s

      13/50      10.1G      1.873     0.8958     0.9574        144       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.9s<2.2s

      13/50      10.1G      1.875     0.8962     0.9576        157       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 17.0s<2.1s

      13/50      10.1G      1.878     0.8965     0.9579        143       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 17.2s<2.0s

      13/50      10.1G      1.876      0.895     0.9576        122       1024: 90% ━━━━━━━━━━╸─ 112/124 6.4it/s 17.3s<1.9s

      13/50      10.1G      1.876      0.895     0.9577        131       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 17.5s<1.7s

      13/50      10.1G      1.877     0.8955     0.9576        182       1024: 92% ━━━━━━━━━━━─ 114/124 6.5it/s 17.6s<1.5s

      13/50      10.1G      1.877     0.8962      0.958        135       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.8s<1.4s

      13/50      10.1G      1.876     0.8961     0.9576        161       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.9s<1.2s

      13/50      10.1G      1.877     0.8973     0.9592        105       1024: 94% ━━━━━━━━━━━─ 117/124 6.5it/s 18.1s<1.1s

      13/50      10.1G      1.876     0.8976     0.9594        125       1024: 95% ━━━━━━━━━━━─ 118/124 6.4it/s 18.3s<0.9s

      13/50      10.1G      1.877     0.8977     0.9597        132       1024: 96% ━━━━━━━━━━━╸ 119/124 6.2it/s 18.4s<0.8s

      13/50      10.1G      1.878     0.8979       0.96        154       1024: 97% ━━━━━━━━━━━╸ 120/124 6.3it/s 18.6s<0.6s

      13/50      10.1G      1.879     0.8981     0.9604        184       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.7s<0.5s

      13/50      10.1G      1.878     0.8972     0.9605        120       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.9s<0.3s

      13/50      10.1G      1.879     0.8974     0.9603        219       1024: 99% ━━━━━━━━━━━╸ 123/124 6.6it/s 19.0s<0.2s

      13/50      10.1G      1.879     0.8974     0.9603        219       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 19.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.671      0.601      0.625      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/50      10.1G      1.384     0.6961     0.8667        103       1024: 0% ──────────── 0/124  0.1s

      14/50      10.1G      1.651     0.7643     0.9284        170       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      14/50      10.1G      1.704     0.8057      0.957        135       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.0s

      14/50      10.1G      1.786     0.8525     0.9637        110       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.4s

      14/50      10.1G      1.781     0.8618     0.9624        138       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.7s

      14/50      10.1G      1.761     0.8531     0.9539        123       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.7s

      14/50      10.1G      1.775      0.844     0.9508        153       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.0s

      14/50      10.1G      1.784     0.8524     0.9495        160       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      14/50      10.1G      1.764     0.8434     0.9444        138       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.3s

      14/50      10.1G      1.764     0.8412     0.9407        115       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.7s

      14/50      10.1G       1.77     0.8413      0.938        137       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.2s

      14/50      10.1G      1.766     0.8453     0.9382        178       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<17.8s

      14/50      10.1G      1.756     0.8439      0.941        114       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.5s

      14/50      10.1G      1.774     0.8535     0.9424        158       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.0s

      14/50      10.1G      1.796     0.8571     0.9461        148       1024: 11% ━─────────── 14/124 6.5it/s 2.3s<16.8s

      14/50      10.1G      1.795     0.8596     0.9474        159       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.5s

      14/50      10.1G      1.785     0.8538     0.9451        177       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.2s

      14/50      10.1G      1.797     0.8558     0.9443        167       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<15.9s

      14/50      10.1G      1.805     0.8618     0.9461        167       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      14/50      10.1G      1.805     0.8581     0.9475        181       1024: 15% ━╸────────── 19/124 6.3it/s 3.0s<16.5s

      14/50      10.1G      1.804     0.8587     0.9459        135       1024: 16% ━╸────────── 20/124 6.4it/s 3.2s<16.2s

      14/50      10.1G      1.805     0.8601     0.9489        111       1024: 17% ━━────────── 21/124 6.5it/s 3.3s<15.7s

      14/50      10.1G      1.807      0.864     0.9506        104       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.3s

      14/50      10.1G      1.808     0.8684     0.9517        100       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

      14/50      10.1G      1.807     0.8683      0.951        129       1024: 19% ━━────────── 24/124 6.8it/s 3.8s<14.8s

      14/50      10.1G      1.813     0.8737     0.9534        158       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

      14/50      10.1G      1.826      0.877      0.952        217       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.5s

      14/50      10.1G      1.823     0.8745     0.9488         94       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<15.0s

      14/50      10.1G      1.821      0.877     0.9486        129       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      14/50      10.1G      1.835     0.8881     0.9512        129       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.3s

      14/50      10.1G      1.831     0.8875     0.9506        185       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      14/50      10.1G      1.828     0.8865     0.9484        148       1024: 25% ━━━───────── 31/124 6.8it/s 4.8s<13.8s

      14/50      10.1G      1.827     0.8823     0.9488        107       1024: 26% ━━━───────── 32/124 6.8it/s 5.0s<13.5s

      14/50      10.1G      1.824     0.8811     0.9485        103       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      14/50      10.1G      1.825     0.8819     0.9503        117       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.2s

      14/50      10.1G      1.824     0.8837     0.9491        137       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.7s

      14/50      10.1G      1.821      0.884     0.9491        121       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.5s

      14/50      10.1G      1.825     0.8868     0.9487        126       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.7s<13.2s

      14/50      10.1G      1.823     0.8848     0.9469        150       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.1s

      14/50      10.1G      1.825     0.8854     0.9472        136       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.0s<12.8s

      14/50      10.1G      1.829     0.8868     0.9471        103       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.2s<12.5s

      14/50      10.1G      1.829     0.8891     0.9474        164       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.3s

      14/50      10.1G      1.833     0.8903     0.9482        120       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.1s

      14/50      10.1G      1.836     0.8908     0.9487        106       1024: 35% ━━━━──────── 43/124 6.5it/s 6.7s<12.5s

      14/50      10.1G      1.839       0.89     0.9489        103       1024: 35% ━━━━──────── 44/124 6.6it/s 6.8s<12.1s

      14/50      10.1G      1.841     0.8906     0.9492        124       1024: 36% ━━━━──────── 45/124 6.7it/s 6.9s<11.8s

      14/50      10.1G      1.846     0.8927     0.9491        265       1024: 37% ━━━━──────── 46/124 6.6it/s 7.1s<11.7s

      14/50      10.1G      1.843     0.8912     0.9483        155       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.2s<11.5s

      14/50      10.1G      1.839     0.8897     0.9473        160       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.3s

      14/50      10.1G      1.837     0.8897      0.947        114       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.1s

      14/50      10.1G      1.838     0.8918     0.9477        138       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      14/50      10.1G      1.835     0.8899     0.9465        131       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.9s<11.3s

      14/50      10.1G      1.832     0.8892     0.9467        131       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      14/50      10.1G      1.831     0.8892     0.9467        168       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

      14/50      10.1G       1.83     0.8886     0.9476        108       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      14/50      10.1G       1.83     0.8879     0.9467        164       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.4s<10.2s

      14/50      10.1G      1.827     0.8852     0.9453        167       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.1s

      14/50      10.1G      1.826      0.884     0.9448        122       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.8s

      14/50      10.1G      1.827     0.8827     0.9452        151       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.7s

      14/50      10.1G      1.828     0.8837      0.945        145       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.1s<10.1s

      14/50      10.1G      1.827     0.8832     0.9444        129       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.2s<9.8s

      14/50      10.1G      1.828     0.8836     0.9443        124       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.5s

      14/50      10.1G      1.832     0.8851     0.9439        193       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.3s

      14/50      10.1G      1.834     0.8848     0.9442        128       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.6s<9.1s

      14/50      10.1G      1.839     0.8867     0.9455        149       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.8s<8.9s

      14/50      10.1G      1.839     0.8867     0.9466        138       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      14/50      10.1G      1.837     0.8864     0.9463        120       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.5s

      14/50      10.1G      1.834     0.8844     0.9456        133       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.3s<8.8s

      14/50      10.1G      1.834     0.8848     0.9449        183       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.5s

      14/50      10.1G      1.836      0.886     0.9455        157       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.6s<8.3s

      14/50      10.1G      1.835     0.8863     0.9457        136       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.1s

      14/50      10.1G      1.836     0.8865     0.9458        151       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      14/50      10.1G      1.838     0.8881     0.9455        213       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.8s

      14/50      10.1G      1.837     0.8874     0.9461         97       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.8s

      14/50      10.1G      1.838     0.8877     0.9459        172       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

      14/50      10.1G      1.837     0.8865     0.9447        194       1024: 60% ━━━━━━━───── 75/124 6.3it/s 11.5s<7.7s

      14/50      10.1G      1.835     0.8852     0.9443        172       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

      14/50      10.1G      1.834     0.8841      0.944        115       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      14/50      10.1G      1.835      0.883     0.9439        125       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<7.0s

      14/50      10.1G      1.833      0.883     0.9437        119       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.8s

      14/50      10.1G      1.835     0.8842      0.944        162       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.2s<6.6s

      14/50      10.1G      1.836     0.8839     0.9432        184       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      14/50      10.1G      1.834     0.8845     0.9436        112       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      14/50      10.1G      1.837     0.8855     0.9433        193       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.7s<6.5s

      14/50      10.1G      1.837     0.8856     0.9425        159       1024: 68% ━━━━━━━━──── 84/124 6.4it/s 12.9s<6.3s

      14/50      10.1G      1.836     0.8845     0.9428         97       1024: 69% ━━━━━━━━──── 85/124 6.3it/s 13.0s<6.2s

      14/50      10.1G      1.838     0.8851     0.9428        102       1024: 69% ━━━━━━━━──── 86/124 6.4it/s 13.2s<5.9s

      14/50      10.1G      1.837     0.8862     0.9428        146       1024: 70% ━━━━━━━━──── 87/124 6.3it/s 13.3s<5.9s

      14/50      10.1G      1.836     0.8858     0.9432        141       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.6s

      14/50      10.1G      1.837     0.8852     0.9436        130       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      14/50      10.1G       1.84      0.887     0.9443        158       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.8s<5.1s

      14/50      10.1G      1.838     0.8866     0.9437        122       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 14.0s<5.2s

      14/50      10.1G      1.837     0.8865     0.9442        126       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.1s<4.9s

      14/50      10.1G      1.837     0.8871     0.9445        144       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      14/50      10.1G      1.838     0.8867      0.944        183       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.4s<4.5s

      14/50      10.1G      1.837     0.8865     0.9445        115       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.5s<4.3s

      14/50      10.1G      1.834     0.8858     0.9438        127       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.7s<4.1s

      14/50      10.1G      1.836     0.8875     0.9441        123       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.8s<4.0s

      14/50      10.1G      1.838     0.8885      0.945        119       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.0s<3.8s

      14/50      10.1G      1.841     0.8904     0.9454        126       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.2s<3.9s

      14/50      10.1G       1.84     0.8906     0.9455        131       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.3s<3.7s

      14/50      10.1G      1.845     0.8931     0.9466        185       1024: 81% ━━━━━━━━━╸── 101/124 6.5it/s 15.5s<3.5s

      14/50      10.1G      1.845     0.8931     0.9466        118       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.6s<3.3s

      14/50      10.1G      1.846     0.8934      0.947        136       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.7s<3.1s

      14/50      10.1G      1.847     0.8947     0.9467        210       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.9s<3.0s

      14/50      10.1G      1.847     0.8947     0.9467        119       1024: 85% ━━━━━━━━━━── 105/124 6.5it/s 16.1s<2.9s

      14/50      10.1G       1.85     0.8982     0.9472        118       1024: 85% ━━━━━━━━━━── 106/124 6.5it/s 16.2s<2.8s

      14/50      10.1G      1.847     0.8964     0.9463        122       1024: 86% ━━━━━━━━━━── 107/124 6.2it/s 16.4s<2.7s

      14/50      10.1G      1.849      0.897     0.9461        148       1024: 87% ━━━━━━━━━━── 108/124 6.2it/s 16.6s<2.6s

      14/50      10.1G      1.851     0.8979     0.9467        205       1024: 88% ━━━━━━━━━━╸─ 109/124 6.3it/s 16.7s<2.4s

      14/50      10.1G      1.853     0.8986     0.9468        168       1024: 89% ━━━━━━━━━━╸─ 110/124 6.4it/s 16.9s<2.2s

      14/50      10.1G      1.851     0.8984     0.9473        111       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 17.0s<2.0s

      14/50      10.1G      1.851     0.8979     0.9471        129       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.2s<1.9s

      14/50      10.1G      1.851     0.8979     0.9469        148       1024: 91% ━━━━━━━━━━╸─ 113/124 6.4it/s 17.3s<1.7s

      14/50      10.1G      1.852      0.898     0.9468        121       1024: 92% ━━━━━━━━━━━─ 114/124 6.3it/s 17.5s<1.6s

      14/50      10.1G       1.85     0.8982     0.9465        107       1024: 93% ━━━━━━━━━━━─ 115/124 6.1it/s 17.7s<1.5s

      14/50      10.1G      1.851      0.898     0.9463        154       1024: 94% ━━━━━━━━━━━─ 116/124 6.2it/s 17.8s<1.3s

      14/50      10.1G      1.852      0.899      0.947        114       1024: 94% ━━━━━━━━━━━─ 117/124 6.3it/s 18.0s<1.1s

      14/50      10.1G      1.851     0.8984     0.9471        131       1024: 95% ━━━━━━━━━━━─ 118/124 6.3it/s 18.1s<1.0s

      14/50      10.1G      1.853     0.8999     0.9475        152       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.3s<0.8s

      14/50      10.1G      1.854     0.9004     0.9475        137       1024: 97% ━━━━━━━━━━━╸ 120/124 6.3it/s 18.5s<0.6s

      14/50      10.1G      1.854     0.8996     0.9474        141       1024: 98% ━━━━━━━━━━━╸ 121/124 6.3it/s 18.6s<0.5s

      14/50      10.1G      1.854     0.8994     0.9474        150       1024: 98% ━━━━━━━━━━━╸ 122/124 6.4it/s 18.8s<0.3s

      14/50      10.1G      1.853     0.8993     0.9471        173       1024: 99% ━━━━━━━━━━━╸ 123/124 6.2it/s 18.9s<0.2s

      14/50      10.1G      1.853     0.8993     0.9471        173       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 18.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.8it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.658      0.607      0.622      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/50      10.1G      1.827     0.8564     0.9593        140       1024: 0% ──────────── 0/124  0.1s

      15/50      10.1G      1.828      0.836     0.9344        149       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:01

      15/50      10.1G      1.821     0.8021     0.9415        110       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.4s

      15/50      10.1G      1.829     0.8202     0.9471        163       1024: 2% ──────────── 3/124 4.5it/s 0.6s<27.1s

      15/50      10.1G      1.813       0.82     0.9477        167       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.7s

      15/50      10.1G      1.822     0.8216     0.9441        138       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.2s

      15/50      10.1G      1.792     0.8213     0.9315        114       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

      15/50      10.1G      1.791     0.8251     0.9326        179       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.8s

      15/50      10.1G      1.822     0.8381     0.9414        131       1024: 6% ╸─────────── 8/124 6.2it/s 1.4s<18.7s

      15/50      10.1G      1.842     0.8486     0.9409        185       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.2s

      15/50      10.1G      1.861      0.857     0.9459        102       1024: 8% ╸─────────── 10/124 6.4it/s 1.7s<17.9s

      15/50      10.1G      1.847     0.8533     0.9484        132       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.3s

      15/50      10.1G       1.87     0.8597     0.9501        163       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<16.9s

      15/50      10.1G      1.867     0.8587     0.9512        132       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      15/50      10.1G      1.863      0.856     0.9535        114       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.3s

      15/50      10.1G      1.871     0.8619     0.9565        118       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.8s

      15/50      10.1G      1.869      0.857     0.9578        111       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.3s

      15/50      10.1G      1.864     0.8568     0.9593        119       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<16.1s

      15/50      10.1G      1.861     0.8588      0.957        156       1024: 15% ━╸────────── 18/124 6.7it/s 2.8s<15.8s

      15/50      10.1G      1.869     0.8622     0.9608        126       1024: 15% ━╸────────── 19/124 6.8it/s 3.0s<15.5s

      15/50      10.1G      1.874     0.8687     0.9589        134       1024: 16% ━╸────────── 20/124 6.8it/s 3.1s<15.3s

      15/50      10.1G       1.88     0.8711     0.9607        136       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.1s

      15/50      10.1G      1.864     0.8647     0.9552        193       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

      15/50      10.1G      1.865     0.8648     0.9557        110       1024: 19% ━━────────── 23/124 6.5it/s 3.6s<15.5s

      15/50      10.1G      1.857     0.8634     0.9522        128       1024: 19% ━━────────── 24/124 6.6it/s 3.7s<15.1s

      15/50      10.1G      1.854     0.8627      0.951        140       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.8s

      15/50      10.1G       1.86     0.8645     0.9509        169       1024: 21% ━━╸───────── 26/124 6.6it/s 4.0s<14.7s

      15/50      10.1G      1.863     0.8655     0.9504        111       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.4s

      15/50      10.1G      1.867       0.87     0.9526        127       1024: 23% ━━╸───────── 28/124 6.8it/s 4.3s<14.2s

      15/50      10.1G      1.869     0.8704     0.9519        185       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      15/50      10.1G      1.865     0.8676     0.9516        104       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      15/50      10.1G      1.869     0.8709     0.9553        112       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.3s

      15/50      10.1G      1.865     0.8687     0.9554        121       1024: 26% ━━━───────── 32/124 6.6it/s 4.9s<13.9s

      15/50      10.1G      1.865     0.8692     0.9544        133       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.6s

      15/50      10.1G      1.869     0.8739     0.9564        106       1024: 27% ━━━───────── 34/124 6.8it/s 5.2s<13.3s

      15/50      10.1G      1.869     0.8769     0.9556        187       1024: 28% ━━━───────── 35/124 6.8it/s 5.4s<13.1s

      15/50      10.1G      1.864     0.8768     0.9551        136       1024: 29% ━━━───────── 36/124 6.8it/s 5.5s<12.9s

      15/50      10.1G      1.864     0.8792     0.9567        111       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.7s

      15/50      10.1G      1.863     0.8775     0.9559        105       1024: 31% ━━━╸──────── 38/124 6.9it/s 5.8s<12.6s

      15/50      10.1G      1.859     0.8796     0.9566        138       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

      15/50      10.1G      1.853     0.8775      0.955        116       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.1s<12.7s

      15/50      10.1G      1.864     0.8833     0.9561        170       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.4s

      15/50      10.1G      1.861      0.883     0.9562        117       1024: 34% ━━━━──────── 42/124 6.8it/s 6.4s<12.1s

      15/50      10.1G      1.859     0.8833      0.955        148       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

      15/50      10.1G      1.858     0.8822     0.9541         97       1024: 35% ━━━━──────── 44/124 6.7it/s 6.7s<11.9s

      15/50      10.1G      1.859     0.8856     0.9542        194       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      15/50      10.1G       1.86     0.8856     0.9555        116       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.4s

      15/50      10.1G      1.859     0.8871     0.9545        162       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.2s<12.0s

      15/50      10.1G      1.862     0.8858     0.9548        132       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.3s<11.6s

      15/50      10.1G      1.865     0.8904     0.9555        249       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.5s<11.3s

      15/50      10.1G      1.866     0.8905     0.9549        189       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.6s<11.1s

      15/50      10.1G       1.87      0.894     0.9559        156       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.8s

      15/50      10.1G      1.871     0.8955     0.9569        127       1024: 42% ━━━━━─────── 52/124 6.8it/s 7.9s<10.6s

      15/50      10.1G      1.871     0.8954     0.9573        153       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

      15/50      10.1G      1.871     0.8962     0.9581        116       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

      15/50      10.1G      1.865     0.8944      0.958        113       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

      15/50      10.1G       1.86     0.8925     0.9571        130       1024: 45% ━━━━━─────── 56/124 6.5it/s 8.5s<10.4s

      15/50      10.1G      1.863      0.893     0.9578        115       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.7s<10.2s

      15/50      10.1G      1.867     0.8931     0.9598        140       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.8s<9.9s

      15/50      10.1G      1.868     0.8926     0.9611        104       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.0s<9.7s

      15/50      10.1G      1.868     0.8911     0.9607        180       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.1s<9.5s

      15/50      10.1G      1.867     0.8922     0.9601        114       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.3s<9.6s

      15/50      10.1G      1.867     0.8931      0.961        114       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.4s<9.3s

      15/50      10.1G      1.869     0.8948     0.9613        155       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.6s<9.6s

      15/50      10.1G      1.869     0.8948     0.9609        129       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.8s<9.2s

      15/50      10.1G      1.869     0.8944     0.9613        127       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<8.9s

      15/50      10.1G      1.869     0.8939     0.9606        156       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      15/50      10.1G      1.875     0.8959     0.9611        126       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.2s<8.5s

      15/50      10.1G      1.876     0.8957     0.9606        150       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.4s

      15/50      10.1G      1.872     0.8953     0.9602        104       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.5s<8.3s

      15/50      10.1G      1.871     0.8958     0.9604        105       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.7s<8.0s

      15/50      10.1G      1.869     0.8962     0.9597        168       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.8s<8.3s

      15/50      10.1G      1.868     0.8957      0.959        170       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

      15/50      10.1G      1.868     0.8955     0.9589        122       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      15/50      10.1G      1.872      0.895     0.9595        171       1024: 60% ━━━━━━━───── 74/124 6.6it/s 11.3s<7.5s

      15/50      10.1G      1.873     0.8972     0.9595        113       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

      15/50      10.1G      1.873     0.8976     0.9597        120       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.2s

      15/50      10.1G      1.871      0.898     0.9597        156       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.7s<7.0s

      15/50      10.1G      1.871     0.8975     0.9588        213       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.8s

      15/50      10.1G      1.872     0.8972     0.9585        157       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.0s<7.0s

      15/50      10.1G      1.872     0.8971     0.9593        102       1024: 65% ━━━━━━━╸──── 80/124 6.4it/s 12.2s<6.9s

      15/50      10.1G      1.872     0.8964     0.9597        114       1024: 65% ━━━━━━━╸──── 81/124 6.5it/s 12.3s<6.7s

      15/50      10.1G      1.871     0.8954     0.9596        126       1024: 66% ━━━━━━━╸──── 82/124 6.4it/s 12.5s<6.6s

      15/50      10.1G      1.869     0.8946     0.9597        139       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.7s<6.3s

      15/50      10.1G      1.867     0.8932     0.9593        142       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.8s<6.0s

      15/50      10.1G      1.867     0.8925     0.9587        137       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.9s<5.8s

      15/50      10.1G      1.867     0.8925     0.9579        186       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.1s<5.6s

      15/50      10.1G      1.869     0.8941     0.9587         97       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.8s

      15/50      10.1G      1.868     0.8943     0.9587        140       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.5s

      15/50      10.1G      1.868     0.8948     0.9588        132       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.3s

      15/50      10.1G      1.869     0.8953     0.9589        147       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      15/50      10.1G      1.869     0.8948      0.958        124       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

      15/50      10.1G      1.868     0.8944     0.9583        130       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

      15/50      10.1G      1.869     0.8953     0.9581        117       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

      15/50      10.1G      1.871     0.8959      0.958        112       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      15/50      10.1G      1.874     0.8979     0.9588        129       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

      15/50      10.1G      1.875     0.8972     0.9595        107       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.2s

      15/50      10.1G      1.873     0.8962     0.9596        111       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.8s<4.0s

      15/50      10.1G      1.871     0.8962     0.9592        102       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      15/50      10.1G      1.871     0.8976     0.9599        102       1024: 80% ━━━━━━━━━╸── 99/124 6.8it/s 15.0s<3.7s

      15/50      10.1G       1.87     0.8973     0.9602        123       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.2s<3.5s

      15/50      10.1G      1.867     0.8963     0.9602        113       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.3s<3.4s

      15/50      10.1G      1.868     0.8956     0.9598        119       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

      15/50      10.1G      1.867     0.8952      0.959        144       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.7s<3.2s

      15/50      10.1G      1.864     0.8949     0.9585        139       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.8s<3.1s

      15/50      10.1G      1.864     0.8951     0.9583        128       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

      15/50      10.1G      1.865     0.8951     0.9581        160       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      15/50      10.1G      1.865     0.8962     0.9579        147       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.3s<2.5s

      15/50      10.1G      1.863     0.8949     0.9571        148       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      15/50      10.1G      1.866     0.8957     0.9572         96       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.5s<2.2s

      15/50      10.1G      1.864     0.8959     0.9568        129       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

      15/50      10.1G      1.863     0.8957     0.9569        134       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

      15/50      10.1G      1.862     0.8955     0.9569        136       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.0s<1.9s

      15/50      10.1G      1.863     0.8956     0.9578        112       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.2s<1.7s

      15/50      10.1G      1.862      0.895     0.9576        115       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      15/50      10.1G      1.862      0.895     0.9572        190       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

      15/50      10.1G       1.86     0.8939     0.9567        137       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      15/50      10.1G       1.86     0.8941     0.9568        162       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.8s<1.0s

      15/50      10.1G      1.859      0.894     0.9568        158       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      15/50      10.1G      1.859     0.8943     0.9572        124       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

      15/50      10.1G      1.858     0.8945     0.9573        132       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.2s<0.6s

      15/50      10.1G      1.858     0.8939     0.9572        121       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.4s<0.5s

      15/50      10.1G      1.858     0.8939     0.9575        107       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

      15/50      10.1G      1.859     0.8949     0.9576        184       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

      15/50      10.1G      1.859     0.8949     0.9576        184       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.1it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.642       0.57      0.603      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/50      10.1G      1.957     0.9283      1.007        130       1024: 0% ──────────── 0/124  0.1s

      16/50      10.1G      1.928     0.9385     0.9777        165       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      16/50      10.1G      1.918     0.9012     0.9834        121       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.1s

      16/50      10.1G      1.955     0.9154     0.9701        155       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.3s

      16/50      10.1G      1.903     0.9021     0.9584        202       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.4s

      16/50      10.1G      1.872     0.8918     0.9546        158       1024: 4% ──────────── 5/124 5.4it/s 0.9s<21.9s

      16/50      10.1G      1.875     0.8849     0.9518        140       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.2s

      16/50      10.1G      1.867      0.887     0.9492        155       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      16/50      10.1G      1.878      0.884     0.9458        145       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.4s

      16/50      10.1G       1.89       0.89     0.9468        128       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.8s

      16/50      10.1G      1.887     0.8936     0.9458        172       1024: 8% ╸─────────── 10/124 6.6it/s 1.7s<17.4s

      16/50      10.1G      1.891     0.8954     0.9435        141       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      16/50      10.1G      1.891     0.8938      0.944        142       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.4s

      16/50      10.1G      1.907     0.9058     0.9469        125       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

      16/50      10.1G      1.901     0.9056     0.9508        121       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.7s

      16/50      10.1G      1.888     0.9095     0.9461        161       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.4s

      16/50      10.1G       1.87     0.8971     0.9422        132       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      16/50      10.1G      1.867     0.8983     0.9439        133       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<15.9s

      16/50      10.1G      1.859     0.8968     0.9469        120       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.0s

      16/50      10.1G      1.858     0.8983     0.9508        121       1024: 15% ━╸────────── 19/124 6.3it/s 3.1s<16.8s

      16/50      10.1G      1.862     0.8969     0.9497        166       1024: 16% ━╸────────── 20/124 6.3it/s 3.2s<16.4s

      16/50      10.1G      1.852     0.8928     0.9488        133       1024: 17% ━━────────── 21/124 6.3it/s 3.4s<16.2s

      16/50      10.1G      1.853     0.8952      0.951        173       1024: 18% ━━────────── 22/124 6.5it/s 3.5s<15.7s

      16/50      10.1G      1.863     0.8955     0.9501        106       1024: 19% ━━────────── 23/124 6.6it/s 3.7s<15.3s

      16/50      10.1G      1.861     0.8956     0.9493        159       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<15.0s

      16/50      10.1G      1.867     0.8994     0.9527        110       1024: 20% ━━────────── 25/124 6.6it/s 4.0s<14.9s

      16/50      10.1G      1.867     0.8973     0.9535        144       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      16/50      10.1G      1.851     0.8885     0.9505        111       1024: 22% ━━╸───────── 27/124 6.4it/s 4.3s<15.3s

      16/50      10.1G      1.851     0.8893     0.9502        127       1024: 23% ━━╸───────── 28/124 6.4it/s 4.4s<14.9s

      16/50      10.1G      1.843      0.885     0.9492        141       1024: 23% ━━╸───────── 29/124 6.3it/s 4.6s<15.0s

      16/50      10.1G      1.845     0.8899     0.9496        150       1024: 24% ━━╸───────── 30/124 6.5it/s 4.7s<14.5s

      16/50      10.1G      1.844     0.8899     0.9491        170       1024: 25% ━━━───────── 31/124 6.6it/s 4.9s<14.2s

      16/50      10.1G      1.839      0.891     0.9508        116       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<14.0s

      16/50      10.1G      1.839     0.8914     0.9507        147       1024: 27% ━━━───────── 33/124 6.7it/s 5.2s<13.7s

      16/50      10.1G      1.832      0.888     0.9501        127       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

      16/50      10.1G      1.835     0.8892     0.9496        129       1024: 28% ━━━───────── 35/124 6.3it/s 5.5s<14.1s

      16/50      10.1G      1.833     0.8873     0.9497        108       1024: 29% ━━━───────── 36/124 6.5it/s 5.7s<13.6s

      16/50      10.1G       1.83     0.8861     0.9493        111       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.2s

      16/50      10.1G       1.83     0.8864     0.9501        163       1024: 31% ━━━╸──────── 38/124 6.7it/s 6.0s<12.9s

      16/50      10.1G      1.831     0.8872     0.9523         96       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.1s<12.6s

      16/50      10.1G      1.826     0.8851     0.9509        134       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.3s<12.4s

      16/50      10.1G      1.821     0.8796     0.9504         95       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.4s<12.3s

      16/50      10.1G      1.825     0.8832     0.9518        130       1024: 34% ━━━━──────── 42/124 6.7it/s 6.6s<12.2s

      16/50      10.1G      1.817      0.879     0.9493        120       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.6s

      16/50      10.1G      1.822     0.8818     0.9499        173       1024: 35% ━━━━──────── 44/124 6.5it/s 6.9s<12.4s

      16/50      10.1G      1.823     0.8809     0.9516        103       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<12.0s

      16/50      10.1G      1.823     0.8809     0.9512        142       1024: 37% ━━━━──────── 46/124 6.6it/s 7.2s<11.7s

      16/50      10.1G      1.829      0.884     0.9527        104       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      16/50      10.1G      1.827     0.8844     0.9532        113       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.5s<11.3s

      16/50      10.1G       1.83     0.8848     0.9541        168       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.6s<11.1s

      16/50      10.1G      1.827     0.8835     0.9528        161       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.8s<11.0s

      16/50      10.1G      1.824     0.8821     0.9514        143       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.3s

      16/50      10.1G      1.823     0.8818     0.9504        131       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.1s<11.0s

      16/50      10.1G      1.822     0.8808     0.9504        110       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.7s

      16/50      10.1G      1.821     0.8794     0.9502        125       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.4s<10.4s

      16/50      10.1G      1.824     0.8792     0.9496        160       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.5s<10.2s

      16/50      10.1G      1.825     0.8802     0.9493        187       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.7s<10.1s

      16/50      10.1G      1.825     0.8801     0.9493        135       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.8s<9.9s

      16/50      10.1G      1.824     0.8803     0.9484        140       1024: 47% ━━━━━╸────── 58/124 6.8it/s 9.0s<9.7s

      16/50      10.1G      1.828     0.8804     0.9482        200       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.1s

      16/50      10.1G      1.825     0.8789     0.9478        155       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.3s<9.7s

      16/50      10.1G      1.829     0.8798     0.9487        126       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.4s<9.5s

      16/50      10.1G      1.833       0.88     0.9499        109       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.6s<9.3s

      16/50      10.1G      1.832     0.8791     0.9498        101       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.0s

      16/50      10.1G       1.83     0.8784     0.9487        142       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.9s<8.9s

      16/50      10.1G       1.83     0.8771     0.9481        160       1024: 52% ━━━━━━────── 65/124 6.8it/s 10.0s<8.7s

      16/50      10.1G      1.836     0.8794     0.9488        154       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.2s<8.6s

      16/50      10.1G      1.842     0.8825     0.9494        160       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.8s

      16/50      10.1G      1.843     0.8847     0.9496        153       1024: 55% ━━━━━━╸───── 68/124 6.4it/s 10.5s<8.7s

      16/50      10.1G      1.842     0.8832     0.9484        197       1024: 56% ━━━━━━╸───── 69/124 6.4it/s 10.7s<8.5s

      16/50      10.1G      1.842     0.8827     0.9486        120       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.8s<8.2s

      16/50      10.1G      1.845     0.8842     0.9503        113       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 10.9s<8.0s

      16/50      10.1G      1.842     0.8831     0.9498        150       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.1s<7.9s

      16/50      10.1G      1.843     0.8835     0.9505        146       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.2s<7.6s

      16/50      10.1G      1.844     0.8845     0.9501        152       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.4s

      16/50      10.1G      1.843      0.883     0.9503        162       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.6s<7.6s

      16/50      10.1G      1.843     0.8831     0.9505        143       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.7s<7.3s

      16/50      10.1G      1.841     0.8816     0.9508        117       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.9s<7.1s

      16/50      10.1G      1.839     0.8811     0.9506        112       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      16/50      10.1G      1.842     0.8819     0.9504        201       1024: 64% ━━━━━━━╸──── 79/124 6.6it/s 12.2s<6.9s

      16/50      10.1G      1.843     0.8831     0.9505        169       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.3s<6.6s

      16/50      10.1G      1.841     0.8832     0.9509         88       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.5s<6.4s

      16/50      10.1G      1.841     0.8844     0.9509        157       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

      16/50      10.1G       1.84      0.883     0.9515        104       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.8s<6.4s

      16/50      10.1G      1.839     0.8839     0.9521        121       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.1s

      16/50      10.1G      1.837     0.8833     0.9514        175       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.1s<5.9s

      16/50      10.1G      1.838     0.8826     0.9518        122       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      16/50      10.1G      1.838     0.8833      0.952        127       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.4s<5.5s

      16/50      10.1G      1.842     0.8852      0.953        123       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.5s<5.4s

      16/50      10.1G      1.841     0.8844     0.9534        141       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.7s<5.2s

      16/50      10.1G      1.842     0.8842     0.9532        159       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

      16/50      10.1G      1.844     0.8852     0.9532        154       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 14.0s<5.1s

      16/50      10.1G      1.847     0.8855     0.9539        149       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.1s<5.0s

      16/50      10.1G      1.845      0.885     0.9532        123       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.3s<4.7s

      16/50      10.1G      1.847     0.8856     0.9533        155       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      16/50      10.1G      1.847     0.8848      0.953        156       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.6s<4.4s

      16/50      10.1G      1.845     0.8843     0.9525        131       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.7s<4.2s

      16/50      10.1G      1.843     0.8824      0.952        143       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.9s<4.0s

      16/50      10.1G      1.844     0.8833     0.9517        143       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.0s<3.8s

      16/50      10.1G      1.844     0.8823      0.952        104       1024: 80% ━━━━━━━━━╸── 99/124 6.3it/s 15.2s<4.0s

      16/50      10.1G      1.843     0.8831     0.9514        177       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.4s<3.7s

      16/50      10.1G      1.842     0.8827     0.9511        126       1024: 81% ━━━━━━━━━╸── 101/124 6.5it/s 15.5s<3.5s

      16/50      10.1G      1.843     0.8826     0.9529        113       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.7s<3.3s

      16/50      10.1G      1.844     0.8831      0.953        160       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.8s<3.1s

      16/50      10.1G      1.844     0.8823     0.9532        123       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 16.0s<3.0s

      16/50      10.1G      1.844     0.8823     0.9528        147       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.1s<2.8s

      16/50      10.1G      1.844     0.8814     0.9526        176       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.3s<2.7s

      16/50      10.1G      1.843     0.8814     0.9523        129       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.4s<2.6s

      16/50      10.1G      1.841     0.8801     0.9523        105       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.6s<2.4s

      16/50      10.1G       1.84     0.8795     0.9521        137       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.7s<2.3s

      16/50      10.1G      1.841     0.8794     0.9522        146       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.9s<2.1s

      16/50      10.1G       1.84     0.8777      0.952        133       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 17.0s<1.9s

      16/50      10.1G      1.841     0.8788     0.9524        126       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.2s<1.8s

      16/50      10.1G       1.84     0.8781      0.952        103       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.3s<1.6s

      16/50      10.1G       1.84     0.8778     0.9514        180       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.4s<1.5s

      16/50      10.1G      1.839     0.8778     0.9512        152       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.6s<1.4s

      16/50      10.1G      1.839     0.8781     0.9509        163       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.8s<1.2s

      16/50      10.1G      1.838     0.8774     0.9509        155       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.9s<1.1s

      16/50      10.1G      1.839     0.8785     0.9518        104       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.1s<0.9s

      16/50      10.1G      1.838     0.8778     0.9515        119       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.2s<0.7s

      16/50      10.1G      1.839     0.8775     0.9517        143       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.4s<0.6s

      16/50      10.1G      1.837     0.8766     0.9512        162       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.5s<0.4s

      16/50      10.1G      1.836     0.8763     0.9511        124       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.7s<0.3s

      16/50      10.1G      1.834     0.8764     0.9512         98       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.8s<0.2s

      16/50      10.1G      1.834     0.8764     0.9512         98       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227       0.67      0.593      0.621      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/50      10.1G      1.775     0.9407     0.9325        177       1024: 0% ──────────── 0/124  0.1s

      17/50      10.1G      1.784     0.8952     0.9437        145       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:02

      17/50      10.1G      1.759     0.8978     0.9313        140       1024: 2% ──────────── 2/124 3.3it/s 0.5s<36.6s

      17/50      10.1G      1.804     0.9052     0.9481        127       1024: 2% ──────────── 3/124 4.3it/s 0.6s<28.3s

      17/50      10.1G      1.828     0.9058     0.9658        115       1024: 3% ──────────── 4/124 5.0it/s 0.8s<23.9s

      17/50      10.1G       1.82     0.8827     0.9563        169       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.4s

      17/50      10.1G      1.832     0.8891     0.9537        124       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.8s

      17/50      10.1G      1.841     0.8825     0.9667        112       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.9s

      17/50      10.1G      1.852     0.8719     0.9624        159       1024: 6% ╸─────────── 8/124 6.2it/s 1.4s<18.8s

      17/50      10.1G      1.868     0.8703     0.9782        115       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

      17/50      10.1G      1.845     0.8678     0.9661        147       1024: 8% ╸─────────── 10/124 6.5it/s 1.7s<17.5s

      17/50      10.1G      1.838      0.863     0.9633        115       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.1s

      17/50      10.1G      1.812     0.8497     0.9574        125       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.7s

      17/50      10.1G      1.813     0.8612     0.9559        130       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      17/50      10.1G      1.803     0.8604     0.9573        135       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.3s

      17/50      10.1G      1.798      0.856     0.9525        155       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.9s

      17/50      10.1G        1.8     0.8605     0.9523        148       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.4s

      17/50      10.1G      1.807     0.8632     0.9563        100       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<16.1s

      17/50      10.1G      1.814     0.8619     0.9531        185       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.8s

      17/50      10.1G      1.812     0.8663      0.952        114       1024: 15% ━╸────────── 19/124 6.8it/s 3.0s<15.6s

      17/50      10.1G      1.822     0.8672     0.9515        164       1024: 16% ━╸────────── 20/124 6.8it/s 3.1s<15.4s

      17/50      10.1G      1.835     0.8715     0.9533        124       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.1s

      17/50      10.1G      1.824      0.869      0.952        171       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

      17/50      10.1G      1.836     0.8728     0.9542        116       1024: 19% ━━────────── 23/124 6.5it/s 3.6s<15.6s

      17/50      10.1G      1.825     0.8692      0.952        120       1024: 19% ━━────────── 24/124 6.6it/s 3.8s<15.3s

      17/50      10.1G      1.825     0.8718     0.9515        167       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<14.9s

      17/50      10.1G      1.833     0.8734     0.9528        131       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      17/50      10.1G      1.833     0.8717     0.9522        121       1024: 22% ━━╸───────── 27/124 6.6it/s 4.2s<14.7s

      17/50      10.1G      1.826     0.8692     0.9507        139       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      17/50      10.1G      1.823     0.8671     0.9526        109       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.3s

      17/50      10.1G      1.822     0.8686     0.9525        150       1024: 24% ━━╸───────── 30/124 6.5it/s 4.7s<14.4s

      17/50      10.1G      1.819     0.8645     0.9532        132       1024: 25% ━━━───────── 31/124 6.3it/s 4.8s<14.7s

      17/50      10.1G      1.823     0.8642     0.9544        134       1024: 26% ━━━───────── 32/124 6.4it/s 5.0s<14.4s

      17/50      10.1G      1.822     0.8625     0.9527        109       1024: 27% ━━━───────── 33/124 6.3it/s 5.2s<14.4s

      17/50      10.1G      1.817     0.8626     0.9526        122       1024: 27% ━━━───────── 34/124 6.5it/s 5.3s<13.9s

      17/50      10.1G      1.818      0.862      0.951        164       1024: 28% ━━━───────── 35/124 6.6it/s 5.5s<13.6s

      17/50      10.1G      1.822     0.8646     0.9545        107       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.2s

      17/50      10.1G      1.827     0.8671     0.9546        155       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.2s

      17/50      10.1G      1.825     0.8659     0.9541        140       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

      17/50      10.1G       1.83     0.8691     0.9568        117       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.3s

      17/50      10.1G      1.839     0.8719     0.9584        107       1024: 32% ━━━╸──────── 40/124 6.3it/s 6.2s<13.2s

      17/50      10.1G      1.837     0.8736     0.9594        157       1024: 33% ━━━╸──────── 41/124 6.5it/s 6.4s<12.8s

      17/50      10.1G      1.839     0.8751     0.9592        163       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.5s

      17/50      10.1G      1.842     0.8748     0.9582        132       1024: 35% ━━━━──────── 43/124 6.6it/s 6.7s<12.2s

      17/50      10.1G      1.843     0.8745     0.9597        157       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<12.0s

      17/50      10.1G      1.841      0.875     0.9591        118       1024: 36% ━━━━──────── 45/124 6.7it/s 7.0s<11.8s

      17/50      10.1G      1.836     0.8732     0.9584        172       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      17/50      10.1G      1.838     0.8728     0.9576         99       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<11.9s

      17/50      10.1G      1.838     0.8716     0.9568        168       1024: 39% ━━━━╸─────── 48/124 6.5it/s 7.4s<11.6s

      17/50      10.1G      1.835     0.8683     0.9557        107       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.6s<11.3s

      17/50      10.1G      1.836     0.8703      0.957        116       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.2s

      17/50      10.1G      1.834     0.8683     0.9567        133       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<11.0s

      17/50      10.1G      1.831     0.8669     0.9574        113       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      17/50      10.1G      1.831     0.8662     0.9563        137       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.5s

      17/50      10.1G      1.827      0.867     0.9556        151       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      17/50      10.1G      1.824     0.8655      0.955        117       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.5s<10.7s

      17/50      10.1G      1.825     0.8672     0.9561        130       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      17/50      10.1G      1.821     0.8648     0.9555        127       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.1s

      17/50      10.1G      1.823     0.8645     0.9566        107       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      17/50      10.1G      1.821     0.8618     0.9557        117       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.6s

      17/50      10.1G      1.825     0.8636     0.9569        149       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.5s

      17/50      10.1G      1.824     0.8629     0.9562        125       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      17/50      10.1G      1.821     0.8624     0.9554        116       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      17/50      10.1G      1.821     0.8623     0.9546        147       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.7s<9.5s

      17/50      10.1G      1.818     0.8614     0.9535        127       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.9s<9.2s

      17/50      10.1G       1.82     0.8628     0.9536        117       1024: 52% ━━━━━━────── 65/124 6.5it/s 10.0s<9.0s

      17/50      10.1G      1.822      0.864     0.9542        150       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.8s

      17/50      10.1G      1.823      0.865     0.9545        118       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.3s<8.5s

      17/50      10.1G      1.824      0.866     0.9549         98       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.4s<8.3s

      17/50      10.1G      1.822     0.8648     0.9546        102       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.6s<8.1s

      17/50      10.1G      1.821     0.8652     0.9551        114       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      17/50      10.1G      1.819     0.8642     0.9535        194       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.9s<8.2s

      17/50      10.1G       1.82     0.8659      0.954        136       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.1s<7.9s

      17/50      10.1G      1.823     0.8664     0.9542        196       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.7s

      17/50      10.1G      1.823     0.8673     0.9546        123       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

      17/50      10.1G      1.822     0.8674     0.9539        164       1024: 60% ━━━━━━━───── 75/124 6.6it/s 11.5s<7.4s

      17/50      10.1G       1.82     0.8683     0.9542        137       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.7s<7.2s

      17/50      10.1G      1.821     0.8693     0.9544        155       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.8s<7.0s

      17/50      10.1G      1.821     0.8699     0.9538        125       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.8s

      17/50      10.1G      1.819     0.8686     0.9533        154       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.1s<7.0s

      17/50      10.1G      1.817     0.8664     0.9524        118       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.3s<6.7s

      17/50      10.1G      1.817     0.8673     0.9523        118       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      17/50      10.1G       1.82     0.8692     0.9524        156       1024: 66% ━━━━━━━╸──── 82/124 6.6it/s 12.6s<6.3s

      17/50      10.1G      1.819     0.8678      0.952        136       1024: 67% ━━━━━━━━──── 83/124 6.6it/s 12.7s<6.2s

      17/50      10.1G      1.821     0.8685     0.9518        177       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.9s<6.0s

      17/50      10.1G      1.821     0.8687     0.9517        106       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.8s

      17/50      10.1G      1.821     0.8685     0.9512        162       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      17/50      10.1G      1.822      0.869     0.9505        154       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.8s

      17/50      10.1G      1.822     0.8689     0.9503        128       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.5s<5.5s

      17/50      10.1G      1.821     0.8684     0.9503        118       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      17/50      10.1G      1.819     0.8672       0.95        151       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

      17/50      10.1G      1.818     0.8675     0.9497        118       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

      17/50      10.1G      1.817     0.8667       0.95        112       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.1s<4.7s

      17/50      10.1G      1.815     0.8666     0.9497        145       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.2s<4.6s

      17/50      10.1G      1.814     0.8655     0.9495        177       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.4s<4.4s

      17/50      10.1G      1.816     0.8662     0.9499        115       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.5s<4.5s

      17/50      10.1G      1.818     0.8669     0.9504        127       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.7s<4.3s

      17/50      10.1G      1.815     0.8656     0.9506        114       1024: 78% ━━━━━━━━━─── 97/124 6.5it/s 14.9s<4.2s

      17/50      10.1G      1.815     0.8657     0.9504        164       1024: 79% ━━━━━━━━━─── 98/124 6.6it/s 15.0s<4.0s

      17/50      10.1G      1.817     0.8666     0.9503        177       1024: 80% ━━━━━━━━━╸── 99/124 6.6it/s 15.1s<3.8s

      17/50      10.1G      1.815     0.8664     0.9499        205       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.3s<3.6s

      17/50      10.1G      1.815     0.8676     0.9502        120       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.4s<3.4s

      17/50      10.1G      1.816     0.8688     0.9508        117       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.6s<3.2s

      17/50      10.1G      1.819     0.8693     0.9509        133       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.8s<3.3s

      17/50      10.1G      1.819     0.8682     0.9505        134       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.9s<3.1s

      17/50      10.1G      1.821      0.868     0.9509        147       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.1s<2.9s

      17/50      10.1G      1.821     0.8678     0.9507        123       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      17/50      10.1G      1.823     0.8693     0.9513        133       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.4s<2.5s

      17/50      10.1G      1.822     0.8686     0.9509        121       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.5s<2.4s

      17/50      10.1G       1.82     0.8675     0.9504        102       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.6s<2.2s

      17/50      10.1G      1.819     0.8682     0.9499        113       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.8s<2.1s

      17/50      10.1G      1.821     0.8681     0.9499        187       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 17.0s<2.0s

      17/50      10.1G      1.824       0.87     0.9505        158       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.1s<1.8s

      17/50      10.1G      1.826     0.8707     0.9509        159       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.3s<1.7s

      17/50      10.1G      1.825     0.8699     0.9501        137       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

      17/50      10.1G      1.824     0.8699     0.9499        170       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.6s<1.3s

      17/50      10.1G      1.824     0.8704     0.9498        207       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.7s<1.2s

      17/50      10.1G      1.824     0.8701       0.95        157       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.9s<1.1s

      17/50      10.1G      1.825      0.871     0.9496        174       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      17/50      10.1G      1.828     0.8726     0.9507        142       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.2s<0.8s

      17/50      10.1G      1.828     0.8715     0.9504        199       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.3s<0.6s

      17/50      10.1G      1.829     0.8717     0.9503        136       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.5s<0.5s

      17/50      10.1G      1.832     0.8726     0.9509        139       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.6s<0.3s

      17/50      10.1G      1.833     0.8727     0.9513        154       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.8s<0.1s

      17/50      10.1G      1.833     0.8727     0.9513        154       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.651      0.596      0.624      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/50      10.1G       1.91     0.8655     0.9418        226       1024: 0% ──────────── 0/124  0.1s

      18/50      10.1G      2.032     0.9333      1.004        127       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      18/50      10.1G      2.043     0.9301     0.9861        191       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.3s

      18/50      10.1G          2     0.9367     0.9778        139       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.4s

      18/50      10.1G      1.973     0.9122     0.9818        118       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.8s

      18/50      10.1G       1.94     0.9079     0.9788        130       1024: 4% ──────────── 5/124 5.4it/s 0.9s<22.1s

      18/50      10.1G      1.942     0.9048     0.9739        117       1024: 5% ╸─────────── 6/124 5.7it/s 1.1s<20.6s

      18/50      10.1G      1.926     0.9006     0.9707        161       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.3s

      18/50      10.1G      1.949     0.9015     0.9764        139       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.5s

      18/50      10.1G      1.922     0.8941       0.97        137       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<17.9s

      18/50      10.1G      1.925     0.8907     0.9747        152       1024: 8% ╸─────────── 10/124 6.6it/s 1.7s<17.4s

      18/50      10.1G        1.9      0.884     0.9694        131       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<17.9s

      18/50      10.1G      1.876     0.8786     0.9626        128       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.6s

      18/50      10.1G      1.857     0.8758     0.9611        108       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.0s

      18/50      10.1G      1.848     0.8715     0.9567        119       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      18/50      10.1G       1.84     0.8716     0.9515        149       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.3s

      18/50      10.1G      1.832     0.8755     0.9482        142       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      18/50      10.1G       1.82     0.8688     0.9449        154       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.1s

      18/50      10.1G      1.824      0.868     0.9423        182       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      18/50      10.1G      1.812     0.8618     0.9396        119       1024: 15% ━╸────────── 19/124 6.4it/s 3.1s<16.4s

      18/50      10.1G      1.814     0.8611     0.9399        147       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.1s

      18/50      10.1G      1.809     0.8616     0.9423        101       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

      18/50      10.1G       1.81     0.8654     0.9441        122       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      18/50      10.1G      1.808     0.8621     0.9439        119       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

      18/50      10.1G      1.805     0.8611     0.9425         96       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.8s

      18/50      10.1G      1.795     0.8581      0.941        122       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.8s

      18/50      10.1G      1.802     0.8616     0.9421        142       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      18/50      10.1G      1.799     0.8587     0.9422        102       1024: 22% ━━╸───────── 27/124 6.4it/s 4.3s<15.1s

      18/50      10.1G      1.797     0.8569      0.942        153       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.9s

      18/50      10.1G      1.803     0.8536     0.9418        108       1024: 23% ━━╸───────── 29/124 6.6it/s 4.6s<14.5s

      18/50      10.1G      1.811     0.8586     0.9428        130       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.1s

      18/50      10.1G      1.818     0.8618     0.9416        152       1024: 25% ━━━───────── 31/124 6.7it/s 4.9s<13.9s

      18/50      10.1G      1.809     0.8558      0.941        124       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.7s

      18/50      10.1G      1.814     0.8584     0.9413        168       1024: 27% ━━━───────── 33/124 6.7it/s 5.2s<13.5s

      18/50      10.1G      1.807     0.8549     0.9404        124       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      18/50      10.1G      1.809     0.8565      0.941        123       1024: 28% ━━━───────── 35/124 6.4it/s 5.5s<13.8s

      18/50      10.1G      1.811     0.8537     0.9426        117       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.6s

      18/50      10.1G      1.807     0.8504     0.9443        122       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.2s

      18/50      10.1G      1.808     0.8484     0.9439        115       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.0s

      18/50      10.1G      1.806      0.849     0.9453        134       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.1s<12.7s

      18/50      10.1G      1.798      0.844     0.9433        134       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.2s<12.5s

      18/50      10.1G      1.797     0.8431     0.9439        104       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.4s<12.3s

      18/50      10.1G      1.797     0.8427     0.9439        134       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      18/50      10.1G      1.794     0.8403     0.9427        147       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.7s

      18/50      10.1G      1.793     0.8401     0.9414        219       1024: 35% ━━━━──────── 44/124 6.4it/s 6.8s<12.5s

      18/50      10.1G      1.792     0.8402     0.9413        118       1024: 36% ━━━━──────── 45/124 6.5it/s 7.0s<12.1s

      18/50      10.1G      1.788     0.8393     0.9413        113       1024: 37% ━━━━──────── 46/124 6.6it/s 7.1s<11.7s

      18/50      10.1G       1.79      0.839     0.9405        141       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      18/50      10.1G      1.787     0.8369     0.9405        116       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.3s

      18/50      10.1G      1.785     0.8354     0.9412        120       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.2s

      18/50      10.1G      1.781      0.834      0.941        162       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      18/50      10.1G      1.782     0.8364     0.9408        152       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.4s

      18/50      10.1G       1.78     0.8347     0.9407        152       1024: 42% ━━━━━─────── 52/124 6.5it/s 8.1s<11.2s

      18/50      10.1G      1.784     0.8356     0.9409        159       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.8s

      18/50      10.1G      1.786     0.8368     0.9408        123       1024: 44% ━━━━━─────── 54/124 6.6it/s 8.4s<10.6s

      18/50      10.1G       1.79     0.8355     0.9411        147       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.5s<10.3s

      18/50      10.1G      1.792     0.8359     0.9404        162       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.7s<10.2s

      18/50      10.1G      1.792     0.8381     0.9408        104       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

      18/50      10.1G      1.791      0.838     0.9407        109       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      18/50      10.1G      1.795     0.8393     0.9416        170       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.1s<10.1s

      18/50      10.1G      1.792     0.8377     0.9401        142       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.3s<9.9s

      18/50      10.1G      1.794     0.8387     0.9412        111       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

      18/50      10.1G      1.794     0.8398     0.9411        113       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.6s<9.3s

      18/50      10.1G      1.797      0.842     0.9421        100       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

      18/50      10.1G        1.8     0.8431     0.9422        134       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.9s<8.9s

      18/50      10.1G      1.799     0.8427     0.9416        176       1024: 52% ━━━━━━────── 65/124 6.8it/s 10.0s<8.7s

      18/50      10.1G      1.802     0.8436      0.943        169       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.2s<8.6s

      18/50      10.1G      1.803     0.8432     0.9425        113       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

      18/50      10.1G      1.805     0.8436     0.9423        142       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.5s<8.5s

      18/50      10.1G      1.807     0.8465      0.943        154       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

      18/50      10.1G      1.807     0.8474     0.9437        111       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.8s<8.1s

      18/50      10.1G      1.805     0.8465      0.943        157       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      18/50      10.1G      1.804      0.846     0.9429        144       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.7s

      18/50      10.1G      1.805     0.8461     0.9436        147       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      18/50      10.1G      1.802     0.8441     0.9435         97       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.4s<7.4s

      18/50      10.1G      1.799     0.8441     0.9434        112       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.5s<7.6s

      18/50      10.1G      1.799     0.8441     0.9444        126       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.7s<7.3s

      18/50      10.1G      1.801     0.8449     0.9447        136       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      18/50      10.1G      1.803     0.8449     0.9454        132       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      18/50      10.1G        1.8     0.8435     0.9447        167       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.7s

      18/50      10.1G        1.8     0.8432     0.9451        137       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.3s<6.5s

      18/50      10.1G      1.798     0.8431      0.944        135       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      18/50      10.1G      1.797     0.8428     0.9438        170       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

      18/50      10.1G      1.795     0.8412     0.9436        114       1024: 67% ━━━━━━━━──── 83/124 6.3it/s 12.8s<6.5s

      18/50      10.1G      1.795      0.841     0.9432        165       1024: 68% ━━━━━━━━──── 84/124 6.3it/s 12.9s<6.3s

      18/50      10.1G      1.797     0.8408     0.9444        120       1024: 69% ━━━━━━━━──── 85/124 6.3it/s 13.1s<6.2s

      18/50      10.1G      1.796     0.8412     0.9441        121       1024: 69% ━━━━━━━━──── 86/124 6.3it/s 13.2s<6.0s

      18/50      10.1G      1.797     0.8443     0.9443        105       1024: 70% ━━━━━━━━──── 87/124 6.3it/s 13.4s<5.8s

      18/50      10.1G      1.795     0.8442     0.9436        132       1024: 71% ━━━━━━━━╸─── 88/124 6.4it/s 13.5s<5.7s

      18/50      10.1G      1.797     0.8455     0.9444        124       1024: 72% ━━━━━━━━╸─── 89/124 6.4it/s 13.7s<5.5s

      18/50      10.1G      1.798     0.8461     0.9441        170       1024: 73% ━━━━━━━━╸─── 90/124 6.4it/s 13.9s<5.3s

      18/50      10.1G      1.799     0.8466     0.9441        163       1024: 73% ━━━━━━━━╸─── 91/124 6.0it/s 14.0s<5.5s

      18/50      10.1G        1.8     0.8463     0.9448        136       1024: 74% ━━━━━━━━╸─── 92/124 6.2it/s 14.2s<5.1s

      18/50      10.1G      1.798     0.8447     0.9446        109       1024: 75% ━━━━━━━━━─── 93/124 6.4it/s 14.3s<4.9s

      18/50      10.1G      1.802     0.8476     0.9464        129       1024: 76% ━━━━━━━━━─── 94/124 6.3it/s 14.5s<4.8s

      18/50      10.1G      1.802     0.8491     0.9465        166       1024: 77% ━━━━━━━━━─── 95/124 6.3it/s 14.7s<4.6s

      18/50      10.1G        1.8     0.8488      0.946        140       1024: 77% ━━━━━━━━━─── 96/124 6.4it/s 14.8s<4.4s

      18/50      10.1G      1.798     0.8486     0.9451        139       1024: 78% ━━━━━━━━━─── 97/124 6.3it/s 15.0s<4.3s

      18/50      10.1G        1.8     0.8488     0.9454        124       1024: 79% ━━━━━━━━━─── 98/124 6.3it/s 15.1s<4.1s

      18/50      10.1G      1.799     0.8488     0.9452        134       1024: 80% ━━━━━━━━━╸── 99/124 6.1it/s 15.3s<4.1s

      18/50      10.1G      1.801     0.8494     0.9453        139       1024: 81% ━━━━━━━━━╸── 100/124 6.2it/s 15.5s<3.9s

      18/50      10.1G        1.8      0.849     0.9451        104       1024: 81% ━━━━━━━━━╸── 101/124 6.2it/s 15.6s<3.7s

      18/50      10.1G      1.802     0.8497      0.945        179       1024: 82% ━━━━━━━━━╸── 102/124 6.2it/s 15.8s<3.5s

      18/50      10.1G      1.802     0.8506     0.9457        116       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.9s<3.3s

      18/50      10.1G      1.802     0.8508     0.9458        132       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 16.1s<3.1s

      18/50      10.1G      1.803      0.851     0.9459        198       1024: 85% ━━━━━━━━━━── 105/124 6.4it/s 16.3s<3.0s

      18/50      10.1G      1.803     0.8511     0.9455        143       1024: 85% ━━━━━━━━━━── 106/124 6.4it/s 16.4s<2.8s

      18/50      10.1G      1.802     0.8504     0.9451        161       1024: 86% ━━━━━━━━━━── 107/124 6.1it/s 16.6s<2.8s

      18/50      10.1G      1.799     0.8487     0.9443        148       1024: 87% ━━━━━━━━━━── 108/124 6.2it/s 16.7s<2.6s

      18/50      10.1G        1.8     0.8498     0.9445        116       1024: 88% ━━━━━━━━━━╸─ 109/124 6.3it/s 16.9s<2.4s

      18/50      10.1G      1.802     0.8499     0.9443        135       1024: 89% ━━━━━━━━━━╸─ 110/124 6.3it/s 17.1s<2.2s

      18/50      10.1G      1.802     0.8508     0.9443        135       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 17.2s<2.0s

      18/50      10.1G      1.804     0.8519      0.945        118       1024: 90% ━━━━━━━━━━╸─ 112/124 6.4it/s 17.4s<1.9s

      18/50      10.1G      1.803     0.8516     0.9445        165       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 17.5s<1.7s

      18/50      10.1G      1.806     0.8525     0.9447        145       1024: 92% ━━━━━━━━━━━─ 114/124 6.4it/s 17.7s<1.6s

      18/50      10.1G      1.805     0.8525     0.9443        126       1024: 93% ━━━━━━━━━━━─ 115/124 6.1it/s 17.9s<1.5s

      18/50      10.1G      1.805     0.8528     0.9451        156       1024: 94% ━━━━━━━━━━━─ 116/124 6.1it/s 18.0s<1.3s

      18/50      10.1G      1.807     0.8521     0.9452        111       1024: 94% ━━━━━━━━━━━─ 117/124 6.2it/s 18.2s<1.1s

      18/50      10.1G      1.806     0.8526     0.9454        117       1024: 95% ━━━━━━━━━━━─ 118/124 6.3it/s 18.3s<1.0s

      18/50      10.1G      1.807     0.8529     0.9459        160       1024: 96% ━━━━━━━━━━━╸ 119/124 6.3it/s 18.5s<0.8s

      18/50      10.1G      1.807     0.8528     0.9463        128       1024: 97% ━━━━━━━━━━━╸ 120/124 6.4it/s 18.6s<0.6s

      18/50      10.1G      1.807     0.8528     0.9461        150       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.8s<0.5s

      18/50      10.1G      1.809     0.8529     0.9462        148       1024: 98% ━━━━━━━━━━━╸ 122/124 6.5it/s 19.0s<0.3s

      18/50      10.1G      1.812     0.8541     0.9462        151       1024: 99% ━━━━━━━━━━━╸ 123/124 6.1it/s 19.1s<0.2s

      18/50      10.1G      1.812     0.8541     0.9462        151       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 19.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.9it/s 0.1s<7.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.9it/s 0.3s<3.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.1it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.3it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.3it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.3it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.3it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227       0.66      0.601      0.626      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/50      10.1G      1.627     0.7827     0.9111        127       1024: 0% ──────────── 0/124  0.1s

      19/50      10.1G      1.879     0.9206     0.9373        136       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:02

      19/50      10.1G      1.905     0.9369     0.9677        122       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.5s

      19/50      10.1G      1.847     0.8924     0.9387        178       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.8s

      19/50      10.1G      1.823     0.8584     0.9316        137       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.5s

      19/50      10.1G      1.779     0.8403     0.9198        141       1024: 4% ──────────── 5/124 5.4it/s 0.9s<22.2s

      19/50      10.1G      1.771     0.8274      0.917        137       1024: 5% ╸─────────── 6/124 5.7it/s 1.1s<20.6s

      19/50      10.1G      1.795     0.8353     0.9268        123       1024: 6% ╸─────────── 7/124 5.7it/s 1.2s<20.4s

      19/50      10.1G      1.795     0.8322     0.9199        116       1024: 6% ╸─────────── 8/124 6.0it/s 1.4s<19.5s

      19/50      10.1G      1.772     0.8247     0.9239        107       1024: 7% ╸─────────── 9/124 6.1it/s 1.6s<18.9s

      19/50      10.1G      1.778     0.8237     0.9232        165       1024: 8% ╸─────────── 10/124 6.1it/s 1.7s<18.7s

      19/50      10.1G      1.793     0.8357     0.9258        196       1024: 9% ━─────────── 11/124 6.2it/s 1.9s<18.3s

      19/50      10.1G      1.782     0.8311     0.9239        118       1024: 10% ━─────────── 12/124 6.2it/s 2.0s<18.1s

      19/50      10.1G      1.785     0.8439     0.9336        115       1024: 10% ━─────────── 13/124 6.3it/s 2.2s<17.7s

      19/50      10.1G      1.794     0.8402     0.9314        178       1024: 11% ━─────────── 14/124 6.4it/s 2.3s<17.1s

      19/50      10.1G      1.789     0.8358     0.9279        125       1024: 12% ━─────────── 15/124 6.2it/s 2.5s<17.5s

      19/50      10.1G      1.787     0.8398     0.9309        128       1024: 13% ━╸────────── 16/124 6.3it/s 2.7s<17.1s

      19/50      10.1G      1.779     0.8396     0.9294        135       1024: 14% ━╸────────── 17/124 6.5it/s 2.8s<16.5s

      19/50      10.1G      1.793     0.8403      0.931         99       1024: 15% ━╸────────── 18/124 6.6it/s 3.0s<16.1s

      19/50      10.1G      1.789     0.8411     0.9311        141       1024: 15% ━╸────────── 19/124 6.7it/s 3.1s<15.7s

      19/50      10.1G      1.797     0.8411     0.9365        117       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.4s

      19/50      10.1G      1.798     0.8432     0.9364        117       1024: 17% ━━────────── 21/124 6.8it/s 3.4s<15.2s

      19/50      10.1G      1.793     0.8397      0.934        201       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.2s

      19/50      10.1G      1.796     0.8362     0.9327        153       1024: 19% ━━────────── 23/124 6.4it/s 3.7s<15.7s

      19/50      10.1G      1.794     0.8381     0.9351        121       1024: 19% ━━────────── 24/124 6.5it/s 3.9s<15.5s

      19/50      10.1G      1.796     0.8379     0.9338        113       1024: 20% ━━────────── 25/124 6.4it/s 4.0s<15.4s

      19/50      10.1G      1.802     0.8399     0.9352        116       1024: 21% ━━╸───────── 26/124 6.6it/s 4.2s<14.9s

      19/50      10.1G      1.803     0.8397     0.9365        110       1024: 22% ━━╸───────── 27/124 6.7it/s 4.3s<14.6s

      19/50      10.1G      1.814     0.8407     0.9384        120       1024: 23% ━━╸───────── 28/124 6.7it/s 4.5s<14.3s

      19/50      10.1G      1.817     0.8479     0.9433        107       1024: 23% ━━╸───────── 29/124 6.8it/s 4.6s<14.1s

      19/50      10.1G      1.821     0.8499     0.9439        152       1024: 24% ━━╸───────── 30/124 6.8it/s 4.8s<13.9s

      19/50      10.1G      1.824     0.8512     0.9443        136       1024: 25% ━━━───────── 31/124 6.5it/s 4.9s<14.4s

      19/50      10.1G       1.82     0.8484     0.9422        149       1024: 26% ━━━───────── 32/124 6.5it/s 5.1s<14.2s

      19/50      10.1G      1.825     0.8523     0.9429        159       1024: 27% ━━━───────── 33/124 6.6it/s 5.2s<13.8s

      19/50      10.1G      1.832      0.853     0.9449        129       1024: 27% ━━━───────── 34/124 6.6it/s 5.4s<13.6s

      19/50      10.1G      1.826     0.8535     0.9435        111       1024: 28% ━━━───────── 35/124 6.7it/s 5.5s<13.3s

      19/50      10.1G      1.823     0.8512     0.9429        127       1024: 29% ━━━───────── 36/124 6.7it/s 5.7s<13.1s

      19/50      10.1G      1.831     0.8516     0.9439        124       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.8s<13.0s

      19/50      10.1G      1.832     0.8515     0.9444        143       1024: 31% ━━━╸──────── 38/124 6.7it/s 6.0s<12.8s

      19/50      10.1G      1.831     0.8525     0.9439        169       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.3s

      19/50      10.1G      1.835      0.853     0.9432        191       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.3s<12.8s

      19/50      10.1G      1.836     0.8521     0.9427        179       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.5s

      19/50      10.1G      1.834       0.85     0.9421        147       1024: 34% ━━━━──────── 42/124 6.7it/s 6.6s<12.2s

      19/50      10.1G      1.833     0.8472     0.9423        126       1024: 35% ━━━━──────── 43/124 6.8it/s 6.7s<12.0s

      19/50      10.1G      1.836     0.8466     0.9419        168       1024: 35% ━━━━──────── 44/124 6.8it/s 6.9s<11.8s

      19/50      10.1G      1.835      0.847     0.9427        151       1024: 36% ━━━━──────── 45/124 6.8it/s 7.0s<11.6s

      19/50      10.1G      1.831     0.8446     0.9419        121       1024: 37% ━━━━──────── 46/124 6.8it/s 7.2s<11.4s

      19/50      10.1G      1.838     0.8462     0.9417        189       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.3s<11.8s

      19/50      10.1G      1.836     0.8452     0.9416        149       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.5s<11.5s

      19/50      10.1G      1.835     0.8429       0.94        105       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.2s

      19/50      10.1G      1.829     0.8396     0.9384        150       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.8s<10.9s

      19/50      10.1G      1.833     0.8406     0.9385        177       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.9s<10.7s

      19/50      10.1G       1.83     0.8413     0.9383        136       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.1s<10.6s

      19/50      10.1G       1.83     0.8401     0.9375        154       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.2s<10.4s

      19/50      10.1G       1.83     0.8399     0.9381        118       1024: 44% ━━━━━─────── 54/124 6.9it/s 8.4s<10.2s

      19/50      10.1G      1.828     0.8411     0.9385        121       1024: 44% ━━━━━─────── 55/124 6.6it/s 8.5s<10.5s

      19/50      10.1G      1.828     0.8402     0.9389        172       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.7s<10.3s

      19/50      10.1G      1.828     0.8396     0.9389        159       1024: 46% ━━━━━╸────── 57/124 6.5it/s 8.8s<10.3s

      19/50      10.1G      1.827     0.8392     0.9392        108       1024: 47% ━━━━━╸────── 58/124 6.6it/s 9.0s<9.9s

      19/50      10.1G      1.829     0.8401     0.9387        139       1024: 48% ━━━━━╸────── 59/124 6.6it/s 9.1s<9.9s

      19/50      10.1G      1.825     0.8381     0.9375        121       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.3s<9.9s

      19/50      10.1G      1.824     0.8386     0.9372        135       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

      19/50      10.1G       1.82     0.8377     0.9366        137       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.6s<9.3s

      19/50      10.1G      1.822     0.8378     0.9373        115       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.8s<9.5s

      19/50      10.1G      1.822     0.8388     0.9376        152       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.9s<9.2s

      19/50      10.1G      1.819     0.8395     0.9378        118       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.1s<8.9s

      19/50      10.1G      1.823     0.8409     0.9384        138       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.2s<8.6s

      19/50      10.1G      1.822     0.8404     0.9384        104       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.3s<8.4s

      19/50      10.1G       1.82     0.8401     0.9386        136       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.5s<8.2s

      19/50      10.1G      1.818     0.8383     0.9381        118       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.6s<8.0s

      19/50      10.1G      1.817     0.8369     0.9381        120       1024: 56% ━━━━━━╸───── 70/124 6.9it/s 10.8s<7.9s

      19/50      10.1G      1.816     0.8376      0.938         95       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 10.9s<8.1s

      19/50      10.1G      1.814     0.8381     0.9377        120       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.8s

      19/50      10.1G      1.818     0.8393     0.9391        122       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.7s

      19/50      10.1G      1.818     0.8404     0.9399        116       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.4s

      19/50      10.1G      1.816     0.8405     0.9394        138       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.5s<7.2s

      19/50      10.1G      1.815     0.8405     0.9387        154       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.7s<7.1s

      19/50      10.1G      1.815     0.8408     0.9389        114       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.8s<6.9s

      19/50      10.1G      1.812     0.8396     0.9386        125       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 12.0s<6.7s

      19/50      10.1G      1.812     0.8394     0.9387        135       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.1s<6.9s

      19/50      10.1G      1.814     0.8398     0.9392        114       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.3s<6.7s

      19/50      10.1G      1.814     0.8397     0.9388        151       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      19/50      10.1G      1.812     0.8387     0.9386        114       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

      19/50      10.1G      1.814     0.8389     0.9395        127       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.7s<6.1s

      19/50      10.1G      1.816     0.8397       0.94        105       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 12.9s<6.0s

      19/50      10.1G      1.816     0.8398     0.9401        112       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.8s

      19/50      10.1G      1.817     0.8401     0.9399        130       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.6s

      19/50      10.1G      1.818     0.8399     0.9399        134       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.4s<5.8s

      19/50      10.1G      1.817     0.8409     0.9399        119       1024: 71% ━━━━━━━━╸─── 88/124 6.4it/s 13.5s<5.6s

      19/50      10.1G      1.816     0.8413     0.9399        138       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.7s<5.3s

      19/50      10.1G      1.816     0.8412     0.9392        158       1024: 73% ━━━━━━━━╸─── 90/124 6.5it/s 13.8s<5.2s

      19/50      10.1G      1.815     0.8403     0.9391        114       1024: 73% ━━━━━━━━╸─── 91/124 6.6it/s 14.0s<5.0s

      19/50      10.1G      1.813       0.84     0.9389        129       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.1s<4.8s

      19/50      10.1G       1.81     0.8389     0.9387         96       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.2s<4.6s

      19/50      10.1G       1.81     0.8389     0.9402         95       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.4s<4.4s

      19/50      10.1G      1.811      0.839     0.9405        131       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.6s<4.5s

      19/50      10.1G      1.808     0.8377     0.9395        157       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.7s<4.3s

      19/50      10.1G      1.809     0.8379     0.9403        103       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.9s<4.1s

      19/50      10.1G       1.81     0.8382      0.941        130       1024: 79% ━━━━━━━━━─── 98/124 6.6it/s 15.0s<3.9s

      19/50      10.1G      1.809     0.8377       0.94        214       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.2s<3.7s

      19/50      10.1G      1.809     0.8381     0.9396        180       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.3s<3.6s

      19/50      10.1G      1.808      0.838     0.9401        117       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.5s<3.4s

      19/50      10.1G      1.807     0.8381       0.94        124       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.6s<3.2s

      19/50      10.1G      1.804     0.8363     0.9397        118       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.8s<3.2s

      19/50      10.1G      1.805     0.8365     0.9402        143       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.9s<3.1s

      19/50      10.1G      1.804     0.8359     0.9396        139       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.1s<2.9s

      19/50      10.1G      1.803     0.8355     0.9397        160       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      19/50      10.1G      1.803     0.8353     0.9396        154       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.4s<2.5s

      19/50      10.1G      1.801     0.8361     0.9397        104       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.5s<2.4s

      19/50      10.1G      1.802     0.8362     0.9401        146       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.7s<2.2s

      19/50      10.1G      1.801     0.8365     0.9403        121       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.8s<2.1s

      19/50      10.1G      1.801     0.8375     0.9403        151       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 17.0s<2.0s

      19/50      10.1G      1.801     0.8374     0.9401        133       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.1s<1.8s

      19/50      10.1G        1.8     0.8364     0.9397        115       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.3s<1.7s

      19/50      10.1G      1.799     0.8357     0.9392        135       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

      19/50      10.1G      1.799      0.836     0.9389        112       1024: 93% ━━━━━━━━━━━─ 115/124 6.6it/s 17.6s<1.4s

      19/50      10.1G      1.799     0.8356     0.9386        128       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.7s<1.2s

      19/50      10.1G      1.799     0.8368     0.9392        136       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.9s<1.0s

      19/50      10.1G      1.798     0.8362     0.9388        147       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 18.0s<0.9s

      19/50      10.1G      1.798     0.8354     0.9389        151       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.2s<0.8s

      19/50      10.1G      1.798     0.8352     0.9388        152       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.3s<0.6s

      19/50      10.1G      1.797     0.8352     0.9386        146       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.5s<0.5s

      19/50      10.1G      1.798     0.8358     0.9392        129       1024: 98% ━━━━━━━━━━━╸ 122/124 6.5it/s 18.6s<0.3s

      19/50      10.1G      1.799     0.8367     0.9389        164       1024: 99% ━━━━━━━━━━━╸ 123/124 6.6it/s 18.8s<0.2s

      19/50      10.1G      1.799     0.8367     0.9389        164       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.689       0.59      0.621      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/50      10.1G      1.667     0.7816     0.9356        124       1024: 0% ──────────── 0/124  0.1s

      20/50      10.1G      1.668     0.8244     0.9299        107       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      20/50      10.1G      1.682     0.7996     0.9381        114       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.0s

      20/50      10.1G      1.802     0.8401     0.9477        142       1024: 2% ──────────── 3/124 4.2it/s 0.6s<29.1s

      20/50      10.1G       1.83     0.8328     0.9477        154       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.6s

      20/50      10.1G      1.839     0.8441     0.9486        137       1024: 4% ──────────── 5/124 5.4it/s 0.9s<21.9s

      20/50      10.1G      1.847     0.8443     0.9481        129       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.2s

      20/50      10.1G       1.83     0.8369     0.9379        165       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      20/50      10.1G      1.808     0.8279     0.9357        150       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.3s

      20/50      10.1G      1.783     0.8167     0.9321        108       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.7s

      20/50      10.1G      1.774     0.8147     0.9334        103       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.3s

      20/50      10.1G      1.781     0.8213     0.9357        153       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<17.9s

      20/50      10.1G      1.788      0.831     0.9331        168       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.6s

      20/50      10.1G      1.791     0.8298     0.9383         83       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

      20/50      10.1G      1.782     0.8278     0.9391        139       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.7s

      20/50      10.1G      1.784     0.8314     0.9438        126       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.4s

      20/50      10.1G       1.78     0.8314     0.9428        124       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      20/50      10.1G       1.79     0.8352     0.9467        125       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      20/50      10.1G       1.78     0.8315     0.9434        173       1024: 15% ━╸────────── 18/124 6.8it/s 2.9s<15.7s

      20/50      10.1G      1.773     0.8253     0.9399        135       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.3s

      20/50      10.1G      1.772     0.8273     0.9378        199       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.1s

      20/50      10.1G      1.767     0.8254     0.9369        167       1024: 17% ━━────────── 21/124 6.5it/s 3.3s<15.8s

      20/50      10.1G      1.762     0.8237     0.9365        123       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.4s

      20/50      10.1G      1.759     0.8236     0.9355        115       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

      20/50      10.1G      1.749     0.8197     0.9324        143       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.9s

      20/50      10.1G      1.751      0.823     0.9332        132       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

      20/50      10.1G      1.751     0.8239     0.9322        149       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.5s

      20/50      10.1G      1.754     0.8299     0.9334        162       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<15.0s

      20/50      10.1G      1.753     0.8292     0.9342        124       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.8s

      20/50      10.1G      1.747     0.8233     0.9326        155       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.5s

      20/50      10.1G      1.743     0.8228     0.9318        138       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.2s

      20/50      10.1G      1.749     0.8246     0.9314        107       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.9s

      20/50      10.1G      1.747     0.8221     0.9296        112       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<14.0s

      20/50      10.1G      1.744     0.8188     0.9293        108       1024: 27% ━━━───────── 33/124 6.5it/s 5.2s<13.9s

      20/50      10.1G       1.75     0.8198     0.9318        129       1024: 27% ━━━───────── 34/124 6.5it/s 5.3s<13.8s

      20/50      10.1G      1.749     0.8179     0.9312        139       1024: 28% ━━━───────── 35/124 6.3it/s 5.5s<14.1s

      20/50      10.1G      1.747      0.818     0.9308        142       1024: 29% ━━━───────── 36/124 6.4it/s 5.6s<13.7s

      20/50      10.1G      1.754     0.8244     0.9307        172       1024: 30% ━━━╸──────── 37/124 6.5it/s 5.8s<13.3s

      20/50      10.1G      1.755     0.8245     0.9306        145       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.0s

      20/50      10.1G      1.754     0.8223     0.9302        111       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.1s<12.7s

      20/50      10.1G      1.756     0.8248      0.931        147       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.2s<12.5s

      20/50      10.1G      1.755     0.8235     0.9299        175       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.4s<12.4s

      20/50      10.1G       1.76     0.8277     0.9301        138       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

      20/50      10.1G       1.76     0.8281     0.9322        117       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.6s

      20/50      10.1G      1.758      0.826      0.931        146       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.3s

      20/50      10.1G      1.764     0.8289     0.9323        139       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<12.0s

      20/50      10.1G      1.768     0.8333     0.9316        224       1024: 37% ━━━━──────── 46/124 6.6it/s 7.1s<11.9s

      20/50      10.1G      1.774     0.8378      0.932        140       1024: 38% ━━━━╸─────── 47/124 6.6it/s 7.3s<11.6s

      20/50      10.1G      1.774     0.8365     0.9311        156       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.4s<11.4s

      20/50      10.1G      1.776     0.8357     0.9315        117       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.2s

      20/50      10.1G      1.782     0.8371     0.9324        113       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      20/50      10.1G      1.782      0.837     0.9329        120       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.3s

      20/50      10.1G      1.776     0.8342     0.9312        145       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      20/50      10.1G      1.778     0.8356     0.9312        141       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.7s

      20/50      10.1G       1.78     0.8356     0.9312        172       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.5s

      20/50      10.1G      1.778     0.8351      0.931        162       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.5s<10.2s

      20/50      10.1G       1.78     0.8359     0.9309        190       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.6s<10.1s

      20/50      10.1G      1.785     0.8378     0.9311        160       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<9.9s

      20/50      10.1G      1.784     0.8355     0.9301        148       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.8s

      20/50      10.1G      1.784      0.835     0.9296        113       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.0s

      20/50      10.1G      1.782     0.8341      0.929        173       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.3s<9.8s

      20/50      10.1G      1.782     0.8333     0.9296        146       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.5s

      20/50      10.1G      1.783     0.8341     0.9294        168       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.3s

      20/50      10.1G      1.783      0.833     0.9288        164       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

      20/50      10.1G      1.783     0.8328     0.9295        123       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<8.9s

      20/50      10.1G      1.783     0.8329     0.9295        144       1024: 52% ━━━━━━────── 65/124 6.8it/s 10.0s<8.7s

      20/50      10.1G      1.782     0.8322     0.9292        144       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.6s

      20/50      10.1G      1.783     0.8319       0.93        133       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.3s<8.8s

      20/50      10.1G      1.783     0.8311     0.9299        126       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.5s<8.6s

      20/50      10.1G      1.783     0.8294     0.9293        132       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

      20/50      10.1G       1.78     0.8278     0.9304        120       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.8s<8.1s

      20/50      10.1G       1.78     0.8282      0.931        137       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      20/50      10.1G      1.782     0.8282      0.931        127       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.7s

      20/50      10.1G       1.78     0.8271     0.9297        129       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      20/50      10.1G      1.782     0.8276     0.9302        141       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

      20/50      10.1G      1.783     0.8285     0.9313        134       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.5s<7.6s

      20/50      10.1G      1.783     0.8293     0.9308        180       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.7s<7.4s

      20/50      10.1G      1.784     0.8299     0.9304        194       1024: 62% ━━━━━━━───── 77/124 6.5it/s 11.8s<7.2s

      20/50      10.1G      1.784     0.8287     0.9312        126       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 12.0s<6.9s

      20/50      10.1G      1.784      0.828     0.9318        133       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.7s

      20/50      10.1G      1.784     0.8281     0.9318        114       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.3s<6.5s

      20/50      10.1G      1.785     0.8283     0.9321         97       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.4s<6.4s

      20/50      10.1G      1.783     0.8272     0.9322        125       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.5s<6.2s

      20/50      10.1G      1.785     0.8283      0.932        182       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.7s<6.3s

      20/50      10.1G      1.788     0.8288     0.9326        134       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.2s

      20/50      10.1G      1.788     0.8284     0.9324        117       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.0s<5.9s

      20/50      10.1G      1.787     0.8282     0.9316        152       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.2s<5.7s

      20/50      10.1G      1.788     0.8291     0.9321        107       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.5s

      20/50      10.1G      1.792      0.829     0.9323        184       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.5s<5.4s

      20/50      10.1G      1.794     0.8308     0.9322        139       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.2s

      20/50      10.1G      1.791     0.8302     0.9319        139       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.8s<5.0s

      20/50      10.1G      1.794     0.8313     0.9319        137       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.9s<5.1s

      20/50      10.1G      1.796     0.8308     0.9326        126       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.1s<4.8s

      20/50      10.1G      1.799     0.8324      0.933        111       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.2s<4.6s

      20/50      10.1G      1.798     0.8327      0.933        143       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.4s<4.5s

      20/50      10.1G      1.799     0.8329     0.9337        157       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.5s<4.3s

      20/50      10.1G      1.799      0.833     0.9339         99       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.7s<4.1s

      20/50      10.1G      1.798     0.8328     0.9339        151       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.8s<4.0s

      20/50      10.1G      1.797      0.832     0.9336        146       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.0s<3.8s

      20/50      10.1G      1.797     0.8335     0.9345        101       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.1s<3.9s

      20/50      10.1G      1.797     0.8327     0.9352        127       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.3s<3.7s

      20/50      10.1G      1.795     0.8318     0.9344        176       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.4s<3.5s

      20/50      10.1G      1.796     0.8314     0.9345        139       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      20/50      10.1G      1.798     0.8317     0.9345        125       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.7s<3.1s

      20/50      10.1G      1.801     0.8333     0.9347        159       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.9s<3.0s

      20/50      10.1G      1.799     0.8335     0.9347        151       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.0s<2.8s

      20/50      10.1G      1.797     0.8326     0.9343        113       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.2s<2.7s

      20/50      10.1G      1.799     0.8337     0.9347        132       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.3s<2.6s

      20/50      10.1G        1.8     0.8338      0.934        117       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.5s<2.4s

      20/50      10.1G        1.8     0.8346     0.9338        160       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.6s<2.3s

      20/50      10.1G        1.8     0.8348     0.9337        166       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.8s<2.1s

      20/50      10.1G      1.801      0.835      0.934        152       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.9s<1.9s

      20/50      10.1G      1.798     0.8343     0.9335        114       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.1s<1.8s

      20/50      10.1G      1.798     0.8353     0.9337        169       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.6s

      20/50      10.1G      1.796     0.8344     0.9336        131       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.4s<1.5s

      20/50      10.1G      1.795     0.8337     0.9331        170       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.5s<1.4s

      20/50      10.1G      1.798     0.8346     0.9333        142       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.7s<1.2s

      20/50      10.1G        1.8     0.8351     0.9338         97       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.8s<1.1s

      20/50      10.1G      1.799     0.8344     0.9337        153       1024: 95% ━━━━━━━━━━━─ 118/124 6.5it/s 18.0s<0.9s

      20/50      10.1G      1.798      0.834      0.934        118       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.1s<0.8s

      20/50      10.1G      1.798     0.8348     0.9347         98       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.3s<0.6s

      20/50      10.1G      1.797     0.8338     0.9343        115       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.4s

      20/50      10.1G      1.796     0.8336      0.934        112       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.6s<0.3s

      20/50      10.1G      1.794     0.8333     0.9341        117       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.8s<0.2s

      20/50      10.1G      1.794     0.8333     0.9341        117       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.671      0.624      0.646      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/50      10.1G      1.761     0.8238      1.002        128       1024: 0% ──────────── 0/124  0.1s

      21/50      10.1G      1.654     0.7727     0.9529        138       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:02

      21/50      10.1G      1.726     0.7801     0.9574        128       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.4s

      21/50      10.1G      1.776     0.7976     0.9646        123       1024: 2% ──────────── 3/124 4.5it/s 0.6s<27.0s

      21/50      10.1G      1.759     0.7919     0.9645        136       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.0s

      21/50      10.1G      1.729     0.7816     0.9494        162       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.9s

      21/50      10.1G      1.745     0.7781     0.9599        117       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

      21/50      10.1G      1.787     0.8022     0.9606        110       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.7s

      21/50      10.1G      1.782     0.7987     0.9518        159       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<18.9s

      21/50      10.1G       1.76     0.7917     0.9453        168       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.2s

      21/50      10.1G      1.747     0.7851     0.9481        110       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.6s

      21/50      10.1G      1.748     0.7911     0.9484        149       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.3s

      21/50      10.1G      1.753      0.797     0.9471        162       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<16.9s

      21/50      10.1G      1.737     0.7912     0.9424        154       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.6s

      21/50      10.1G      1.731     0.7868     0.9391        108       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.3s

      21/50      10.1G      1.759     0.8001     0.9477        136       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.9s

      21/50      10.1G      1.758     0.7966     0.9457        137       1024: 13% ━╸────────── 16/124 6.6it/s 2.5s<16.4s

      21/50      10.1G      1.748     0.7914     0.9421        155       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      21/50      10.1G      1.745     0.7899     0.9423        104       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.0s

      21/50      10.1G      1.732     0.7892     0.9381        168       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      21/50      10.1G      1.724     0.7863     0.9359        159       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.5s

      21/50      10.1G      1.728      0.788     0.9412        134       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      21/50      10.1G      1.738     0.7942     0.9384        111       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.2s

      21/50      10.1G      1.738     0.7939     0.9383        136       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

      21/50      10.1G      1.739     0.7948     0.9408        103       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.5s

      21/50      10.1G      1.739     0.7938     0.9381        162       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.1s

      21/50      10.1G      1.751     0.7978     0.9429        121       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.9s

      21/50      10.1G      1.745     0.7998     0.9423        121       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.6s

      21/50      10.1G      1.741      0.798     0.9411        101       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      21/50      10.1G      1.744     0.8004     0.9423        107       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      21/50      10.1G      1.744     0.8014     0.9412        115       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      21/50      10.1G      1.744     0.8035     0.9421        119       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.3s

      21/50      10.1G      1.748     0.8039     0.9422        120       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<13.9s

      21/50      10.1G      1.753     0.8049      0.941        144       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.6s

      21/50      10.1G      1.744     0.8006     0.9385        131       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      21/50      10.1G       1.74     0.8013      0.938        125       1024: 28% ━━━───────── 35/124 6.8it/s 5.4s<13.2s

      21/50      10.1G      1.747     0.8063     0.9398        122       1024: 29% ━━━───────── 36/124 6.8it/s 5.6s<13.0s

      21/50      10.1G      1.745     0.8075     0.9393        191       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      21/50      10.1G      1.741     0.8079     0.9387        140       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

      21/50      10.1G       1.74     0.8083     0.9391        113       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.0s<13.3s

      21/50      10.1G      1.743     0.8096     0.9398        128       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      21/50      10.1G      1.745     0.8124     0.9397        164       1024: 33% ━━━╸──────── 41/124 6.5it/s 6.3s<12.8s

      21/50      10.1G      1.748     0.8144     0.9388        171       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.4s

      21/50      10.1G      1.754     0.8183     0.9378        189       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.2s

      21/50      10.1G      1.754     0.8186     0.9396        121       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

      21/50      10.1G      1.762     0.8205     0.9399        124       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      21/50      10.1G      1.764     0.8189     0.9393        147       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      21/50      10.1G       1.77     0.8203     0.9397        146       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.9s

      21/50      10.1G      1.771     0.8205     0.9412        136       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.5s

      21/50      10.1G      1.774     0.8197     0.9412        130       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

      21/50      10.1G      1.779     0.8214     0.9421        133       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      21/50      10.1G      1.781     0.8213     0.9415        143       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.8s

      21/50      10.1G       1.78     0.8216     0.9423        116       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.0s<10.6s

      21/50      10.1G      1.777     0.8195     0.9411        129       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

      21/50      10.1G      1.778     0.8188     0.9404        187       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      21/50      10.1G      1.778     0.8203     0.9399        129       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.4s<10.7s

      21/50      10.1G      1.779     0.8227     0.9391        148       1024: 45% ━━━━━─────── 56/124 6.5it/s 8.6s<10.4s

      21/50      10.1G      1.778     0.8236     0.9398        122       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.7s<10.1s

      21/50      10.1G      1.776     0.8205     0.9402        105       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.9s

      21/50      10.1G      1.777       0.82     0.9417        115       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

      21/50      10.1G      1.774     0.8196     0.9413        135       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.4s

      21/50      10.1G      1.772     0.8192     0.9405        121       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.3s

      21/50      10.1G      1.774     0.8212     0.9415        135       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      21/50      10.1G      1.771     0.8204     0.9401        168       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

      21/50      10.1G      1.772     0.8205     0.9397        141       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.8s<9.2s

      21/50      10.1G      1.772      0.822     0.9396        169       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<8.9s

      21/50      10.1G      1.776     0.8237       0.94        100       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      21/50      10.1G      1.776     0.8246     0.9403        170       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.2s<8.5s

      21/50      10.1G      1.773     0.8225     0.9399        142       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.4s<8.3s

      21/50      10.1G      1.771     0.8214     0.9392        174       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

      21/50      10.1G      1.773     0.8227     0.9384        204       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      21/50      10.1G      1.775     0.8239     0.9394        125       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.8s<8.2s

      21/50      10.1G      1.777     0.8249     0.9393        153       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.9s

      21/50      10.1G      1.775     0.8241     0.9384        178       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      21/50      10.1G      1.776      0.824     0.9377        154       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

      21/50      10.1G      1.777     0.8236     0.9379        129       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

      21/50      10.1G      1.775     0.8237     0.9381        122       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      21/50      10.1G      1.776     0.8232     0.9378        165       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

      21/50      10.1G      1.776      0.823     0.9378        119       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

      21/50      10.1G      1.774      0.823     0.9374        116       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.0s<6.9s

      21/50      10.1G      1.775     0.8237     0.9374        125       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.2s<6.7s

      21/50      10.1G      1.771     0.8222     0.9366        118       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.3s<6.5s

      21/50      10.1G      1.771     0.8206     0.9366        132       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      21/50      10.1G      1.772      0.822     0.9376        135       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.6s<6.1s

      21/50      10.1G      1.773     0.8214     0.9378        123       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

      21/50      10.1G      1.772     0.8207     0.9377        110       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.9s<5.7s

      21/50      10.1G      1.772     0.8214      0.938        140       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      21/50      10.1G      1.774     0.8217     0.9389        124       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.2s<5.7s

      21/50      10.1G      1.773     0.8214     0.9389        175       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.4s<5.5s

      21/50      10.1G      1.774     0.8214     0.9393        153       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.5s<5.3s

      21/50      10.1G      1.774      0.821     0.9391        168       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      21/50      10.1G      1.773       0.82     0.9381        136       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.8s<4.9s

      21/50      10.1G      1.773     0.8215     0.9387        140       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.0s<4.8s

      21/50      10.1G      1.772      0.821     0.9384        125       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

      21/50      10.1G      1.772     0.8218     0.9392        117       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      21/50      10.1G       1.77     0.8207     0.9381        116       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.4s<4.5s

      21/50      10.1G      1.769     0.8208     0.9381        178       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.6s<4.3s

      21/50      10.1G      1.771     0.8203     0.9375        153       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.7s<4.1s

      21/50      10.1G      1.773     0.8204     0.9376        135       1024: 79% ━━━━━━━━━─── 98/124 6.6it/s 14.9s<3.9s

      21/50      10.1G      1.772     0.8213     0.9378        150       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.0s<3.7s

      21/50      10.1G      1.773     0.8219     0.9384        104       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.2s<3.6s

      21/50      10.1G      1.771      0.821     0.9378        116       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.3s<3.4s

      21/50      10.1G      1.775     0.8233     0.9387        158       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

      21/50      10.1G      1.774     0.8234     0.9386        152       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

      21/50      10.1G      1.773     0.8231     0.9383        117       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.8s<3.1s

      21/50      10.1G      1.773     0.8226     0.9379        166       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

      21/50      10.1G      1.771     0.8217     0.9372        158       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.1s<2.7s

      21/50      10.1G      1.773     0.8229     0.9373        164       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.3s<2.6s

      21/50      10.1G      1.772     0.8224     0.9373        136       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      21/50      10.1G      1.773     0.8229     0.9372        118       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.5s<2.2s

      21/50      10.1G      1.773     0.8223     0.9376        110       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

      21/50      10.1G      1.771     0.8218     0.9372        136       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.9s<2.0s

      21/50      10.1G      1.774     0.8232     0.9376        131       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.0s<1.8s

      21/50      10.1G      1.775     0.8236     0.9378        132       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.7s

      21/50      10.1G      1.773     0.8232     0.9376        103       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      21/50      10.1G      1.775     0.8249     0.9374        127       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

      21/50      10.1G      1.776     0.8263      0.938        125       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      21/50      10.1G      1.776     0.8263     0.9381        137       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.7s<1.0s

      21/50      10.1G      1.777     0.8266     0.9377        130       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      21/50      10.1G      1.777     0.8257     0.9373        153       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

      21/50      10.1G      1.776     0.8252     0.9371        122       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.2s<0.6s

      21/50      10.1G      1.776     0.8251     0.9367        132       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.5s

      21/50      10.1G      1.775     0.8254     0.9364        114       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

      21/50      10.1G      1.775     0.8249      0.936        200       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

      21/50      10.1G      1.775     0.8249      0.936        200       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227       0.66      0.618      0.636      0.388

Closing dataloader mosaic

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/50      10.1G      1.672      0.739     0.8795        113       1024: 0% ──────────── 0/124  0.4s

      22/50      10.1G      1.648     0.6928     0.8973         99       1024: 1% ──────────── 1/124 1.8it/s 0.5s<1:10

      22/50      10.1G      1.638     0.7098     0.8887        119       1024: 2% ──────────── 2/124 2.9it/s 0.7s<42.6s

      22/50      10.1G       1.74     0.7614     0.9008        111       1024: 2% ──────────── 3/124 3.1it/s 1.0s<39.3s

      22/50      10.1G      1.775     0.7698     0.9114        110       1024: 3% ──────────── 4/124 4.2it/s 1.1s<28.3s

      22/50      10.1G      1.791     0.7958     0.9229        100       1024: 4% ──────────── 5/124 5.0it/s 1.3s<23.7s

      22/50      10.1G      1.776     0.8033     0.9184        109       1024: 5% ╸─────────── 6/124 5.3it/s 1.4s<22.2s

      22/50      10.1G      1.768     0.7983     0.9203        122       1024: 6% ╸─────────── 7/124 5.8it/s 1.6s<20.2s

      22/50      10.1G      1.758      0.792     0.9188        129       1024: 6% ╸─────────── 8/124 6.0it/s 1.7s<19.3s

      22/50      10.1G       1.78     0.7965      0.927        114       1024: 7% ╸─────────── 9/124 6.2it/s 1.9s<18.7s

      22/50      10.1G       1.77     0.7898     0.9268         90       1024: 8% ╸─────────── 10/124 6.4it/s 2.0s<17.9s

      22/50      10.1G      1.762     0.7976     0.9256        118       1024: 9% ━─────────── 11/124 6.2it/s 2.2s<18.3s

      22/50      10.1G      1.777     0.7992     0.9247        137       1024: 10% ━─────────── 12/124 6.3it/s 2.4s<17.9s

      22/50      10.1G      1.767     0.8039     0.9254        117       1024: 10% ━─────────── 13/124 6.5it/s 2.5s<17.2s

      22/50      10.1G      1.768     0.8023     0.9237        112       1024: 11% ━─────────── 14/124 6.4it/s 2.7s<17.2s

      22/50      10.1G      1.779      0.816     0.9309        117       1024: 12% ━─────────── 15/124 6.5it/s 2.8s<16.7s

      22/50      10.1G      1.793     0.8177      0.937        103       1024: 13% ━╸────────── 16/124 6.6it/s 3.0s<16.3s

      22/50      10.1G      1.789     0.8138     0.9339        116       1024: 14% ━╸────────── 17/124 6.7it/s 3.1s<16.0s

      22/50      10.1G      1.783     0.8114     0.9344        121       1024: 15% ━╸────────── 18/124 6.7it/s 3.3s<15.7s

      22/50      10.1G      1.772     0.8073     0.9352        116       1024: 15% ━╸────────── 19/124 6.4it/s 3.4s<16.3s

      22/50      10.1G      1.758     0.8033     0.9327        133       1024: 16% ━╸────────── 20/124 6.5it/s 3.6s<16.1s

      22/50      10.1G      1.762     0.8017     0.9347        129       1024: 17% ━━────────── 21/124 6.6it/s 3.7s<15.6s

      22/50      10.1G      1.753      0.797      0.935         98       1024: 18% ━━────────── 22/124 6.7it/s 3.9s<15.3s

      22/50      10.1G      1.763     0.7995     0.9366        115       1024: 19% ━━────────── 23/124 6.7it/s 4.0s<15.0s

      22/50      10.1G      1.767     0.7997     0.9355        134       1024: 19% ━━────────── 24/124 6.8it/s 4.2s<14.7s

      22/50      10.1G      1.765     0.7964     0.9375        114       1024: 20% ━━────────── 25/124 6.6it/s 4.3s<15.0s

      22/50      10.1G       1.76      0.792     0.9354        113       1024: 21% ━━╸───────── 26/124 6.7it/s 4.5s<14.7s

      22/50      10.1G      1.757     0.7913     0.9327        117       1024: 22% ━━╸───────── 27/124 6.4it/s 4.6s<15.1s

      22/50      10.1G      1.749     0.7908     0.9337        116       1024: 23% ━━╸───────── 28/124 6.4it/s 4.8s<14.9s

      22/50      10.1G      1.753     0.7887     0.9325        115       1024: 23% ━━╸───────── 29/124 6.5it/s 5.0s<14.6s

      22/50      10.1G       1.76     0.7897     0.9318        102       1024: 24% ━━╸───────── 30/124 6.6it/s 5.1s<14.2s

      22/50      10.1G      1.768     0.7979     0.9324        125       1024: 25% ━━━───────── 31/124 6.5it/s 5.3s<14.2s

      22/50      10.1G      1.767     0.7991     0.9328        112       1024: 26% ━━━───────── 32/124 6.7it/s 5.4s<13.8s

      22/50      10.1G      1.762     0.7962     0.9335        107       1024: 27% ━━━───────── 33/124 6.7it/s 5.5s<13.5s

      22/50      10.1G      1.757     0.7942      0.932        123       1024: 27% ━━━───────── 34/124 6.6it/s 5.7s<13.7s

      22/50      10.1G       1.76     0.7938     0.9322         99       1024: 28% ━━━───────── 35/124 6.3it/s 5.9s<14.1s

      22/50      10.1G      1.764     0.7931      0.933        121       1024: 29% ━━━───────── 36/124 6.5it/s 6.0s<13.5s

      22/50      10.1G      1.756     0.7895     0.9307        103       1024: 30% ━━━╸──────── 37/124 6.5it/s 6.2s<13.4s

      22/50      10.1G      1.757     0.7916     0.9296        112       1024: 31% ━━━╸──────── 38/124 6.5it/s 6.3s<13.2s

      22/50      10.1G       1.76     0.7936     0.9303        116       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.5s<12.8s

      22/50      10.1G       1.76     0.7938     0.9296        117       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.6s<12.8s

      22/50      10.1G      1.761      0.792     0.9276        107       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.8s<12.5s

      22/50      10.1G      1.759     0.7938     0.9275         95       1024: 34% ━━━━──────── 42/124 6.7it/s 6.9s<12.2s

      22/50      10.1G      1.757     0.7921     0.9262        125       1024: 35% ━━━━──────── 43/124 6.4it/s 7.1s<12.7s

      22/50      10.1G      1.755     0.7933     0.9276        112       1024: 35% ━━━━──────── 44/124 6.5it/s 7.2s<12.3s

      22/50      10.1G      1.754     0.7914     0.9275        109       1024: 36% ━━━━──────── 45/124 6.6it/s 7.4s<11.9s

      22/50      10.1G      1.752      0.791     0.9266        126       1024: 37% ━━━━──────── 46/124 6.7it/s 7.5s<11.6s

      22/50      10.1G      1.748       0.79     0.9268        121       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.7s<11.4s

      22/50      10.1G      1.748     0.7902     0.9276        124       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.8s<11.5s

      22/50      10.1G      1.745     0.7905     0.9288        106       1024: 40% ━━━━╸─────── 49/124 6.7it/s 8.0s<11.2s

      22/50      10.1G      1.742     0.7883     0.9295        117       1024: 40% ━━━━╸─────── 50/124 6.7it/s 8.1s<11.0s

      22/50      10.1G      1.741      0.788     0.9304        131       1024: 41% ━━━━╸─────── 51/124 6.4it/s 8.3s<11.5s

      22/50      10.1G       1.74     0.7876     0.9309        117       1024: 42% ━━━━━─────── 52/124 6.4it/s 8.5s<11.2s

      22/50      10.1G      1.737      0.788     0.9313        104       1024: 43% ━━━━━─────── 53/124 6.5it/s 8.6s<10.9s

      22/50      10.1G      1.734     0.7887     0.9312        120       1024: 44% ━━━━━─────── 54/124 6.6it/s 8.8s<10.6s

      22/50      10.1G      1.735     0.7905     0.9314        132       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.9s<10.3s

      22/50      10.1G      1.733     0.7891       0.93        110       1024: 45% ━━━━━─────── 56/124 6.8it/s 9.1s<10.1s

      22/50      10.1G      1.736     0.7924     0.9299        121       1024: 46% ━━━━━╸────── 57/124 6.8it/s 9.2s<9.9s

      22/50      10.1G      1.732     0.7908     0.9294        115       1024: 47% ━━━━━╸────── 58/124 6.7it/s 9.4s<9.9s

      22/50      10.1G      1.736     0.7904     0.9294        124       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.5s<10.1s

      22/50      10.1G      1.738     0.7919     0.9311         98       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.7s<9.7s

      22/50      10.1G      1.737     0.7909     0.9303        102       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.8s<9.4s

      22/50      10.1G      1.741     0.7906     0.9317        109       1024: 50% ━━━━━━────── 62/124 6.6it/s 10.0s<9.4s

      22/50      10.1G      1.744     0.7915     0.9317        112       1024: 51% ━━━━━━────── 63/124 6.7it/s 10.1s<9.1s

      22/50      10.1G      1.744     0.7901     0.9325        107       1024: 52% ━━━━━━────── 64/124 6.8it/s 10.3s<8.9s

      22/50      10.1G      1.742     0.7905     0.9317        110       1024: 52% ━━━━━━────── 65/124 6.8it/s 10.4s<8.7s

      22/50      10.1G      1.741     0.7908     0.9317        127       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.6s<8.5s

      22/50      10.1G      1.746     0.7922     0.9332        115       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.7s<8.8s

      22/50      10.1G      1.745      0.791     0.9331        116       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.9s<8.6s

      22/50      10.1G      1.747     0.7929     0.9343        107       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 11.0s<8.3s

      22/50      10.1G      1.746     0.7927     0.9341        111       1024: 56% ━━━━━━╸───── 70/124 6.5it/s 11.2s<8.3s

      22/50      10.1G      1.747     0.7925     0.9339        107       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 11.3s<8.0s

      22/50      10.1G      1.746     0.7919     0.9343        112       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.5s<7.9s

      22/50      10.1G      1.745      0.792     0.9346        111       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.6s<7.6s

      22/50      10.1G      1.746     0.7914     0.9345         99       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.8s<7.4s

      22/50      10.1G      1.745     0.7914      0.935        121       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.9s<7.6s

      22/50      10.1G      1.746     0.7912     0.9353        103       1024: 61% ━━━━━━━───── 76/124 6.4it/s 12.1s<7.5s

      22/50      10.1G      1.747     0.7912     0.9361        112       1024: 62% ━━━━━━━───── 77/124 6.5it/s 12.3s<7.2s

      22/50      10.1G      1.746     0.7906     0.9357        114       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 12.4s<7.0s

      22/50      10.1G      1.744     0.7896     0.9356        129       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.5s<6.7s

      22/50      10.1G      1.743     0.7894     0.9362         98       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.7s<6.5s

      22/50      10.1G      1.747     0.7899     0.9372        113       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.8s<6.5s

      22/50      10.1G      1.746     0.7896     0.9366        101       1024: 66% ━━━━━━━╸──── 82/124 6.5it/s 13.0s<6.4s

      22/50      10.1G      1.748     0.7899      0.937        100       1024: 67% ━━━━━━━━──── 83/124 6.3it/s 13.2s<6.5s

      22/50      10.1G      1.749     0.7892      0.937        112       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 13.3s<6.2s

      22/50      10.1G      1.748     0.7893     0.9369        116       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.5s<5.9s

      22/50      10.1G      1.749     0.7897     0.9363        113       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.6s<5.7s

      22/50      10.1G      1.754     0.7907     0.9364        125       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.8s<5.5s

      22/50      10.1G      1.753     0.7896     0.9364        120       1024: 71% ━━━━━━━━╸─── 88/124 6.8it/s 13.9s<5.3s

      22/50      10.1G      1.752      0.789     0.9359        128       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 14.1s<5.2s

      22/50      10.1G      1.753     0.7881      0.936        120       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 14.2s<5.0s

      22/50      10.1G      1.755      0.789      0.936        115       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 14.4s<5.1s

      22/50      10.1G      1.759     0.7904     0.9361        112       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.5s<4.9s

      22/50      10.1G       1.76      0.791     0.9364        116       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.7s<4.7s

      22/50      10.1G       1.76     0.7913     0.9367        108       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.8s<4.5s

      22/50      10.1G      1.759     0.7902     0.9371        113       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 15.0s<4.3s

      22/50      10.1G      1.755     0.7887     0.9367        105       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 15.1s<4.2s

      22/50      10.1G      1.753     0.7876     0.9367        108       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 15.3s<4.0s

      22/50      10.1G      1.756     0.7885     0.9376         97       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.4s<3.8s

      22/50      10.1G      1.754     0.7873     0.9368        119       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.6s<3.9s

      22/50      10.1G      1.753     0.7868      0.936        111       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.7s<3.7s

      22/50      10.1G      1.755     0.7869     0.9365        106       1024: 81% ━━━━━━━━━╸── 101/124 6.5it/s 15.9s<3.5s

      22/50      10.1G      1.757     0.7883     0.9372        110       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 16.0s<3.3s

      22/50      10.1G      1.755     0.7878     0.9366        132       1024: 83% ━━━━━━━━━╸── 103/124 6.6it/s 16.2s<3.2s

      22/50      10.1G      1.755     0.7873     0.9366        119       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 16.3s<3.0s

      22/50      10.1G      1.756     0.7876     0.9375        121       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.5s<2.9s

      22/50      10.1G      1.755     0.7873     0.9368        118       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.6s<2.7s

      22/50      10.1G      1.754     0.7864     0.9371        107       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.8s<2.7s

      22/50      10.1G      1.753      0.786     0.9367        109       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.9s<2.4s

      22/50      10.1G      1.755     0.7868     0.9373         92       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 17.1s<2.3s

      22/50      10.1G      1.753     0.7865     0.9364        119       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 17.2s<2.1s

      22/50      10.1G      1.751     0.7856     0.9362        121       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 17.4s<1.9s

      22/50      10.1G      1.753     0.7866     0.9367        107       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.5s<1.8s

      22/50      10.1G      1.751     0.7865     0.9373         90       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.7s<1.6s

      22/50      10.1G      1.749     0.7854     0.9367         97       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.8s<1.5s

      22/50      10.1G      1.751     0.7864     0.9369        109       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 18.0s<1.4s

      22/50      10.1G      1.751     0.7867     0.9367        120       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 18.2s<1.2s

      22/50      10.1G      1.752      0.787     0.9375        109       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 18.3s<1.1s

      22/50      10.1G      1.751     0.7863     0.9372        114       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 18.5s<0.9s

      22/50      10.1G      1.749     0.7861     0.9376        102       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.6s<0.7s

      22/50      10.1G      1.747     0.7855      0.937        106       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.7s<0.6s

      22/50      10.1G      1.749     0.7863     0.9371        112       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.9s<0.4s

      22/50      10.1G       1.75     0.7861     0.9368        129       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 19.0s<0.3s

      22/50      10.1G      1.751     0.7872     0.9372        106       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 19.2s<0.2s

      22/50      10.1G      1.751     0.7872     0.9372        106       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 19.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.1it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.5it/s 2.5s

                   all        330       4227       0.67      0.607      0.633      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/50      10.1G      1.542     0.8125     0.8863        119       1024: 0% ──────────── 0/124  0.1s

      23/50      10.1G      1.578     0.7837     0.9355        103       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:03

      23/50      10.1G      1.508     0.7335      0.912        108       1024: 2% ──────────── 2/124 3.3it/s 0.5s<36.7s

      23/50      10.1G      1.616     0.7616      0.934        116       1024: 2% ──────────── 3/124 4.2it/s 0.6s<28.5s

      23/50      10.1G      1.659     0.7729     0.9318        126       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.6s

      23/50      10.1G      1.635     0.7568     0.9274         92       1024: 4% ──────────── 5/124 5.3it/s 0.9s<22.3s

      23/50      10.1G      1.674     0.7637     0.9479        104       1024: 5% ╸─────────── 6/124 5.8it/s 1.1s<20.5s

      23/50      10.1G      1.678     0.7565     0.9498        112       1024: 6% ╸─────────── 7/124 5.6it/s 1.3s<20.7s

      23/50      10.1G        1.7     0.7752     0.9488        106       1024: 6% ╸─────────── 8/124 5.9it/s 1.4s<19.8s

      23/50      10.1G      1.685     0.7634     0.9459        127       1024: 7% ╸─────────── 9/124 6.0it/s 1.6s<19.2s

      23/50      10.1G      1.719     0.7744     0.9462        120       1024: 8% ╸─────────── 10/124 6.2it/s 1.7s<18.5s

      23/50      10.1G      1.707     0.7734     0.9395        102       1024: 9% ━─────────── 11/124 6.3it/s 1.9s<18.1s

      23/50      10.1G      1.717     0.7789     0.9399        108       1024: 10% ━─────────── 12/124 6.2it/s 2.0s<18.0s

      23/50      10.1G      1.728      0.796     0.9387        113       1024: 10% ━─────────── 13/124 6.4it/s 2.2s<17.5s

      23/50      10.1G       1.74     0.7955     0.9386        130       1024: 11% ━─────────── 14/124 6.4it/s 2.3s<17.1s

      23/50      10.1G      1.734     0.7947     0.9355        110       1024: 12% ━─────────── 15/124 6.2it/s 2.5s<17.7s

      23/50      10.1G      1.734      0.795     0.9377        113       1024: 13% ━╸────────── 16/124 6.2it/s 2.7s<17.4s

      23/50      10.1G      1.742     0.7927     0.9421         95       1024: 14% ━╸────────── 17/124 6.4it/s 2.8s<16.7s

      23/50      10.1G      1.729     0.7851     0.9364        122       1024: 15% ━╸────────── 18/124 6.4it/s 3.0s<16.4s

      23/50      10.1G      1.726     0.7797     0.9327        108       1024: 15% ━╸────────── 19/124 6.6it/s 3.1s<16.0s

      23/50      10.1G       1.73     0.7781     0.9307        128       1024: 16% ━╸────────── 20/124 6.7it/s 3.3s<15.6s

      23/50      10.1G       1.74     0.7771     0.9326        115       1024: 17% ━━────────── 21/124 6.6it/s 3.4s<15.5s

      23/50      10.1G      1.757      0.791     0.9354        116       1024: 18% ━━────────── 22/124 6.7it/s 3.6s<15.2s

      23/50      10.1G      1.749     0.7883     0.9336        112       1024: 19% ━━────────── 23/124 6.4it/s 3.7s<15.8s

      23/50      10.1G      1.757     0.7879     0.9344        138       1024: 19% ━━────────── 24/124 6.5it/s 3.9s<15.5s

      23/50      10.1G      1.747     0.7852     0.9339        112       1024: 20% ━━────────── 25/124 6.6it/s 4.0s<15.0s

      23/50      10.1G      1.739     0.7833     0.9337        101       1024: 21% ━━╸───────── 26/124 6.7it/s 4.2s<14.7s

      23/50      10.1G      1.733     0.7814     0.9334         92       1024: 22% ━━╸───────── 27/124 6.7it/s 4.3s<14.4s

      23/50      10.1G      1.732     0.7807     0.9326        105       1024: 23% ━━╸───────── 28/124 6.8it/s 4.5s<14.2s

      23/50      10.1G      1.735     0.7824     0.9343        109       1024: 23% ━━╸───────── 29/124 6.8it/s 4.6s<14.0s

      23/50      10.1G      1.736     0.7818     0.9354         99       1024: 24% ━━╸───────── 30/124 6.7it/s 4.8s<14.0s

      23/50      10.1G       1.73     0.7797     0.9325        127       1024: 25% ━━━───────── 31/124 6.4it/s 5.0s<14.5s

      23/50      10.1G      1.721     0.7765     0.9314        107       1024: 26% ━━━───────── 32/124 6.6it/s 5.1s<14.0s

      23/50      10.1G      1.724     0.7802     0.9318        103       1024: 27% ━━━───────── 33/124 6.6it/s 5.2s<13.7s

      23/50      10.1G      1.721     0.7781     0.9305        120       1024: 27% ━━━───────── 34/124 6.7it/s 5.4s<13.4s

      23/50      10.1G      1.716     0.7766     0.9297        112       1024: 28% ━━━───────── 35/124 6.7it/s 5.5s<13.2s

      23/50      10.1G      1.716      0.778     0.9307        101       1024: 29% ━━━───────── 36/124 6.8it/s 5.7s<13.0s

      23/50      10.1G      1.713     0.7783     0.9289        111       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.8s<12.8s

      23/50      10.1G      1.712     0.7775     0.9281        107       1024: 31% ━━━╸──────── 38/124 6.8it/s 6.0s<12.6s

      23/50      10.1G      1.712     0.7763     0.9288        107       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.2s<13.2s

      23/50      10.1G      1.722     0.7808     0.9299        122       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.3s<12.7s

      23/50      10.1G      1.719     0.7806      0.928        124       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.4s<12.4s

      23/50      10.1G      1.715     0.7785     0.9266        117       1024: 34% ━━━━──────── 42/124 6.6it/s 6.6s<12.4s

      23/50      10.1G      1.713     0.7786     0.9257        113       1024: 35% ━━━━──────── 43/124 6.7it/s 6.7s<12.1s

      23/50      10.1G      1.716     0.7797     0.9263        100       1024: 35% ━━━━──────── 44/124 6.7it/s 6.9s<11.9s

      23/50      10.1G      1.714     0.7793     0.9274        110       1024: 36% ━━━━──────── 45/124 6.8it/s 7.0s<11.7s

      23/50      10.1G      1.714     0.7778     0.9277        114       1024: 37% ━━━━──────── 46/124 6.8it/s 7.2s<11.5s

      23/50      10.1G      1.714     0.7776      0.928        104       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.4s<11.9s

      23/50      10.1G      1.717     0.7781     0.9277        120       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.5s<11.5s

      23/50      10.1G      1.721     0.7788     0.9286        117       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.6s<11.3s

      23/50      10.1G      1.722     0.7766     0.9287        123       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.8s<11.0s

      23/50      10.1G      1.719     0.7751     0.9292        108       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.9s<10.8s

      23/50      10.1G       1.72     0.7733     0.9282        126       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.1s<10.6s

      23/50      10.1G       1.72     0.7728     0.9284        120       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.2s<10.5s

      23/50      10.1G      1.717     0.7737     0.9278        103       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.4s<10.3s

      23/50      10.1G      1.716     0.7737     0.9282        116       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.6s<10.6s

      23/50      10.1G      1.715     0.7728     0.9285        124       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.7s<10.3s

      23/50      10.1G      1.714     0.7716     0.9284        114       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.8s<10.1s

      23/50      10.1G       1.72     0.7739     0.9302         88       1024: 47% ━━━━━╸────── 58/124 6.7it/s 9.0s<9.8s

      23/50      10.1G      1.719     0.7744     0.9294        106       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.7s

      23/50      10.1G      1.725     0.7757     0.9308        122       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.3s<9.5s

      23/50      10.1G      1.723     0.7736     0.9301        106       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      23/50      10.1G      1.725      0.775     0.9313        133       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.6s<9.1s

      23/50      10.1G      1.724     0.7744     0.9316        125       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.8s<9.4s

      23/50      10.1G      1.724     0.7756     0.9318        114       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.9s<9.2s

      23/50      10.1G      1.723     0.7741     0.9311        115       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.1s<8.9s

      23/50      10.1G      1.728     0.7774     0.9315        110       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.2s<8.7s

      23/50      10.1G      1.729     0.7774     0.9327        109       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.4s<8.6s

      23/50      10.1G      1.728     0.7763     0.9318        105       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.5s<8.4s

      23/50      10.1G      1.731     0.7776     0.9318        129       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.7s<8.3s

      23/50      10.1G      1.732     0.7782     0.9327        118       1024: 56% ━━━━━━╸───── 70/124 6.5it/s 10.8s<8.3s

      23/50      10.1G      1.731     0.7764     0.9322        103       1024: 57% ━━━━━━╸───── 71/124 6.2it/s 11.0s<8.6s

      23/50      10.1G       1.73     0.7778     0.9318        111       1024: 58% ━━━━━━╸───── 72/124 6.3it/s 11.1s<8.2s

      23/50      10.1G      1.732     0.7794     0.9326        124       1024: 59% ━━━━━━━───── 73/124 6.4it/s 11.3s<8.0s

      23/50      10.1G       1.73     0.7789      0.932        112       1024: 60% ━━━━━━━───── 74/124 6.5it/s 11.5s<7.7s

      23/50      10.1G      1.733     0.7799     0.9328         96       1024: 60% ━━━━━━━───── 75/124 6.6it/s 11.6s<7.5s

      23/50      10.1G      1.734     0.7802     0.9325        116       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.7s<7.2s

      23/50      10.1G      1.737     0.7802      0.935        125       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.9s<7.1s

      23/50      10.1G      1.735      0.778     0.9351        114       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      23/50      10.1G      1.736     0.7771     0.9349        103       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.2s<7.0s

      23/50      10.1G      1.733     0.7759     0.9346         94       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.4s<6.8s

      23/50      10.1G      1.736     0.7766      0.935        119       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.5s<6.5s

      23/50      10.1G      1.734     0.7757     0.9352        100       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.7s<6.3s

      23/50      10.1G      1.736     0.7754     0.9351        107       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.8s<6.1s

      23/50      10.1G      1.737     0.7762     0.9353        111       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 13.0s<6.0s

      23/50      10.1G      1.733     0.7738     0.9341        118       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.1s<5.8s

      23/50      10.1G      1.732     0.7738     0.9337        123       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.3s<5.7s

      23/50      10.1G      1.734     0.7732     0.9338         90       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.4s<5.8s

      23/50      10.1G      1.735     0.7746     0.9335        123       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.6s<5.6s

      23/50      10.1G      1.734     0.7744     0.9333        130       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.7s<5.3s

      23/50      10.1G      1.733     0.7742     0.9331        112       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.9s<5.1s

      23/50      10.1G      1.731     0.7731     0.9328        129       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 14.0s<4.9s

      23/50      10.1G       1.73     0.7724     0.9324        111       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.2s<4.8s

      23/50      10.1G      1.731     0.7735     0.9327        118       1024: 75% ━━━━━━━━━─── 93/124 6.5it/s 14.3s<4.8s

      23/50      10.1G      1.731     0.7741     0.9325        117       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.5s<4.5s

      23/50      10.1G      1.734     0.7765     0.9325        112       1024: 77% ━━━━━━━━━─── 95/124 6.3it/s 14.7s<4.6s

      23/50      10.1G      1.736     0.7771     0.9328        127       1024: 77% ━━━━━━━━━─── 96/124 6.3it/s 14.8s<4.4s

      23/50      10.1G      1.738     0.7773     0.9329        112       1024: 78% ━━━━━━━━━─── 97/124 6.5it/s 15.0s<4.2s

      23/50      10.1G      1.739     0.7776     0.9332        112       1024: 79% ━━━━━━━━━─── 98/124 6.4it/s 15.1s<4.0s

      23/50      10.1G      1.737     0.7773     0.9329        102       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.3s<3.9s

      23/50      10.1G      1.736     0.7777      0.933        107       1024: 81% ━━━━━━━━━╸── 100/124 6.4it/s 15.4s<3.8s

      23/50      10.1G      1.733     0.7761      0.932        110       1024: 81% ━━━━━━━━━╸── 101/124 6.3it/s 15.6s<3.6s

      23/50      10.1G      1.733     0.7755     0.9317        114       1024: 82% ━━━━━━━━━╸── 102/124 6.4it/s 15.8s<3.5s

      23/50      10.1G      1.729     0.7738     0.9308        109       1024: 83% ━━━━━━━━━╸── 103/124 6.2it/s 15.9s<3.4s

      23/50      10.1G      1.731     0.7741     0.9317        126       1024: 84% ━━━━━━━━━━── 104/124 6.3it/s 16.1s<3.2s

      23/50      10.1G      1.734      0.776      0.933        108       1024: 85% ━━━━━━━━━━── 105/124 6.5it/s 16.2s<2.9s

      23/50      10.1G      1.735     0.7758     0.9328        122       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.4s<2.7s

      23/50      10.1G      1.734     0.7748     0.9326        132       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.5s<2.6s

      23/50      10.1G      1.734     0.7755     0.9335         95       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.7s<2.4s

      23/50      10.1G      1.734     0.7756      0.933        109       1024: 88% ━━━━━━━━━━╸─ 109/124 6.5it/s 16.8s<2.3s

      23/50      10.1G      1.734     0.7761     0.9333        111       1024: 89% ━━━━━━━━━━╸─ 110/124 6.5it/s 17.0s<2.1s

      23/50      10.1G      1.732     0.7746     0.9326         96       1024: 90% ━━━━━━━━━━╸─ 111/124 6.3it/s 17.2s<2.1s

      23/50      10.1G      1.732     0.7748     0.9325        119       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.3s<1.9s

      23/50      10.1G      1.733     0.7757     0.9322        114       1024: 91% ━━━━━━━━━━╸─ 113/124 6.4it/s 17.5s<1.7s

      23/50      10.1G       1.73     0.7738     0.9314        101       1024: 92% ━━━━━━━━━━━─ 114/124 6.5it/s 17.6s<1.5s

      23/50      10.1G       1.73     0.7719     0.9308        105       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.8s<1.4s

      23/50      10.1G      1.728     0.7718     0.9306        121       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.9s<1.2s

      23/50      10.1G       1.73      0.772     0.9303        120       1024: 94% ━━━━━━━━━━━─ 117/124 6.5it/s 18.1s<1.1s

      23/50      10.1G       1.73     0.7717     0.9306        115       1024: 95% ━━━━━━━━━━━─ 118/124 6.5it/s 18.2s<0.9s

      23/50      10.1G      1.728     0.7711     0.9306        100       1024: 96% ━━━━━━━━━━━╸ 119/124 6.2it/s 18.4s<0.8s

      23/50      10.1G       1.73     0.7718     0.9312        127       1024: 97% ━━━━━━━━━━━╸ 120/124 6.3it/s 18.6s<0.6s

      23/50      10.1G      1.729     0.7712     0.9313        108       1024: 98% ━━━━━━━━━━━╸ 121/124 6.4it/s 18.7s<0.5s

      23/50      10.1G      1.728     0.7711     0.9313        119       1024: 98% ━━━━━━━━━━━╸ 122/124 6.4it/s 18.9s<0.3s

      23/50      10.1G      1.728     0.7711      0.931        107       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 19.0s<0.2s

      23/50      10.1G      1.728     0.7711      0.931        107       1024: 100% ━━━━━━━━━━━━ 124/124 6.5it/s 19.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.5it/s 0.4s<3.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.661      0.597       0.63      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/50      10.1G      1.482     0.6951     0.8404        116       1024: 0% ──────────── 0/124  0.1s

      24/50      10.1G      1.561     0.7125     0.8893        104       1024: 1% ──────────── 1/124 1.9it/s 0.3s<1:03

      24/50      10.1G      1.688     0.7374     0.8918        120       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.6s

      24/50      10.1G       1.63     0.7272     0.8892         95       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.3s

      24/50      10.1G      1.653     0.7362     0.8941        112       1024: 3% ──────────── 4/124 5.0it/s 0.8s<24.2s

      24/50      10.1G      1.648      0.742     0.9003        110       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.5s

      24/50      10.1G      1.654     0.7462     0.9096         96       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<19.9s

      24/50      10.1G      1.625     0.7411     0.9012        117       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

      24/50      10.1G      1.608     0.7253     0.8988        118       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.1s

      24/50      10.1G      1.605     0.7254     0.9002        108       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.6s

      24/50      10.1G      1.601     0.7191     0.8998        117       1024: 8% ╸─────────── 10/124 6.7it/s 1.6s<17.1s

      24/50      10.1G        1.6     0.7179     0.8994        113       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.8s

      24/50      10.1G      1.606     0.7236     0.9013        107       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.1s

      24/50      10.1G      1.609     0.7201     0.8995        121       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.7s

      24/50      10.1G       1.62     0.7191     0.8989         98       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.4s

      24/50      10.1G      1.628       0.72     0.8972        125       1024: 12% ━─────────── 15/124 6.8it/s 2.4s<16.1s

      24/50      10.1G      1.625     0.7175     0.8956        116       1024: 13% ━╸────────── 16/124 6.7it/s 2.5s<16.0s

      24/50      10.1G      1.631     0.7194     0.8978        106       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      24/50      10.1G      1.638     0.7165     0.8996        125       1024: 15% ━╸────────── 18/124 6.8it/s 2.8s<15.5s

      24/50      10.1G       1.66      0.725     0.9042        117       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.2s

      24/50      10.1G      1.671     0.7275      0.905        118       1024: 16% ━╸────────── 20/124 6.6it/s 3.2s<15.7s

      24/50      10.1G      1.668     0.7288     0.9058         97       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

      24/50      10.1G      1.675     0.7327     0.9084        105       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      24/50      10.1G      1.677      0.736     0.9096        102       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

      24/50      10.1G      1.679     0.7372     0.9117        112       1024: 19% ━━────────── 24/124 6.8it/s 3.7s<14.8s

      24/50      10.1G      1.672     0.7378     0.9114        105       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.5s

      24/50      10.1G      1.676     0.7427     0.9122        120       1024: 21% ━━╸───────── 26/124 6.8it/s 4.0s<14.4s

      24/50      10.1G      1.685     0.7485     0.9144        111       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.9s

      24/50      10.1G      1.697     0.7533      0.917        131       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      24/50      10.1G      1.714     0.7589     0.9205        134       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.4s

      24/50      10.1G      1.718      0.758     0.9223        120       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

      24/50      10.1G      1.718     0.7593      0.923        109       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

      24/50      10.1G       1.72     0.7627     0.9228        112       1024: 26% ━━━───────── 32/124 6.8it/s 4.9s<13.6s

      24/50      10.1G      1.714     0.7616     0.9209        106       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      24/50      10.1G      1.715      0.763     0.9217        111       1024: 27% ━━━───────── 34/124 6.7it/s 5.2s<13.4s

      24/50      10.1G      1.724     0.7679     0.9247        121       1024: 28% ━━━───────── 35/124 6.4it/s 5.4s<13.8s

      24/50      10.1G      1.725     0.7661      0.926        110       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.6s

      24/50      10.1G      1.718     0.7655     0.9263        113       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.7s<13.2s

      24/50      10.1G      1.713     0.7643      0.925        109       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.9s

      24/50      10.1G      1.708     0.7626     0.9242        109       1024: 31% ━━━╸──────── 39/124 6.8it/s 6.0s<12.6s

      24/50      10.1G      1.707     0.7621     0.9241        110       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.1s<12.3s

      24/50      10.1G      1.707     0.7625      0.923        116       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.2s

      24/50      10.1G      1.708     0.7623     0.9248         97       1024: 34% ━━━━──────── 42/124 6.8it/s 6.4s<12.0s

      24/50      10.1G      1.702     0.7586     0.9231        112       1024: 35% ━━━━──────── 43/124 6.5it/s 6.6s<12.4s

      24/50      10.1G      1.701     0.7592     0.9243        124       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

      24/50      10.1G      1.702     0.7622     0.9264        105       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<12.1s

      24/50      10.1G        1.7     0.7613     0.9261        102       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      24/50      10.1G        1.7     0.7612     0.9275        110       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.2s<11.4s

      24/50      10.1G        1.7     0.7616     0.9269        123       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.3s<11.2s

      24/50      10.1G        1.7     0.7614     0.9269        121       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.1s

      24/50      10.1G      1.704     0.7613     0.9268        116       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.6s<10.9s

      24/50      10.1G      1.698     0.7599      0.926        107       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.3s

      24/50      10.1G      1.698     0.7606     0.9262        103       1024: 42% ━━━━━─────── 52/124 6.5it/s 8.0s<11.1s

      24/50      10.1G      1.696     0.7577     0.9263        109       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.1s<10.7s

      24/50      10.1G      1.693     0.7561     0.9258        106       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      24/50      10.1G      1.693      0.754     0.9258        111       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.2s

      24/50      10.1G      1.695     0.7549     0.9262        115       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      24/50      10.1G      1.697     0.7555     0.9268        125       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.8s

      24/50      10.1G      1.694     0.7538     0.9259        132       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.7s

      24/50      10.1G      1.693     0.7532     0.9266        101       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.0s<10.2s

      24/50      10.1G      1.696     0.7546     0.9271        117       1024: 48% ━━━━━╸────── 60/124 6.4it/s 9.2s<9.9s

      24/50      10.1G      1.696     0.7539     0.9269        114       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.3s<9.6s

      24/50      10.1G      1.693     0.7516     0.9257        115       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.3s

      24/50      10.1G      1.693     0.7522     0.9263        124       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.6s<9.2s

      24/50      10.1G      1.691      0.751      0.926        115       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<8.9s

      24/50      10.1G      1.691     0.7522     0.9252        110       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      24/50      10.1G      1.686     0.7501     0.9247        115       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.5s

      24/50      10.1G      1.686      0.751     0.9239        108       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.2s<8.8s

      24/50      10.1G      1.689     0.7521      0.924        127       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.5s

      24/50      10.1G      1.691     0.7516     0.9249        108       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.5s<8.2s

      24/50      10.1G      1.691     0.7515     0.9248        114       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      24/50      10.1G      1.691     0.7505     0.9245        114       1024: 57% ━━━━━━╸───── 71/124 6.8it/s 10.8s<7.8s

      24/50      10.1G       1.69     0.7505     0.9237        131       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.6s

      24/50      10.1G      1.691       0.75     0.9237        126       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      24/50      10.1G      1.694     0.7513     0.9238        123       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.4s

      24/50      10.1G      1.697     0.7506     0.9246        122       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.4s<7.6s

      24/50      10.1G      1.701     0.7506     0.9253        103       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.6s<7.3s

      24/50      10.1G        1.7     0.7494     0.9246        123       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.7s<7.1s

      24/50      10.1G      1.695     0.7478     0.9235        114       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.9s

      24/50      10.1G      1.697     0.7489     0.9235        126       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.0s<6.7s

      24/50      10.1G      1.699     0.7492      0.923        117       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.2s<6.5s

      24/50      10.1G        1.7     0.7482     0.9228        106       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.3s<6.3s

      24/50      10.1G      1.704     0.7487     0.9233        102       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.5s<6.2s

      24/50      10.1G      1.704     0.7481     0.9234        110       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.6s<6.3s

      24/50      10.1G      1.705      0.751     0.9232        103       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.8s<6.1s

      24/50      10.1G      1.706     0.7512     0.9237        119       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 12.9s<5.9s

      24/50      10.1G      1.706     0.7509     0.9239        121       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.7s

      24/50      10.1G      1.704     0.7496     0.9233        122       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.2s<5.5s

      24/50      10.1G      1.704     0.7496     0.9226        117       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.3s

      24/50      10.1G      1.705     0.7501      0.923        107       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.5s<5.2s

      24/50      10.1G      1.707     0.7516     0.9234         97       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.7s<5.0s

      24/50      10.1G      1.705       0.75     0.9237        107       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.8s<5.1s

      24/50      10.1G      1.706     0.7502     0.9238        121       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.0s<4.9s

      24/50      10.1G      1.705       0.75     0.9233        119       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.1s<4.7s

      24/50      10.1G      1.708     0.7507     0.9241        105       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.3s<4.5s

      24/50      10.1G      1.706     0.7505     0.9246         88       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.4s<4.3s

      24/50      10.1G      1.708     0.7505     0.9247        120       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.6s<4.1s

      24/50      10.1G      1.705     0.7489      0.924        104       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.7s<4.0s

      24/50      10.1G      1.705     0.7486     0.9238        125       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.9s<3.8s

      24/50      10.1G      1.705     0.7491     0.9244        116       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.1s<3.9s

      24/50      10.1G      1.707     0.7493      0.924        117       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.2s<3.7s

      24/50      10.1G      1.709     0.7496     0.9249        101       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.3s<3.5s

      24/50      10.1G      1.708     0.7497     0.9248        126       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

      24/50      10.1G      1.709     0.7495      0.925        102       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.6s<3.1s

      24/50      10.1G      1.708     0.7486     0.9246        108       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.8s<3.0s

      24/50      10.1G       1.71       0.75      0.925        114       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 15.9s<2.8s

      24/50      10.1G       1.71     0.7496      0.925        106       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.1s<2.6s

      24/50      10.1G       1.71     0.7498     0.9249        116       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.2s<2.6s

      24/50      10.1G      1.709     0.7495     0.9248         96       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.4s<2.4s

      24/50      10.1G       1.71     0.7497     0.9251        112       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.5s<2.2s

      24/50      10.1G      1.713     0.7496     0.9259        108       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

      24/50      10.1G      1.712     0.7488     0.9255         98       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.8s<1.9s

      24/50      10.1G      1.713     0.7484     0.9246        140       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.0s<1.8s

      24/50      10.1G      1.715     0.7491     0.9248        120       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.1s<1.6s

      24/50      10.1G      1.715     0.7491     0.9247         94       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.3s<1.5s

      24/50      10.1G      1.717     0.7496      0.925        121       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.5s<1.4s

      24/50      10.1G      1.718     0.7499     0.9247        121       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.6s<1.2s

      24/50      10.1G      1.716     0.7499     0.9244        104       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.7s<1.1s

      24/50      10.1G      1.715     0.7505     0.9247        104       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 17.9s<0.9s

      24/50      10.1G      1.715     0.7498     0.9246         99       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.0s<0.7s

      24/50      10.1G      1.714       0.75     0.9245        120       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.2s<0.6s

      24/50      10.1G      1.714     0.7496     0.9241        125       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.3s<0.4s

      24/50      10.1G      1.713     0.7495      0.924        103       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.5s<0.3s

      24/50      10.1G      1.712     0.7486     0.9238        105       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.7s<0.2s

      24/50      10.1G      1.712     0.7486     0.9238        105       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.655      0.598      0.619      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/50      10.1G      1.605     0.7966     0.9831        117       1024: 0% ──────────── 0/124  0.1s

      25/50      10.1G      1.721     0.7934     0.9931         84       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      25/50      10.1G      1.648     0.7577     0.9611        104       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.1s

      25/50      10.1G      1.738     0.7687     0.9681        125       1024: 2% ──────────── 3/124 4.5it/s 0.6s<27.0s

      25/50      10.1G      1.675     0.7382     0.9429        121       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.1s

      25/50      10.1G      1.719      0.757     0.9557        134       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.3s

      25/50      10.1G      1.723     0.7474     0.9445         99       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.8s

      25/50      10.1G      1.735     0.7573     0.9414        123       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.9s

      25/50      10.1G       1.71     0.7489     0.9332        116       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<19.0s

      25/50      10.1G      1.709     0.7439      0.933        117       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.2s

      25/50      10.1G        1.7     0.7472       0.93        120       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.6s

      25/50      10.1G      1.713     0.7566       0.93        121       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.2s

      25/50      10.1G      1.712     0.7562     0.9322        115       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.8s

      25/50      10.1G      1.711     0.7564      0.933        112       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.8s

      25/50      10.1G      1.712      0.759      0.932         91       1024: 11% ━─────────── 14/124 6.6it/s 2.2s<16.7s

      25/50      10.1G      1.694     0.7545     0.9273        107       1024: 12% ━─────────── 15/124 6.3it/s 2.4s<17.2s

      25/50      10.1G      1.701     0.7574      0.924        117       1024: 13% ━╸────────── 16/124 6.4it/s 2.6s<16.9s

      25/50      10.1G      1.688     0.7565     0.9216         98       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.5s

      25/50      10.1G      1.676     0.7525     0.9167        112       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.1s

      25/50      10.1G      1.673     0.7472     0.9168        108       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<15.8s

      25/50      10.1G      1.667     0.7403     0.9157        110       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.5s

      25/50      10.1G      1.667     0.7439     0.9155         95       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.3s

      25/50      10.1G      1.664     0.7409     0.9139        101       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      25/50      10.1G      1.657       0.74      0.912        107       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.9s

      25/50      10.1G      1.651     0.7378     0.9128        110       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

      25/50      10.1G      1.651     0.7391     0.9138        113       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      25/50      10.1G      1.649     0.7343     0.9137        107       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

      25/50      10.1G      1.652     0.7364     0.9138        123       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.5s

      25/50      10.1G      1.645     0.7317     0.9121        115       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.2s

      25/50      10.1G      1.649     0.7307     0.9112        105       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      25/50      10.1G      1.648     0.7297     0.9111        104       1024: 24% ━━╸───────── 30/124 6.8it/s 4.7s<13.9s

      25/50      10.1G      1.655     0.7329     0.9127         97       1024: 25% ━━━───────── 31/124 6.4it/s 4.9s<14.6s

      25/50      10.1G      1.666     0.7359     0.9163        113       1024: 26% ━━━───────── 32/124 6.4it/s 5.0s<14.3s

      25/50      10.1G      1.665     0.7341     0.9158         99       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.9s

      25/50      10.1G      1.672     0.7352     0.9178        118       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

      25/50      10.1G      1.674     0.7371     0.9193        138       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

      25/50      10.1G      1.673     0.7347     0.9184        122       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

      25/50      10.1G      1.668      0.732     0.9188        105       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<12.9s

      25/50      10.1G      1.677     0.7366     0.9208        111       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      25/50      10.1G      1.685     0.7388     0.9219        114       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.3s

      25/50      10.1G      1.692     0.7391     0.9251        119       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      25/50      10.1G      1.693     0.7382     0.9263        111       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.6s

      25/50      10.1G       1.69     0.7366     0.9248        119       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      25/50      10.1G      1.687     0.7346     0.9247        122       1024: 35% ━━━━──────── 43/124 6.7it/s 6.7s<12.1s

      25/50      10.1G      1.687     0.7323     0.9232        129       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

      25/50      10.1G      1.685     0.7352     0.9238        106       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      25/50      10.1G      1.691     0.7399     0.9249        119       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      25/50      10.1G      1.697     0.7431     0.9262        113       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<12.1s

      25/50      10.1G      1.699     0.7449     0.9276        115       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.4s<11.8s

      25/50      10.1G        1.7     0.7447     0.9275        114       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.6s<11.4s

      25/50      10.1G      1.699     0.7423     0.9266        134       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.1s

      25/50      10.1G      1.701     0.7434     0.9269        110       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<10.9s

      25/50      10.1G      1.701     0.7425     0.9277        111       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      25/50      10.1G      1.699     0.7427     0.9278        119       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.2s<10.5s

      25/50      10.1G      1.695     0.7415     0.9278        112       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      25/50      10.1G      1.696      0.742     0.9276        108       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.5s<10.7s

      25/50      10.1G      1.694     0.7405     0.9274        123       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      25/50      10.1G       1.69      0.738     0.9273        103       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

      25/50      10.1G       1.69     0.7387      0.929        125       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      25/50      10.1G      1.689     0.7362     0.9276        105       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.1s<9.6s

      25/50      10.1G      1.687     0.7357     0.9268        129       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.4s

      25/50      10.1G      1.689     0.7342     0.9269         97       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      25/50      10.1G      1.691     0.7348     0.9265        128       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      25/50      10.1G      1.689     0.7332     0.9254        111       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.7s<9.4s

      25/50      10.1G      1.694     0.7377     0.9257        120       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      25/50      10.1G      1.698     0.7381     0.9258        107       1024: 52% ━━━━━━────── 65/124 6.7it/s 10.0s<8.8s

      25/50      10.1G      1.697     0.7372     0.9257        111       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.6s

      25/50      10.1G      1.696      0.737      0.926        112       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.3s<8.4s

      25/50      10.1G      1.695     0.7369     0.9262        103       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.2s

      25/50      10.1G      1.696     0.7364     0.9257        114       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

      25/50      10.1G      1.695     0.7363     0.9261        106       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      25/50      10.1G      1.696     0.7362     0.9258        110       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.9s<8.2s

      25/50      10.1G      1.698     0.7363     0.9257        113       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

      25/50      10.1G      1.697     0.7354     0.9248        118       1024: 59% ━━━━━━━───── 73/124 6.5it/s 11.2s<7.8s

      25/50      10.1G      1.696     0.7338      0.924        122       1024: 60% ━━━━━━━───── 74/124 6.6it/s 11.3s<7.6s

      25/50      10.1G      1.696     0.7334     0.9247        121       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.5s<7.4s

      25/50      10.1G      1.694      0.733     0.9245        106       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.2s

      25/50      10.1G      1.697      0.735     0.9248        133       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.8s<7.0s

      25/50      10.1G      1.697     0.7352     0.9242        120       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<6.9s

      25/50      10.1G      1.696     0.7358     0.9241        121       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.1s<7.1s

      25/50      10.1G        1.7      0.736     0.9244        129       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.2s<6.8s

      25/50      10.1G      1.699      0.736     0.9248        123       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      25/50      10.1G      1.697     0.7352     0.9251         91       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      25/50      10.1G      1.696     0.7344     0.9256        106       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.7s<6.1s

      25/50      10.1G      1.694     0.7334     0.9257        110       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

      25/50      10.1G      1.696      0.734     0.9259        117       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.9s

      25/50      10.1G      1.697     0.7335     0.9256         98       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.1s<5.7s

      25/50      10.1G      1.699     0.7339     0.9254        113       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.8s

      25/50      10.1G      1.699     0.7344     0.9253        106       1024: 71% ━━━━━━━━╸─── 88/124 6.4it/s 13.5s<5.6s

      25/50      10.1G        1.7     0.7352     0.9256        114       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      25/50      10.1G      1.699     0.7351     0.9254        116       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.8s<5.1s

      25/50      10.1G        1.7     0.7361     0.9246        106       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

      25/50      10.1G      1.701     0.7357     0.9248        114       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.0s<4.7s

      25/50      10.1G      1.701     0.7361      0.925        110       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.2s<4.6s

      25/50      10.1G      1.703     0.7373     0.9246        113       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      25/50      10.1G        1.7     0.7364      0.924         98       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

      25/50      10.1G      1.702     0.7369     0.9251        106       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.7s<4.2s

      25/50      10.1G      1.703     0.7379     0.9247        119       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.8s<4.0s

      25/50      10.1G      1.704     0.7377     0.9247        112       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      25/50      10.1G      1.706     0.7382     0.9247        133       1024: 80% ━━━━━━━━━╸── 99/124 6.8it/s 15.1s<3.7s

      25/50      10.1G      1.705     0.7391     0.9248        111       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.2s<3.5s

      25/50      10.1G      1.708       0.74     0.9257         95       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.4s<3.4s

      25/50      10.1G      1.708     0.7399     0.9251        121       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

      25/50      10.1G      1.709     0.7406      0.925         99       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.7s<3.2s

      25/50      10.1G      1.711     0.7415     0.9246        106       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.9s<3.1s

      25/50      10.1G      1.709     0.7411     0.9243        108       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

      25/50      10.1G      1.712     0.7418     0.9249        115       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      25/50      10.1G      1.713     0.7423      0.925        132       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.3s<2.5s

      25/50      10.1G       1.71     0.7417     0.9249        109       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.4s<2.4s

      25/50      10.1G      1.708     0.7412     0.9242         99       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.6s<2.2s

      25/50      10.1G      1.709     0.7414     0.9245        117       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

      25/50      10.1G      1.708     0.7405     0.9244        114       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.9s<2.0s

      25/50      10.1G      1.707     0.7404     0.9246        103       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.1s<1.9s

      25/50      10.1G      1.707     0.7415     0.9245        127       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.2s<1.7s

      25/50      10.1G      1.712     0.7442     0.9248        129       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

      25/50      10.1G      1.712     0.7446      0.925        105       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

      25/50      10.1G      1.714     0.7449     0.9251        105       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.7s<1.2s

      25/50      10.1G      1.713     0.7454     0.9253        119       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.8s<1.0s

      25/50      10.1G      1.713     0.7458     0.9252        121       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      25/50      10.1G      1.715     0.7464     0.9253        107       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.1s<0.8s

      25/50      10.1G      1.714     0.7457     0.9249        125       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.3s<0.6s

      25/50      10.1G      1.718      0.747     0.9249        140       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.4s<0.5s

      25/50      10.1G      1.718     0.7472      0.925        109       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.6s<0.3s

      25/50      10.1G      1.715     0.7466     0.9247        101       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

      25/50      10.1G      1.715     0.7466     0.9247        101       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.672      0.621       0.64      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/50      10.1G      1.904     0.7167     0.9546        120       1024: 0% ──────────── 0/124  0.1s

      26/50      10.1G      1.855     0.7088     0.9668        111       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      26/50      10.1G      1.845     0.7216      0.964        117       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.0s

      26/50      10.1G      1.858      0.756     0.9574        100       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.5s

      26/50      10.1G      1.843     0.7632      0.962        120       1024: 3% ──────────── 4/124 5.0it/s 0.8s<24.2s

      26/50      10.1G       1.84     0.7626     0.9515        111       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.6s

      26/50      10.1G      1.768     0.7421     0.9391        119       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<19.9s

      26/50      10.1G      1.791     0.7523     0.9442        116       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

      26/50      10.1G       1.78     0.7513     0.9412        114       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.1s

      26/50      10.1G       1.76      0.749     0.9322        114       1024: 7% ╸─────────── 9/124 6.6it/s 1.5s<17.6s

      26/50      10.1G      1.763     0.7443     0.9319        126       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.2s

      26/50      10.1G      1.774     0.7482     0.9316         97       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.7s

      26/50      10.1G      1.756     0.7477     0.9322        101       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.1s

      26/50      10.1G      1.752     0.7536     0.9386        118       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.7s

      26/50      10.1G      1.737     0.7462     0.9356        115       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.4s

      26/50      10.1G      1.721     0.7365     0.9318         96       1024: 12% ━─────────── 15/124 6.8it/s 2.4s<16.1s

      26/50      10.1G       1.73     0.7438     0.9309        111       1024: 13% ━╸────────── 16/124 6.8it/s 2.5s<15.9s

      26/50      10.1G       1.72     0.7384     0.9275        108       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.6s

      26/50      10.1G      1.718     0.7378     0.9271        106       1024: 15% ━╸────────── 18/124 6.9it/s 2.8s<15.5s

      26/50      10.1G      1.722     0.7451     0.9265        120       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.0s

      26/50      10.1G      1.722     0.7468     0.9279        100       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.6s

      26/50      10.1G      1.722     0.7446     0.9249        127       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.3s

      26/50      10.1G      1.718     0.7427     0.9254        107       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.1s

      26/50      10.1G       1.71     0.7414      0.923        101       1024: 19% ━━────────── 23/124 6.8it/s 3.6s<14.8s

      26/50      10.1G      1.712     0.7403     0.9241        115       1024: 19% ━━────────── 24/124 6.8it/s 3.7s<14.6s

      26/50      10.1G      1.704      0.739     0.9224        119       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.5s

      26/50      10.1G      1.703     0.7389      0.921         93       1024: 21% ━━╸───────── 26/124 6.9it/s 4.0s<14.3s

      26/50      10.1G      1.695     0.7368      0.918        118       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.8s

      26/50      10.1G      1.698     0.7388     0.9182        109       1024: 23% ━━╸───────── 28/124 6.7it/s 4.3s<14.4s

      26/50      10.1G      1.694     0.7354       0.92         89       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

      26/50      10.1G      1.684     0.7341     0.9199        101       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.9s

      26/50      10.1G      1.688     0.7345     0.9188        120       1024: 25% ━━━───────── 31/124 6.8it/s 4.8s<13.7s

      26/50      10.1G      1.689     0.7381     0.9175        113       1024: 26% ━━━───────── 32/124 6.8it/s 4.9s<13.5s

      26/50      10.1G      1.686     0.7362     0.9168        124       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.3s

      26/50      10.1G       1.69     0.7365     0.9173        125       1024: 27% ━━━───────── 34/124 6.8it/s 5.2s<13.2s

      26/50      10.1G      1.692     0.7359     0.9189        103       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.6s

      26/50      10.1G      1.687     0.7343     0.9177        120       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.2s

      26/50      10.1G      1.681     0.7335     0.9158         97       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<12.9s

      26/50      10.1G      1.675     0.7291     0.9135        109       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.7s

      26/50      10.1G      1.671     0.7264     0.9156         89       1024: 31% ━━━╸──────── 39/124 6.8it/s 6.0s<12.5s

      26/50      10.1G      1.676     0.7277     0.9166        124       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.1s<12.3s

      26/50      10.1G      1.678     0.7307     0.9155        121       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.1s

      26/50      10.1G      1.685      0.732     0.9173        132       1024: 34% ━━━━──────── 42/124 6.8it/s 6.4s<12.0s

      26/50      10.1G      1.679     0.7294      0.916        113       1024: 35% ━━━━──────── 43/124 6.5it/s 6.6s<12.4s

      26/50      10.1G       1.68     0.7313     0.9163        114       1024: 35% ━━━━──────── 44/124 6.6it/s 6.7s<12.2s

      26/50      10.1G      1.683     0.7333      0.917        126       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<11.9s

      26/50      10.1G      1.682      0.731     0.9161        113       1024: 37% ━━━━──────── 46/124 6.7it/s 7.0s<11.6s

      26/50      10.1G      1.683     0.7308     0.9156         98       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.2s<11.4s

      26/50      10.1G      1.682     0.7285      0.916        126       1024: 39% ━━━━╸─────── 48/124 6.7it/s 7.3s<11.3s

      26/50      10.1G      1.678      0.727      0.915        114       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.1s

      26/50      10.1G      1.681     0.7272      0.915        120       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.6s<10.9s

      26/50      10.1G      1.682      0.729     0.9157        107       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.2s

      26/50      10.1G       1.68     0.7275     0.9159        116       1024: 42% ━━━━━─────── 52/124 6.5it/s 7.9s<11.0s

      26/50      10.1G      1.681     0.7268      0.916        123       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.1s<10.8s

      26/50      10.1G      1.681     0.7267     0.9169        102       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.2s<10.5s

      26/50      10.1G      1.678     0.7254      0.917        108       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.4s<10.2s

      26/50      10.1G      1.673      0.722     0.9155        107       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.5s<10.0s

      26/50      10.1G      1.671     0.7204     0.9156        122       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.9s

      26/50      10.1G       1.67     0.7196     0.9157        130       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.7s

      26/50      10.1G      1.667     0.7197     0.9149        117       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.0s<10.0s

      26/50      10.1G      1.665     0.7197     0.9147        126       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.1s<9.7s

      26/50      10.1G      1.664     0.7184     0.9142        127       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.4s

      26/50      10.1G      1.667     0.7191     0.9142        133       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.4s<9.2s

      26/50      10.1G      1.669     0.7202     0.9144         96       1024: 51% ━━━━━━────── 63/124 6.8it/s 9.6s<9.0s

      26/50      10.1G      1.668     0.7203     0.9144        119       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.7s<8.9s

      26/50      10.1G      1.664     0.7188     0.9137        102       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      26/50      10.1G      1.664     0.7187     0.9139        108       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.0s<8.5s

      26/50      10.1G      1.665     0.7201     0.9144        109       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.2s<8.9s

      26/50      10.1G      1.663      0.719     0.9143        102       1024: 55% ━━━━━━╸───── 68/124 6.4it/s 10.3s<8.8s

      26/50      10.1G      1.668     0.7216     0.9151        126       1024: 56% ━━━━━━╸───── 69/124 6.5it/s 10.5s<8.4s

      26/50      10.1G      1.668     0.7223     0.9149        110       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.6s<8.2s

      26/50      10.1G      1.668      0.721     0.9149         99       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.8s<8.0s

      26/50      10.1G      1.669     0.7196     0.9148        116       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 10.9s<7.7s

      26/50      10.1G      1.671     0.7194     0.9149        121       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      26/50      10.1G      1.673     0.7216     0.9151        112       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.2s<7.5s

      26/50      10.1G      1.673     0.7216     0.9149        118       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.4s<7.6s

      26/50      10.1G      1.672     0.7214     0.9151        121       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

      26/50      10.1G      1.671     0.7206     0.9148        118       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.7s<7.1s

      26/50      10.1G      1.673     0.7224     0.9148        127       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.8s<6.9s

      26/50      10.1G      1.676     0.7227     0.9154        119       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.0s<6.7s

      26/50      10.1G      1.678     0.7233     0.9153        132       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.1s<6.5s

      26/50      10.1G      1.678     0.7224     0.9158        109       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.3s<6.3s

      26/50      10.1G      1.677      0.721     0.9151        117       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.4s<6.1s

      26/50      10.1G      1.678     0.7217     0.9147        113       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.6s<6.3s

      26/50      10.1G      1.677     0.7215     0.9143        109       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.8s<6.1s

      26/50      10.1G       1.68     0.7218     0.9162        105       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 12.9s<6.0s

      26/50      10.1G      1.685     0.7249     0.9173        115       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.7s

      26/50      10.1G      1.687     0.7252     0.9174         98       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.2s<5.5s

      26/50      10.1G      1.687      0.725     0.9175        107       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.3s<5.4s

      26/50      10.1G      1.683     0.7235     0.9176        107       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.3s

      26/50      10.1G      1.682     0.7227     0.9171        110       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.6s<5.1s

      26/50      10.1G      1.683     0.7235     0.9173        124       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 13.8s<5.1s

      26/50      10.1G      1.683     0.7239     0.9172        109       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.0s<4.9s

      26/50      10.1G      1.689     0.7265     0.9175        120       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

      26/50      10.1G      1.692     0.7272     0.9175        116       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.2s<4.4s

      26/50      10.1G      1.694     0.7279     0.9182        125       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 14.4s<4.3s

      26/50      10.1G      1.692     0.7272     0.9184        119       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.5s<4.1s

      26/50      10.1G      1.693     0.7281     0.9185        113       1024: 78% ━━━━━━━━━─── 97/124 6.9it/s 14.7s<3.9s

      26/50      10.1G      1.693     0.7288     0.9187         92       1024: 79% ━━━━━━━━━─── 98/124 6.9it/s 14.8s<3.8s

      26/50      10.1G      1.694     0.7291     0.9187        122       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.0s<3.8s

      26/50      10.1G      1.693     0.7295     0.9189        119       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.1s<3.6s

      26/50      10.1G      1.694     0.7289     0.9189        110       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.3s<3.5s

      26/50      10.1G      1.695     0.7297      0.919        116       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.4s<3.3s

      26/50      10.1G      1.695     0.7293     0.9184        103       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.6s<3.1s

      26/50      10.1G      1.695       0.73     0.9185        111       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.7s<2.9s

      26/50      10.1G      1.692     0.7285     0.9179        106       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.8s

      26/50      10.1G      1.692     0.7287     0.9178        113       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.0s<2.7s

      26/50      10.1G      1.689     0.7279     0.9171        109       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.2s<2.6s

      26/50      10.1G       1.69     0.7278     0.9173        113       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.4s<2.5s

      26/50      10.1G      1.689     0.7278     0.9171        107       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.5s<2.3s

      26/50      10.1G      1.691     0.7285     0.9173        121       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.6s<2.1s

      26/50      10.1G       1.69     0.7278     0.9171        114       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.8s<1.9s

      26/50      10.1G       1.69      0.728      0.917        106       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 16.9s<1.8s

      26/50      10.1G      1.691     0.7287     0.9171        113       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.1s<1.6s

      26/50      10.1G       1.69     0.7283     0.9171        109       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.2s<1.5s

      26/50      10.1G      1.689     0.7284     0.9165        117       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.4s<1.4s

      26/50      10.1G       1.69     0.7281     0.9166        104       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.6s<1.2s

      26/50      10.1G      1.692     0.7296     0.9172        112       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.7s<1.1s

      26/50      10.1G      1.691     0.7297     0.9169        116       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 17.9s<0.9s

      26/50      10.1G      1.691       0.73     0.9167        131       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.0s<0.8s

      26/50      10.1G      1.692     0.7303      0.916        118       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.2s<0.6s

      26/50      10.1G      1.692     0.7317     0.9162        117       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.3s<0.4s

      26/50      10.1G      1.692     0.7307      0.916        116       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.5s<0.3s

      26/50      10.1G      1.694     0.7315     0.9163        130       1024: 99% ━━━━━━━━━━━╸ 123/124 6.3it/s 18.6s<0.2s

      26/50      10.1G      1.694     0.7315     0.9163        130       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.1it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.5it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.666      0.623      0.628       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/50      10.1G       1.74     0.7423      0.947        110       1024: 0% ──────────── 0/124  0.1s

      27/50      10.1G       1.73     0.7171     0.9616        106       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.8s

      27/50      10.1G      1.688     0.7061     0.9326        102       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      27/50      10.1G      1.685     0.6997      0.925        131       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.9s

      27/50      10.1G      1.684     0.6971     0.9134        121       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.5s

      27/50      10.1G      1.711     0.7126     0.9062        127       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.2s

      27/50      10.1G      1.695     0.6962     0.9184         98       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

      27/50      10.1G      1.698     0.6914     0.9147        105       1024: 6% ╸─────────── 7/124 5.8it/s 1.2s<20.1s

      27/50      10.1G      1.698     0.6908     0.9198        112       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<18.9s

      27/50      10.1G      1.698     0.6911     0.9199        126       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.1s

      27/50      10.1G      1.673     0.6822     0.9146        124       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.5s

      27/50      10.1G      1.664     0.6775     0.9106        133       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.1s

      27/50      10.1G      1.661      0.677     0.9098        105       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.8s

      27/50      10.1G       1.67     0.6769     0.9068        119       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      27/50      10.1G      1.696     0.6888     0.9144        106       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.2s

      27/50      10.1G      1.715      0.695     0.9139        107       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.9s

      27/50      10.1G       1.71      0.689     0.9123        115       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.4s

      27/50      10.1G      1.735     0.6978     0.9175         96       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      27/50      10.1G      1.721     0.6997     0.9134        103       1024: 15% ━╸────────── 18/124 6.7it/s 2.8s<15.8s

      27/50      10.1G      1.722     0.7016     0.9139        116       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

      27/50      10.1G      1.722      0.706     0.9132        135       1024: 16% ━╸────────── 20/124 6.8it/s 3.1s<15.3s

      27/50      10.1G      1.721     0.7064     0.9131        126       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.1s

      27/50      10.1G      1.721     0.7076     0.9115        109       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<14.9s

      27/50      10.1G      1.728     0.7118     0.9154        130       1024: 19% ━━────────── 23/124 6.5it/s 3.6s<15.5s

      27/50      10.1G      1.713     0.7073     0.9132        100       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

      27/50      10.1G      1.705     0.7053     0.9118        126       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<14.9s

      27/50      10.1G      1.696     0.6994     0.9095        115       1024: 21% ━━╸───────── 26/124 6.7it/s 4.0s<14.6s

      27/50      10.1G      1.695     0.6984     0.9084        115       1024: 22% ━━╸───────── 27/124 6.8it/s 4.2s<14.4s

      27/50      10.1G      1.698     0.7018     0.9092        127       1024: 23% ━━╸───────── 28/124 6.8it/s 4.3s<14.2s

      27/50      10.1G      1.694     0.7022     0.9107        100       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      27/50      10.1G      1.694     0.7029     0.9099        116       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      27/50      10.1G       1.69     0.7002     0.9111        119       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.4s

      27/50      10.1G       1.69     0.7022     0.9108         94       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.1s

      27/50      10.1G       1.69     0.7035     0.9116        116       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

      27/50      10.1G      1.693     0.7069     0.9107        106       1024: 27% ━━━───────── 34/124 6.7it/s 5.2s<13.5s

      27/50      10.1G       1.69     0.7066     0.9104        128       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.2s

      27/50      10.1G      1.684     0.7055     0.9113        114       1024: 29% ━━━───────── 36/124 6.8it/s 5.5s<13.0s

      27/50      10.1G      1.689     0.7097      0.912        112       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      27/50      10.1G      1.689     0.7103     0.9118        109       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.6s

      27/50      10.1G      1.689     0.7107       0.91        110       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

      27/50      10.1G      1.684     0.7101     0.9085        114       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

      27/50      10.1G      1.689     0.7125     0.9092        118       1024: 33% ━━━╸──────── 41/124 6.5it/s 6.3s<12.7s

      27/50      10.1G      1.689     0.7126     0.9097        116       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.4s

      27/50      10.1G      1.691     0.7147     0.9095        105       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

      27/50      10.1G      1.696     0.7193      0.912        100       1024: 35% ━━━━──────── 44/124 6.6it/s 6.8s<12.1s

      27/50      10.1G        1.7     0.7202     0.9128        108       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<11.9s

      27/50      10.1G      1.702     0.7208     0.9137        124       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      27/50      10.1G      1.703     0.7212     0.9137        117       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.2s<12.0s

      27/50      10.1G      1.703      0.723     0.9152         97       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.6s

      27/50      10.1G      1.697     0.7202     0.9147        105       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.3s

      27/50      10.1G      1.695       0.72     0.9162         91       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      27/50      10.1G      1.695     0.7222     0.9149        116       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.8s

      27/50      10.1G      1.694     0.7223     0.9146        124       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.0s<10.6s

      27/50      10.1G      1.695     0.7214      0.915        117       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

      27/50      10.1G      1.692     0.7199      0.914        107       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

      27/50      10.1G      1.695     0.7211     0.9157        112       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

      27/50      10.1G      1.697     0.7206      0.916        113       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      27/50      10.1G      1.698     0.7201     0.9152        123       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

      27/50      10.1G      1.696     0.7199     0.9153        108       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      27/50      10.1G      1.694     0.7202      0.915        102       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

      27/50      10.1G      1.696     0.7218     0.9163        107       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.5s

      27/50      10.1G      1.696     0.7214     0.9162        125       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.4s

      27/50      10.1G      1.697     0.7217      0.917         98       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.5s<9.4s

      27/50      10.1G      1.694     0.7207     0.9168        110       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.6s<9.6s

      27/50      10.1G      1.693     0.7203     0.9168        100       1024: 52% ━━━━━━────── 64/124 6.4it/s 9.8s<9.3s

      27/50      10.1G      1.691     0.7211     0.9162        111       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<9.0s

      27/50      10.1G      1.692     0.7223     0.9166        108       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.1s<8.8s

      27/50      10.1G      1.689     0.7213     0.9159         93       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.2s<8.6s

      27/50      10.1G       1.69     0.7232     0.9158        111       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.4s<8.4s

      27/50      10.1G      1.692     0.7246     0.9166        109       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.5s<8.2s

      27/50      10.1G       1.69     0.7237     0.9166        113       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      27/50      10.1G      1.689     0.7227     0.9166        100       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.9s<8.3s

      27/50      10.1G      1.687     0.7217     0.9168        112       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

      27/50      10.1G       1.69     0.7232     0.9166        126       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      27/50      10.1G       1.69     0.7223     0.9167        114       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

      27/50      10.1G       1.69     0.7219     0.9164        108       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.3s

      27/50      10.1G       1.69     0.7209     0.9159        106       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      27/50      10.1G       1.69      0.722     0.9155        115       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

      27/50      10.1G      1.688     0.7215     0.9158        119       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

      27/50      10.1G      1.689     0.7207      0.916        100       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.1s<6.9s

      27/50      10.1G      1.687     0.7203     0.9154        118       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.7s

      27/50      10.1G      1.689     0.7213     0.9162        107       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.3s<6.4s

      27/50      10.1G      1.688      0.721     0.9153        128       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.2s

      27/50      10.1G      1.687     0.7206     0.9157        131       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.6s<6.1s

      27/50      10.1G       1.69     0.7219     0.9167        111       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

      27/50      10.1G      1.689     0.7215     0.9167        105       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.9s<5.8s

      27/50      10.1G      1.687     0.7212     0.9159        110       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      27/50      10.1G      1.686     0.7214     0.9153         97       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.3s<5.7s

      27/50      10.1G      1.686     0.7223     0.9163        113       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.5s

      27/50      10.1G      1.683     0.7217     0.9156        108       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.5s<5.3s

      27/50      10.1G      1.683     0.7221     0.9153        114       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      27/50      10.1G      1.683     0.7214     0.9153        121       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.8s<4.9s

      27/50      10.1G      1.682     0.7212     0.9154        123       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

      27/50      10.1G      1.684     0.7216     0.9154        117       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

      27/50      10.1G      1.682     0.7213     0.9151        108       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      27/50      10.1G      1.681     0.7212     0.9152        110       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

      27/50      10.1G      1.682     0.7208     0.9158        125       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.6s<4.3s

      27/50      10.1G      1.681     0.7201     0.9151        110       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

      27/50      10.1G      1.683     0.7202     0.9156        116       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      27/50      10.1G      1.683     0.7209     0.9161        106       1024: 80% ━━━━━━━━━╸── 99/124 6.6it/s 15.1s<3.8s

      27/50      10.1G      1.682      0.721     0.9158        102       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.2s<3.6s

      27/50      10.1G      1.684     0.7215     0.9158        118       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.3s<3.4s

      27/50      10.1G       1.68     0.7201     0.9155        112       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

      27/50      10.1G      1.684     0.7211     0.9153        131       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

      27/50      10.1G      1.685     0.7215     0.9152        130       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.8s<3.0s

      27/50      10.1G      1.682     0.7206     0.9145        109       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

      27/50      10.1G       1.68     0.7216     0.9144        113       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      27/50      10.1G      1.679     0.7208     0.9143        109       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.3s<2.6s

      27/50      10.1G      1.679     0.7199     0.9141        127       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      27/50      10.1G      1.678     0.7188     0.9136        130       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

      27/50      10.1G       1.68       0.72     0.9142        102       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

      27/50      10.1G       1.68     0.7196     0.9145        118       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

      27/50      10.1G      1.678     0.7193     0.9141        111       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.0s<1.8s

      27/50      10.1G      1.677     0.7196     0.9143         94       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 17.2s<1.7s

      27/50      10.1G      1.679     0.7195     0.9141        114       1024: 92% ━━━━━━━━━━━─ 114/124 6.6it/s 17.3s<1.5s

      27/50      10.1G      1.681     0.7201     0.9147        113       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.4s

      27/50      10.1G      1.683     0.7212     0.9147        123       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.6s<1.2s

      27/50      10.1G      1.682     0.7213     0.9148        107       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.8s<1.1s

      27/50      10.1G      1.682     0.7213     0.9152        117       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 17.9s<0.9s

      27/50      10.1G      1.683     0.7215     0.9152        121       1024: 96% ━━━━━━━━━━━╸ 119/124 6.3it/s 18.1s<0.8s

      27/50      10.1G      1.684     0.7224     0.9159        108       1024: 97% ━━━━━━━━━━━╸ 120/124 6.4it/s 18.3s<0.6s

      27/50      10.1G      1.684     0.7224     0.9156        101       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.4s<0.5s

      27/50      10.1G      1.684     0.7219     0.9159        109       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.6s<0.3s

      27/50      10.1G      1.683     0.7213     0.9157        116       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

      27/50      10.1G      1.683     0.7213     0.9157        116       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.683      0.615      0.634      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/50      10.1G      1.825     0.8818     0.9169        111       1024: 0% ──────────── 0/124  0.1s

      28/50      10.1G      1.723     0.8161     0.9067        120       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.6s

      28/50      10.1G      1.822     0.8179     0.9267        110       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.7s

      28/50      10.1G      1.759     0.8022     0.9142        102       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.5s

      28/50      10.1G      1.764     0.8043     0.9377        107       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.3s

      28/50      10.1G      1.793     0.7983     0.9544        123       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.6s

      28/50      10.1G      1.798     0.7955     0.9539        102       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.0s

      28/50      10.1G      1.804      0.787     0.9505        120       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

      28/50      10.1G      1.766     0.7658     0.9409        113       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.2s

      28/50      10.1G      1.784     0.7823     0.9404        104       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.6s

      28/50      10.1G       1.78      0.775     0.9399        114       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.4s

      28/50      10.1G      1.769     0.7658     0.9395        106       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      28/50      10.1G      1.744     0.7585     0.9359         90       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.3s

      28/50      10.1G      1.716     0.7522     0.9331        103       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.0s

      28/50      10.1G      1.697     0.7416     0.9282        112       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      28/50      10.1G      1.686     0.7338      0.926        105       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.3s

      28/50      10.1G      1.687     0.7356      0.923         96       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      28/50      10.1G        1.7     0.7434     0.9234        135       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      28/50      10.1G        1.7     0.7397     0.9224        115       1024: 15% ━╸────────── 18/124 6.8it/s 2.8s<15.6s

      28/50      10.1G      1.704     0.7412     0.9227        108       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.2s

      28/50      10.1G      1.696     0.7366     0.9226         95       1024: 16% ━╸────────── 20/124 6.6it/s 3.2s<15.7s

      28/50      10.1G      1.695     0.7408     0.9246        117       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      28/50      10.1G      1.689     0.7355     0.9211        114       1024: 18% ━━────────── 22/124 6.8it/s 3.5s<15.1s

      28/50      10.1G      1.689     0.7385     0.9217        108       1024: 19% ━━────────── 23/124 6.8it/s 3.6s<14.8s

      28/50      10.1G       1.68     0.7344     0.9226        111       1024: 19% ━━────────── 24/124 6.8it/s 3.7s<14.6s

      28/50      10.1G      1.674     0.7323     0.9212        110       1024: 20% ━━────────── 25/124 6.9it/s 3.9s<14.4s

      28/50      10.1G      1.666     0.7286     0.9206        110       1024: 21% ━━╸───────── 26/124 6.9it/s 4.0s<14.2s

      28/50      10.1G      1.663     0.7243      0.921        102       1024: 22% ━━╸───────── 27/124 6.6it/s 4.2s<14.7s

      28/50      10.1G      1.666     0.7257     0.9199        116       1024: 23% ━━╸───────── 28/124 6.7it/s 4.3s<14.3s

      28/50      10.1G      1.665     0.7244     0.9202        115       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      28/50      10.1G      1.653     0.7185     0.9173         99       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      28/50      10.1G      1.659     0.7178     0.9171        121       1024: 25% ━━━───────── 31/124 6.9it/s 4.8s<13.6s

      28/50      10.1G      1.664       0.72     0.9169        135       1024: 26% ━━━───────── 32/124 6.9it/s 4.9s<13.4s

      28/50      10.1G       1.66     0.7204     0.9144        100       1024: 27% ━━━───────── 33/124 6.9it/s 5.1s<13.2s

      28/50      10.1G      1.659     0.7198     0.9144        105       1024: 27% ━━━───────── 34/124 6.9it/s 5.2s<13.1s

      28/50      10.1G      1.668     0.7241     0.9156        130       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.7s

      28/50      10.1G      1.671     0.7247     0.9181        115       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.4s

      28/50      10.1G      1.671     0.7256     0.9198        109       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

      28/50      10.1G      1.675     0.7257     0.9184        120       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.7s

      28/50      10.1G      1.671     0.7278     0.9174        106       1024: 31% ━━━╸──────── 39/124 6.8it/s 6.0s<12.5s

      28/50      10.1G      1.664     0.7249     0.9167        106       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.1s<12.3s

      28/50      10.1G      1.664      0.724     0.9159        110       1024: 33% ━━━╸──────── 41/124 6.9it/s 6.3s<12.1s

      28/50      10.1G      1.678     0.7274      0.916        134       1024: 34% ━━━━──────── 42/124 6.9it/s 6.4s<11.9s

      28/50      10.1G       1.68     0.7267     0.9177        110       1024: 35% ━━━━──────── 43/124 6.6it/s 6.6s<12.3s

      28/50      10.1G      1.678     0.7254     0.9185        117       1024: 35% ━━━━──────── 44/124 6.7it/s 6.7s<11.9s

      28/50      10.1G      1.676     0.7231     0.9179        119       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      28/50      10.1G      1.678     0.7219     0.9194        117       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.4s

      28/50      10.1G      1.677     0.7208     0.9179        119       1024: 38% ━━━━╸─────── 47/124 6.9it/s 7.1s<11.2s

      28/50      10.1G       1.68     0.7207     0.9182        124       1024: 39% ━━━━╸─────── 48/124 6.9it/s 7.3s<11.0s

      28/50      10.1G      1.681     0.7195      0.919        106       1024: 40% ━━━━╸─────── 49/124 6.9it/s 7.4s<10.9s

      28/50      10.1G      1.676     0.7171     0.9177        102       1024: 40% ━━━━╸─────── 50/124 6.9it/s 7.6s<10.7s

      28/50      10.1G      1.672     0.7151     0.9163        113       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.2s

      28/50      10.1G      1.668     0.7132     0.9159        109       1024: 42% ━━━━━─────── 52/124 6.5it/s 7.9s<11.0s

      28/50      10.1G      1.665     0.7119     0.9152        116       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.1s<10.8s

      28/50      10.1G      1.662     0.7111     0.9161        113       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.2s<10.5s

      28/50      10.1G      1.664       0.71     0.9163        106       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.4s<10.2s

      28/50      10.1G      1.664     0.7113     0.9168        111       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.5s<10.0s

      28/50      10.1G      1.663     0.7131      0.917        109       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.6s<9.8s

      28/50      10.1G      1.665     0.7129     0.9175        118       1024: 47% ━━━━━╸────── 58/124 6.9it/s 8.8s<9.6s

      28/50      10.1G      1.673     0.7158     0.9186        128       1024: 48% ━━━━━╸────── 59/124 6.6it/s 9.0s<9.9s

      28/50      10.1G      1.671      0.715     0.9199        118       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.1s<9.6s

      28/50      10.1G      1.674     0.7163       0.92        127       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.2s<9.3s

      28/50      10.1G       1.67     0.7135     0.9197        117       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.4s<9.1s

      28/50      10.1G      1.667     0.7124     0.9197        119       1024: 51% ━━━━━━────── 63/124 6.9it/s 9.5s<8.9s

      28/50      10.1G      1.663     0.7117     0.9186        110       1024: 52% ━━━━━━────── 64/124 6.9it/s 9.7s<8.7s

      28/50      10.1G      1.666     0.7129     0.9189        117       1024: 52% ━━━━━━────── 65/124 6.9it/s 9.8s<8.6s

      28/50      10.1G      1.665     0.7124      0.918        109       1024: 53% ━━━━━━────── 66/124 6.9it/s 10.0s<8.4s

      28/50      10.1G      1.666     0.7123     0.9178        115       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.1s<8.7s

      28/50      10.1G      1.666     0.7114     0.9176        127       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.3s<8.5s

      28/50      10.1G      1.667     0.7129     0.9182        108       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.4s<8.2s

      28/50      10.1G      1.663     0.7105     0.9165        123       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.6s<8.0s

      28/50      10.1G      1.662     0.7101     0.9163        116       1024: 57% ━━━━━━╸───── 71/124 6.8it/s 10.7s<7.8s

      28/50      10.1G      1.662     0.7094     0.9158        126       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 10.9s<7.7s

      28/50      10.1G      1.662     0.7092     0.9158        106       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.0s<7.5s

      28/50      10.1G      1.664       0.71      0.916        106       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.2s<7.3s

      28/50      10.1G      1.663     0.7099     0.9162        108       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.3s<7.5s

      28/50      10.1G      1.663       0.71     0.9161         94       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.5s<7.2s

      28/50      10.1G      1.665     0.7106      0.916        107       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.6s<7.0s

      28/50      10.1G      1.663     0.7104     0.9158        120       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.8s<6.8s

      28/50      10.1G      1.664      0.711     0.9157        126       1024: 64% ━━━━━━━╸──── 79/124 6.8it/s 11.9s<6.6s

      28/50      10.1G      1.663     0.7111     0.9164        117       1024: 65% ━━━━━━━╸──── 80/124 6.9it/s 12.1s<6.4s

      28/50      10.1G      1.663     0.7101     0.9164        112       1024: 65% ━━━━━━━╸──── 81/124 6.9it/s 12.2s<6.2s

      28/50      10.1G      1.665     0.7099     0.9167        102       1024: 66% ━━━━━━━╸──── 82/124 6.9it/s 12.3s<6.1s

      28/50      10.1G      1.669      0.711     0.9168        127       1024: 67% ━━━━━━━━──── 83/124 6.6it/s 12.5s<6.2s

      28/50      10.1G      1.671     0.7117     0.9169        120       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 12.7s<6.0s

      28/50      10.1G      1.671     0.7106     0.9171        111       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.8s<5.7s

      28/50      10.1G       1.67     0.7102     0.9169        128       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 12.9s<5.6s

      28/50      10.1G       1.67     0.7106     0.9169        109       1024: 70% ━━━━━━━━──── 87/124 6.9it/s 13.1s<5.4s

      28/50      10.1G      1.672     0.7106     0.9172        130       1024: 71% ━━━━━━━━╸─── 88/124 6.9it/s 13.2s<5.2s

      28/50      10.1G      1.671      0.711     0.9169        108       1024: 72% ━━━━━━━━╸─── 89/124 6.9it/s 13.4s<5.1s

      28/50      10.1G      1.669     0.7102     0.9165        103       1024: 73% ━━━━━━━━╸─── 90/124 6.9it/s 13.5s<4.9s

      28/50      10.1G      1.672      0.711     0.9166        110       1024: 73% ━━━━━━━━╸─── 91/124 6.6it/s 13.7s<5.0s

      28/50      10.1G       1.67     0.7101     0.9162        124       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 13.8s<4.8s

      28/50      10.1G       1.67     0.7097     0.9162        139       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.0s<4.6s

      28/50      10.1G      1.671     0.7089     0.9159        110       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.1s<4.4s

      28/50      10.1G       1.67     0.7076      0.916         98       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 14.3s<4.2s

      28/50      10.1G      1.669      0.708     0.9156        116       1024: 77% ━━━━━━━━━─── 96/124 6.9it/s 14.4s<4.1s

      28/50      10.1G       1.67      0.709     0.9156        135       1024: 78% ━━━━━━━━━─── 97/124 6.9it/s 14.6s<3.9s

      28/50      10.1G      1.666     0.7072     0.9151         99       1024: 79% ━━━━━━━━━─── 98/124 6.9it/s 14.7s<3.8s

      28/50      10.1G      1.665     0.7078     0.9143        117       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 14.9s<3.9s

      28/50      10.1G      1.669     0.7085     0.9145        105       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.0s<3.7s

      28/50      10.1G      1.669     0.7095     0.9153        102       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.2s<3.5s

      28/50      10.1G       1.67     0.7101     0.9146        122       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.3s<3.3s

      28/50      10.1G      1.678     0.7147      0.917        125       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.5s<3.1s

      28/50      10.1G      1.679      0.714     0.9173        123       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.6s<3.0s

      28/50      10.1G      1.677      0.713     0.9176         96       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.8s<2.8s

      28/50      10.1G      1.676     0.7127     0.9171        109       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 15.9s<2.7s

      28/50      10.1G      1.677     0.7129     0.9168        120       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.1s<2.6s

      28/50      10.1G      1.676      0.713     0.9163         98       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.2s<2.4s

      28/50      10.1G      1.676     0.7127     0.9169         98       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.4s<2.3s

      28/50      10.1G      1.675     0.7124     0.9163        110       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.5s<2.1s

      28/50      10.1G      1.675     0.7118     0.9161        115       1024: 90% ━━━━━━━━━━╸─ 111/124 6.6it/s 16.7s<2.0s

      28/50      10.1G      1.678     0.7131     0.9163        138       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 16.8s<1.8s

      28/50      10.1G      1.678     0.7128     0.9161        126       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.0s<1.6s

      28/50      10.1G       1.68     0.7135     0.9165        101       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.1s<1.5s

      28/50      10.1G      1.679     0.7128     0.9162        110       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.3s<1.4s

      28/50      10.1G      1.677     0.7124      0.916        102       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.5s<1.2s

      28/50      10.1G      1.678     0.7133     0.9157        121       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.6s<1.1s

      28/50      10.1G      1.678     0.7136     0.9156        118       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 17.7s<0.9s

      28/50      10.1G      1.677     0.7131     0.9152        126       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 17.9s<0.8s

      28/50      10.1G      1.677     0.7131     0.9157         89       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.0s<0.6s

      28/50      10.1G      1.676     0.7123     0.9157        128       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.2s<0.4s

      28/50      10.1G      1.678     0.7124     0.9156        126       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.3s<0.3s

      28/50      10.1G      1.677     0.7122     0.9153        109       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 18.5s<0.2s

      28/50      10.1G      1.677     0.7122     0.9153        109       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.7it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.4it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.5it/s 0.8s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 7.9it/s 1.0s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.0it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.0it/s 1.2s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.1it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.2it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.2it/s 1.6s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.2it/s 1.7s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.3it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.3it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.2s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.4it/s 2.5s

                   all        330       4227      0.672      0.622      0.626      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/50      10.1G      1.521     0.7147     0.9155        115       1024: 0% ──────────── 0/124  0.1s

      29/50      10.1G      1.655     0.7159     0.9478        105       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.1s

      29/50      10.1G      1.624     0.7068     0.9114        114       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      29/50      10.1G       1.62      0.688     0.9072        113       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.9s

      29/50      10.1G       1.64      0.683     0.9158        109       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.0s

      29/50      10.1G      1.634     0.6832     0.9045        112       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.8s

      29/50      10.1G      1.632     0.6755     0.9041        126       1024: 5% ╸─────────── 6/124 6.1it/s 1.0s<19.4s

      29/50      10.1G      1.601     0.6851     0.9024        117       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.5s

      29/50      10.1G      1.591     0.6762     0.8975        134       1024: 6% ╸─────────── 8/124 6.2it/s 1.3s<18.8s

      29/50      10.1G      1.594     0.6753     0.8934        125       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.3s

      29/50      10.1G      1.615     0.6796     0.8932        106       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.6s

      29/50      10.1G      1.625     0.6844     0.8953        105       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.1s

      29/50      10.1G      1.625     0.6795     0.8989        112       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.8s

      29/50      10.1G      1.635     0.6822     0.9094        105       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      29/50      10.1G      1.638     0.6899     0.9107         97       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.3s

      29/50      10.1G      1.639     0.6896     0.9092        121       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<16.9s

      29/50      10.1G      1.633     0.6937     0.9074         95       1024: 13% ━╸────────── 16/124 6.5it/s 2.5s<16.6s

      29/50      10.1G      1.628     0.6935     0.9044        116       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      29/50      10.1G      1.626      0.695     0.9046        113       1024: 15% ━╸────────── 18/124 6.6it/s 2.8s<16.1s

      29/50      10.1G       1.63     0.6961     0.9061        118       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<15.8s

      29/50      10.1G      1.641     0.6987     0.9046        126       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.5s

      29/50      10.1G      1.631     0.6956      0.903        111       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      29/50      10.1G      1.628     0.6936     0.9012        106       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.1s

      29/50      10.1G      1.626     0.6942     0.9012        111       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

      29/50      10.1G      1.649     0.7023     0.9041         99       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

      29/50      10.1G      1.649     0.7039     0.9039         93       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      29/50      10.1G      1.649     0.7044     0.9038        119       1024: 21% ━━╸───────── 26/124 6.5it/s 4.1s<15.0s

      29/50      10.1G      1.652     0.7022     0.9037        110       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.9s

      29/50      10.1G      1.657     0.7056     0.9061        115       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      29/50      10.1G      1.651     0.7045     0.9052        109       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.3s

      29/50      10.1G      1.656      0.707     0.9068        114       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      29/50      10.1G       1.65      0.705     0.9052        118       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.4s

      29/50      10.1G      1.648     0.7068     0.9051        108       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.2s

      29/50      10.1G      1.657     0.7096     0.9062        125       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

      29/50      10.1G      1.658     0.7098     0.9081        117       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

      29/50      10.1G      1.661     0.7102     0.9084        111       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

      29/50      10.1G       1.66     0.7105     0.9083        119       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.2s

      29/50      10.1G      1.658     0.7114     0.9085        120       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<12.9s

      29/50      10.1G      1.657     0.7109     0.9087         99       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.7s

      29/50      10.1G       1.66     0.7126     0.9104        109       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.0s<13.3s

      29/50      10.1G      1.655     0.7099     0.9097        116       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<13.0s

      29/50      10.1G      1.655     0.7095     0.9095        107       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

      29/50      10.1G      1.654     0.7098     0.9101        120       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      29/50      10.1G      1.656     0.7104       0.91        121       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.0s

      29/50      10.1G      1.652     0.7073     0.9093         94       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

      29/50      10.1G      1.655     0.7107     0.9088        117       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

      29/50      10.1G      1.656     0.7102     0.9091        101       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.4s

      29/50      10.1G      1.661     0.7129     0.9108        110       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.8s

      29/50      10.1G      1.661     0.7114      0.912        114       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.5s

      29/50      10.1G      1.668     0.7141     0.9123        115       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

      29/50      10.1G      1.667     0.7167     0.9131        120       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.1s

      29/50      10.1G      1.673     0.7175     0.9152        123       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.9s

      29/50      10.1G      1.666     0.7153     0.9142        106       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      29/50      10.1G      1.666     0.7153     0.9149        115       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

      29/50      10.1G       1.67     0.7161      0.916        110       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.5s

      29/50      10.1G      1.669     0.7137     0.9163        131       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.8s

      29/50      10.1G      1.672     0.7145     0.9175        119       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.4s

      29/50      10.1G      1.669     0.7124     0.9164        116       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.1s

      29/50      10.1G      1.674     0.7137     0.9171        124       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      29/50      10.1G       1.67     0.7113     0.9166        114       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.0s<9.6s

      29/50      10.1G      1.668     0.7114     0.9157        119       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.4s

      29/50      10.1G      1.667     0.7113     0.9175        103       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.2s

      29/50      10.1G      1.665     0.7088     0.9179         98       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      29/50      10.1G      1.666     0.7092     0.9184        114       1024: 51% ━━━━━━────── 63/124 6.4it/s 9.7s<9.5s

      29/50      10.1G      1.664     0.7087     0.9179        120       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      29/50      10.1G      1.664     0.7105     0.9172         99       1024: 52% ━━━━━━────── 65/124 6.7it/s 9.9s<8.8s

      29/50      10.1G       1.67     0.7124     0.9181        119       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.6s

      29/50      10.1G      1.667     0.7129     0.9174        117       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.2s<8.4s

      29/50      10.1G       1.67     0.7148     0.9166        106       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.2s

      29/50      10.1G      1.675     0.7157     0.9177        121       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.0s

      29/50      10.1G      1.677     0.7169     0.9176        122       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<7.9s

      29/50      10.1G      1.679     0.7177     0.9178        108       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.9s<8.2s

      29/50      10.1G      1.678     0.7169     0.9173        120       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.9s

      29/50      10.1G      1.676     0.7164     0.9172         96       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      29/50      10.1G      1.675     0.7164     0.9172        106       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.4s

      29/50      10.1G      1.674      0.715     0.9166        121       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.4s<7.2s

      29/50      10.1G      1.671     0.7141     0.9161        115       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      29/50      10.1G      1.668     0.7121     0.9159        105       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.7s<7.1s

      29/50      10.1G      1.669     0.7124     0.9157        119       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.9s

      29/50      10.1G       1.67     0.7138     0.9163        105       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.1s<7.0s

      29/50      10.1G      1.671     0.7133     0.9161        108       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.2s<6.8s

      29/50      10.1G      1.669     0.7116     0.9155        118       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      29/50      10.1G      1.671      0.713     0.9166         98       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      29/50      10.1G       1.67     0.7126     0.9158        105       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.7s<6.1s

      29/50      10.1G      1.669     0.7117     0.9154        105       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

      29/50      10.1G      1.668     0.7121     0.9145        108       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.9s<5.7s

      29/50      10.1G       1.67     0.7124     0.9144        101       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      29/50      10.1G      1.672     0.7125     0.9155        132       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.3s<5.7s

      29/50      10.1G      1.669     0.7116      0.915        126       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.4s

      29/50      10.1G      1.669     0.7123     0.9153         85       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.2s

      29/50      10.1G      1.669     0.7117     0.9151        117       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      29/50      10.1G       1.67     0.7122      0.915        126       1024: 73% ━━━━━━━━╸─── 91/124 6.8it/s 13.8s<4.9s

      29/50      10.1G       1.67     0.7117     0.9153        112       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

      29/50      10.1G       1.67     0.7113     0.9156         97       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.5s

      29/50      10.1G      1.671     0.7115     0.9159        103       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      29/50      10.1G      1.669     0.7103     0.9159        107       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.4s

      29/50      10.1G      1.666     0.7097     0.9152        123       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.2s

      29/50      10.1G      1.669     0.7107     0.9151        113       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.0s

      29/50      10.1G      1.667     0.7102     0.9147        118       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.9s<3.8s

      29/50      10.1G      1.665      0.709     0.9147        103       1024: 80% ━━━━━━━━━╸── 99/124 6.8it/s 15.0s<3.7s

      29/50      10.1G      1.667     0.7096     0.9156        113       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.2s<3.5s

      29/50      10.1G      1.667     0.7093     0.9156        126       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.3s<3.4s

      29/50      10.1G      1.665     0.7097     0.9154        101       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

      29/50      10.1G      1.665     0.7094     0.9147        114       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

      29/50      10.1G      1.666     0.7123      0.915        103       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.8s<3.0s

      29/50      10.1G      1.666     0.7122     0.9147        120       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.8s

      29/50      10.1G      1.665      0.712     0.9147        121       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      29/50      10.1G      1.664     0.7116     0.9147         97       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.2s<2.6s

      29/50      10.1G      1.664     0.7107     0.9139        128       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      29/50      10.1G      1.665     0.7103     0.9147        100       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.5s<2.2s

      29/50      10.1G      1.667     0.7103     0.9151        112       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

      29/50      10.1G      1.667     0.7103     0.9149        105       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.9s<2.0s

      29/50      10.1G      1.668     0.7102     0.9151        127       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.0s<1.8s

      29/50      10.1G      1.668     0.7096      0.915        121       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.2s<1.7s

      29/50      10.1G      1.667     0.7101     0.9149        113       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      29/50      10.1G      1.668     0.7105     0.9154        110       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.4s<1.3s

      29/50      10.1G      1.669     0.7103     0.9152        119       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      29/50      10.1G      1.668     0.7104     0.9156        116       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.7s<1.0s

      29/50      10.1G      1.669     0.7109     0.9157        100       1024: 95% ━━━━━━━━━━━─ 118/124 6.9it/s 17.9s<0.9s

      29/50      10.1G      1.671     0.7118      0.916        131       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.1s<0.8s

      29/50      10.1G      1.671     0.7111     0.9159        110       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.2s<0.6s

      29/50      10.1G      1.671     0.7116     0.9158         99       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.4s<0.5s

      29/50      10.1G       1.67     0.7109     0.9155        107       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

      29/50      10.1G       1.67     0.7104     0.9153        114       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.6s<0.1s

      29/50      10.1G       1.67     0.7104     0.9153        114       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.8it/s 0.1s<7.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.1it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.2it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.3it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.2it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.656      0.646      0.637      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/50      10.1G      1.484       0.79     0.8905        106       1024: 0% ──────────── 0/124  0.1s

      30/50      10.1G      1.594     0.7551     0.8792        117       1024: 1% ──────────── 1/124 2.1it/s 0.3s<58.9s

      30/50      10.1G       1.51     0.6899     0.8635        115       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      30/50      10.1G      1.581     0.7081     0.8848        103       1024: 2% ──────────── 3/124 4.0it/s 0.6s<30.2s

      30/50      10.1G      1.624     0.6968     0.8916        132       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.5s

      30/50      10.1G      1.641     0.7136     0.9052        120       1024: 4% ──────────── 5/124 5.4it/s 0.9s<22.2s

      30/50      10.1G      1.614     0.6972     0.9007         97       1024: 5% ╸─────────── 6/124 5.8it/s 1.1s<20.2s

      30/50      10.1G      1.615     0.6901     0.9054        115       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.9s

      30/50      10.1G      1.656     0.6977     0.9126        115       1024: 6% ╸─────────── 8/124 6.4it/s 1.4s<18.1s

      30/50      10.1G      1.674     0.7102     0.9179        125       1024: 7% ╸─────────── 9/124 6.6it/s 1.5s<17.5s

      30/50      10.1G      1.668     0.7076     0.9188        107       1024: 8% ╸─────────── 10/124 6.7it/s 1.6s<17.0s

      30/50      10.1G      1.668     0.7113     0.9159        100       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.5s

      30/50      10.1G      1.662     0.7104      0.915        102       1024: 10% ━─────────── 12/124 6.5it/s 2.0s<17.2s

      30/50      10.1G      1.644     0.7045     0.9101        116       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.7s

      30/50      10.1G      1.644     0.7011     0.9119        106       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      30/50      10.1G      1.645     0.7028     0.9105        108       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.2s

      30/50      10.1G      1.662     0.7064      0.914        101       1024: 13% ━╸────────── 16/124 6.8it/s 2.5s<15.9s

      30/50      10.1G      1.668     0.7082     0.9158        126       1024: 14% ━╸────────── 17/124 6.9it/s 2.7s<15.6s

      30/50      10.1G      1.669     0.7076     0.9158        122       1024: 15% ━╸────────── 18/124 6.9it/s 2.8s<15.4s

      30/50      10.1G      1.662     0.7098     0.9165        115       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<16.0s

      30/50      10.1G      1.641     0.7031     0.9134        112       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.5s

      30/50      10.1G      1.632      0.698      0.912        116       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      30/50      10.1G      1.632     0.6966     0.9095        113       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

      30/50      10.1G      1.632     0.6976      0.908         99       1024: 19% ━━────────── 23/124 6.8it/s 3.6s<14.8s

      30/50      10.1G      1.631     0.6952     0.9078        111       1024: 19% ━━────────── 24/124 6.9it/s 3.7s<14.5s

      30/50      10.1G      1.623     0.6941     0.9052        127       1024: 20% ━━────────── 25/124 6.9it/s 3.9s<14.3s

      30/50      10.1G      1.625     0.6919     0.9054        105       1024: 21% ━━╸───────── 26/124 6.9it/s 4.0s<14.2s

      30/50      10.1G      1.628      0.692     0.9041        115       1024: 22% ━━╸───────── 27/124 6.6it/s 4.2s<14.7s

      30/50      10.1G      1.626     0.6891     0.9054        114       1024: 23% ━━╸───────── 28/124 6.7it/s 4.3s<14.3s

      30/50      10.1G      1.619     0.6862     0.9032        118       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.0s

      30/50      10.1G      1.619     0.6835      0.903        127       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      30/50      10.1G      1.617      0.685      0.905        115       1024: 25% ━━━───────── 31/124 6.9it/s 4.8s<13.5s

      30/50      10.1G      1.613     0.6823     0.9053         98       1024: 26% ━━━───────── 32/124 6.9it/s 4.9s<13.3s

      30/50      10.1G      1.612     0.6813     0.9043        108       1024: 27% ━━━───────── 33/124 6.9it/s 5.0s<13.1s

      30/50      10.1G      1.611     0.6818     0.9041        116       1024: 27% ━━━───────── 34/124 6.9it/s 5.2s<13.0s

      30/50      10.1G      1.611     0.6812      0.905        112       1024: 28% ━━━───────── 35/124 6.6it/s 5.4s<13.4s

      30/50      10.1G      1.615     0.6823     0.9075        106       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.3s

      30/50      10.1G      1.612     0.6828     0.9071        104       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<12.9s

      30/50      10.1G      1.613     0.6835     0.9076        111       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.6s

      30/50      10.1G      1.611      0.682     0.9062        119       1024: 31% ━━━╸──────── 39/124 6.8it/s 5.9s<12.4s

      30/50      10.1G      1.613     0.6835     0.9063        137       1024: 32% ━━━╸──────── 40/124 6.9it/s 6.1s<12.2s

      30/50      10.1G      1.613     0.6841     0.9046        121       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.2s<12.2s

      30/50      10.1G      1.612      0.682     0.9033        123       1024: 34% ━━━━──────── 42/124 6.9it/s 6.4s<12.0s

      30/50      10.1G      1.608     0.6821     0.9039        119       1024: 35% ━━━━──────── 43/124 6.6it/s 6.6s<12.4s

      30/50      10.1G      1.612     0.6838     0.9046        109       1024: 35% ━━━━──────── 44/124 6.6it/s 6.7s<12.2s

      30/50      10.1G      1.614     0.6828     0.9032        123       1024: 36% ━━━━──────── 45/124 6.7it/s 6.8s<11.8s

      30/50      10.1G      1.614     0.6834     0.9035        131       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.5s

      30/50      10.1G      1.619     0.6835     0.9036        117       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.1s<11.3s

      30/50      10.1G      1.617     0.6818     0.9035        123       1024: 39% ━━━━╸─────── 48/124 6.9it/s 7.3s<11.0s

      30/50      10.1G      1.622     0.6824     0.9042        135       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.4s<11.0s

      30/50      10.1G      1.623     0.6848     0.9041         93       1024: 40% ━━━━╸─────── 50/124 6.9it/s 7.6s<10.8s

      30/50      10.1G      1.623     0.6851     0.9037        113       1024: 41% ━━━━╸─────── 51/124 6.6it/s 7.7s<11.1s

      30/50      10.1G      1.627     0.6858      0.904        112       1024: 42% ━━━━━─────── 52/124 6.6it/s 7.9s<10.9s

      30/50      10.1G      1.629     0.6846     0.9042        116       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.0s<10.6s

      30/50      10.1G      1.629     0.6839     0.9041        130       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

      30/50      10.1G      1.631     0.6858     0.9044        138       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.3s<10.1s

      30/50      10.1G      1.634     0.6855     0.9051        113       1024: 45% ━━━━━─────── 56/124 6.9it/s 8.5s<9.9s

      30/50      10.1G      1.634      0.687     0.9064        108       1024: 46% ━━━━━╸────── 57/124 6.9it/s 8.6s<9.7s

      30/50      10.1G      1.635     0.6874     0.9069        104       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.6s

      30/50      10.1G      1.635     0.6875     0.9062        124       1024: 48% ━━━━━╸────── 59/124 6.5it/s 8.9s<10.0s

      30/50      10.1G      1.636     0.6873     0.9062        107       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.1s<9.6s

      30/50      10.1G      1.637      0.687     0.9058        120       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.2s<9.3s

      30/50      10.1G      1.637     0.6858     0.9055         97       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.4s<9.1s

      30/50      10.1G      1.636      0.685     0.9046        122       1024: 51% ━━━━━━────── 63/124 6.9it/s 9.5s<8.9s

      30/50      10.1G      1.636     0.6854     0.9041        117       1024: 52% ━━━━━━────── 64/124 6.9it/s 9.7s<8.7s

      30/50      10.1G      1.636     0.6855     0.9039        100       1024: 52% ━━━━━━────── 65/124 6.9it/s 9.8s<8.5s

      30/50      10.1G      1.633     0.6849     0.9037        111       1024: 53% ━━━━━━────── 66/124 6.9it/s 9.9s<8.4s

      30/50      10.1G      1.635     0.6872     0.9049        121       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.1s<8.7s

      30/50      10.1G      1.633     0.6855     0.9041        123       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.3s<8.5s

      30/50      10.1G      1.637     0.6878     0.9046        106       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.4s<8.2s

      30/50      10.1G      1.638     0.6876     0.9049        123       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.6s<8.0s

      30/50      10.1G      1.638     0.6863      0.905        118       1024: 57% ━━━━━━╸───── 71/124 6.8it/s 10.7s<7.7s

      30/50      10.1G      1.634      0.684     0.9041        103       1024: 58% ━━━━━━╸───── 72/124 6.9it/s 10.8s<7.5s

      30/50      10.1G      1.635     0.6849     0.9042        108       1024: 59% ━━━━━━━───── 73/124 6.9it/s 11.0s<7.4s

      30/50      10.1G      1.635     0.6834     0.9042        129       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.1s<7.3s

      30/50      10.1G      1.635     0.6852     0.9038        123       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.3s<7.5s

      30/50      10.1G      1.635     0.6856     0.9036        122       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.4s<7.2s

      30/50      10.1G      1.635     0.6852     0.9034        110       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.6s<7.0s

      30/50      10.1G      1.638     0.6857     0.9033        110       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.7s<6.8s

      30/50      10.1G      1.638     0.6858     0.9029        112       1024: 64% ━━━━━━━╸──── 79/124 6.9it/s 11.9s<6.6s

      30/50      10.1G      1.638     0.6856     0.9025        108       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.0s<6.5s

      30/50      10.1G      1.638     0.6855     0.9041        120       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.2s<6.3s

      30/50      10.1G      1.638     0.6852     0.9038         88       1024: 66% ━━━━━━━╸──── 82/124 6.9it/s 12.3s<6.1s

      30/50      10.1G       1.64     0.6858     0.9049        142       1024: 67% ━━━━━━━━──── 83/124 6.6it/s 12.5s<6.3s

      30/50      10.1G      1.639     0.6854     0.9051        107       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.6s<6.1s

      30/50      10.1G       1.64     0.6854     0.9052        116       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.8s<5.8s

      30/50      10.1G      1.637     0.6838     0.9047        108       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 12.9s<5.6s

      30/50      10.1G      1.636     0.6839     0.9044        105       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.1s<5.5s

      30/50      10.1G      1.633     0.6826     0.9036        120       1024: 71% ━━━━━━━━╸─── 88/124 6.8it/s 13.2s<5.3s

      30/50      10.1G      1.633     0.6828     0.9035        115       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.4s<5.1s

      30/50      10.1G      1.636     0.6844     0.9027        103       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.5s<5.0s

      30/50      10.1G      1.638     0.6855     0.9027        114       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.7s<5.1s

      30/50      10.1G      1.637     0.6848     0.9026        103       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 13.8s<4.9s

      30/50      10.1G      1.636     0.6847      0.902        118       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.0s<4.6s

      30/50      10.1G      1.638     0.6851     0.9025        110       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.1s<4.5s

      30/50      10.1G      1.636     0.6838     0.9019         90       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 14.3s<4.3s

      30/50      10.1G      1.642     0.6854     0.9027        109       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.4s<4.1s

      30/50      10.1G      1.643     0.6867     0.9031        116       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.6s<4.0s

      30/50      10.1G      1.643      0.686      0.903        116       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.7s<3.8s

      30/50      10.1G      1.641     0.6849      0.903        110       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 14.9s<3.8s

      30/50      10.1G      1.643     0.6855     0.9033        104       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.0s<3.7s

      30/50      10.1G      1.643     0.6849     0.9035        101       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.2s<3.5s

      30/50      10.1G      1.643     0.6837     0.9037        108       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.3s<3.3s

      30/50      10.1G      1.643     0.6844     0.9039        114       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.5s<3.1s

      30/50      10.1G      1.646     0.6847     0.9041        116       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.6s<3.0s

      30/50      10.1G      1.645     0.6841      0.904         99       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 15.8s<2.8s

      30/50      10.1G      1.648     0.6857     0.9041        124       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 15.9s<2.6s

      30/50      10.1G      1.647     0.6845     0.9041         97       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.1s<2.6s

      30/50      10.1G      1.648     0.6859     0.9041        116       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.2s<2.4s

      30/50      10.1G      1.647     0.6847     0.9035        107       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.4s<2.2s

      30/50      10.1G      1.646     0.6844      0.904        103       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.5s<2.1s

      30/50      10.1G      1.646     0.6838     0.9036        121       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.7s<1.9s

      30/50      10.1G      1.643     0.6828     0.9031        107       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 16.8s<1.8s

      30/50      10.1G      1.644     0.6833     0.9029        115       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.0s<1.6s

      30/50      10.1G      1.643     0.6832     0.9026        104       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.1s<1.5s

      30/50      10.1G      1.642     0.6829     0.9031        113       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.3s<1.4s

      30/50      10.1G       1.64     0.6816     0.9021        111       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.4s<1.2s

      30/50      10.1G       1.64     0.6819     0.9024         97       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.6s<1.0s

      30/50      10.1G      1.642     0.6839     0.9033        108       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 17.7s<0.9s

      30/50      10.1G      1.642      0.684     0.9034        118       1024: 96% ━━━━━━━━━━━╸ 119/124 6.8it/s 17.9s<0.7s

      30/50      10.1G      1.643     0.6842     0.9034        116       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.0s<0.6s

      30/50      10.1G      1.644     0.6846     0.9039        117       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.2s<0.4s

      30/50      10.1G      1.643     0.6844     0.9036        125       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.3s<0.3s

      30/50      10.1G      1.644     0.6851      0.904        120       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.5s<0.2s

      30/50      10.1G      1.644     0.6851      0.904        120       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.691      0.605      0.637      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/50      10.1G      1.998     0.7794      0.945         82       1024: 0% ──────────── 0/124  0.1s

      31/50      10.1G      1.919     0.7627     0.9335        118       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.5s

      31/50      10.1G      1.802     0.7185     0.9237        109       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      31/50      10.1G       1.77     0.7174     0.9337        122       1024: 2% ──────────── 3/124 4.5it/s 0.6s<27.0s

      31/50      10.1G      1.718     0.7098     0.9238         96       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.1s

      31/50      10.1G       1.74      0.714     0.9346        121       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.9s

      31/50      10.1G      1.753     0.7202     0.9399        126       1024: 5% ╸─────────── 6/124 6.1it/s 1.0s<19.5s

      31/50      10.1G      1.727     0.7079     0.9297        112       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.6s

      31/50      10.1G      1.735     0.7047      0.931        132       1024: 6% ╸─────────── 8/124 6.1it/s 1.3s<19.0s

      31/50      10.1G      1.748     0.7165     0.9317        127       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.1s

      31/50      10.1G      1.734     0.7128     0.9292        117       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.5s

      31/50      10.1G      1.709     0.7024     0.9227        105       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.4s

      31/50      10.1G      1.716      0.705     0.9198        134       1024: 10% ━─────────── 12/124 6.5it/s 1.9s<17.2s

      31/50      10.1G      1.718     0.7067     0.9198        119       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.8s

      31/50      10.1G       1.72     0.7024     0.9211        114       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.4s

      31/50      10.1G      1.722     0.7092     0.9186        128       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<17.1s

      31/50      10.1G      1.719     0.7146     0.9194        101       1024: 13% ━╸────────── 16/124 6.4it/s 2.6s<16.8s

      31/50      10.1G      1.711     0.7121     0.9185        115       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.6s

      31/50      10.1G      1.704     0.7073     0.9154        112       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.1s

      31/50      10.1G      1.695      0.706     0.9143        103       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      31/50      10.1G      1.674     0.6992     0.9098        117       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.4s

      31/50      10.1G      1.662     0.7034     0.9073         92       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      31/50      10.1G      1.661     0.7003     0.9044        119       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

      31/50      10.1G      1.666     0.6996     0.9059        116       1024: 19% ━━────────── 23/124 6.5it/s 3.6s<15.6s

      31/50      10.1G      1.666     0.7037      0.905        110       1024: 19% ━━────────── 24/124 6.6it/s 3.8s<15.1s

      31/50      10.1G      1.664     0.7058     0.9065         97       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.8s

      31/50      10.1G      1.665     0.7047     0.9054        126       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      31/50      10.1G      1.657     0.7016     0.9022        107       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.5s

      31/50      10.1G      1.656     0.7026     0.9013        121       1024: 23% ━━╸───────── 28/124 6.8it/s 4.4s<14.2s

      31/50      10.1G      1.651     0.7036     0.9028         95       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.1s

      31/50      10.1G      1.648     0.7022     0.9018        113       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.8s

      31/50      10.1G      1.653     0.7053     0.9049        119       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.3s

      31/50      10.1G      1.652      0.705     0.9045        127       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.1s

      31/50      10.1G      1.654     0.7043     0.9052        122       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

      31/50      10.1G      1.662     0.7055     0.9066        117       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

      31/50      10.1G      1.662      0.704     0.9064        110       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.2s

      31/50      10.1G      1.659     0.7023      0.907        130       1024: 29% ━━━───────── 36/124 6.8it/s 5.6s<13.0s

      31/50      10.1G      1.654      0.699     0.9059        120       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      31/50      10.1G      1.645     0.6953     0.9044        101       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.6s

      31/50      10.1G      1.639     0.6921     0.9029        101       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.0s

      31/50      10.1G      1.638      0.691      0.902        115       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      31/50      10.1G      1.637     0.6896     0.9006        114       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.5s

      31/50      10.1G      1.635     0.6897     0.8996        120       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

      31/50      10.1G      1.638     0.6925        0.9         97       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.2s

      31/50      10.1G       1.64     0.6946      0.901        113       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

      31/50      10.1G      1.644     0.6961     0.9018        134       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      31/50      10.1G      1.646      0.696     0.9036        113       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.5s

      31/50      10.1G      1.649      0.696      0.902        130       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.2s<12.1s

      31/50      10.1G      1.647     0.6969     0.9018        107       1024: 39% ━━━━╸─────── 48/124 6.5it/s 7.4s<11.6s

      31/50      10.1G      1.649     0.6956     0.9012        108       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.5s<11.3s

      31/50      10.1G      1.648     0.6942     0.9016        115       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.1s

      31/50      10.1G      1.644     0.6913     0.9002        130       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.9s

      31/50      10.1G      1.647      0.693     0.9017        128       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      31/50      10.1G      1.647     0.6914     0.9012        111       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

      31/50      10.1G      1.647     0.6924     0.9021        109       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      31/50      10.1G       1.65     0.6948     0.9026        111       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.7s

      31/50      10.1G      1.652     0.6949     0.9022        118       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      31/50      10.1G      1.655     0.6952     0.9047         93       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

      31/50      10.1G      1.655     0.6949     0.9062        104       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      31/50      10.1G      1.652     0.6939     0.9063        106       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

      31/50      10.1G      1.651     0.6929     0.9057        107       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.4s

      31/50      10.1G      1.657      0.694     0.9072        115       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.2s

      31/50      10.1G      1.657     0.6943      0.908        117       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      31/50      10.1G      1.656     0.6932     0.9078        103       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

      31/50      10.1G      1.655     0.6925     0.9072        109       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      31/50      10.1G      1.652     0.6916     0.9064        126       1024: 52% ━━━━━━────── 65/124 6.7it/s 9.9s<8.9s

      31/50      10.1G      1.648     0.6895     0.9055        102       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      31/50      10.1G      1.645     0.6879     0.9043        117       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.2s<8.4s

      31/50      10.1G      1.645      0.688     0.9037        118       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.3s

      31/50      10.1G      1.643     0.6879     0.9036        113       1024: 56% ━━━━━━╸───── 69/124 6.7it/s 10.5s<8.2s

      31/50      10.1G      1.643     0.6891     0.9045        123       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      31/50      10.1G      1.643      0.689     0.9043        104       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.8s<8.2s

      31/50      10.1G      1.644     0.6886     0.9039        100       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.9s

      31/50      10.1G      1.643     0.6898     0.9043        117       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      31/50      10.1G      1.642     0.6887     0.9051         95       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.4s

      31/50      10.1G      1.641     0.6886     0.9043         98       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.4s<7.2s

      31/50      10.1G      1.639     0.6881     0.9045         98       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      31/50      10.1G      1.637     0.6873     0.9035        108       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

      31/50      10.1G       1.64     0.6878     0.9035        132       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.8s<6.7s

      31/50      10.1G      1.638     0.6877     0.9038        108       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.0s<7.0s

      31/50      10.1G      1.638     0.6869     0.9036        118       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.2s<6.7s

      31/50      10.1G      1.642     0.6888     0.9042        105       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.3s<6.5s

      31/50      10.1G      1.641     0.6884     0.9037        104       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      31/50      10.1G      1.642     0.6874     0.9034        102       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.6s<6.1s

      31/50      10.1G       1.64      0.686     0.9039        113       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.8s<5.9s

      31/50      10.1G       1.64     0.6862     0.9037        104       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.9s<5.7s

      31/50      10.1G      1.639     0.6849     0.9033        128       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      31/50      10.1G       1.64     0.6857     0.9036        118       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.2s<5.8s

      31/50      10.1G       1.64     0.6854     0.9032        119       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.4s<5.6s

      31/50      10.1G       1.64     0.6856     0.9031         99       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.5s<5.3s

      31/50      10.1G      1.641     0.6852     0.9031        105       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.7s<5.1s

      31/50      10.1G      1.642     0.6856     0.9039        102       1024: 73% ━━━━━━━━╸─── 91/124 6.6it/s 13.8s<5.0s

      31/50      10.1G      1.642      0.685     0.9038         99       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.0s<4.8s

      31/50      10.1G       1.64     0.6845     0.9033        119       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

      31/50      10.1G      1.639     0.6842     0.9034        111       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      31/50      10.1G      1.643     0.6858     0.9046        113       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.4s<4.5s

      31/50      10.1G      1.643      0.685     0.9046        106       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.3s

      31/50      10.1G      1.641     0.6839      0.904        118       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.1s

      31/50      10.1G      1.642     0.6841     0.9035        111       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      31/50      10.1G       1.64     0.6831     0.9029        128       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.0s<3.7s

      31/50      10.1G      1.639     0.6825     0.9026        114       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.2s<3.5s

      31/50      10.1G      1.638     0.6817      0.902        115       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.3s<3.4s

      31/50      10.1G      1.636     0.6812     0.9016        109       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.2s

      31/50      10.1G      1.635     0.6808     0.9013        129       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.6s<3.3s

      31/50      10.1G      1.638     0.6816      0.902        130       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.8s<3.0s

      31/50      10.1G      1.638     0.6814     0.9023        102       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.9s

      31/50      10.1G      1.639     0.6816     0.9027        117       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.1s<2.7s

      31/50      10.1G      1.642     0.6831     0.9038        111       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.2s<2.5s

      31/50      10.1G      1.643     0.6841     0.9037        120       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      31/50      10.1G      1.644      0.685     0.9045        100       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.5s<2.2s

      31/50      10.1G      1.646     0.6853     0.9049        122       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

      31/50      10.1G      1.644     0.6851     0.9046        111       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

      31/50      10.1G      1.645     0.6846     0.9045        128       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.0s<1.8s

      31/50      10.1G      1.644     0.6838     0.9037        114       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.1s<1.7s

      31/50      10.1G      1.643     0.6833     0.9031        115       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      31/50      10.1G      1.643     0.6839     0.9034        109       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.4s<1.3s

      31/50      10.1G      1.642     0.6838     0.9041        110       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      31/50      10.1G       1.64     0.6832     0.9037        113       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.7s<1.0s

      31/50      10.1G      1.641     0.6831     0.9033        133       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      31/50      10.1G       1.64     0.6831     0.9033        112       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.1s<0.8s

      31/50      10.1G      1.639     0.6821     0.9036        113       1024: 97% ━━━━━━━━━━━╸ 120/124 6.4it/s 18.2s<0.6s

      31/50      10.1G      1.643     0.6833     0.9043        126       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.4s<0.5s

      31/50      10.1G      1.644     0.6835      0.904        130       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.5s<0.3s

      31/50      10.1G      1.643     0.6829     0.9037        108       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.2s

      31/50      10.1G      1.643     0.6829     0.9037        108       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.1it/s 0.6s<2.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.8it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.8s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.703      0.579      0.611      0.376

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/50      10.1G      1.579     0.6339     0.9086        103       1024: 0% ──────────── 0/124  0.1s

      32/50      10.1G      1.458     0.6005     0.8565        124       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:01

      32/50      10.1G      1.592     0.6206     0.8682        106       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.1s

      32/50      10.1G      1.606     0.6316     0.8737        132       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.2s

      32/50      10.1G      1.596     0.6262     0.8858        118       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.5s

      32/50      10.1G      1.611     0.6445     0.8892        116       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.7s

      32/50      10.1G      1.604     0.6352     0.8899        100       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.1s

      32/50      10.1G      1.596     0.6346     0.8882        109       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.0s

      32/50      10.1G      1.599     0.6345     0.8887        113       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.3s

      32/50      10.1G      1.616     0.6357     0.8933        112       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.7s

      32/50      10.1G      1.617     0.6459      0.901        105       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.3s

      32/50      10.1G      1.613     0.6418     0.9029        100       1024: 9% ━─────────── 11/124 6.2it/s 1.8s<18.1s

      32/50      10.1G      1.609     0.6386     0.9035        111       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.4s

      32/50      10.1G      1.623     0.6443     0.9037        117       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.9s

      32/50      10.1G      1.636     0.6522     0.9072        112       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      32/50      10.1G      1.645     0.6562     0.9077        115       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.3s

      32/50      10.1G      1.645     0.6576      0.906        120       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.0s

      32/50      10.1G       1.65     0.6551     0.9026        131       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      32/50      10.1G      1.643      0.656     0.9017         97       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      32/50      10.1G      1.636     0.6544     0.9026         99       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.5s

      32/50      10.1G      1.632     0.6546     0.9018        115       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.0s

      32/50      10.1G      1.637     0.6568     0.9011        112       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

      32/50      10.1G      1.632     0.6539     0.9019        120       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.5s

      32/50      10.1G      1.623     0.6524      0.901        113       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.2s

      32/50      10.1G       1.64     0.6582     0.9029        113       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.9s

      32/50      10.1G      1.639     0.6563     0.9028        106       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.6s

      32/50      10.1G      1.632     0.6542     0.9015        110       1024: 21% ━━╸───────── 26/124 6.8it/s 4.1s<14.4s

      32/50      10.1G      1.621     0.6515     0.8993        113       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.9s

      32/50      10.1G       1.62     0.6509     0.8998        115       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.7s

      32/50      10.1G       1.62     0.6534      0.902        116       1024: 23% ━━╸───────── 29/124 6.5it/s 4.5s<14.5s

      32/50      10.1G      1.624      0.655     0.9016        110       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.2s

      32/50      10.1G       1.62     0.6558     0.9004        106       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.9s

      32/50      10.1G      1.632     0.6611     0.9019        120       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<13.9s

      32/50      10.1G      1.626     0.6584     0.8995        110       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.7s

      32/50      10.1G      1.629     0.6611     0.9011        117       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      32/50      10.1G      1.635      0.669     0.9022         95       1024: 28% ━━━───────── 35/124 6.4it/s 5.5s<13.9s

      32/50      10.1G      1.631     0.6682      0.903        121       1024: 29% ━━━───────── 36/124 6.4it/s 5.6s<13.7s

      32/50      10.1G      1.631     0.6677      0.904        123       1024: 30% ━━━╸──────── 37/124 6.5it/s 5.8s<13.5s

      32/50      10.1G      1.631     0.6676     0.9027        125       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.1s

      32/50      10.1G      1.635     0.6679     0.9031        106       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.1s<12.8s

      32/50      10.1G      1.637     0.6688     0.9037        121       1024: 32% ━━━╸──────── 40/124 6.7it/s 6.2s<12.6s

      32/50      10.1G      1.638     0.6664      0.904        117       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.4s<12.4s

      32/50      10.1G      1.639     0.6675     0.9039        117       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.1s

      32/50      10.1G      1.632     0.6653     0.9032        122       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.7s

      32/50      10.1G      1.634     0.6651     0.9038        130       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

      32/50      10.1G      1.634     0.6669     0.9034        126       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<12.0s

      32/50      10.1G      1.632     0.6641     0.9027        125       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      32/50      10.1G      1.629     0.6638      0.902        115       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      32/50      10.1G      1.622      0.664     0.9016        129       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.3s

      32/50      10.1G      1.621     0.6662     0.9023         97       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.6s<11.0s

      32/50      10.1G      1.617     0.6655     0.9019        110       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      32/50      10.1G      1.616     0.6672      0.901        115       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.9s<11.3s

      32/50      10.1G      1.618      0.668      0.901        112       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      32/50      10.1G      1.618     0.6676      0.901        122       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.6s

      32/50      10.1G      1.623     0.6681     0.9017        143       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      32/50      10.1G      1.623      0.668     0.9015        112       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.5s<10.2s

      32/50      10.1G      1.617     0.6667     0.9003        107       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      32/50      10.1G      1.617     0.6679     0.9002        107       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.8s<9.8s

      32/50      10.1G      1.614     0.6686     0.9006        121       1024: 47% ━━━━━╸────── 58/124 6.9it/s 8.9s<9.6s

      32/50      10.1G      1.609     0.6663     0.8996        107       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.0s

      32/50      10.1G      1.614      0.668     0.9006        110       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.6s

      32/50      10.1G      1.617     0.6689     0.9003        138       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.4s<9.4s

      32/50      10.1G      1.613     0.6668     0.8993         93       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.2s

      32/50      10.1G      1.613     0.6668     0.8995        110       1024: 51% ━━━━━━────── 63/124 6.8it/s 9.7s<9.0s

      32/50      10.1G      1.612     0.6663     0.8987        113       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<8.9s

      32/50      10.1G      1.615     0.6683      0.899        106       1024: 52% ━━━━━━────── 65/124 6.7it/s 10.0s<8.8s

      32/50      10.1G      1.615     0.6689     0.8993        112       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      32/50      10.1G      1.611      0.669      0.899         97       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

      32/50      10.1G      1.606     0.6682     0.8981        103       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.4s<8.7s

      32/50      10.1G      1.604     0.6672     0.8982        119       1024: 56% ━━━━━━╸───── 69/124 6.5it/s 10.6s<8.4s

      32/50      10.1G      1.603     0.6673     0.8989        107       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.1s

      32/50      10.1G      1.603     0.6679     0.8988        127       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      32/50      10.1G      1.602     0.6671     0.8984        113       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.7s

      32/50      10.1G      1.604     0.6685     0.8984        108       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      32/50      10.1G      1.604     0.6695     0.8978        120       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

      32/50      10.1G      1.605     0.6698     0.8976        118       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.5s<7.7s

      32/50      10.1G      1.606       0.67     0.8979        126       1024: 61% ━━━━━━━───── 76/124 6.4it/s 11.7s<7.5s

      32/50      10.1G      1.603     0.6693     0.8974         90       1024: 62% ━━━━━━━───── 77/124 6.5it/s 11.8s<7.2s

      32/50      10.1G      1.605     0.6688     0.8972        131       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<6.9s

      32/50      10.1G      1.606      0.671     0.8984        119       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.7s

      32/50      10.1G      1.603     0.6701     0.8981        106       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.2s<6.5s

      32/50      10.1G      1.603     0.6697      0.898        125       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      32/50      10.1G      1.604     0.6714     0.8989        129       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      32/50      10.1G      1.607     0.6729     0.8986        125       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.7s<6.4s

      32/50      10.1G      1.605     0.6719     0.8976        105       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.1s

      32/50      10.1G      1.609      0.673     0.8978        122       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.0s<5.9s

      32/50      10.1G      1.607     0.6721     0.8974        105       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      32/50      10.1G      1.605     0.6716      0.897        109       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.5s

      32/50      10.1G      1.605     0.6708     0.8965        104       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.3s

      32/50      10.1G      1.606     0.6719     0.8973        112       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.3s

      32/50      10.1G      1.602     0.6704     0.8967        125       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      32/50      10.1G      1.603     0.6705     0.8973        107       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 13.9s<5.1s

      32/50      10.1G      1.606     0.6729      0.898        102       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.1s<4.9s

      32/50      10.1G      1.605      0.673     0.8977        107       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      32/50      10.1G      1.603     0.6727     0.8974        109       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.6s

      32/50      10.1G      1.605     0.6741     0.8975        115       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.5s<4.4s

      32/50      10.1G      1.606     0.6747     0.8977        117       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.7s<4.2s

      32/50      10.1G       1.61     0.6754     0.8987        111       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.8s<4.0s

      32/50      10.1G       1.61     0.6754     0.8988        119       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.0s<3.8s

      32/50      10.1G      1.611     0.6761     0.8985        116       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.1s<3.9s

      32/50      10.1G       1.61      0.675     0.8984        114       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.3s<3.6s

      32/50      10.1G      1.611     0.6757      0.898        116       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.4s<3.4s

      32/50      10.1G      1.612     0.6754     0.8976        108       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      32/50      10.1G      1.613     0.6758     0.8976        128       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.7s<3.1s

      32/50      10.1G      1.613     0.6756     0.8977         99       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.9s<2.9s

      32/50      10.1G      1.614     0.6761     0.8976        132       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.0s<2.8s

      32/50      10.1G      1.612     0.6751     0.8971        101       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.2s<2.6s

      32/50      10.1G      1.613     0.6756     0.8977        112       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.3s<2.6s

      32/50      10.1G      1.614     0.6765     0.8982        103       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.5s<2.4s

      32/50      10.1G      1.615     0.6775     0.8985        112       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

      32/50      10.1G      1.616      0.679     0.8998        106       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.8s<2.1s

      32/50      10.1G      1.616     0.6786     0.8997        101       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.9s<1.9s

      32/50      10.1G      1.616     0.6786     0.8999        127       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.1s<1.8s

      32/50      10.1G      1.619     0.6785     0.9005        118       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.2s<1.6s

      32/50      10.1G       1.62     0.6795     0.9007        109       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.3s<1.5s

      32/50      10.1G       1.62     0.6792     0.9005        111       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.5s<1.4s

      32/50      10.1G      1.617     0.6777     0.8998        103       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.7s<1.2s

      32/50      10.1G      1.618     0.6783     0.9004        117       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.1s

      32/50      10.1G      1.617     0.6786     0.8998        110       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      32/50      10.1G      1.618     0.6785     0.8996        110       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.1s<0.7s

      32/50      10.1G      1.618     0.6789     0.8999         95       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.3s<0.6s

      32/50      10.1G      1.616     0.6781     0.8997        112       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.4s<0.5s

      32/50      10.1G      1.617     0.6785     0.8993        122       1024: 98% ━━━━━━━━━━━╸ 122/124 6.5it/s 18.6s<0.3s

      32/50      10.1G      1.619     0.6786     0.8991        126       1024: 99% ━━━━━━━━━━━╸ 123/124 6.3it/s 18.8s<0.2s

      32/50      10.1G      1.619     0.6786     0.8991        126       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.678      0.611      0.629      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      33/50      10.1G      1.673      0.746     0.9288        104       1024: 0% ──────────── 0/124  0.1s

      33/50      10.1G       1.75     0.7719     0.9294        108       1024: 1% ──────────── 1/124 2.1it/s 0.3s<60.0s

      33/50      10.1G      1.766     0.7567     0.9446        108       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.9s

      33/50      10.1G      1.702     0.7324     0.9261        111       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.9s

      33/50      10.1G      1.678     0.7301     0.9153        116       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.0s

      33/50      10.1G      1.703     0.7324     0.9154        114       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.9s

      33/50      10.1G      1.671     0.7181     0.9143        110       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.5s

      33/50      10.1G       1.66     0.7076     0.9167        109       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.6s

      33/50      10.1G      1.641     0.6903     0.9159        113       1024: 6% ╸─────────── 8/124 6.1it/s 1.3s<18.9s

      33/50      10.1G      1.615     0.6886     0.9123        100       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.1s

      33/50      10.1G      1.628      0.694     0.9161        123       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.5s

      33/50      10.1G      1.629     0.6933     0.9169        113       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.2s

      33/50      10.1G      1.622      0.687     0.9161        112       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.8s

      33/50      10.1G      1.635     0.6971     0.9149        118       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      33/50      10.1G      1.636     0.6932     0.9096        113       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.3s

      33/50      10.1G      1.649     0.6975     0.9128        118       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<16.9s

      33/50      10.1G      1.644     0.6984     0.9132        110       1024: 13% ━╸────────── 16/124 6.5it/s 2.6s<16.7s

      33/50      10.1G      1.653     0.6973     0.9156        106       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.4s

      33/50      10.1G       1.64     0.6922     0.9115        111       1024: 15% ━╸────────── 18/124 6.5it/s 2.9s<16.3s

      33/50      10.1G      1.631     0.6843     0.9089        106       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<15.9s

      33/50      10.1G      1.626     0.6831     0.9083        111       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.6s

      33/50      10.1G      1.623     0.6803     0.9057        120       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.3s

      33/50      10.1G      1.631      0.682     0.9063        124       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.1s

      33/50      10.1G      1.641     0.6898      0.909        134       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

      33/50      10.1G      1.638     0.6884     0.9082        116       1024: 19% ━━────────── 24/124 6.4it/s 3.8s<15.5s

      33/50      10.1G      1.632     0.6863     0.9098        117       1024: 20% ━━────────── 25/124 6.5it/s 3.9s<15.2s

      33/50      10.1G      1.625     0.6849     0.9063        105       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.9s

      33/50      10.1G      1.633     0.6856     0.9058        115       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.6s

      33/50      10.1G      1.626     0.6811     0.9033        123       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      33/50      10.1G      1.629     0.6801     0.9034        115       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.1s

      33/50      10.1G      1.636      0.683     0.9053         97       1024: 24% ━━╸───────── 30/124 6.8it/s 4.7s<13.9s

      33/50      10.1G       1.63     0.6789      0.904        116       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.4s

      33/50      10.1G      1.625     0.6797     0.9029        105       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<13.9s

      33/50      10.1G      1.617     0.6779     0.9015         96       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.6s

      33/50      10.1G      1.609     0.6765     0.8998        108       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      33/50      10.1G      1.603     0.6751     0.8993        112       1024: 28% ━━━───────── 35/124 6.8it/s 5.4s<13.2s

      33/50      10.1G      1.606     0.6744     0.8999        115       1024: 29% ━━━───────── 36/124 6.8it/s 5.6s<13.0s

      33/50      10.1G      1.604     0.6726     0.9006        127       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      33/50      10.1G      1.612     0.6745     0.9017        125       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.7s

      33/50      10.1G      1.609     0.6733        0.9        120       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

      33/50      10.1G      1.613     0.6745     0.9003        122       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      33/50      10.1G      1.614     0.6755      0.901        131       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

      33/50      10.1G      1.611     0.6737        0.9        112       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      33/50      10.1G      1.614     0.6737     0.8994        136       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

      33/50      10.1G      1.616     0.6729     0.9009        112       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

      33/50      10.1G      1.615       0.67     0.9005        120       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

      33/50      10.1G      1.622     0.6714     0.9011        101       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      33/50      10.1G      1.626     0.6746      0.902        122       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.2s<12.0s

      33/50      10.1G       1.62     0.6722     0.9006        116       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.4s<11.8s

      33/50      10.1G       1.62     0.6716     0.9005        112       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.5s<11.4s

      33/50      10.1G      1.624     0.6726     0.9008        131       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.1s

      33/50      10.1G      1.625     0.6734     0.9005        117       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.9s

      33/50      10.1G      1.622     0.6715     0.8995        124       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.0s<10.7s

      33/50      10.1G       1.62     0.6733     0.8987        114       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.4s

      33/50      10.1G      1.621     0.6735     0.8986        111       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      33/50      10.1G      1.625     0.6732     0.8993        118       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

      33/50      10.1G      1.625     0.6731     0.8992        117       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.2s

      33/50      10.1G      1.619     0.6711     0.8984        111       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

      33/50      10.1G      1.617     0.6712     0.8988         99       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.9s

      33/50      10.1G      1.619     0.6711      0.899        107       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.0s<9.7s

      33/50      10.1G       1.62     0.6707     0.8993         99       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.2s<9.5s

      33/50      10.1G       1.62     0.6722     0.8997        101       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.4s

      33/50      10.1G      1.621     0.6727     0.9006        101       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      33/50      10.1G      1.621     0.6724     0.9012         98       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

      33/50      10.1G      1.623     0.6729     0.9005        120       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      33/50      10.1G      1.627     0.6746     0.9007        133       1024: 52% ━━━━━━────── 65/124 6.7it/s 9.9s<8.8s

      33/50      10.1G      1.624     0.6729        0.9        118       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.6s

      33/50      10.1G      1.622     0.6731     0.8997        100       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.2s<8.4s

      33/50      10.1G      1.621     0.6726     0.8993        115       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.2s

      33/50      10.1G      1.619     0.6732     0.8987        100       1024: 56% ━━━━━━╸───── 69/124 6.9it/s 10.5s<8.0s

      33/50      10.1G      1.616     0.6712     0.8985         95       1024: 56% ━━━━━━╸───── 70/124 6.9it/s 10.7s<7.9s

      33/50      10.1G      1.613     0.6703     0.8978        116       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 10.8s<8.1s

      33/50      10.1G      1.615     0.6715     0.8985        123       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.0s<7.8s

      33/50      10.1G      1.613       0.67     0.8978        106       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      33/50      10.1G      1.611     0.6688     0.8972        115       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

      33/50      10.1G      1.613     0.6687     0.8973        114       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.4s<7.2s

      33/50      10.1G      1.612      0.668     0.8962        115       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.6s<7.1s

      33/50      10.1G      1.613     0.6687     0.8966        113       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.7s<6.9s

      33/50      10.1G      1.613     0.6679     0.8982        118       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.7s

      33/50      10.1G      1.619     0.6697     0.8994        106       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.0s<6.9s

      33/50      10.1G      1.622     0.6709     0.8998        124       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.6s

      33/50      10.1G      1.624     0.6711     0.9003        121       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.3s<6.4s

      33/50      10.1G      1.626     0.6717     0.9008        113       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.5s<6.2s

      33/50      10.1G      1.624     0.6715     0.9006        119       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.6s<6.0s

      33/50      10.1G      1.626     0.6717     0.9002         98       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.7s<5.8s

      33/50      10.1G      1.627     0.6717     0.9007        113       1024: 69% ━━━━━━━━──── 85/124 6.9it/s 12.9s<5.7s

      33/50      10.1G      1.626     0.6713     0.9004        110       1024: 69% ━━━━━━━━──── 86/124 6.9it/s 13.0s<5.5s

      33/50      10.1G      1.626     0.6707     0.9008         99       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.2s<5.6s

      33/50      10.1G      1.624     0.6697     0.9005        117       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.4s

      33/50      10.1G      1.622     0.6691        0.9        106       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.5s<5.2s

      33/50      10.1G      1.622     0.6699        0.9        108       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.6s<5.1s

      33/50      10.1G      1.625     0.6705     0.9003        120       1024: 73% ━━━━━━━━╸─── 91/124 6.8it/s 13.8s<4.9s

      33/50      10.1G      1.622     0.6692     0.8996        106       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 13.9s<4.8s

      33/50      10.1G      1.623     0.6701        0.9        120       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

      33/50      10.1G      1.621     0.6695        0.9        111       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.2s<4.5s

      33/50      10.1G      1.622     0.6699     0.8999        125       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.4s<4.5s

      33/50      10.1G      1.622     0.6694     0.9005        115       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.6s<4.3s

      33/50      10.1G       1.62     0.6695     0.8999        120       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.7s<4.1s

      33/50      10.1G      1.619     0.6682     0.8998        101       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      33/50      10.1G       1.62     0.6688     0.8994        119       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.0s<3.7s

      33/50      10.1G       1.62     0.6685      0.899        111       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.1s<3.5s

      33/50      10.1G      1.619     0.6679     0.8996         89       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.3s<3.4s

      33/50      10.1G      1.619     0.6677     0.8994        126       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.4s<3.2s

      33/50      10.1G      1.619      0.668     0.8994        124       1024: 83% ━━━━━━━━━╸── 103/124 6.5it/s 15.6s<3.2s

      33/50      10.1G      1.618     0.6674     0.8993        112       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 15.8s<3.1s

      33/50      10.1G       1.62      0.668     0.9001        118       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 15.9s<2.9s

      33/50      10.1G      1.619     0.6676     0.9003        102       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      33/50      10.1G      1.619      0.668     0.9008         86       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.2s<2.5s

      33/50      10.1G      1.618     0.6678     0.9003        126       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      33/50      10.1G      1.619     0.6678        0.9        120       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.5s<2.2s

      33/50      10.1G      1.618     0.6675     0.8996        120       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

      33/50      10.1G      1.616     0.6664     0.8992        129       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.8s<2.0s

      33/50      10.1G      1.615     0.6667     0.8994        124       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.0s<1.9s

      33/50      10.1G      1.616     0.6673     0.8992        109       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.1s<1.7s

      33/50      10.1G      1.614     0.6671     0.8993        107       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      33/50      10.1G      1.613      0.668     0.8996         89       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.4s<1.3s

      33/50      10.1G      1.612     0.6676     0.8993         98       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      33/50      10.1G      1.613     0.6687      0.899        104       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.7s<1.0s

      33/50      10.1G      1.612     0.6684     0.8988        105       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      33/50      10.1G      1.613      0.669     0.8989        113       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.0s<0.8s

      33/50      10.1G      1.616       0.67     0.8993        121       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.2s<0.6s

      33/50      10.1G      1.617     0.6696     0.8994        117       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.3s<0.5s

      33/50      10.1G      1.615     0.6687     0.8993        113       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.5s<0.3s

      33/50      10.1G      1.614     0.6681     0.8991        105       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.6s<0.1s

      33/50      10.1G      1.614     0.6681     0.8991        105       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.8it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.4it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.5it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.6it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.7it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.7it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.7it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.7it/s 1.8s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.7it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.7it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.8it/s 2.4s

                   all        330       4227      0.676      0.612      0.627      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      34/50      10.1G      1.563     0.6343     0.8504        112       1024: 0% ──────────── 0/124  0.1s

      34/50      10.1G      1.563     0.6318     0.8704        118       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      34/50      10.1G      1.564     0.6421     0.8693        111       1024: 2% ──────────── 2/124 3.5it/s 0.4s<35.0s

      34/50      10.1G      1.548     0.6281     0.8595        129       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.8s

      34/50      10.1G      1.557     0.6451     0.8718        130       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.4s

      34/50      10.1G      1.559     0.6363     0.8727         88       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.6s

      34/50      10.1G      1.615     0.6628     0.8753        115       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.1s

      34/50      10.1G      1.623     0.6588     0.8868         97       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.2s

      34/50      10.1G      1.639       0.67     0.8953        120       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.4s

      34/50      10.1G      1.624     0.6681     0.8954        120       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.8s

      34/50      10.1G      1.605     0.6585     0.8939        123       1024: 8% ╸─────────── 10/124 6.6it/s 1.7s<17.3s

      34/50      10.1G      1.589     0.6538     0.8899        107       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      34/50      10.1G      1.577     0.6525     0.8873        112       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.4s

      34/50      10.1G      1.576     0.6507     0.8883        119       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.9s

      34/50      10.1G      1.581     0.6547     0.8932        119       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      34/50      10.1G      1.592     0.6565      0.894        108       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.3s

      34/50      10.1G       1.59     0.6599     0.8933        102       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.0s

      34/50      10.1G      1.587     0.6606     0.8976        110       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      34/50      10.1G      1.594     0.6625     0.8982        107       1024: 15% ━╸────────── 18/124 6.8it/s 2.9s<15.6s

      34/50      10.1G      1.596     0.6586     0.8958        117       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.2s

      34/50      10.1G      1.595     0.6611     0.8942        123       1024: 16% ━╸────────── 20/124 6.6it/s 3.2s<15.7s

      34/50      10.1G      1.599     0.6629     0.8971        101       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      34/50      10.1G      1.596     0.6601     0.8956        114       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      34/50      10.1G      1.589     0.6606     0.8943         94       1024: 19% ━━────────── 23/124 6.6it/s 3.6s<15.4s

      34/50      10.1G      1.591     0.6646     0.8958        108       1024: 19% ━━────────── 24/124 6.6it/s 3.8s<15.0s

      34/50      10.1G      1.599     0.6637     0.8961        125       1024: 20% ━━────────── 25/124 6.7it/s 3.9s<14.8s

      34/50      10.1G      1.596     0.6618     0.8943        121       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.5s

      34/50      10.1G      1.601     0.6618     0.8945        113       1024: 22% ━━╸───────── 27/124 6.4it/s 4.2s<15.2s

      34/50      10.1G      1.601     0.6643     0.8935         91       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.7s

      34/50      10.1G       1.61      0.665      0.895        116       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.3s

      34/50      10.1G      1.605     0.6625     0.8932        105       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      34/50      10.1G      1.613     0.6639     0.8963        119       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

      34/50      10.1G      1.614     0.6638     0.8958        100       1024: 26% ━━━───────── 32/124 6.8it/s 5.0s<13.6s

      34/50      10.1G      1.606     0.6589     0.8942        107       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      34/50      10.1G        1.6     0.6573     0.8928        115       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.3s

      34/50      10.1G      1.596     0.6593      0.893        111       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.8s

      34/50      10.1G      1.608     0.6642     0.8933        115       1024: 29% ━━━───────── 36/124 6.6it/s 5.6s<13.4s

      34/50      10.1G      1.606     0.6609     0.8939         95       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

      34/50      10.1G       1.61     0.6626     0.8937        118       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      34/50      10.1G      1.616     0.6635     0.8943        119       1024: 31% ━━━╸──────── 39/124 6.8it/s 6.0s<12.6s

      34/50      10.1G      1.616     0.6648     0.8933        125       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.2s<12.4s

      34/50      10.1G      1.616     0.6653     0.8948        112       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.2s

      34/50      10.1G      1.614     0.6651     0.8939        106       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.0s

      34/50      10.1G      1.623     0.6675     0.8959        118       1024: 35% ━━━━──────── 43/124 6.5it/s 6.6s<12.5s

      34/50      10.1G      1.624     0.6673     0.8978        105       1024: 35% ━━━━──────── 44/124 6.6it/s 6.8s<12.1s

      34/50      10.1G      1.622     0.6656     0.8973        107       1024: 36% ━━━━──────── 45/124 6.7it/s 6.9s<11.8s

      34/50      10.1G      1.626     0.6672     0.8979        117       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      34/50      10.1G      1.626     0.6668     0.8969        105       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.2s<11.4s

      34/50      10.1G      1.627     0.6677     0.8983        108       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      34/50      10.1G      1.625     0.6671     0.8988        117       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.0s

      34/50      10.1G      1.632     0.6677     0.8989        133       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      34/50      10.1G      1.632     0.6678     0.8995        100       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.8s<11.3s

      34/50      10.1G      1.632     0.6671     0.8995         99       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      34/50      10.1G      1.632     0.6659     0.8992        125       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.1s<10.6s

      34/50      10.1G       1.63     0.6641     0.8989        117       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      34/50      10.1G      1.628     0.6629     0.8992        114       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.2s

      34/50      10.1G      1.626     0.6623     0.8988        109       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      34/50      10.1G      1.625     0.6629     0.8986        123       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.9s

      34/50      10.1G      1.624      0.663     0.8988        109       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.7s

      34/50      10.1G      1.629     0.6653     0.8991        121       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.0s<10.0s

      34/50      10.1G      1.627     0.6641     0.8986        127       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

      34/50      10.1G      1.625     0.6637     0.8988        126       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.4s

      34/50      10.1G      1.624     0.6636     0.8984        131       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.2s

      34/50      10.1G      1.621      0.662     0.8978        127       1024: 51% ━━━━━━────── 63/124 6.8it/s 9.6s<9.0s

      34/50      10.1G      1.619     0.6615      0.898        114       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.8s<8.9s

      34/50      10.1G      1.621     0.6608     0.8986        121       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      34/50      10.1G      1.622     0.6612     0.8982        119       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.5s

      34/50      10.1G      1.623     0.6615     0.8977        117       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.2s<8.8s

      34/50      10.1G      1.621     0.6611     0.8975        125       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.4s<8.6s

      34/50      10.1G      1.626     0.6625     0.8982        113       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.5s<8.4s

      34/50      10.1G      1.626     0.6618     0.8974        106       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.2s

      34/50      10.1G      1.626     0.6624     0.8972        110       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 10.8s<8.0s

      34/50      10.1G      1.629     0.6652     0.8976        115       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.0s<7.8s

      34/50      10.1G      1.627     0.6638     0.8972        119       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      34/50      10.1G      1.627     0.6634      0.897        112       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.5s

      34/50      10.1G      1.624      0.662     0.8965        124       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.5s<7.7s

      34/50      10.1G      1.622     0.6609      0.896        130       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

      34/50      10.1G      1.622     0.6617     0.8962        112       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      34/50      10.1G      1.623      0.664     0.8964        138       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<7.0s

      34/50      10.1G       1.62     0.6626     0.8958        116       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.8s

      34/50      10.1G       1.62     0.6628     0.8962        111       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.7s

      34/50      10.1G       1.62     0.6627     0.8965        119       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      34/50      10.1G      1.619     0.6628     0.8972        108       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      34/50      10.1G      1.615     0.6605     0.8965        125       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.7s<6.4s

      34/50      10.1G      1.615     0.6612     0.8967        107       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.8s<6.2s

      34/50      10.1G      1.615     0.6609     0.8964        123       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.0s<5.9s

      34/50      10.1G      1.616     0.6616     0.8966        111       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.7s

      34/50      10.1G      1.614     0.6611      0.896        122       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.5s

      34/50      10.1G      1.613     0.6606     0.8959        108       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.4s

      34/50      10.1G       1.61     0.6597     0.8953        108       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.6s<5.2s

      34/50      10.1G      1.609     0.6594     0.8954        115       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.0s

      34/50      10.1G      1.606     0.6581     0.8944        113       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 13.9s<5.1s

      34/50      10.1G      1.606     0.6577     0.8944        112       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.0s<4.9s

      34/50      10.1G      1.604     0.6573     0.8941        113       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      34/50      10.1G      1.603     0.6568      0.894        114       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.3s<4.5s

      34/50      10.1G      1.603     0.6576     0.8941        116       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.5s<4.4s

      34/50      10.1G      1.601     0.6565     0.8933        120       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.6s<4.2s

      34/50      10.1G      1.601     0.6565     0.8935        117       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

      34/50      10.1G        1.6     0.6565     0.8937         97       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      34/50      10.1G      1.598     0.6555      0.893        126       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.1s<3.9s

      34/50      10.1G      1.599     0.6556     0.8935         94       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.3s<3.7s

      34/50      10.1G      1.598     0.6552      0.893        103       1024: 81% ━━━━━━━━━╸── 101/124 6.5it/s 15.4s<3.5s

      34/50      10.1G      1.598      0.655     0.8931        108       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.5s<3.3s

      34/50      10.1G      1.597      0.655     0.8925        109       1024: 83% ━━━━━━━━━╸── 103/124 6.6it/s 15.7s<3.2s

      34/50      10.1G      1.599     0.6554     0.8925        120       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.8s<3.0s

      34/50      10.1G      1.601      0.657     0.8934         98       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.0s<2.8s

      34/50      10.1G      1.601     0.6568      0.893        125       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      34/50      10.1G      1.601     0.6567     0.8934        116       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.3s<2.7s

      34/50      10.1G      1.601     0.6563     0.8936         99       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.5s<2.5s

      34/50      10.1G      1.602      0.657     0.8939         99       1024: 88% ━━━━━━━━━━╸─ 109/124 6.5it/s 16.6s<2.3s

      34/50      10.1G      1.601     0.6565     0.8938        115       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.8s<2.1s

      34/50      10.1G        1.6     0.6568     0.8934        132       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.9s<1.9s

      34/50      10.1G        1.6     0.6569      0.894         92       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.1s<1.8s

      34/50      10.1G      1.601      0.656     0.8946        108       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.7s

      34/50      10.1G      1.601     0.6552     0.8948        106       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

      34/50      10.1G      1.602     0.6555     0.8947        124       1024: 93% ━━━━━━━━━━━─ 115/124 6.4it/s 17.5s<1.4s

      34/50      10.1G      1.602     0.6554     0.8949        111       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.7s<1.2s

      34/50      10.1G      1.604     0.6557     0.8954        110       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.8s<1.1s

      34/50      10.1G      1.603      0.655     0.8961        103       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      34/50      10.1G      1.603     0.6548     0.8958        102       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.1s<0.7s

      34/50      10.1G      1.603     0.6542     0.8957        115       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.3s<0.6s

      34/50      10.1G      1.601     0.6537     0.8956         99       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.4s<0.4s

      34/50      10.1G      1.603     0.6533     0.8958        127       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.6s<0.3s

      34/50      10.1G      1.603     0.6536     0.8956        126       1024: 99% ━━━━━━━━━━━╸ 123/124 6.3it/s 18.8s<0.2s

      34/50      10.1G      1.603     0.6536     0.8956        126       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.1it/s 0.6s<2.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.8it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.659      0.611      0.619      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      35/50      10.1G      1.478     0.5586     0.8744        129       1024: 0% ──────────── 0/124  0.1s

      35/50      10.1G       1.52     0.6291     0.8857        117       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:01

      35/50      10.1G      1.585     0.6447     0.8687        105       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.4s

      35/50      10.1G      1.577     0.6268     0.8716        106       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.6s

      35/50      10.1G      1.572     0.6226     0.9036        106       1024: 3% ──────────── 4/124 5.0it/s 0.7s<23.8s

      35/50      10.1G      1.577      0.634     0.9043        107       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.3s

      35/50      10.1G      1.559     0.6508     0.8987         91       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.8s

      35/50      10.1G      1.549     0.6403     0.8914        115       1024: 6% ╸─────────── 7/124 5.8it/s 1.2s<20.1s

      35/50      10.1G      1.591      0.652     0.8973        113       1024: 6% ╸─────────── 8/124 6.0it/s 1.4s<19.3s

      35/50      10.1G      1.587     0.6452     0.8951        116       1024: 7% ╸─────────── 9/124 6.1it/s 1.5s<18.8s

      35/50      10.1G      1.582     0.6478     0.9051        111       1024: 8% ╸─────────── 10/124 6.3it/s 1.7s<18.0s

      35/50      10.1G      1.578      0.647     0.8988        130       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.6s

      35/50      10.1G      1.589     0.6489     0.9014        119       1024: 10% ━─────────── 12/124 6.6it/s 2.0s<17.0s

      35/50      10.1G      1.612     0.6567     0.9058        122       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.6s

      35/50      10.1G      1.616     0.6552     0.9046        125       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.5s

      35/50      10.1G      1.618     0.6576     0.9064        116       1024: 12% ━─────────── 15/124 6.3it/s 2.4s<17.2s

      35/50      10.1G      1.617     0.6574     0.9027        135       1024: 13% ━╸────────── 16/124 6.4it/s 2.6s<17.0s

      35/50      10.1G      1.618      0.653     0.8981        129       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.4s

      35/50      10.1G      1.602     0.6504     0.8952        107       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.0s

      35/50      10.1G      1.604     0.6517     0.8954        101       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      35/50      10.1G      1.601     0.6483     0.8909        143       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.4s

      35/50      10.1G      1.618     0.6538     0.8936        106       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      35/50      10.1G      1.613     0.6504     0.8933        111       1024: 18% ━━────────── 22/124 6.8it/s 3.5s<15.0s

      35/50      10.1G      1.602     0.6438     0.8911        120       1024: 19% ━━────────── 23/124 6.5it/s 3.6s<15.5s

      35/50      10.1G      1.608     0.6497     0.8902        111       1024: 19% ━━────────── 24/124 6.6it/s 3.8s<15.1s

      35/50      10.1G      1.594     0.6492     0.8866        107       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      35/50      10.1G      1.598     0.6504     0.8875        108       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

      35/50      10.1G      1.597     0.6512     0.8882        106       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.4s

      35/50      10.1G        1.6     0.6539     0.8903         93       1024: 23% ━━╸───────── 28/124 6.8it/s 4.4s<14.2s

      35/50      10.1G      1.601     0.6529      0.891        114       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

      35/50      10.1G      1.595     0.6504      0.889        126       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<13.9s

      35/50      10.1G      1.594     0.6515     0.8877        128       1024: 25% ━━━───────── 31/124 6.4it/s 4.9s<14.4s

      35/50      10.1G      1.589     0.6476     0.8881        124       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<14.0s

      35/50      10.1G      1.588     0.6476     0.8868        111       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.6s

      35/50      10.1G       1.59     0.6466     0.8885        112       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      35/50      10.1G      1.594     0.6504     0.8895        102       1024: 28% ━━━───────── 35/124 6.8it/s 5.4s<13.2s

      35/50      10.1G       1.59      0.649       0.89        109       1024: 29% ━━━───────── 36/124 6.8it/s 5.6s<13.0s

      35/50      10.1G       1.59     0.6483     0.8915        122       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      35/50      10.1G      1.594     0.6505     0.8921        120       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      35/50      10.1G      1.596     0.6512     0.8917        114       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.3s

      35/50      10.1G      1.595     0.6496     0.8912        118       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

      35/50      10.1G       1.59     0.6477     0.8905        128       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.5s

      35/50      10.1G      1.586     0.6455     0.8884        119       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

      35/50      10.1G      1.585     0.6441      0.888        114       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.0s

      35/50      10.1G      1.589      0.644     0.8873        119       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

      35/50      10.1G      1.587     0.6434     0.8875        108       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      35/50      10.1G      1.595     0.6464     0.8877        137       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      35/50      10.1G      1.594      0.646     0.8881         96       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<12.0s

      35/50      10.1G      1.597     0.6469     0.8884        112       1024: 39% ━━━━╸─────── 48/124 6.5it/s 7.4s<11.6s

      35/50      10.1G      1.597     0.6457     0.8893        109       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.6s<11.3s

      35/50      10.1G      1.596      0.646     0.8889        142       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      35/50      10.1G      1.593     0.6438     0.8891        113       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<10.8s

      35/50      10.1G        1.6     0.6479     0.8897        150       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      35/50      10.1G        1.6     0.6478     0.8912        107       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.6s

      35/50      10.1G      1.601     0.6478     0.8906        100       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      35/50      10.1G      1.601     0.6473     0.8903        108       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.8s

      35/50      10.1G      1.602     0.6475      0.891        105       1024: 45% ━━━━━─────── 56/124 6.5it/s 8.6s<10.4s

      35/50      10.1G      1.601     0.6462     0.8901        104       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.8s<10.1s

      35/50      10.1G      1.602     0.6463     0.8906        101       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.9s

      35/50      10.1G      1.601     0.6454     0.8904        115       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.6s

      35/50      10.1G      1.603     0.6475     0.8907        102       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.5s

      35/50      10.1G      1.602     0.6473     0.8918        111       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      35/50      10.1G      1.601     0.6477     0.8919        110       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      35/50      10.1G      1.599     0.6472     0.8921        116       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.7s<9.4s

      35/50      10.1G      1.599     0.6468     0.8924        111       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      35/50      10.1G        1.6     0.6467      0.893        102       1024: 52% ━━━━━━────── 65/124 6.7it/s 10.0s<8.9s

      35/50      10.1G        1.6     0.6469     0.8931        106       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      35/50      10.1G      1.595     0.6457     0.8921        104       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.3s<8.5s

      35/50      10.1G      1.594     0.6453     0.8929        112       1024: 55% ━━━━━━╸───── 68/124 6.8it/s 10.4s<8.3s

      35/50      10.1G      1.595     0.6457     0.8928        127       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.6s<8.1s

      35/50      10.1G      1.597     0.6459      0.894        116       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<8.0s

      35/50      10.1G      1.592     0.6451     0.8934        113       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.9s<8.2s

      35/50      10.1G       1.59      0.644     0.8929        106       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.9s

      35/50      10.1G      1.592      0.644     0.8928        130       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.2s<7.6s

      35/50      10.1G      1.593     0.6443     0.8933        109       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.3s<7.4s

      35/50      10.1G      1.595     0.6444     0.8936        115       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.5s<7.2s

      35/50      10.1G      1.596     0.6441     0.8933        126       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      35/50      10.1G      1.593     0.6435     0.8931        114       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.8s<6.9s

      35/50      10.1G      1.591     0.6426     0.8934         93       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

      35/50      10.1G      1.591     0.6431     0.8935        119       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.1s<6.9s

      35/50      10.1G      1.589     0.6425     0.8938        108       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.2s<6.7s

      35/50      10.1G      1.589     0.6421     0.8936        112       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      35/50      10.1G      1.589     0.6413     0.8937        105       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      35/50      10.1G       1.59      0.642     0.8939        108       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.7s<6.1s

      35/50      10.1G       1.59     0.6422     0.8951        110       1024: 68% ━━━━━━━━──── 84/124 6.7it/s 12.8s<5.9s

      35/50      10.1G      1.592     0.6425     0.8948        118       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 13.0s<5.8s

      35/50      10.1G      1.592     0.6421     0.8949        112       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      35/50      10.1G      1.593     0.6423     0.8951        112       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.7s

      35/50      10.1G      1.595     0.6425      0.895        115       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.5s

      35/50      10.1G      1.594     0.6414     0.8943        120       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      35/50      10.1G      1.599     0.6443     0.8959        102       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      35/50      10.1G        1.6     0.6444     0.8954        125       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

      35/50      10.1G      1.601     0.6447     0.8954        119       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.0s<4.7s

      35/50      10.1G      1.597     0.6444     0.8954        102       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.2s<4.6s

      35/50      10.1G      1.597     0.6451     0.8954         87       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.3s<4.4s

      35/50      10.1G      1.598     0.6459     0.8952        126       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

      35/50      10.1G      1.597     0.6449     0.8952        105       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.2s

      35/50      10.1G      1.597     0.6454     0.8956         91       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.8s<4.0s

      35/50      10.1G      1.596     0.6446     0.8956         99       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      35/50      10.1G      1.594     0.6441     0.8953        120       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.1s<3.7s

      35/50      10.1G      1.593     0.6428     0.8954        121       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.2s<3.6s

      35/50      10.1G      1.593     0.6426      0.895        104       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.4s<3.5s

      35/50      10.1G      1.593     0.6426     0.8954        104       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.5s<3.3s

      35/50      10.1G      1.592      0.642     0.8949        125       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

      35/50      10.1G      1.591     0.6415     0.8945        103       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.8s<3.1s

      35/50      10.1G      1.588     0.6408     0.8945        115       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.0s<2.9s

      35/50      10.1G      1.587       0.64     0.8943         93       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.1s<2.7s

      35/50      10.1G      1.587     0.6405     0.8945        108       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.3s<2.5s

      35/50      10.1G      1.589     0.6413     0.8951        111       1024: 87% ━━━━━━━━━━── 108/124 6.7it/s 16.4s<2.4s

      35/50      10.1G      1.588     0.6413     0.8948        106       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

      35/50      10.1G      1.587     0.6403     0.8943        114       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.7s<2.1s

      35/50      10.1G      1.587     0.6401     0.8943        114       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 16.9s<2.0s

      35/50      10.1G      1.586     0.6395     0.8939        115       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.0s<1.8s

      35/50      10.1G      1.588       0.64     0.8935        122       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.2s<1.7s

      35/50      10.1G      1.589     0.6402     0.8935        116       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.3s<1.5s

      35/50      10.1G      1.587     0.6392     0.8931        118       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.3s

      35/50      10.1G      1.586     0.6383     0.8929        111       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.6s<1.2s

      35/50      10.1G      1.584     0.6381     0.8926        103       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.0s

      35/50      10.1G      1.584     0.6381     0.8925        102       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      35/50      10.1G      1.586     0.6386     0.8925        128       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

      35/50      10.1G      1.584     0.6381     0.8915        118       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.2s<0.6s

      35/50      10.1G      1.584     0.6377     0.8914        132       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.4s

      35/50      10.1G      1.584     0.6381     0.8917        122       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

      35/50      10.1G      1.584     0.6371     0.8915        103       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.7s<0.1s

      35/50      10.1G      1.584     0.6371     0.8915        103       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.7it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.7it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.7it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.7it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.7it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.679      0.593      0.616      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      36/50      10.1G      1.698     0.6849     0.9451        103       1024: 0% ──────────── 0/124  0.1s

      36/50      10.1G      1.627     0.6421     0.9227        109       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.4s

      36/50      10.1G      1.528     0.6246     0.8862        124       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.8s

      36/50      10.1G      1.501      0.623     0.8958        119       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.7s

      36/50      10.1G      1.478     0.6076     0.8922        125       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.9s

      36/50      10.1G      1.475     0.6039     0.8789        114       1024: 4% ──────────── 5/124 5.4it/s 0.9s<21.9s

      36/50      10.1G      1.508     0.6131     0.8912        129       1024: 5% ╸─────────── 6/124 5.8it/s 1.1s<20.4s

      36/50      10.1G      1.495     0.6057     0.8893        103       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.2s

      36/50      10.1G      1.531     0.6204     0.8931         99       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.5s

      36/50      10.1G      1.536     0.6195     0.8893        115       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<17.8s

      36/50      10.1G      1.544     0.6214     0.8889        102       1024: 8% ╸─────────── 10/124 6.5it/s 1.7s<17.6s

      36/50      10.1G      1.545     0.6254     0.8915        109       1024: 9% ━─────────── 11/124 6.2it/s 1.8s<18.3s

      36/50      10.1G       1.54     0.6221     0.8869        128       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.5s

      36/50      10.1G      1.567     0.6271     0.8894        109       1024: 10% ━─────────── 13/124 6.6it/s 2.1s<16.9s

      36/50      10.1G      1.567     0.6276     0.8882        119       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.5s

      36/50      10.1G      1.564     0.6288     0.8872         98       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.2s

      36/50      10.1G       1.56     0.6299      0.886        118       1024: 13% ━╸────────── 16/124 6.8it/s 2.6s<16.0s

      36/50      10.1G       1.56     0.6279     0.8859        100       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.7s

      36/50      10.1G      1.569     0.6363     0.8892        111       1024: 15% ━╸────────── 18/124 6.8it/s 2.9s<15.5s

      36/50      10.1G      1.559     0.6337     0.8867        113       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.1s

      36/50      10.1G      1.554     0.6284     0.8858        115       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<15.9s

      36/50      10.1G      1.552     0.6279     0.8829        119       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.7s

      36/50      10.1G      1.548     0.6245     0.8829        108       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.4s

      36/50      10.1G      1.555     0.6258     0.8826        111       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

      36/50      10.1G       1.54      0.619     0.8799        102       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

      36/50      10.1G       1.54     0.6195     0.8776        122       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<14.9s

      36/50      10.1G      1.543      0.625     0.8773        115       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      36/50      10.1G      1.547     0.6267     0.8792        108       1024: 22% ━━╸───────── 27/124 6.4it/s 4.3s<15.3s

      36/50      10.1G      1.556      0.631     0.8802        113       1024: 23% ━━╸───────── 28/124 6.3it/s 4.4s<15.2s

      36/50      10.1G      1.554     0.6319     0.8809        105       1024: 23% ━━╸───────── 29/124 6.5it/s 4.6s<14.6s

      36/50      10.1G      1.552     0.6343     0.8815        105       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.2s

      36/50      10.1G      1.556     0.6374     0.8831         94       1024: 25% ━━━───────── 31/124 6.5it/s 4.9s<14.3s

      36/50      10.1G      1.573      0.643     0.8849        116       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.1s

      36/50      10.1G      1.575     0.6475      0.886        111       1024: 27% ━━━───────── 33/124 6.6it/s 5.2s<13.7s

      36/50      10.1G       1.58     0.6457     0.8876         91       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

      36/50      10.1G      1.575     0.6439     0.8866        101       1024: 28% ━━━───────── 35/124 6.3it/s 5.5s<14.0s

      36/50      10.1G      1.575     0.6436     0.8869        118       1024: 29% ━━━───────── 36/124 6.4it/s 5.7s<13.7s

      36/50      10.1G      1.578     0.6473     0.8896        108       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.3s

      36/50      10.1G      1.577     0.6481     0.8917        110       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.0s

      36/50      10.1G      1.579     0.6487     0.8922        105       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.1s<12.7s

      36/50      10.1G      1.583     0.6511     0.8934        103       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.2s<12.4s

      36/50      10.1G      1.582     0.6499     0.8929        111       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.4s<12.2s

      36/50      10.1G      1.581     0.6515     0.8935        116       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.0s

      36/50      10.1G      1.579     0.6496     0.8921        116       1024: 35% ━━━━──────── 43/124 6.5it/s 6.7s<12.5s

      36/50      10.1G      1.579     0.6498      0.891        114       1024: 35% ━━━━──────── 44/124 6.5it/s 6.9s<12.3s

      36/50      10.1G       1.58      0.649     0.8911        118       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<11.9s

      36/50      10.1G      1.585     0.6508     0.8922         96       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      36/50      10.1G      1.583     0.6502      0.893        115       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.4s

      36/50      10.1G      1.583     0.6513     0.8944        118       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      36/50      10.1G      1.579     0.6478     0.8934         95       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.6s<11.1s

      36/50      10.1G      1.574     0.6457     0.8924         94       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      36/50      10.1G      1.575     0.6465     0.8918        107       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.4s

      36/50      10.1G      1.576     0.6456     0.8924        125       1024: 42% ━━━━━─────── 52/124 6.4it/s 8.1s<11.2s

      36/50      10.1G      1.579     0.6453      0.893        106       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.8s

      36/50      10.1G      1.577     0.6442      0.893         99       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.4s<10.5s

      36/50      10.1G      1.574      0.642     0.8926        123       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.5s<10.3s

      36/50      10.1G      1.577     0.6437     0.8927        109       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.1s

      36/50      10.1G      1.577      0.643     0.8917         97       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.8s<10.0s

      36/50      10.1G      1.578      0.644     0.8922        113       1024: 47% ━━━━━╸────── 58/124 6.6it/s 9.0s<9.9s

      36/50      10.1G      1.583     0.6461     0.8926         93       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.1s<10.2s

      36/50      10.1G      1.586     0.6473     0.8926        118       1024: 48% ━━━━━╸────── 60/124 6.4it/s 9.3s<10.0s

      36/50      10.1G      1.591     0.6488     0.8923        115       1024: 49% ━━━━━╸────── 61/124 6.4it/s 9.4s<9.8s

      36/50      10.1G      1.588     0.6466     0.8914        117       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.6s<9.5s

      36/50      10.1G      1.586     0.6459     0.8913        106       1024: 51% ━━━━━━────── 63/124 6.6it/s 9.7s<9.2s

      36/50      10.1G      1.586     0.6454     0.8917        107       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.9s<9.0s

      36/50      10.1G      1.585     0.6446     0.8921        113       1024: 52% ━━━━━━────── 65/124 6.5it/s 10.0s<9.0s

      36/50      10.1G      1.587     0.6451     0.8933        126       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.7s

      36/50      10.1G      1.591     0.6459     0.8935        119       1024: 54% ━━━━━━────── 67/124 6.3it/s 10.4s<9.1s

      36/50      10.1G      1.589     0.6456     0.8929        111       1024: 55% ━━━━━━╸───── 68/124 6.4it/s 10.5s<8.8s

      36/50      10.1G      1.592     0.6469     0.8934        122       1024: 56% ━━━━━━╸───── 69/124 6.5it/s 10.7s<8.5s

      36/50      10.1G      1.592     0.6465     0.8937        100       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.8s<8.2s

      36/50      10.1G      1.593     0.6465     0.8938        119       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 11.0s<7.9s

      36/50      10.1G       1.59     0.6448     0.8924        112       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.7s

      36/50      10.1G      1.589     0.6452     0.8925        101       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      36/50      10.1G      1.587     0.6441     0.8914        123       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.4s<7.3s

      36/50      10.1G      1.587     0.6432     0.8908        112       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.6s<7.6s

      36/50      10.1G      1.588     0.6432     0.8907        115       1024: 61% ━━━━━━━───── 76/124 6.6it/s 11.7s<7.3s

      36/50      10.1G      1.587     0.6425     0.8906        103       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.9s<7.1s

      36/50      10.1G       1.59     0.6433     0.8916        115       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      36/50      10.1G      1.591     0.6423      0.892        109       1024: 64% ━━━━━━━╸──── 79/124 6.8it/s 12.2s<6.7s

      36/50      10.1G       1.59     0.6415     0.8916        116       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.3s<6.5s

      36/50      10.1G      1.589     0.6412     0.8915        112       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.4s<6.3s

      36/50      10.1G      1.587      0.641     0.8909        108       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.6s<6.1s

      36/50      10.1G      1.585     0.6404     0.8904        124       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.8s<6.3s

      36/50      10.1G      1.588     0.6413     0.8911        122       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.1s

      36/50      10.1G      1.588      0.641     0.8911        114       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.1s<5.9s

      36/50      10.1G      1.585     0.6396     0.8907        124       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      36/50      10.1G      1.586     0.6396     0.8906        110       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.4s<5.6s

      36/50      10.1G      1.588     0.6407     0.8909        134       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.5s<5.4s

      36/50      10.1G      1.587     0.6401     0.8904        120       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.6s<5.2s

      36/50      10.1G      1.587     0.6397     0.8903        120       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.8s<5.0s

      36/50      10.1G      1.585     0.6385     0.8908        110       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 14.0s<5.1s

      36/50      10.1G      1.587     0.6391     0.8912        120       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.1s<4.8s

      36/50      10.1G      1.588     0.6399     0.8913        116       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.3s<4.6s

      36/50      10.1G      1.591     0.6409      0.892        104       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      36/50      10.1G      1.588     0.6398     0.8915        102       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.6s<4.3s

      36/50      10.1G      1.587     0.6395     0.8915        113       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.7s<4.2s

      36/50      10.1G      1.584     0.6384     0.8911        117       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.9s<4.1s

      36/50      10.1G      1.583     0.6381     0.8913        111       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

      36/50      10.1G      1.583     0.6381     0.8916        104       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.2s<3.9s

      36/50      10.1G      1.583     0.6386     0.8922        119       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.3s<3.7s

      36/50      10.1G      1.579     0.6376     0.8918        116       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

      36/50      10.1G      1.581      0.638     0.8918        111       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.6s<3.3s

      36/50      10.1G      1.579     0.6381     0.8913        100       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.8s<3.1s

      36/50      10.1G      1.581     0.6382     0.8914        117       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.9s<3.0s

      36/50      10.1G       1.58     0.6382      0.891        105       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.1s<2.8s

      36/50      10.1G      1.582     0.6396     0.8908        113       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.2s<2.6s

      36/50      10.1G      1.583     0.6395     0.8903        121       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.4s<2.6s

      36/50      10.1G      1.585     0.6391     0.8902        123       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.5s<2.4s

      36/50      10.1G      1.586     0.6396     0.8898        104       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.7s<2.3s

      36/50      10.1G      1.587     0.6403     0.8904         98       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.8s<2.1s

      36/50      10.1G      1.588     0.6407     0.8906        100       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 17.0s<1.9s

      36/50      10.1G      1.586     0.6401     0.8907        136       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.1s<1.8s

      36/50      10.1G      1.589     0.6404      0.891        117       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.3s<1.6s

      36/50      10.1G      1.589     0.6401     0.8915         93       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.4s<1.5s

      36/50      10.1G       1.59     0.6405     0.8918        127       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.6s<1.4s

      36/50      10.1G      1.589     0.6396     0.8912        101       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.7s<1.2s

      36/50      10.1G      1.588     0.6397     0.8911        123       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.9s<1.1s

      36/50      10.1G      1.589     0.6407     0.8906        135       1024: 95% ━━━━━━━━━━━─ 118/124 6.5it/s 18.0s<0.9s

      36/50      10.1G      1.587     0.6399     0.8901        110       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.2s<0.8s

      36/50      10.1G      1.586     0.6392     0.8896        108       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.4s<0.6s

      36/50      10.1G      1.586      0.639     0.8894        137       1024: 98% ━━━━━━━━━━━╸ 121/124 6.4it/s 18.5s<0.5s

      36/50      10.1G      1.587     0.6395     0.8899        117       1024: 98% ━━━━━━━━━━━╸ 122/124 6.5it/s 18.7s<0.3s

      36/50      10.1G      1.589     0.6396     0.8901        127       1024: 99% ━━━━━━━━━━━╸ 123/124 6.2it/s 18.8s<0.2s

      36/50      10.1G      1.589     0.6396     0.8901        127       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.7it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 7.9it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.0it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.3it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.3it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.3it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.659      0.631      0.626      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      37/50      10.1G      1.525     0.6149     0.8454        118       1024: 0% ──────────── 0/124  0.1s

      37/50      10.1G      1.496     0.5859     0.8514        116       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.2s

      37/50      10.1G      1.554     0.5973     0.8707        115       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.7s

      37/50      10.1G      1.562     0.5784     0.8841        106       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.8s

      37/50      10.1G       1.59     0.5962     0.8901        118       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.0s

      37/50      10.1G      1.606     0.6009     0.8951        130       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.9s

      37/50      10.1G       1.62     0.6085     0.8971        101       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.6s

      37/50      10.1G      1.624     0.6206     0.8962        111       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.7s

      37/50      10.1G      1.643     0.6331     0.8918        122       1024: 6% ╸─────────── 8/124 6.1it/s 1.3s<18.9s

      37/50      10.1G       1.62     0.6229     0.8857         99       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.3s

      37/50      10.1G      1.613     0.6178     0.8839        112       1024: 8% ╸─────────── 10/124 6.3it/s 1.7s<18.1s

      37/50      10.1G      1.604     0.6205      0.881         97       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.5s

      37/50      10.1G      1.598     0.6174     0.8824        113       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<17.0s

      37/50      10.1G      1.593     0.6162     0.8806        116       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

      37/50      10.1G       1.58     0.6108     0.8797        108       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.8s

      37/50      10.1G      1.565     0.6063     0.8753        130       1024: 12% ━─────────── 15/124 6.2it/s 2.4s<17.5s

      37/50      10.1G      1.563     0.6049     0.8767        113       1024: 13% ━╸────────── 16/124 6.3it/s 2.6s<17.3s

      37/50      10.1G      1.571     0.6104     0.8786        119       1024: 14% ━╸────────── 17/124 6.4it/s 2.7s<16.6s

      37/50      10.1G       1.58     0.6177     0.8855        101       1024: 15% ━╸────────── 18/124 6.6it/s 2.9s<16.2s

      37/50      10.1G       1.57     0.6222     0.8841        100       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<15.9s

      37/50      10.1G      1.573     0.6235     0.8827        120       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.6s

      37/50      10.1G      1.568       0.62      0.881        116       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.6s

      37/50      10.1G      1.572     0.6245     0.8861        106       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.2s

      37/50      10.1G      1.569     0.6246     0.8855        108       1024: 19% ━━────────── 23/124 6.2it/s 3.7s<16.2s

      37/50      10.1G      1.564     0.6239     0.8846        112       1024: 19% ━━────────── 24/124 6.3it/s 3.8s<15.8s

      37/50      10.1G      1.563     0.6269      0.885        105       1024: 20% ━━────────── 25/124 6.5it/s 4.0s<15.3s

      37/50      10.1G      1.556     0.6241     0.8825         98       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.9s

      37/50      10.1G      1.559     0.6259     0.8817        108       1024: 22% ━━╸───────── 27/124 6.7it/s 4.3s<14.5s

      37/50      10.1G      1.564     0.6277     0.8805        123       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      37/50      10.1G      1.564     0.6265     0.8804        108       1024: 23% ━━╸───────── 29/124 6.6it/s 4.6s<14.3s

      37/50      10.1G      1.556      0.622     0.8793        127       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      37/50      10.1G      1.553     0.6219     0.8785        111       1024: 25% ━━━───────── 31/124 6.4it/s 4.9s<14.5s

      37/50      10.1G      1.551     0.6239      0.878        116       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.1s

      37/50      10.1G      1.546     0.6209     0.8771        111       1024: 27% ━━━───────── 33/124 6.6it/s 5.2s<13.7s

      37/50      10.1G      1.541     0.6214      0.876        113       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      37/50      10.1G      1.542     0.6234     0.8764        124       1024: 28% ━━━───────── 35/124 6.7it/s 5.5s<13.3s

      37/50      10.1G      1.541     0.6236     0.8762        120       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.2s

      37/50      10.1G      1.539     0.6225     0.8757        126       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.8s<13.0s

      37/50      10.1G      1.535     0.6214     0.8747        113       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.7s

      37/50      10.1G      1.541     0.6219     0.8759        115       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.2s

      37/50      10.1G      1.546     0.6236     0.8774         98       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<13.0s

      37/50      10.1G      1.548     0.6236     0.8778        107       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.6s

      37/50      10.1G      1.545     0.6207     0.8785        100       1024: 34% ━━━━──────── 42/124 6.6it/s 6.6s<12.5s

      37/50      10.1G      1.545     0.6204     0.8789        127       1024: 35% ━━━━──────── 43/124 6.6it/s 6.7s<12.2s

      37/50      10.1G      1.546     0.6222     0.8792        110       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<11.9s

      37/50      10.1G      1.545     0.6218      0.879        130       1024: 36% ━━━━──────── 45/124 6.7it/s 7.0s<11.7s

      37/50      10.1G      1.541     0.6209     0.8776        102       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      37/50      10.1G      1.539     0.6204     0.8765        107       1024: 38% ━━━━╸─────── 47/124 6.3it/s 7.3s<12.2s

      37/50      10.1G      1.539     0.6204     0.8761        131       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.5s<11.9s

      37/50      10.1G      1.542     0.6204     0.8763        125       1024: 40% ━━━━╸─────── 49/124 6.5it/s 7.6s<11.5s

      37/50      10.1G       1.54     0.6205     0.8766        115       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.8s<11.2s

      37/50      10.1G      1.539     0.6212     0.8768        125       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<10.9s

      37/50      10.1G      1.545     0.6224     0.8768        137       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.1s<10.7s

      37/50      10.1G      1.542     0.6205     0.8757        117       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.2s<10.5s

      37/50      10.1G      1.539     0.6189     0.8761        102       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.4s<10.4s

      37/50      10.1G      1.539       0.62     0.8769        120       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.7s

      37/50      10.1G      1.538     0.6202     0.8774        110       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.7s<10.4s

      37/50      10.1G      1.541     0.6213     0.8772        123       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.8s<10.1s

      37/50      10.1G      1.544     0.6225     0.8777        122       1024: 47% ━━━━━╸────── 58/124 6.7it/s 9.0s<9.9s

      37/50      10.1G       1.54      0.621     0.8783        103       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.7s

      37/50      10.1G      1.541     0.6214      0.878        107       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.3s<9.5s

      37/50      10.1G      1.548      0.624     0.8792        118       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      37/50      10.1G      1.549     0.6247     0.8793        105       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.6s<9.1s

      37/50      10.1G      1.548     0.6244     0.8793        107       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.7s<9.4s

      37/50      10.1G      1.552      0.625     0.8794        109       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.9s<9.3s

      37/50      10.1G      1.557     0.6253     0.8797        120       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.0s<9.0s

      37/50      10.1G      1.553     0.6244     0.8796         99       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.7s

      37/50      10.1G      1.552     0.6244     0.8798        123       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.3s<8.5s

      37/50      10.1G      1.548     0.6232     0.8799        116       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.5s<8.3s

      37/50      10.1G      1.548      0.623     0.8795        119       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.6s<8.1s

      37/50      10.1G      1.547      0.623     0.8793        107       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.8s<8.0s

      37/50      10.1G      1.544     0.6221     0.8783        121       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.9s<8.2s

      37/50      10.1G      1.545      0.624     0.8794        117       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.1s<8.0s

      37/50      10.1G      1.544     0.6242     0.8792         93       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.7s

      37/50      10.1G      1.547     0.6245      0.879        118       1024: 60% ━━━━━━━───── 74/124 6.6it/s 11.4s<7.6s

      37/50      10.1G      1.544     0.6235     0.8781         88       1024: 60% ━━━━━━━───── 75/124 6.6it/s 11.5s<7.4s

      37/50      10.1G      1.548     0.6256     0.8792        128       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.7s<7.2s

      37/50      10.1G      1.551      0.627     0.8801        117       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      37/50      10.1G       1.55     0.6267     0.8802        122       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 12.0s<6.9s

      37/50      10.1G      1.549     0.6263     0.8806        118       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.2s<7.1s

      37/50      10.1G      1.545     0.6246     0.8797        121       1024: 65% ━━━━━━━╸──── 80/124 6.4it/s 12.3s<6.8s

      37/50      10.1G      1.543     0.6238     0.8787        127       1024: 65% ━━━━━━━╸──── 81/124 6.5it/s 12.5s<6.6s

      37/50      10.1G      1.548     0.6264     0.8794        103       1024: 66% ━━━━━━━╸──── 82/124 6.5it/s 12.6s<6.4s

      37/50      10.1G       1.55     0.6263     0.8797        119       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.8s<6.3s

      37/50      10.1G      1.548     0.6256       0.88        119       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.9s<6.1s

      37/50      10.1G      1.547     0.6262     0.8799         99       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.1s<5.9s

      37/50      10.1G      1.547     0.6267     0.8807        107       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      37/50      10.1G      1.546     0.6255     0.8804        128       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.4s<5.8s

      37/50      10.1G      1.546     0.6258     0.8809        103       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.5s

      37/50      10.1G      1.547     0.6263     0.8823        100       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.7s<5.3s

      37/50      10.1G      1.544     0.6248     0.8816        121       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

      37/50      10.1G      1.545     0.6252     0.8817        102       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 14.0s<4.9s

      37/50      10.1G      1.546     0.6251     0.8813        114       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.1s<4.7s

      37/50      10.1G      1.549     0.6267     0.8816        118       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.3s<4.6s

      37/50      10.1G      1.547     0.6257     0.8817        115       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.4s<4.4s

      37/50      10.1G      1.549     0.6258     0.8823        114       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.6s<4.5s

      37/50      10.1G      1.553     0.6268     0.8824        145       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.8s<4.3s

      37/50      10.1G      1.552     0.6266     0.8827        111       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.9s<4.1s

      37/50      10.1G      1.551     0.6264     0.8826        109       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

      37/50      10.1G      1.551     0.6251     0.8824        115       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.2s<3.7s

      37/50      10.1G      1.552     0.6244     0.8825        117       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.3s<3.6s

      37/50      10.1G      1.551     0.6241     0.8822        122       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

      37/50      10.1G      1.551     0.6243     0.8822        106       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      37/50      10.1G       1.55     0.6239     0.8817        114       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.8s<3.3s

      37/50      10.1G      1.552     0.6246     0.8824        113       1024: 84% ━━━━━━━━━━── 104/124 6.5it/s 16.0s<3.1s

      37/50      10.1G      1.552     0.6245     0.8829        103       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.1s<2.9s

      37/50      10.1G      1.552     0.6254     0.8826        127       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.3s<2.7s

      37/50      10.1G       1.55     0.6248     0.8822        105       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.4s<2.5s

      37/50      10.1G      1.549     0.6239      0.882        120       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.5s<2.4s

      37/50      10.1G       1.55     0.6242     0.8823        117       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.7s<2.2s

      37/50      10.1G      1.552     0.6241     0.8821        105       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.8s<2.1s

      37/50      10.1G      1.551     0.6235     0.8817        118       1024: 90% ━━━━━━━━━━╸─ 111/124 6.3it/s 17.0s<2.0s

      37/50      10.1G      1.553     0.6234     0.8817        134       1024: 90% ━━━━━━━━━━╸─ 112/124 6.4it/s 17.2s<1.9s

      37/50      10.1G      1.553      0.624     0.8818        109       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 17.3s<1.7s

      37/50      10.1G      1.553     0.6245     0.8815        119       1024: 92% ━━━━━━━━━━━─ 114/124 6.6it/s 17.5s<1.5s

      37/50      10.1G      1.553     0.6241     0.8818         97       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.6s<1.3s

      37/50      10.1G      1.554     0.6241     0.8817        131       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.8s<1.2s

      37/50      10.1G      1.556     0.6247     0.8822        103       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.9s<1.0s

      37/50      10.1G      1.557     0.6253     0.8824        112       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 18.1s<0.9s

      37/50      10.1G      1.557     0.6243     0.8823        127       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.2s<0.8s

      37/50      10.1G      1.558     0.6241     0.8823        114       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.4s<0.6s

      37/50      10.1G      1.557      0.624     0.8825         98       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.5s<0.5s

      37/50      10.1G      1.557     0.6237     0.8824        100       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.7s<0.3s

      37/50      10.1G      1.557      0.624     0.8826        101       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.8s<0.1s

      37/50      10.1G      1.557      0.624     0.8826        101       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.6it/s 0.1s<7.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.683      0.629      0.626      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      38/50      10.1G      1.514     0.5925     0.9136        102       1024: 0% ──────────── 0/124  0.1s

      38/50      10.1G       1.62      0.634     0.9273        120       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:01

      38/50      10.1G       1.58      0.629     0.9162        117       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.4s

      38/50      10.1G      1.553     0.6184     0.9062        114       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.3s

      38/50      10.1G      1.548     0.6126      0.904        133       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.6s

      38/50      10.1G      1.546     0.6226     0.8969        112       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.7s

      38/50      10.1G       1.56     0.6318      0.896        118       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.2s

      38/50      10.1G      1.561     0.6221     0.8938        118       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<19.0s

      38/50      10.1G      1.554     0.6296     0.8892         94       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.5s

      38/50      10.1G      1.554      0.624      0.883        109       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.8s

      38/50      10.1G       1.57     0.6293     0.8817        121       1024: 8% ╸─────────── 10/124 6.6it/s 1.7s<17.3s

      38/50      10.1G      1.578     0.6377     0.8825        123       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<18.0s

      38/50      10.1G      1.572     0.6424     0.8805         91       1024: 10% ━─────────── 12/124 6.3it/s 2.0s<17.7s

      38/50      10.1G      1.561      0.636     0.8765        133       1024: 10% ━─────────── 13/124 6.3it/s 2.1s<17.7s

      38/50      10.1G      1.559     0.6339     0.8741        120       1024: 11% ━─────────── 14/124 6.5it/s 2.3s<17.0s

      38/50      10.1G      1.573     0.6379     0.8777        116       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.8s

      38/50      10.1G      1.588     0.6436     0.8793        118       1024: 13% ━╸────────── 16/124 6.5it/s 2.6s<16.6s

      38/50      10.1G      1.573     0.6363     0.8748        113       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      38/50      10.1G      1.569     0.6306     0.8743        115       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      38/50      10.1G      1.568     0.6277     0.8734        109       1024: 15% ━╸────────── 19/124 6.4it/s 3.1s<16.4s

      38/50      10.1G      1.564      0.627     0.8701        110       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.0s

      38/50      10.1G      1.573     0.6323     0.8705        110       1024: 17% ━━────────── 21/124 6.6it/s 3.4s<15.6s

      38/50      10.1G      1.561     0.6256     0.8692        100       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.3s

      38/50      10.1G      1.558      0.625     0.8688        131       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

      38/50      10.1G      1.559     0.6263     0.8673        121       1024: 19% ━━────────── 24/124 6.8it/s 3.8s<14.7s

      38/50      10.1G       1.56     0.6258     0.8705        101       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.5s

      38/50      10.1G      1.556     0.6222     0.8717        122       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.5s

      38/50      10.1G      1.574     0.6323     0.8759        125       1024: 22% ━━╸───────── 27/124 6.4it/s 4.3s<15.1s

      38/50      10.1G      1.577     0.6317     0.8756        126       1024: 23% ━━╸───────── 28/124 6.6it/s 4.4s<14.6s

      38/50      10.1G       1.58     0.6328      0.877        100       1024: 23% ━━╸───────── 29/124 6.7it/s 4.6s<14.2s

      38/50      10.1G      1.577     0.6314     0.8797        109       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.0s

      38/50      10.1G      1.577     0.6308     0.8793        113       1024: 25% ━━━───────── 31/124 6.8it/s 4.8s<13.7s

      38/50      10.1G       1.58     0.6298     0.8797        120       1024: 26% ━━━───────── 32/124 6.8it/s 5.0s<13.5s

      38/50      10.1G      1.586     0.6329     0.8815        109       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      38/50      10.1G      1.592      0.635     0.8806        120       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.2s

      38/50      10.1G      1.585     0.6326     0.8818         99       1024: 28% ━━━───────── 35/124 6.5it/s 5.5s<13.7s

      38/50      10.1G      1.579     0.6314      0.881        111       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.4s

      38/50      10.1G      1.576     0.6283     0.8809        120       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.1s

      38/50      10.1G      1.572     0.6263       0.88        108       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      38/50      10.1G      1.576     0.6265     0.8802        113       1024: 31% ━━━╸──────── 39/124 6.7it/s 6.0s<12.6s

      38/50      10.1G      1.578     0.6303     0.8797        111       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.2s<12.4s

      38/50      10.1G      1.578     0.6303     0.8796        104       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.2s

      38/50      10.1G      1.573      0.628     0.8791        111       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.0s

      38/50      10.1G      1.574     0.6274     0.8788        107       1024: 35% ━━━━──────── 43/124 6.5it/s 6.7s<12.4s

      38/50      10.1G      1.572     0.6259      0.878        129       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.3s

      38/50      10.1G      1.569     0.6253     0.8763        111       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<11.9s

      38/50      10.1G      1.564     0.6228     0.8756        120       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      38/50      10.1G       1.56     0.6224      0.876        123       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      38/50      10.1G      1.563     0.6227     0.8773        110       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      38/50      10.1G      1.564     0.6231     0.8773        108       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.1s

      38/50      10.1G      1.566     0.6247     0.8787        129       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      38/50      10.1G      1.566     0.6224     0.8779        124       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.9s<11.3s

      38/50      10.1G      1.564     0.6219     0.8772        116       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      38/50      10.1G      1.563     0.6209     0.8763        113       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.6s

      38/50      10.1G      1.564     0.6213     0.8753        102       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      38/50      10.1G      1.565     0.6215      0.875        125       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.2s

      38/50      10.1G      1.568     0.6225     0.8755        108       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      38/50      10.1G       1.57     0.6222      0.876        112       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.9s

      38/50      10.1G      1.568     0.6223     0.8766        120       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      38/50      10.1G      1.571     0.6238     0.8784         97       1024: 48% ━━━━━╸────── 59/124 6.4it/s 9.1s<10.1s

      38/50      10.1G      1.571     0.6238      0.879        112       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.2s<9.9s

      38/50      10.1G      1.571     0.6235     0.8787        122       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

      38/50      10.1G      1.568     0.6229     0.8785        107       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.5s<9.3s

      38/50      10.1G      1.574     0.6252     0.8794        116       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

      38/50      10.1G      1.571     0.6234     0.8789        124       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.8s<8.9s

      38/50      10.1G      1.571     0.6237      0.879        114       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.0s<8.9s

      38/50      10.1G      1.567      0.622     0.8775        109       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.1s<8.7s

      38/50      10.1G      1.563     0.6206     0.8771        118       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

      38/50      10.1G      1.562     0.6199     0.8761        123       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.4s<8.6s

      38/50      10.1G      1.567     0.6212     0.8788        111       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

      38/50      10.1G       1.57      0.622     0.8785        117       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.7s<8.1s

      38/50      10.1G      1.566       0.62     0.8774        113       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      38/50      10.1G      1.567     0.6198     0.8776        126       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.7s

      38/50      10.1G      1.564     0.6195     0.8774        107       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      38/50      10.1G      1.564     0.6209     0.8774        102       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.3s

      38/50      10.1G      1.561     0.6201      0.877        113       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.5s<7.5s

      38/50      10.1G      1.559     0.6191     0.8772        103       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.3s

      38/50      10.1G      1.559     0.6188     0.8772        120       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      38/50      10.1G      1.561     0.6191     0.8779        117       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<7.0s

      38/50      10.1G      1.562     0.6199     0.8779        117       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.8s

      38/50      10.1G      1.562     0.6215     0.8781        129       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.2s<6.5s

      38/50      10.1G      1.562     0.6219     0.8778         97       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.4s<6.4s

      38/50      10.1G      1.561     0.6226     0.8778        118       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.5s<6.2s

      38/50      10.1G       1.56     0.6234     0.8779         92       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.7s<6.3s

      38/50      10.1G      1.559     0.6229     0.8775        107       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.8s<6.0s

      38/50      10.1G      1.559      0.623     0.8783        110       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 13.0s<5.8s

      38/50      10.1G      1.561     0.6236      0.879        124       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.7s

      38/50      10.1G      1.559     0.6228     0.8782        107       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.3s<5.6s

      38/50      10.1G      1.559     0.6226     0.8784        112       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.4s<5.5s

      38/50      10.1G      1.557     0.6221     0.8784        108       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      38/50      10.1G      1.557     0.6219     0.8784        111       1024: 73% ━━━━━━━━╸─── 90/124 6.6it/s 13.7s<5.2s

      38/50      10.1G      1.557     0.6211     0.8785        115       1024: 73% ━━━━━━━━╸─── 91/124 6.2it/s 13.9s<5.3s

      38/50      10.1G      1.556     0.6209     0.8786        107       1024: 74% ━━━━━━━━╸─── 92/124 6.4it/s 14.1s<5.0s

      38/50      10.1G      1.559     0.6223     0.8785        100       1024: 75% ━━━━━━━━━─── 93/124 6.5it/s 14.2s<4.7s

      38/50      10.1G      1.558     0.6215     0.8793        105       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      38/50      10.1G      1.558     0.6223     0.8796        104       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.5s<4.4s

      38/50      10.1G      1.558     0.6227     0.8791        125       1024: 77% ━━━━━━━━━─── 96/124 6.4it/s 14.7s<4.4s

      38/50      10.1G       1.56     0.6237     0.8794        112       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

      38/50      10.1G       1.56     0.6248     0.8798         96       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

      38/50      10.1G       1.56     0.6245     0.8795        116       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.2s<3.9s

      38/50      10.1G      1.559     0.6238     0.8797        114       1024: 81% ━━━━━━━━━╸── 100/124 6.5it/s 15.3s<3.7s

      38/50      10.1G      1.559     0.6235     0.8798        108       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.4s<3.5s

      38/50      10.1G      1.557     0.6232     0.8797        108       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      38/50      10.1G      1.559     0.6236     0.8799        118       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.7s<3.1s

      38/50      10.1G      1.559     0.6235     0.8797        108       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.9s<3.0s

      38/50      10.1G      1.558     0.6229     0.8796        102       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 16.0s<2.8s

      38/50      10.1G       1.56     0.6245     0.8804        131       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      38/50      10.1G      1.558     0.6232     0.8804        117       1024: 86% ━━━━━━━━━━── 107/124 6.4it/s 16.4s<2.6s

      38/50      10.1G      1.558      0.623       0.88        111       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.5s<2.4s

      38/50      10.1G      1.558     0.6242     0.8798         97       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

      38/50      10.1G      1.558     0.6254     0.8799         97       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.8s<2.1s

      38/50      10.1G      1.558     0.6253     0.8798        127       1024: 90% ━━━━━━━━━━╸─ 111/124 6.8it/s 16.9s<1.9s

      38/50      10.1G      1.558     0.6256     0.8802        104       1024: 90% ━━━━━━━━━━╸─ 112/124 6.8it/s 17.1s<1.8s

      38/50      10.1G      1.559     0.6253     0.8801        110       1024: 91% ━━━━━━━━━━╸─ 113/124 6.9it/s 17.2s<1.6s

      38/50      10.1G      1.558     0.6245     0.8803        117       1024: 92% ━━━━━━━━━━━─ 114/124 6.9it/s 17.4s<1.5s

      38/50      10.1G      1.556     0.6238     0.8801        118       1024: 93% ━━━━━━━━━━━─ 115/124 6.6it/s 17.5s<1.4s

      38/50      10.1G      1.556     0.6236     0.8804        110       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.7s<1.2s

      38/50      10.1G      1.559     0.6251     0.8808         94       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.8s<1.0s

      38/50      10.1G      1.558     0.6245     0.8809        138       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 18.0s<0.9s

      38/50      10.1G      1.558     0.6246     0.8811        107       1024: 96% ━━━━━━━━━━━╸ 119/124 6.8it/s 18.1s<0.7s

      38/50      10.1G      1.558     0.6244     0.8813        122       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.3s<0.6s

      38/50      10.1G      1.556     0.6232     0.8808        107       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.4s

      38/50      10.1G      1.556     0.6235     0.8808        114       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.6s<0.3s

      38/50      10.1G      1.555     0.6229     0.8803        101       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.7s<0.2s

      38/50      10.1G      1.555     0.6229     0.8803        101       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.0it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.0s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.7it/s 1.4s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.644      0.631      0.621      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      39/50      10.1G      1.289     0.5615     0.7763        115       1024: 0% ──────────── 0/124  0.1s

      39/50      10.1G      1.452     0.6292     0.8382        112       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.3s

      39/50      10.1G      1.471     0.6086     0.8588        109       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.7s

      39/50      10.1G      1.573     0.6496     0.8723        119       1024: 2% ──────────── 3/124 4.5it/s 0.6s<26.7s

      39/50      10.1G      1.547     0.6385      0.872        119       1024: 3% ──────────── 4/124 5.2it/s 0.7s<22.9s

      39/50      10.1G      1.553     0.6281     0.8689        123       1024: 4% ──────────── 5/124 5.7it/s 0.9s<20.8s

      39/50      10.1G      1.548     0.6197     0.8696        109       1024: 5% ╸─────────── 6/124 6.1it/s 1.0s<19.4s

      39/50      10.1G      1.527     0.6084     0.8715        107       1024: 6% ╸─────────── 7/124 6.0it/s 1.2s<19.5s

      39/50      10.1G      1.529     0.6135     0.8701        128       1024: 6% ╸─────────── 8/124 6.2it/s 1.3s<18.7s

      39/50      10.1G      1.531     0.6133     0.8776        104       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<18.0s

      39/50      10.1G      1.516     0.6073     0.8777        111       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.4s

      39/50      10.1G      1.512     0.6013     0.8746        116       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.0s

      39/50      10.1G      1.532     0.6088     0.8764        126       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.7s

      39/50      10.1G      1.533     0.6072     0.8738        114       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      39/50      10.1G      1.543     0.6115     0.8742        105       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.2s

      39/50      10.1G      1.539     0.6163     0.8778         99       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.8s

      39/50      10.1G      1.532     0.6219     0.8792         93       1024: 13% ━╸────────── 16/124 6.5it/s 2.5s<16.6s

      39/50      10.1G      1.533      0.625     0.8847        118       1024: 14% ━╸────────── 17/124 6.5it/s 2.7s<16.5s

      39/50      10.1G      1.541     0.6266     0.8859        121       1024: 15% ━╸────────── 18/124 6.5it/s 2.8s<16.4s

      39/50      10.1G      1.533     0.6269     0.8848        104       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.1s

      39/50      10.1G      1.553     0.6335     0.8865        119       1024: 16% ━╸────────── 20/124 6.6it/s 3.1s<15.7s

      39/50      10.1G      1.553     0.6339     0.8869        112       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      39/50      10.1G      1.563     0.6376     0.8883        113       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.2s

      39/50      10.1G      1.568     0.6382     0.8895        107       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.9s

      39/50      10.1G       1.56     0.6359     0.8878        105       1024: 19% ━━────────── 24/124 6.4it/s 3.8s<15.5s

      39/50      10.1G      1.555     0.6334     0.8854        116       1024: 20% ━━────────── 25/124 6.5it/s 3.9s<15.2s

      39/50      10.1G      1.551     0.6345      0.885        100       1024: 21% ━━╸───────── 26/124 6.6it/s 4.1s<14.8s

      39/50      10.1G      1.542     0.6326     0.8823         99       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.5s

      39/50      10.1G       1.54     0.6298     0.8816        113       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      39/50      10.1G      1.532     0.6263     0.8806        108       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.1s

      39/50      10.1G      1.531     0.6253     0.8813        105       1024: 24% ━━╸───────── 30/124 6.8it/s 4.7s<13.9s

      39/50      10.1G      1.528     0.6231     0.8805        116       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.5s

      39/50      10.1G      1.527      0.623     0.8823        115       1024: 26% ━━━───────── 32/124 6.4it/s 5.0s<14.3s

      39/50      10.1G      1.531     0.6247     0.8831        110       1024: 27% ━━━───────── 33/124 6.5it/s 5.1s<13.9s

      39/50      10.1G      1.526     0.6223     0.8818        118       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.7s

      39/50      10.1G      1.539     0.6267     0.8839         97       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.4s

      39/50      10.1G      1.541     0.6288     0.8845        123       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

      39/50      10.1G      1.539     0.6264     0.8831        107       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.9s

      39/50      10.1G      1.543      0.628     0.8831        115       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      39/50      10.1G      1.536     0.6251     0.8821        116       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.2s

      39/50      10.1G      1.545     0.6269     0.8816        115       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      39/50      10.1G      1.545     0.6258      0.882        108       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

      39/50      10.1G      1.542     0.6237     0.8805        114       1024: 34% ━━━━──────── 42/124 6.6it/s 6.5s<12.4s

      39/50      10.1G      1.539     0.6208     0.8795        107       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.1s

      39/50      10.1G       1.54     0.6192     0.8778        138       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<12.0s

      39/50      10.1G      1.536     0.6188     0.8772        118       1024: 36% ━━━━──────── 45/124 6.7it/s 6.9s<11.8s

      39/50      10.1G      1.535     0.6171     0.8763        124       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      39/50      10.1G      1.531     0.6163     0.8757        124       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<12.0s

      39/50      10.1G      1.531     0.6161      0.875        104       1024: 39% ━━━━╸─────── 48/124 6.4it/s 7.4s<11.8s

      39/50      10.1G      1.535     0.6167      0.875        108       1024: 40% ━━━━╸─────── 49/124 6.6it/s 7.6s<11.4s

      39/50      10.1G      1.534     0.6167     0.8758        100       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.1s

      39/50      10.1G      1.536     0.6178     0.8758        127       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.9s<10.9s

      39/50      10.1G      1.536     0.6173     0.8757        111       1024: 42% ━━━━━─────── 52/124 6.7it/s 8.0s<10.7s

      39/50      10.1G      1.542     0.6185     0.8762        125       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.8s

      39/50      10.1G      1.544     0.6192     0.8772        124       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.5s

      39/50      10.1G      1.544      0.619     0.8775        111       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.8s

      39/50      10.1G      1.543     0.6178     0.8776        107       1024: 45% ━━━━━─────── 56/124 6.5it/s 8.6s<10.4s

      39/50      10.1G      1.544     0.6184      0.879        109       1024: 46% ━━━━━╸────── 57/124 6.5it/s 8.8s<10.2s

      39/50      10.1G      1.542     0.6169     0.8786        123       1024: 47% ━━━━━╸────── 58/124 6.6it/s 8.9s<10.0s

      39/50      10.1G      1.547     0.6187     0.8785        111       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.7s

      39/50      10.1G      1.542     0.6162     0.8784        112       1024: 48% ━━━━━╸────── 60/124 6.7it/s 9.2s<9.5s

      39/50      10.1G       1.54     0.6151      0.878         97       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      39/50      10.1G       1.54     0.6157     0.8794        106       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.2s

      39/50      10.1G      1.538      0.615      0.879        116       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.7s<9.5s

      39/50      10.1G      1.535     0.6134     0.8781        106       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.8s<9.1s

      39/50      10.1G      1.531     0.6123     0.8775        113       1024: 52% ━━━━━━────── 65/124 6.5it/s 10.0s<9.0s

      39/50      10.1G      1.532     0.6128     0.8775        118       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.1s<8.8s

      39/50      10.1G      1.535     0.6137      0.878        107       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.3s<8.5s

      39/50      10.1G      1.539     0.6151     0.8785        119       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.4s<8.5s

      39/50      10.1G      1.541     0.6173     0.8789        110       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.4s

      39/50      10.1G      1.543     0.6196     0.8789        113       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.7s<8.2s

      39/50      10.1G      1.546     0.6209     0.8797        105       1024: 57% ━━━━━━╸───── 71/124 6.3it/s 10.9s<8.4s

      39/50      10.1G      1.545     0.6215     0.8797        108       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.1s<8.0s

      39/50      10.1G      1.545     0.6218     0.8798         93       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.2s<7.7s

      39/50      10.1G      1.542     0.6211      0.879        113       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

      39/50      10.1G      1.543     0.6204     0.8796        118       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.5s<7.3s

      39/50      10.1G      1.541     0.6195     0.8793         96       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      39/50      10.1G      1.538     0.6188     0.8781        105       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.8s<6.9s

      39/50      10.1G       1.54     0.6195      0.878        117       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.8s

      39/50      10.1G       1.54     0.6193     0.8778        105       1024: 64% ━━━━━━━╸──── 79/124 6.4it/s 12.1s<7.0s

      39/50      10.1G      1.539     0.6191     0.8779        125       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.3s<6.7s

      39/50      10.1G       1.54     0.6195     0.8784        100       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.4s<6.5s

      39/50      10.1G      1.539     0.6195     0.8789        115       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

      39/50      10.1G      1.538     0.6185     0.8789        136       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.7s<6.1s

      39/50      10.1G      1.538     0.6193      0.879        111       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.9s<5.9s

      39/50      10.1G       1.54     0.6196     0.8785        118       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 13.0s<5.7s

      39/50      10.1G      1.542     0.6203     0.8791        102       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.2s<5.7s

      39/50      10.1G      1.544      0.621     0.8801        115       1024: 70% ━━━━━━━━──── 87/124 6.4it/s 13.3s<5.8s

      39/50      10.1G      1.543     0.6204     0.8794        120       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.5s

      39/50      10.1G      1.542     0.6198     0.8797        120       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.6s<5.3s

      39/50      10.1G      1.543       0.62     0.8796        106       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.8s<5.1s

      39/50      10.1G      1.541     0.6197     0.8793        117       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.9s<4.9s

      39/50      10.1G      1.542     0.6193     0.8799        119       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 14.1s<4.7s

      39/50      10.1G      1.542     0.6186       0.88        115       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.2s<4.6s

      39/50      10.1G      1.543     0.6184     0.8802        135       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.4s<4.4s

      39/50      10.1G      1.542     0.6176       0.88        109       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.5s<4.5s

      39/50      10.1G      1.544     0.6192     0.8812         96       1024: 77% ━━━━━━━━━─── 96/124 6.5it/s 14.7s<4.3s

      39/50      10.1G      1.548     0.6205     0.8815        102       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

      39/50      10.1G      1.549     0.6205     0.8813        128       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 15.0s<3.9s

      39/50      10.1G      1.548     0.6192     0.8814        109       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.1s<3.7s

      39/50      10.1G      1.547     0.6197     0.8814         99       1024: 81% ━━━━━━━━━╸── 100/124 6.7it/s 15.3s<3.6s

      39/50      10.1G      1.547     0.6201     0.8813        132       1024: 81% ━━━━━━━━━╸── 101/124 6.8it/s 15.4s<3.4s

      39/50      10.1G      1.547     0.6201     0.8812        121       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      39/50      10.1G      1.548       0.62     0.8814        111       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.7s<3.3s

      39/50      10.1G       1.55       0.62     0.8816        112       1024: 84% ━━━━━━━━━━── 104/124 6.4it/s 15.9s<3.1s

      39/50      10.1G       1.55     0.6196     0.8816        105       1024: 85% ━━━━━━━━━━── 105/124 6.5it/s 16.0s<2.9s

      39/50      10.1G      1.551     0.6201     0.8818        109       1024: 85% ━━━━━━━━━━── 106/124 6.4it/s 16.2s<2.8s

      39/50      10.1G      1.549     0.6201     0.8817        105       1024: 86% ━━━━━━━━━━── 107/124 6.6it/s 16.4s<2.6s

      39/50      10.1G      1.549     0.6199     0.8814        120       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.5s<2.4s

      39/50      10.1G      1.549     0.6208     0.8813        115       1024: 88% ━━━━━━━━━━╸─ 109/124 6.7it/s 16.6s<2.2s

      39/50      10.1G      1.548     0.6209      0.882        106       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.8s<2.1s

      39/50      10.1G      1.549     0.6205     0.8822        110       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 17.0s<2.0s

      39/50      10.1G      1.548     0.6209     0.8818        105       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.1s<1.9s

      39/50      10.1G      1.549     0.6208     0.8822        116       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.3s<1.7s

      39/50      10.1G      1.548     0.6206     0.8826        103       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.4s<1.5s

      39/50      10.1G      1.548     0.6213     0.8827        107       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.6s<1.3s

      39/50      10.1G      1.546     0.6206     0.8827        109       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.7s<1.2s

      39/50      10.1G      1.546     0.6204     0.8828        114       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.8s<1.0s

      39/50      10.1G      1.548     0.6212     0.8832        127       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 18.0s<0.9s

      39/50      10.1G      1.548     0.6211     0.8835        114       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.2s<0.8s

      39/50      10.1G      1.548     0.6213     0.8836        111       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.3s<0.6s

      39/50      10.1G      1.548     0.6215     0.8839         97       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.5s<0.4s

      39/50      10.1G      1.548     0.6214     0.8838        100       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.6s<0.3s

      39/50      10.1G      1.549     0.6224     0.8843        105       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.7s<0.1s

      39/50      10.1G      1.549     0.6224     0.8843        105       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.4it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.672      0.625      0.623      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      40/50      10.1G      1.299     0.5605     0.8147        114       1024: 0% ──────────── 0/124  0.1s

      40/50      10.1G      1.437     0.5741     0.8389        102       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      40/50      10.1G       1.46     0.5718      0.842        108       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.5s

      40/50      10.1G      1.461     0.5747     0.8392        120       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.4s

      40/50      10.1G       1.51     0.5921     0.8668        114       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.4s

      40/50      10.1G      1.509     0.5943     0.8708        121       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.7s

      40/50      10.1G        1.5     0.5879     0.8666        124       1024: 5% ╸─────────── 6/124 5.9it/s 1.1s<20.1s

      40/50      10.1G      1.503     0.5886     0.8696        111       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<19.0s

      40/50      10.1G      1.504     0.5935     0.8725        115       1024: 6% ╸─────────── 8/124 6.4it/s 1.4s<18.3s

      40/50      10.1G      1.514     0.6034     0.8759        119       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.3s

      40/50      10.1G       1.52     0.5995     0.8802        118       1024: 8% ╸─────────── 10/124 6.3it/s 1.7s<18.0s

      40/50      10.1G      1.516     0.6022     0.8732        126       1024: 9% ━─────────── 11/124 6.1it/s 1.8s<18.5s

      40/50      10.1G      1.518     0.6086     0.8723         90       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.6s

      40/50      10.1G      1.558     0.6267     0.8773        125       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.1s

      40/50      10.1G      1.557     0.6206     0.8777        110       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.7s

      40/50      10.1G      1.554     0.6176      0.875        111       1024: 12% ━─────────── 15/124 6.6it/s 2.4s<16.4s

      40/50      10.1G      1.544      0.615     0.8721        129       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      40/50      10.1G      1.526     0.6077     0.8687        108       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<15.9s

      40/50      10.1G      1.512     0.6037     0.8673        101       1024: 15% ━╸────────── 18/124 6.8it/s 2.9s<15.7s

      40/50      10.1G      1.509     0.6036     0.8674        109       1024: 15% ━╸────────── 19/124 6.4it/s 3.1s<16.3s

      40/50      10.1G      1.491     0.5972     0.8648        109       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<16.1s

      40/50      10.1G      1.489     0.5969     0.8651        129       1024: 17% ━━────────── 21/124 6.6it/s 3.4s<15.7s

      40/50      10.1G      1.487     0.5962     0.8632        119       1024: 18% ━━────────── 22/124 6.6it/s 3.5s<15.4s

      40/50      10.1G      1.493     0.6003     0.8637        114       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.1s

      40/50      10.1G        1.5     0.6023     0.8638        123       1024: 19% ━━────────── 24/124 6.7it/s 3.8s<14.9s

      40/50      10.1G      1.501     0.6012     0.8682        109       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.7s

      40/50      10.1G      1.507     0.6004     0.8678        107       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      40/50      10.1G      1.506     0.5996     0.8672        120       1024: 22% ━━╸───────── 27/124 6.4it/s 4.3s<15.2s

      40/50      10.1G      1.507     0.5985     0.8664        126       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.7s

      40/50      10.1G      1.503     0.5959     0.8672        101       1024: 23% ━━╸───────── 29/124 6.6it/s 4.6s<14.3s

      40/50      10.1G      1.512     0.5999     0.8683        132       1024: 24% ━━╸───────── 30/124 6.6it/s 4.7s<14.3s

      40/50      10.1G       1.51     0.5987     0.8685        116       1024: 25% ━━━───────── 31/124 6.7it/s 4.9s<14.0s

      40/50      10.1G      1.507     0.5974      0.868        117       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.7s

      40/50      10.1G      1.512     0.6007     0.8697        110       1024: 27% ━━━───────── 33/124 6.8it/s 5.2s<13.5s

      40/50      10.1G      1.513     0.5998     0.8694        112       1024: 27% ━━━───────── 34/124 6.8it/s 5.3s<13.3s

      40/50      10.1G      1.506     0.5974     0.8677        122       1024: 28% ━━━───────── 35/124 6.5it/s 5.5s<13.8s

      40/50      10.1G      1.512     0.5998      0.868        102       1024: 29% ━━━───────── 36/124 6.5it/s 5.6s<13.6s

      40/50      10.1G      1.518     0.6044     0.8683        122       1024: 30% ━━━╸──────── 37/124 6.6it/s 5.8s<13.2s

      40/50      10.1G      1.518     0.6047     0.8695         97       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.9s<13.1s

      40/50      10.1G      1.518      0.603     0.8695        107       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.1s<13.0s

      40/50      10.1G      1.519     0.6025     0.8702        117       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

      40/50      10.1G      1.521     0.6022     0.8697        115       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.6s

      40/50      10.1G      1.523     0.6019     0.8725        106       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      40/50      10.1G      1.522     0.6004     0.8727        126       1024: 35% ━━━━──────── 43/124 6.4it/s 6.7s<12.6s

      40/50      10.1G      1.525     0.6024     0.8737        111       1024: 35% ━━━━──────── 44/124 6.5it/s 6.9s<12.4s

      40/50      10.1G      1.524     0.6058      0.873        124       1024: 36% ━━━━──────── 45/124 6.6it/s 7.0s<12.0s

      40/50      10.1G      1.523     0.6053     0.8724        103       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      40/50      10.1G      1.523     0.6068     0.8727        121       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.3s<11.5s

      40/50      10.1G       1.52     0.6049     0.8729        113       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      40/50      10.1G      1.524      0.606     0.8741        111       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.6s<11.1s

      40/50      10.1G      1.522     0.6061     0.8754        101       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.9s

      40/50      10.1G      1.521     0.6063     0.8762        105       1024: 41% ━━━━╸─────── 51/124 6.4it/s 7.9s<11.4s

      40/50      10.1G      1.519      0.605     0.8758        102       1024: 42% ━━━━━─────── 52/124 6.5it/s 8.1s<11.1s

      40/50      10.1G      1.514     0.6026     0.8744        109       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.2s<10.8s

      40/50      10.1G      1.519     0.6039     0.8743        111       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.4s<10.5s

      40/50      10.1G      1.523     0.6054     0.8756        125       1024: 44% ━━━━━─────── 55/124 6.7it/s 8.5s<10.3s

      40/50      10.1G      1.521     0.6043     0.8751        109       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.6s<10.1s

      40/50      10.1G      1.518     0.6026     0.8746        116       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.8s<9.9s

      40/50      10.1G      1.516     0.6028     0.8743         98       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.7s

      40/50      10.1G      1.522     0.6055     0.8753        104       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.1s

      40/50      10.1G      1.525     0.6055     0.8756        116       1024: 48% ━━━━━╸────── 60/124 6.5it/s 9.3s<9.8s

      40/50      10.1G      1.525     0.6051      0.875        119       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.4s<9.6s

      40/50      10.1G      1.525     0.6047     0.8745        123       1024: 50% ━━━━━━────── 62/124 6.6it/s 9.6s<9.3s

      40/50      10.1G      1.524     0.6046     0.8742        124       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.7s<9.1s

      40/50      10.1G      1.528     0.6052     0.8748        113       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.9s<8.9s

      40/50      10.1G      1.525     0.6047      0.874        105       1024: 52% ━━━━━━────── 65/124 6.8it/s 10.0s<8.7s

      40/50      10.1G      1.526     0.6042     0.8736         99       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.6s

      40/50      10.1G      1.526     0.6045      0.874        111       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.3s<8.8s

      40/50      10.1G      1.526     0.6048      0.874         96       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.5s<8.6s

      40/50      10.1G      1.522     0.6028     0.8732        127       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.4s

      40/50      10.1G      1.524     0.6041     0.8732        126       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.8s<8.1s

      40/50      10.1G      1.524     0.6035     0.8725        123       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.9s<7.9s

      40/50      10.1G      1.525     0.6057     0.8724        102       1024: 58% ━━━━━━╸───── 72/124 6.7it/s 11.1s<7.7s

      40/50      10.1G      1.526      0.606     0.8722        117       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.2s<7.5s

      40/50      10.1G      1.528     0.6066     0.8721        121       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.5s

      40/50      10.1G      1.531     0.6074     0.8727        135       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.5s<7.7s

      40/50      10.1G      1.528     0.6068      0.873        127       1024: 61% ━━━━━━━───── 76/124 6.4it/s 11.7s<7.4s

      40/50      10.1G      1.526     0.6051     0.8728        108       1024: 62% ━━━━━━━───── 77/124 6.5it/s 11.8s<7.2s

      40/50      10.1G      1.524     0.6046     0.8732        131       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 12.0s<6.9s

      40/50      10.1G      1.526     0.6048     0.8734        126       1024: 64% ━━━━━━━╸──── 79/124 6.6it/s 12.1s<6.8s

      40/50      10.1G      1.523     0.6036     0.8731        105       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.3s<6.6s

      40/50      10.1G      1.522     0.6023     0.8728         96       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      40/50      10.1G      1.521     0.6023     0.8727         95       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.6s<6.2s

      40/50      10.1G       1.52     0.6015     0.8727        121       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.8s<6.4s

      40/50      10.1G      1.521     0.6023     0.8724        114       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.9s<6.1s

      40/50      10.1G      1.522     0.6024     0.8725        106       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 13.1s<6.0s

      40/50      10.1G       1.52     0.6017     0.8723         98       1024: 69% ━━━━━━━━──── 86/124 6.5it/s 13.2s<5.8s

      40/50      10.1G      1.519     0.6013     0.8724        112       1024: 70% ━━━━━━━━──── 87/124 6.6it/s 13.4s<5.6s

      40/50      10.1G      1.521     0.6017     0.8727         90       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.5s<5.4s

      40/50      10.1G      1.522     0.6022     0.8726        131       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.7s<5.2s

      40/50      10.1G      1.522     0.6023     0.8729        120       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.8s<5.0s

      40/50      10.1G      1.524     0.6028     0.8734        138       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 14.0s<5.1s

      40/50      10.1G      1.522     0.6021     0.8731        113       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.1s<4.9s

      40/50      10.1G      1.524     0.6025      0.873        108       1024: 75% ━━━━━━━━━─── 93/124 6.5it/s 14.3s<4.7s

      40/50      10.1G      1.525     0.6026     0.8728        123       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.4s<4.5s

      40/50      10.1G      1.527     0.6038     0.8728        122       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.6s<4.3s

      40/50      10.1G      1.527     0.6033     0.8732        101       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.7s<4.2s

      40/50      10.1G      1.525     0.6023     0.8731        122       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.9s<4.0s

      40/50      10.1G      1.523     0.6014      0.873        103       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 15.0s<3.8s

      40/50      10.1G      1.524     0.6025     0.8741         98       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.2s<3.9s

      40/50      10.1G      1.526     0.6032     0.8744        123       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.3s<3.6s

      40/50      10.1G      1.527     0.6035     0.8744        103       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.5s<3.5s

      40/50      10.1G      1.527     0.6031     0.8742        115       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.6s<3.3s

      40/50      10.1G      1.527     0.6032     0.8741        100       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.8s<3.1s

      40/50      10.1G      1.527     0.6033     0.8747        105       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.9s<3.0s

      40/50      10.1G      1.527     0.6032     0.8747        116       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.1s<2.8s

      40/50      10.1G       1.53     0.6041     0.8755        116       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.2s<2.7s

      40/50      10.1G      1.532     0.6059     0.8768        112       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.4s<2.6s

      40/50      10.1G      1.533     0.6056     0.8761        129       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.5s<2.5s

      40/50      10.1G      1.534     0.6059     0.8762        100       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.7s<2.3s

      40/50      10.1G      1.534     0.6056     0.8761        102       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.8s<2.1s

      40/50      10.1G      1.536     0.6057     0.8766        113       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 17.0s<1.9s

      40/50      10.1G      1.534     0.6053     0.8765         94       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.1s<1.8s

      40/50      10.1G      1.534     0.6048     0.8763        120       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.3s<1.6s

      40/50      10.1G      1.532     0.6049     0.8761        113       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.4s<1.5s

      40/50      10.1G      1.529      0.604     0.8763        101       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.6s<1.4s

      40/50      10.1G      1.529     0.6047     0.8764        123       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.8s<1.2s

      40/50      10.1G      1.528     0.6042     0.8762         96       1024: 94% ━━━━━━━━━━━─ 117/124 6.5it/s 17.9s<1.1s

      40/50      10.1G      1.527     0.6034     0.8762         88       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 18.1s<0.9s

      40/50      10.1G      1.527     0.6039     0.8767        107       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.2s<0.8s

      40/50      10.1G      1.528      0.604     0.8768        109       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.3s<0.6s

      40/50      10.1G      1.529     0.6049     0.8777        104       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.5s<0.4s

      40/50      10.1G      1.531      0.606     0.8781        111       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.6s<0.3s

      40/50      10.1G      1.533     0.6066     0.8785        120       1024: 99% ━━━━━━━━━━━╸ 123/124 6.4it/s 18.8s<0.2s

      40/50      10.1G      1.533     0.6066     0.8785        120       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.688      0.596      0.617      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      41/50      10.1G      1.579     0.6193     0.8716        113       1024: 0% ──────────── 0/124  0.1s

      41/50      10.1G      1.512     0.6239     0.9066        102       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:02

      41/50      10.1G      1.501     0.5967     0.8993        111       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.5s

      41/50      10.1G      1.462     0.5782     0.8818        113       1024: 2% ──────────── 3/124 4.5it/s 0.6s<27.2s

      41/50      10.1G      1.486     0.5923      0.881        125       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.2s

      41/50      10.1G      1.523     0.5931     0.8771        108       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.4s

      41/50      10.1G      1.559     0.6108     0.8836        103       1024: 5% ╸─────────── 6/124 5.9it/s 1.0s<19.8s

      41/50      10.1G      1.589     0.6263     0.8902        104       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<20.0s

      41/50      10.1G      1.545     0.6114     0.8821        119       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<19.1s

      41/50      10.1G      1.557     0.6115     0.8834        114       1024: 7% ╸─────────── 9/124 6.3it/s 1.5s<18.3s

      41/50      10.1G      1.538     0.6055     0.8805        109       1024: 8% ╸─────────── 10/124 6.4it/s 1.7s<17.7s

      41/50      10.1G      1.516     0.5963     0.8755        104       1024: 9% ━─────────── 11/124 6.5it/s 1.8s<17.5s

      41/50      10.1G      1.506     0.5915     0.8717        105       1024: 10% ━─────────── 12/124 6.6it/s 2.0s<17.0s

      41/50      10.1G       1.51     0.5908     0.8695        125       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.7s

      41/50      10.1G      1.503     0.5878     0.8659        102       1024: 11% ━─────────── 14/124 6.7it/s 2.3s<16.4s

      41/50      10.1G      1.496     0.5855     0.8664        103       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<17.0s

      41/50      10.1G      1.513     0.5909     0.8733        105       1024: 13% ━╸────────── 16/124 6.6it/s 2.6s<16.5s

      41/50      10.1G      1.505     0.5904     0.8744        115       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.1s

      41/50      10.1G       1.51      0.593     0.8758        107       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      41/50      10.1G      1.499     0.5919     0.8761        118       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

      41/50      10.1G      1.507     0.5961     0.8755        111       1024: 16% ━╸────────── 20/124 6.7it/s 3.2s<15.5s

      41/50      10.1G      1.504     0.5946     0.8751        111       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.3s

      41/50      10.1G      1.498     0.5916     0.8721        112       1024: 18% ━━────────── 22/124 6.8it/s 3.5s<15.1s

      41/50      10.1G      1.495     0.5884     0.8708        116       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.8s

      41/50      10.1G        1.5     0.5899     0.8739        125       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.3s

      41/50      10.1G      1.491      0.585     0.8735         97       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      41/50      10.1G      1.488     0.5843     0.8726        112       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

      41/50      10.1G      1.484     0.5836     0.8713        117       1024: 22% ━━╸───────── 27/124 6.6it/s 4.2s<14.6s

      41/50      10.1G      1.484     0.5849     0.8713         98       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      41/50      10.1G      1.488     0.5871     0.8715        111       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.1s

      41/50      10.1G      1.487     0.5849     0.8702        139       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

      41/50      10.1G      1.492     0.5893     0.8713        103       1024: 25% ━━━───────── 31/124 6.3it/s 4.9s<14.7s

      41/50      10.1G      1.493     0.5889     0.8714        110       1024: 26% ━━━───────── 32/124 6.4it/s 5.0s<14.4s

      41/50      10.1G      1.498     0.5899     0.8719        105       1024: 27% ━━━───────── 33/124 6.5it/s 5.2s<13.9s

      41/50      10.1G      1.494     0.5891      0.871        107       1024: 27% ━━━───────── 34/124 6.6it/s 5.3s<13.6s

      41/50      10.1G      1.496     0.5901     0.8729        106       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.3s

      41/50      10.1G      1.497      0.591     0.8747        124       1024: 29% ━━━───────── 36/124 6.7it/s 5.6s<13.1s

      41/50      10.1G      1.498     0.5907     0.8749        127       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

      41/50      10.1G      1.499     0.5911     0.8751        110       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      41/50      10.1G      1.494     0.5901     0.8739        111       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.1s<13.2s

      41/50      10.1G      1.496     0.5896     0.8742        118       1024: 32% ━━━╸──────── 40/124 6.5it/s 6.2s<12.9s

      41/50      10.1G      1.495     0.5905     0.8751        120       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.4s<12.6s

      41/50      10.1G        1.5     0.5911     0.8751        114       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.3s

      41/50      10.1G      1.501     0.5911     0.8766        124       1024: 35% ━━━━──────── 43/124 6.7it/s 6.7s<12.0s

      41/50      10.1G      1.502     0.5903     0.8763        114       1024: 35% ━━━━──────── 44/124 6.7it/s 6.8s<12.0s

      41/50      10.1G        1.5     0.5904      0.876        116       1024: 36% ━━━━──────── 45/124 6.7it/s 7.0s<11.8s

      41/50      10.1G      1.497     0.5892     0.8753        108       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.7s

      41/50      10.1G      1.499     0.5902     0.8755        109       1024: 38% ━━━━╸─────── 47/124 6.4it/s 7.3s<12.1s

      41/50      10.1G      1.493     0.5868     0.8754         92       1024: 39% ━━━━╸─────── 48/124 6.5it/s 7.4s<11.6s

      41/50      10.1G      1.495     0.5873     0.8747        116       1024: 40% ━━━━╸─────── 49/124 6.4it/s 7.6s<11.7s

      41/50      10.1G      1.494      0.588     0.8743        110       1024: 40% ━━━━╸─────── 50/124 6.4it/s 7.7s<11.5s

      41/50      10.1G      1.498     0.5877     0.8758        108       1024: 41% ━━━━╸─────── 51/124 6.6it/s 7.9s<11.1s

      41/50      10.1G      1.497     0.5866     0.8745        120       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      41/50      10.1G      1.497     0.5874     0.8746        112       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.2s<10.7s

      41/50      10.1G      1.501     0.5899     0.8761        108       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      41/50      10.1G        1.5      0.589     0.8753        103       1024: 44% ━━━━━─────── 55/124 6.4it/s 8.5s<10.7s

      41/50      10.1G      1.504     0.5904     0.8755        119       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.7s<10.4s

      41/50      10.1G      1.503     0.5897     0.8757        103       1024: 46% ━━━━━╸────── 57/124 6.6it/s 8.8s<10.1s

      41/50      10.1G      1.508      0.591     0.8754        112       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.9s

      41/50      10.1G      1.508     0.5911     0.8755        124       1024: 48% ━━━━━╸────── 59/124 6.7it/s 9.1s<9.7s

      41/50      10.1G      1.509     0.5908     0.8754        109       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.5s

      41/50      10.1G      1.508     0.5902     0.8747        114       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.4s<9.3s

      41/50      10.1G      1.506     0.5908     0.8746        110       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      41/50      10.1G      1.507     0.5906      0.874        110       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.7s<9.4s

      41/50      10.1G      1.504     0.5896     0.8738        119       1024: 52% ━━━━━━────── 64/124 6.6it/s 9.9s<9.1s

      41/50      10.1G      1.507     0.5913     0.8746        111       1024: 52% ━━━━━━────── 65/124 6.6it/s 10.0s<8.9s

      41/50      10.1G      1.507     0.5918     0.8753        118       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.2s<8.8s

      41/50      10.1G      1.508     0.5925     0.8755        110       1024: 54% ━━━━━━────── 67/124 6.6it/s 10.3s<8.6s

      41/50      10.1G      1.507     0.5928     0.8752        109       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.5s<8.4s

      41/50      10.1G      1.508     0.5927      0.875        114       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.3s

      41/50      10.1G      1.508     0.5925     0.8755        114       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.7s<8.1s

      41/50      10.1G      1.511     0.5945      0.876        129       1024: 57% ━━━━━━╸───── 71/124 6.4it/s 10.9s<8.3s

      41/50      10.1G      1.509     0.5945     0.8762        103       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.1s<7.9s

      41/50      10.1G      1.513     0.5961     0.8775        126       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.2s<7.7s

      41/50      10.1G      1.513     0.5958     0.8771        104       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.4s<7.4s

      41/50      10.1G      1.515     0.5955     0.8772        137       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.5s<7.2s

      41/50      10.1G      1.517     0.5962      0.878        124       1024: 61% ━━━━━━━───── 76/124 6.8it/s 11.6s<7.1s

      41/50      10.1G      1.518     0.5972     0.8784        119       1024: 62% ━━━━━━━───── 77/124 6.8it/s 11.8s<6.9s

      41/50      10.1G       1.52     0.5972     0.8782        125       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.9s<6.7s

      41/50      10.1G       1.52     0.5971     0.8789        119       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.1s<7.0s

      41/50      10.1G      1.518     0.5966     0.8789        112       1024: 65% ━━━━━━━╸──── 80/124 6.6it/s 12.3s<6.7s

      41/50      10.1G      1.516     0.5955      0.879        110       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.5s

      41/50      10.1G      1.514     0.5948     0.8783        111       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.6s<6.3s

      41/50      10.1G      1.517     0.5958      0.878        114       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.7s<6.1s

      41/50      10.1G      1.517      0.596     0.8773        104       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.9s<5.9s

      41/50      10.1G      1.516     0.5962     0.8772        111       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 13.0s<5.8s

      41/50      10.1G      1.515     0.5962     0.8769        123       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.1s<5.6s

      41/50      10.1G      1.515     0.5962     0.8769        109       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.3s<5.7s

      41/50      10.1G      1.515     0.5963     0.8763        118       1024: 71% ━━━━━━━━╸─── 88/124 6.5it/s 13.5s<5.5s

      41/50      10.1G      1.513     0.5945     0.8758        127       1024: 72% ━━━━━━━━╸─── 89/124 6.5it/s 13.6s<5.3s

      41/50      10.1G      1.513     0.5942     0.8758        106       1024: 73% ━━━━━━━━╸─── 90/124 6.5it/s 13.8s<5.2s

      41/50      10.1G      1.512     0.5932     0.8751        107       1024: 73% ━━━━━━━━╸─── 91/124 6.6it/s 13.9s<5.0s

      41/50      10.1G      1.512     0.5932     0.8752        115       1024: 74% ━━━━━━━━╸─── 92/124 6.7it/s 14.1s<4.8s

      41/50      10.1G      1.513     0.5935     0.8749        117       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      41/50      10.1G      1.511     0.5929     0.8746        125       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.4s<4.5s

      41/50      10.1G       1.51      0.592     0.8745        117       1024: 77% ━━━━━━━━━─── 95/124 6.4it/s 14.5s<4.5s

      41/50      10.1G      1.509     0.5913     0.8741         99       1024: 77% ━━━━━━━━━─── 96/124 6.4it/s 14.7s<4.4s

      41/50      10.1G      1.508     0.5912     0.8739        111       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.8s<4.1s

      41/50      10.1G       1.51     0.5917      0.874        114       1024: 79% ━━━━━━━━━─── 98/124 6.5it/s 15.0s<4.0s

      41/50      10.1G      1.508     0.5906     0.8734        128       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.2s<3.8s

      41/50      10.1G      1.507     0.5906     0.8731        113       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.3s<3.6s

      41/50      10.1G      1.507     0.5897     0.8729        112       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.4s<3.4s

      41/50      10.1G      1.504     0.5883     0.8721        113       1024: 82% ━━━━━━━━━╸── 102/124 6.7it/s 15.6s<3.3s

      41/50      10.1G      1.502     0.5876     0.8721        114       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.8s<3.3s

      41/50      10.1G      1.503     0.5881     0.8718        123       1024: 84% ━━━━━━━━━━── 104/124 6.6it/s 15.9s<3.1s

      41/50      10.1G      1.503     0.5878     0.8714        125       1024: 85% ━━━━━━━━━━── 105/124 6.6it/s 16.1s<2.9s

      41/50      10.1G      1.503     0.5874     0.8711        105       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.2s<2.7s

      41/50      10.1G      1.503     0.5872     0.8715        101       1024: 86% ━━━━━━━━━━── 107/124 6.8it/s 16.4s<2.5s

      41/50      10.1G      1.503     0.5873     0.8717        109       1024: 87% ━━━━━━━━━━── 108/124 6.8it/s 16.5s<2.4s

      41/50      10.1G      1.503     0.5873     0.8718        125       1024: 88% ━━━━━━━━━━╸─ 109/124 6.8it/s 16.6s<2.2s

      41/50      10.1G      1.502     0.5872     0.8718        108       1024: 89% ━━━━━━━━━━╸─ 110/124 6.8it/s 16.8s<2.1s

      41/50      10.1G      1.505     0.5879     0.8717        105       1024: 90% ━━━━━━━━━━╸─ 111/124 6.5it/s 17.0s<2.0s

      41/50      10.1G      1.506     0.5883     0.8722        130       1024: 90% ━━━━━━━━━━╸─ 112/124 6.6it/s 17.1s<1.8s

      41/50      10.1G      1.509     0.5902     0.8727        116       1024: 91% ━━━━━━━━━━╸─ 113/124 6.6it/s 17.3s<1.7s

      41/50      10.1G      1.509     0.5898     0.8729        112       1024: 92% ━━━━━━━━━━━─ 114/124 6.6it/s 17.4s<1.5s

      41/50      10.1G       1.51      0.591     0.8732        113       1024: 93% ━━━━━━━━━━━─ 115/124 6.6it/s 17.6s<1.4s

      41/50      10.1G       1.51     0.5912     0.8732        121       1024: 94% ━━━━━━━━━━━─ 116/124 6.7it/s 17.7s<1.2s

      41/50      10.1G       1.51     0.5911     0.8731        106       1024: 94% ━━━━━━━━━━━─ 117/124 6.7it/s 17.9s<1.0s

      41/50      10.1G      1.509     0.5905     0.8732        115       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 18.0s<0.9s

      41/50      10.1G      1.509     0.5905     0.8734        130       1024: 96% ━━━━━━━━━━━╸ 119/124 6.4it/s 18.2s<0.8s

      41/50      10.1G      1.508     0.5905     0.8736         95       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.3s<0.6s

      41/50      10.1G      1.509     0.5907     0.8734        101       1024: 98% ━━━━━━━━━━━╸ 121/124 6.5it/s 18.5s<0.5s

      41/50      10.1G      1.507     0.5904     0.8732        104       1024: 98% ━━━━━━━━━━━╸ 122/124 6.6it/s 18.6s<0.3s

      41/50      10.1G      1.505     0.5899     0.8728         97       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.8s<0.2s

      41/50      10.1G      1.505     0.5899     0.8728         97       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.4s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.2it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.5it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.5it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.5it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.663      0.632      0.626      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      42/50      10.1G      1.459      0.591      0.891        114       1024: 0% ──────────── 0/124  0.1s

      42/50      10.1G      1.461     0.5923     0.8825        113       1024: 1% ──────────── 1/124 1.9it/s 0.3s<1:03

      42/50      10.1G      1.477     0.5703     0.8742        117       1024: 2% ──────────── 2/124 3.4it/s 0.4s<35.7s

      42/50      10.1G      1.393     0.5512     0.8687        118       1024: 2% ──────────── 3/124 4.1it/s 0.6s<29.4s

      42/50      10.1G      1.417     0.5607     0.8696        113       1024: 3% ──────────── 4/124 4.8it/s 0.8s<24.8s

      42/50      10.1G       1.42     0.5601     0.8619        113       1024: 4% ──────────── 5/124 5.4it/s 0.9s<21.9s

      42/50      10.1G      1.421     0.5709     0.8686        104       1024: 5% ╸─────────── 6/124 5.8it/s 1.1s<20.2s

      42/50      10.1G      1.418     0.5666     0.8678        113       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      42/50      10.1G       1.44     0.5716     0.8678        130       1024: 6% ╸─────────── 8/124 6.3it/s 1.4s<18.4s

      42/50      10.1G      1.443     0.5691     0.8684        111       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.8s

      42/50      10.1G       1.44     0.5701     0.8708        102       1024: 8% ╸─────────── 10/124 6.6it/s 1.7s<17.4s

      42/50      10.1G      1.441     0.5643      0.867        115       1024: 9% ━─────────── 11/124 6.3it/s 1.8s<17.9s

      42/50      10.1G      1.443     0.5694     0.8681        103       1024: 10% ━─────────── 12/124 6.4it/s 2.0s<17.5s

      42/50      10.1G      1.433     0.5627     0.8675         99       1024: 10% ━─────────── 13/124 6.5it/s 2.1s<17.0s

      42/50      10.1G      1.431     0.5661     0.8701        111       1024: 11% ━─────────── 14/124 6.6it/s 2.3s<16.6s

      42/50      10.1G      1.427     0.5645     0.8686         88       1024: 12% ━─────────── 15/124 6.7it/s 2.4s<16.3s

      42/50      10.1G      1.431     0.5639     0.8685        121       1024: 13% ━╸────────── 16/124 6.7it/s 2.6s<16.1s

      42/50      10.1G      1.424     0.5624     0.8701        115       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.8s

      42/50      10.1G      1.434     0.5616     0.8689        115       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.8s

      42/50      10.1G      1.446     0.5645     0.8698        119       1024: 15% ━╸────────── 19/124 6.4it/s 3.0s<16.4s

      42/50      10.1G      1.445     0.5636     0.8709        104       1024: 16% ━╸────────── 20/124 6.5it/s 3.2s<15.9s

      42/50      10.1G      1.439     0.5595      0.871        107       1024: 17% ━━────────── 21/124 6.6it/s 3.3s<15.5s

      42/50      10.1G      1.442      0.559     0.8703        112       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.2s

      42/50      10.1G      1.442      0.559     0.8694        120       1024: 19% ━━────────── 23/124 6.7it/s 3.6s<15.0s

      42/50      10.1G      1.454     0.5649     0.8709        114       1024: 19% ━━────────── 24/124 6.8it/s 3.8s<14.8s

      42/50      10.1G      1.464     0.5707     0.8711        117       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.5s

      42/50      10.1G      1.464     0.5704     0.8704        121       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.6s

      42/50      10.1G       1.46     0.5674      0.869        110       1024: 22% ━━╸───────── 27/124 6.4it/s 4.2s<15.1s

      42/50      10.1G      1.455     0.5653     0.8671        103       1024: 23% ━━╸───────── 28/124 6.5it/s 4.4s<14.9s

      42/50      10.1G      1.453     0.5634     0.8679        118       1024: 23% ━━╸───────── 29/124 6.6it/s 4.5s<14.4s

      42/50      10.1G      1.452      0.563     0.8677        115       1024: 24% ━━╸───────── 30/124 6.7it/s 4.7s<14.1s

      42/50      10.1G      1.457     0.5686     0.8676        132       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.8s

      42/50      10.1G      1.462     0.5694     0.8664        132       1024: 26% ━━━───────── 32/124 6.7it/s 5.0s<13.8s

      42/50      10.1G      1.469     0.5705     0.8667        122       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.7s

      42/50      10.1G      1.469     0.5701     0.8666        116       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      42/50      10.1G       1.47     0.5704     0.8681         97       1024: 28% ━━━───────── 35/124 6.4it/s 5.5s<13.8s

      42/50      10.1G       1.47     0.5688     0.8675        101       1024: 29% ━━━───────── 36/124 6.6it/s 5.6s<13.4s

      42/50      10.1G       1.47     0.5691     0.8674        112       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

      42/50      10.1G      1.475     0.5716     0.8678        110       1024: 31% ━━━╸──────── 38/124 6.7it/s 5.9s<12.8s

      42/50      10.1G      1.473     0.5712      0.868        109       1024: 31% ━━━╸──────── 39/124 6.8it/s 6.0s<12.5s

      42/50      10.1G      1.467     0.5694     0.8659         99       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.2s<12.3s

      42/50      10.1G      1.473     0.5699     0.8671        107       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.3s<12.1s

      42/50      10.1G      1.475     0.5697     0.8664        110       1024: 34% ━━━━──────── 42/124 6.8it/s 6.5s<12.0s

      42/50      10.1G      1.477     0.5711     0.8682        125       1024: 35% ━━━━──────── 43/124 6.5it/s 6.6s<12.4s

      42/50      10.1G      1.475     0.5703     0.8677        110       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.2s

      42/50      10.1G      1.485     0.5744     0.8693        111       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<11.9s

      42/50      10.1G      1.484     0.5761     0.8683        108       1024: 37% ━━━━──────── 46/124 6.7it/s 7.1s<11.6s

      42/50      10.1G      1.484     0.5771     0.8699        101       1024: 38% ━━━━╸─────── 47/124 6.7it/s 7.2s<11.4s

      42/50      10.1G      1.487     0.5785       0.87        110       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.4s<11.2s

      42/50      10.1G      1.488      0.579       0.87        111       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.5s<11.0s

      42/50      10.1G      1.494     0.5808     0.8706        116       1024: 40% ━━━━╸─────── 50/124 6.8it/s 7.7s<10.8s

      42/50      10.1G      1.497     0.5818     0.8711         96       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.9s<11.3s

      42/50      10.1G      1.501     0.5825     0.8711        131       1024: 42% ━━━━━─────── 52/124 6.6it/s 8.0s<10.9s

      42/50      10.1G      1.502     0.5835      0.871        117       1024: 43% ━━━━━─────── 53/124 6.6it/s 8.1s<10.7s

      42/50      10.1G      1.503     0.5835     0.8715         96       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.3s<10.4s

      42/50      10.1G      1.507     0.5863     0.8726        122       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.2s

      42/50      10.1G      1.502     0.5836     0.8717        105       1024: 45% ━━━━━─────── 56/124 6.8it/s 8.6s<10.0s

      42/50      10.1G      1.503      0.584     0.8711        108       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.7s<9.9s

      42/50      10.1G      1.507     0.5855     0.8729        116       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.9s<9.7s

      42/50      10.1G      1.506     0.5853     0.8739        128       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.1s<10.0s

      42/50      10.1G      1.508     0.5851     0.8738        110       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.2s<9.7s

      42/50      10.1G      1.505     0.5832     0.8734        112       1024: 49% ━━━━━╸────── 61/124 6.7it/s 9.3s<9.4s

      42/50      10.1G      1.507     0.5841     0.8739        117       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.5s<9.2s

      42/50      10.1G      1.506     0.5852     0.8733        105       1024: 51% ━━━━━━────── 63/124 6.8it/s 9.6s<9.0s

      42/50      10.1G      1.502     0.5837     0.8724        100       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.8s<8.8s

      42/50      10.1G      1.501     0.5838     0.8721        109       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.6s

      42/50      10.1G        1.5     0.5836      0.872        119       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.1s<8.5s

      42/50      10.1G      1.499     0.5842     0.8724        103       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.3s<8.9s

      42/50      10.1G      1.503     0.5857     0.8724        117       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.4s<8.7s

      42/50      10.1G      1.502     0.5852     0.8722         94       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.6s<8.4s

      42/50      10.1G      1.497     0.5834     0.8708         98       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.7s<8.1s

      42/50      10.1G      1.495     0.5836     0.8703        119       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.8s<7.9s

      42/50      10.1G      1.491     0.5834     0.8703         92       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 11.0s<7.7s

      42/50      10.1G      1.489     0.5828     0.8704        103       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.1s<7.5s

      42/50      10.1G       1.49      0.583     0.8705        113       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

      42/50      10.1G      1.488     0.5826     0.8702        101       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.5s<7.7s

      42/50      10.1G      1.482     0.5807     0.8688        112       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

      42/50      10.1G      1.482     0.5801     0.8686        108       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.8s<7.1s

      42/50      10.1G      1.482     0.5806     0.8688        106       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.9s<6.9s

      42/50      10.1G      1.481     0.5806     0.8694        108       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.1s<6.7s

      42/50      10.1G      1.482     0.5808     0.8694        125       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.2s<6.5s

      42/50      10.1G      1.482     0.5805     0.8692        102       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.4s<6.4s

      42/50      10.1G      1.486     0.5814      0.869        142       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      42/50      10.1G      1.485     0.5808     0.8689        116       1024: 67% ━━━━━━━━──── 83/124 6.3it/s 12.7s<6.5s

      42/50      10.1G      1.486     0.5808     0.8689        121       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.8s<6.2s

      42/50      10.1G      1.486     0.5809     0.8691        122       1024: 69% ━━━━━━━━──── 85/124 6.6it/s 13.0s<5.9s

      42/50      10.1G      1.486     0.5813     0.8692        105       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.1s<5.7s

      42/50      10.1G      1.487     0.5814     0.8704        123       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.3s<5.5s

      42/50      10.1G      1.486     0.5804     0.8702        127       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.4s<5.3s

      42/50      10.1G      1.487     0.5807     0.8702        124       1024: 72% ━━━━━━━━╸─── 89/124 6.8it/s 13.6s<5.2s

      42/50      10.1G      1.489     0.5814     0.8705        104       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.7s<5.0s

      42/50      10.1G      1.492     0.5823     0.8709         90       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.9s<5.1s

      42/50      10.1G      1.495     0.5834     0.8706        119       1024: 74% ━━━━━━━━╸─── 92/124 6.5it/s 14.0s<4.9s

      42/50      10.1G      1.496     0.5853     0.8709        116       1024: 75% ━━━━━━━━━─── 93/124 6.6it/s 14.2s<4.7s

      42/50      10.1G      1.497     0.5855     0.8709        117       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.3s<4.5s

      42/50      10.1G      1.499     0.5855     0.8708        102       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.5s<4.3s

      42/50      10.1G      1.497     0.5845     0.8705        122       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.6s<4.1s

      42/50      10.1G      1.497      0.584     0.8706        112       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.8s<4.0s

      42/50      10.1G      1.498     0.5849     0.8707        120       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.9s<3.8s

      42/50      10.1G      1.498     0.5846     0.8712        101       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.1s<3.8s

      42/50      10.1G      1.498     0.5839      0.871        122       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.2s<3.6s

      42/50      10.1G      1.499     0.5846     0.8709        109       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.4s<3.4s

      42/50      10.1G      1.499     0.5844      0.871        104       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.5s<3.3s

      42/50      10.1G      1.499     0.5842     0.8709        114       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.7s<3.1s

      42/50      10.1G        1.5      0.584     0.8711        103       1024: 84% ━━━━━━━━━━── 104/124 6.8it/s 15.8s<2.9s

      42/50      10.1G        1.5     0.5844     0.8708        116       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 16.0s<2.8s

      42/50      10.1G      1.501     0.5849     0.8711        125       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.1s<2.6s

      42/50      10.1G      1.501     0.5845     0.8711        105       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.3s<2.6s

      42/50      10.1G      1.502     0.5846     0.8711        122       1024: 87% ━━━━━━━━━━── 108/124 6.6it/s 16.4s<2.4s

      42/50      10.1G      1.504     0.5847      0.871        128       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.6s<2.3s

      42/50      10.1G      1.504     0.5848      0.871        130       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.7s<2.1s

      42/50      10.1G      1.506     0.5845     0.8712        121       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.9s<2.0s

      42/50      10.1G      1.502     0.5833     0.8706        111       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 17.0s<1.8s

      42/50      10.1G        1.5     0.5821     0.8704        118       1024: 91% ━━━━━━━━━━╸─ 113/124 6.8it/s 17.2s<1.6s

      42/50      10.1G      1.499      0.582     0.8705        118       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.3s<1.5s

      42/50      10.1G        1.5     0.5824     0.8704        125       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.5s<1.4s

      42/50      10.1G      1.501     0.5835     0.8709         96       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.6s<1.2s

      42/50      10.1G      1.502     0.5837     0.8706        120       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.8s<1.1s

      42/50      10.1G      1.501     0.5835     0.8707        100       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 17.9s<0.9s

      42/50      10.1G      1.501     0.5832     0.8709        111       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.1s<0.7s

      42/50      10.1G      1.502     0.5833     0.8708        119       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.2s<0.6s

      42/50      10.1G      1.503     0.5837     0.8709        142       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.4s<0.4s

      42/50      10.1G      1.504     0.5843     0.8709        100       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.5s<0.3s

      42/50      10.1G      1.503     0.5844     0.8707        104       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.7s<0.2s

      42/50      10.1G      1.503     0.5844     0.8707        104       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.4it/s 0.2s<4.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.6it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.6it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.7it/s 2.1s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.7it/s 2.4s

                   all        330       4227      0.686      0.601      0.618      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      43/50      10.1G      1.591     0.5902     0.8602        119       1024: 0% ──────────── 0/124  0.1s

      43/50      10.1G      1.495     0.5748     0.8402        115       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:00

      43/50      10.1G      1.446       0.56     0.8381        118       1024: 2% ──────────── 2/124 3.4it/s 0.4s<36.0s

      43/50      10.1G        1.5     0.5804     0.8439        114       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.4s

      43/50      10.1G      1.575     0.6057      0.874         94       1024: 3% ──────────── 4/124 5.2it/s 0.7s<23.3s

      43/50      10.1G      1.576     0.6087     0.8786        111       1024: 4% ──────────── 5/124 5.7it/s 0.9s<21.0s

      43/50      10.1G      1.531     0.5919     0.8742        115       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.6s

      43/50      10.1G      1.529     0.5867     0.8729        111       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.7s

      43/50      10.1G      1.536     0.5847     0.8722        122       1024: 6% ╸─────────── 8/124 6.2it/s 1.3s<18.6s

      43/50      10.1G      1.523     0.5792     0.8726        117       1024: 7% ╸─────────── 9/124 6.4it/s 1.5s<17.9s

      43/50      10.1G      1.535     0.5791     0.8714        121       1024: 8% ╸─────────── 10/124 6.5it/s 1.6s<17.4s

      43/50      10.1G      1.516     0.5742     0.8682        123       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.0s

      43/50      10.1G      1.542     0.5857     0.8768        114       1024: 10% ━─────────── 12/124 6.7it/s 1.9s<16.7s

      43/50      10.1G      1.521     0.5795     0.8734        108       1024: 10% ━─────────── 13/124 6.8it/s 2.1s<16.4s

      43/50      10.1G      1.517     0.5779     0.8721        129       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.2s

      43/50      10.1G      1.513     0.5803     0.8789        119       1024: 12% ━─────────── 15/124 6.5it/s 2.4s<16.8s

      43/50      10.1G      1.515     0.5798     0.8788        118       1024: 13% ━╸────────── 16/124 6.6it/s 2.5s<16.4s

      43/50      10.1G        1.5     0.5752     0.8767        105       1024: 14% ━╸────────── 17/124 6.7it/s 2.7s<16.0s

      43/50      10.1G      1.498     0.5766     0.8748        105       1024: 15% ━╸────────── 18/124 6.6it/s 2.8s<16.0s

      43/50      10.1G      1.502     0.5765     0.8741        108       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.7s

      43/50      10.1G      1.496     0.5748     0.8728        134       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.4s

      43/50      10.1G      1.501     0.5781     0.8755        111       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      43/50      10.1G      1.497     0.5755     0.8734        121       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.2s

      43/50      10.1G      1.499     0.5749     0.8745        131       1024: 19% ━━────────── 23/124 6.4it/s 3.6s<15.7s

      43/50      10.1G      1.498      0.577     0.8769        101       1024: 19% ━━────────── 24/124 6.6it/s 3.7s<15.2s

      43/50      10.1G      1.491     0.5778      0.875        120       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      43/50      10.1G      1.498     0.5832     0.8739        106       1024: 21% ━━╸───────── 26/124 6.7it/s 4.0s<14.7s

      43/50      10.1G      1.509     0.5869     0.8758        114       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.6s

      43/50      10.1G      1.501     0.5837      0.873        103       1024: 23% ━━╸───────── 28/124 6.7it/s 4.3s<14.3s

      43/50      10.1G      1.503     0.5843     0.8723        106       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.3s

      43/50      10.1G      1.498     0.5818     0.8715        106       1024: 24% ━━╸───────── 30/124 6.7it/s 4.6s<14.0s

      43/50      10.1G      1.491     0.5798      0.871        100       1024: 25% ━━━───────── 31/124 6.4it/s 4.8s<14.5s

      43/50      10.1G      1.494     0.5795     0.8707        113       1024: 26% ━━━───────── 32/124 6.5it/s 5.0s<14.2s

      43/50      10.1G      1.491      0.578     0.8713        102       1024: 27% ━━━───────── 33/124 6.6it/s 5.1s<13.8s

      43/50      10.1G      1.484     0.5759     0.8704        115       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.5s

      43/50      10.1G      1.482     0.5738     0.8694        117       1024: 28% ━━━───────── 35/124 6.8it/s 5.4s<13.2s

      43/50      10.1G      1.483     0.5727     0.8688        107       1024: 29% ━━━───────── 36/124 6.8it/s 5.5s<13.0s

      43/50      10.1G      1.489     0.5754     0.8704        104       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      43/50      10.1G      1.485     0.5748     0.8689        115       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.7s

      43/50      10.1G      1.483     0.5757     0.8681        111       1024: 31% ━━━╸──────── 39/124 6.5it/s 6.0s<13.1s

      43/50      10.1G       1.48     0.5756     0.8675        102       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.7s

      43/50      10.1G      1.479     0.5757     0.8685        126       1024: 33% ━━━╸──────── 41/124 6.7it/s 6.3s<12.4s

      43/50      10.1G      1.474      0.574     0.8664        114       1024: 34% ━━━━──────── 42/124 6.8it/s 6.4s<12.1s

      43/50      10.1G      1.476     0.5748     0.8667        125       1024: 35% ━━━━──────── 43/124 6.8it/s 6.6s<11.9s

      43/50      10.1G      1.471     0.5734     0.8666         92       1024: 35% ━━━━──────── 44/124 6.8it/s 6.7s<11.7s

      43/50      10.1G      1.473     0.5761     0.8675        111       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.7s

      43/50      10.1G      1.477     0.5782     0.8673        109       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.5s

      43/50      10.1G      1.474     0.5763     0.8668         98       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.9s

      43/50      10.1G       1.48     0.5808     0.8683        121       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.6s

      43/50      10.1G      1.481     0.5822      0.868        124       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

      43/50      10.1G      1.481     0.5813     0.8681        124       1024: 40% ━━━━╸─────── 50/124 6.6it/s 7.7s<11.2s

      43/50      10.1G      1.481     0.5805     0.8673        123       1024: 41% ━━━━╸─────── 51/124 6.7it/s 7.8s<10.9s

      43/50      10.1G      1.481     0.5789      0.868        110       1024: 42% ━━━━━─────── 52/124 6.8it/s 7.9s<10.7s

      43/50      10.1G      1.478     0.5787     0.8681        100       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.4s

      43/50      10.1G      1.477     0.5782     0.8676        130       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

      43/50      10.1G      1.476     0.5775     0.8679        107       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

      43/50      10.1G       1.48     0.5795     0.8676        119       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      43/50      10.1G      1.479     0.5791     0.8675        111       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

      43/50      10.1G      1.477     0.5779     0.8677        105       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.8s

      43/50      10.1G      1.475     0.5774     0.8673         99       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

      43/50      10.1G      1.474     0.5789     0.8681        104       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.1s<9.4s

      43/50      10.1G      1.476     0.5796     0.8687        107       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.3s

      43/50      10.1G      1.475     0.5788      0.869        128       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.4s<9.1s

      43/50      10.1G      1.477     0.5794     0.8696        102       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

      43/50      10.1G      1.479     0.5813     0.8707        110       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.8s<9.2s

      43/50      10.1G      1.478     0.5814     0.8705        108       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<8.9s

      43/50      10.1G      1.481     0.5826     0.8706        118       1024: 53% ━━━━━━────── 66/124 6.7it/s 10.0s<8.6s

      43/50      10.1G      1.481     0.5824     0.8704        117       1024: 54% ━━━━━━────── 67/124 6.8it/s 10.2s<8.4s

      43/50      10.1G       1.48     0.5818     0.8702        117       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.3s<8.3s

      43/50      10.1G      1.477     0.5807     0.8692        111       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

      43/50      10.1G      1.477     0.5808     0.8685        113       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.6s<8.0s

      43/50      10.1G      1.476     0.5807     0.8681        104       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.8s<8.2s

      43/50      10.1G      1.476     0.5814     0.8684        117       1024: 58% ━━━━━━╸───── 72/124 6.5it/s 11.0s<8.0s

      43/50      10.1G      1.477     0.5824     0.8689        122       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      43/50      10.1G      1.478     0.5822     0.8689        119       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.2s<7.5s

      43/50      10.1G      1.477     0.5814     0.8685        104       1024: 60% ━━━━━━━───── 75/124 6.7it/s 11.4s<7.4s

      43/50      10.1G      1.479     0.5831     0.8681        128       1024: 61% ━━━━━━━───── 76/124 6.7it/s 11.5s<7.2s

      43/50      10.1G      1.481     0.5841     0.8698        103       1024: 62% ━━━━━━━───── 77/124 6.7it/s 11.7s<7.0s

      43/50      10.1G      1.478     0.5834      0.869        102       1024: 63% ━━━━━━━╸──── 78/124 6.8it/s 11.8s<6.8s

      43/50      10.1G      1.479     0.5832     0.8691        123       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.0s<7.0s

      43/50      10.1G      1.476     0.5823     0.8685        100       1024: 65% ━━━━━━━╸──── 80/124 6.5it/s 12.2s<6.8s

      43/50      10.1G      1.476     0.5818     0.8684        104       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.3s<6.5s

      43/50      10.1G      1.475     0.5813     0.8681        105       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.3s

      43/50      10.1G      1.476     0.5814     0.8681        106       1024: 67% ━━━━━━━━──── 83/124 6.7it/s 12.6s<6.1s

      43/50      10.1G      1.477     0.5816     0.8682        114       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.7s<5.9s

      43/50      10.1G      1.479      0.582     0.8688        106       1024: 69% ━━━━━━━━──── 85/124 6.8it/s 12.9s<5.7s

      43/50      10.1G      1.481     0.5829      0.869        128       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.0s<5.6s

      43/50      10.1G      1.481     0.5831     0.8691        106       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.2s<5.7s

      43/50      10.1G      1.478      0.582      0.869        100       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.5s

      43/50      10.1G      1.478     0.5822     0.8687         99       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.3s

      43/50      10.1G       1.48     0.5826      0.869        118       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.7s<5.1s

      43/50      10.1G      1.479     0.5827     0.8688        112       1024: 73% ━━━━━━━━╸─── 91/124 6.7it/s 13.8s<4.9s

      43/50      10.1G       1.48     0.5826     0.8687        113       1024: 74% ━━━━━━━━╸─── 92/124 6.8it/s 13.9s<4.7s

      43/50      10.1G      1.481     0.5826     0.8687        124       1024: 75% ━━━━━━━━━─── 93/124 6.8it/s 14.1s<4.6s

      43/50      10.1G      1.481      0.582     0.8682        118       1024: 76% ━━━━━━━━━─── 94/124 6.8it/s 14.2s<4.4s

      43/50      10.1G      1.481     0.5818     0.8685        110       1024: 77% ━━━━━━━━━─── 95/124 6.5it/s 14.4s<4.5s

      43/50      10.1G      1.484     0.5829     0.8686        113       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.6s<4.2s

      43/50      10.1G      1.487     0.5828     0.8687        117       1024: 78% ━━━━━━━━━─── 97/124 6.7it/s 14.7s<4.1s

      43/50      10.1G      1.486     0.5824     0.8687        115       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.9s<3.9s

      43/50      10.1G      1.485     0.5821     0.8686        124       1024: 80% ━━━━━━━━━╸── 99/124 6.7it/s 15.0s<3.7s

      43/50      10.1G      1.488     0.5837     0.8689        106       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.2s<3.6s

      43/50      10.1G       1.49     0.5843     0.8687        126       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.3s<3.4s

      43/50      10.1G      1.493     0.5847      0.869        106       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.5s<3.3s

      43/50      10.1G      1.492     0.5849     0.8685        120       1024: 83% ━━━━━━━━━╸── 103/124 6.4it/s 15.6s<3.3s

      43/50      10.1G      1.491     0.5844     0.8682        126       1024: 84% ━━━━━━━━━━── 104/124 6.4it/s 15.8s<3.1s

      43/50      10.1G      1.491     0.5845      0.868         90       1024: 85% ━━━━━━━━━━── 105/124 6.5it/s 15.9s<2.9s

      43/50      10.1G      1.491     0.5837     0.8685        120       1024: 85% ━━━━━━━━━━── 106/124 6.6it/s 16.1s<2.7s

      43/50      10.1G       1.49     0.5839      0.868        106       1024: 86% ━━━━━━━━━━── 107/124 6.7it/s 16.2s<2.5s

      43/50      10.1G      1.494     0.5859     0.8686        124       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.4s<2.5s

      43/50      10.1G      1.493     0.5852     0.8684        118       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.5s<2.3s

      43/50      10.1G      1.495     0.5858     0.8685        120       1024: 89% ━━━━━━━━━━╸─ 110/124 6.7it/s 16.7s<2.1s

      43/50      10.1G      1.492      0.585     0.8685        106       1024: 90% ━━━━━━━━━━╸─ 111/124 6.4it/s 16.9s<2.0s

      43/50      10.1G      1.492     0.5845     0.8685        116       1024: 90% ━━━━━━━━━━╸─ 112/124 6.5it/s 17.0s<1.9s

      43/50      10.1G      1.493     0.5851     0.8692        118       1024: 91% ━━━━━━━━━━╸─ 113/124 6.5it/s 17.2s<1.7s

      43/50      10.1G      1.492     0.5846     0.8688        122       1024: 92% ━━━━━━━━━━━─ 114/124 6.5it/s 17.3s<1.5s

      43/50      10.1G      1.491      0.584     0.8682        115       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.5s<1.4s

      43/50      10.1G      1.489     0.5831      0.868        108       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.6s<1.2s

      43/50      10.1G      1.491     0.5839     0.8683        116       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.7s<1.0s

      43/50      10.1G       1.49     0.5834     0.8681        126       1024: 95% ━━━━━━━━━━━─ 118/124 6.8it/s 17.9s<0.9s

      43/50      10.1G      1.491     0.5831     0.8679         93       1024: 96% ━━━━━━━━━━━╸ 119/124 6.5it/s 18.1s<0.8s

      43/50      10.1G       1.49      0.583     0.8683        102       1024: 97% ━━━━━━━━━━━╸ 120/124 6.5it/s 18.2s<0.6s

      43/50      10.1G      1.491      0.584     0.8687        114       1024: 98% ━━━━━━━━━━━╸ 121/124 6.6it/s 18.4s<0.5s

      43/50      10.1G      1.492     0.5854     0.8691        105       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.5s<0.3s

      43/50      10.1G      1.492     0.5861     0.8695         96       1024: 99% ━━━━━━━━━━━╸ 123/124 6.7it/s 18.7s<0.1s

      43/50      10.1G      1.492     0.5861     0.8695         96       1024: 100% ━━━━━━━━━━━━ 124/124 6.6it/s 18.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.9it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.7it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.1it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.3it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.4it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.4it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.5it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.6it/s 2.4s

                   all        330       4227      0.708      0.605      0.627       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      44/50      10.1G      1.314     0.5127     0.8513        103       1024: 0% ──────────── 0/124  0.1s

      44/50      10.1G      1.401     0.5164      0.868        118       1024: 1% ──────────── 1/124 2.1it/s 0.3s<59.4s

      44/50      10.1G      1.413     0.5095     0.8615        132       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.7s

      44/50      10.1G       1.44     0.5388     0.8638        120       1024: 2% ──────────── 3/124 4.2it/s 0.6s<28.8s

      44/50      10.1G      1.442     0.5418     0.8595         95       1024: 3% ──────────── 4/124 4.9it/s 0.8s<24.3s

      44/50      10.1G       1.44     0.5405      0.855        124       1024: 4% ──────────── 5/124 5.5it/s 0.9s<21.6s

      44/50      10.1G      1.458     0.5469     0.8629        116       1024: 5% ╸─────────── 6/124 5.9it/s 1.0s<19.9s

      44/50      10.1G       1.46     0.5416     0.8691        107       1024: 6% ╸─────────── 7/124 6.1it/s 1.2s<19.1s

      44/50      10.1G      1.452     0.5428      0.867        115       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.3s

      44/50      10.1G      1.437     0.5374     0.8633         97       1024: 7% ╸─────────── 9/124 6.5it/s 1.5s<17.7s

      44/50      10.1G      1.457     0.5472      0.868        118       1024: 8% ╸─────────── 10/124 6.6it/s 1.6s<17.2s

      44/50      10.1G      1.471     0.5481     0.8721        105       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.6s

      44/50      10.1G      1.493     0.5554      0.875        117       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<17.0s

      44/50      10.1G      1.499     0.5581     0.8752        110       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.6s

      44/50      10.1G      1.496     0.5583     0.8774        109       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.3s

      44/50      10.1G      1.498     0.5603     0.8768        118       1024: 12% ━─────────── 15/124 6.8it/s 2.4s<16.1s

      44/50      10.1G        1.5     0.5643     0.8802        119       1024: 13% ━╸────────── 16/124 6.8it/s 2.5s<15.9s

      44/50      10.1G      1.506     0.5662     0.8817        117       1024: 14% ━╸────────── 17/124 6.8it/s 2.7s<15.7s

      44/50      10.1G      1.506     0.5652     0.8815        116       1024: 15% ━╸────────── 18/124 6.8it/s 2.8s<15.5s

      44/50      10.1G      1.511     0.5687     0.8824        123       1024: 15% ━╸────────── 19/124 6.5it/s 3.0s<16.1s

      44/50      10.1G      1.498      0.569     0.8787         92       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.6s

      44/50      10.1G      1.491     0.5674     0.8793        118       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      44/50      10.1G      1.495     0.5682     0.8791        136       1024: 18% ━━────────── 22/124 6.7it/s 3.4s<15.2s

      44/50      10.1G      1.487     0.5668     0.8764        116       1024: 19% ━━────────── 23/124 6.8it/s 3.6s<14.9s

      44/50      10.1G      1.484     0.5662     0.8741        121       1024: 19% ━━────────── 24/124 6.8it/s 3.7s<14.7s

      44/50      10.1G      1.481     0.5638     0.8728        112       1024: 20% ━━────────── 25/124 6.8it/s 3.9s<14.5s

      44/50      10.1G       1.48     0.5636     0.8718        104       1024: 21% ━━╸───────── 26/124 6.9it/s 4.0s<14.3s

      44/50      10.1G      1.476     0.5609      0.871        104       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.8s

      44/50      10.1G      1.481     0.5652     0.8726        113       1024: 23% ━━╸───────── 28/124 6.6it/s 4.3s<14.5s

      44/50      10.1G      1.474     0.5612     0.8719        113       1024: 23% ━━╸───────── 29/124 6.7it/s 4.5s<14.2s

      44/50      10.1G      1.471     0.5612     0.8719        100       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.9s

      44/50      10.1G       1.48     0.5631     0.8731        112       1024: 25% ━━━───────── 31/124 6.7it/s 4.8s<13.9s

      44/50      10.1G      1.478     0.5609     0.8727        113       1024: 26% ━━━───────── 32/124 6.7it/s 4.9s<13.6s

      44/50      10.1G      1.475     0.5606     0.8716        126       1024: 27% ━━━───────── 33/124 6.8it/s 5.1s<13.4s

      44/50      10.1G      1.474     0.5623     0.8708        111       1024: 27% ━━━───────── 34/124 6.8it/s 5.2s<13.2s

      44/50      10.1G      1.469     0.5616     0.8699        118       1024: 28% ━━━───────── 35/124 6.5it/s 5.4s<13.7s

      44/50      10.1G      1.466     0.5614     0.8691        107       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.3s

      44/50      10.1G      1.465     0.5612     0.8688        109       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.7s<13.0s

      44/50      10.1G      1.465     0.5625     0.8689        131       1024: 31% ━━━╸──────── 38/124 6.6it/s 5.8s<12.9s

      44/50      10.1G      1.463     0.5635     0.8682         99       1024: 31% ━━━╸──────── 39/124 6.6it/s 6.0s<12.8s

      44/50      10.1G      1.466      0.564     0.8684        113       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.1s<12.8s

      44/50      10.1G      1.467      0.564     0.8683        118       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.6s

      44/50      10.1G      1.466     0.5638     0.8681        109       1024: 34% ━━━━──────── 42/124 6.7it/s 6.4s<12.3s

      44/50      10.1G       1.46     0.5628     0.8672         98       1024: 35% ━━━━──────── 43/124 6.4it/s 6.6s<12.7s

      44/50      10.1G       1.46     0.5634      0.867        105       1024: 35% ━━━━──────── 44/124 6.5it/s 6.8s<12.3s

      44/50      10.1G       1.46     0.5636     0.8668        124       1024: 36% ━━━━──────── 45/124 6.6it/s 6.9s<11.9s

      44/50      10.1G      1.464     0.5654      0.866        112       1024: 37% ━━━━──────── 46/124 6.7it/s 7.0s<11.6s

      44/50      10.1G      1.463     0.5656     0.8662        109       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.2s<11.3s

      44/50      10.1G       1.46     0.5647     0.8654        108       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.3s<11.1s

      44/50      10.1G      1.463     0.5677     0.8678         99       1024: 40% ━━━━╸─────── 49/124 6.9it/s 7.5s<10.9s

      44/50      10.1G      1.465     0.5685     0.8687        117       1024: 40% ━━━━╸─────── 50/124 6.9it/s 7.6s<10.7s

      44/50      10.1G      1.469      0.569     0.8691         98       1024: 41% ━━━━╸─────── 51/124 6.6it/s 7.8s<11.1s

      44/50      10.1G      1.475     0.5714     0.8697        106       1024: 42% ━━━━━─────── 52/124 6.7it/s 7.9s<10.7s

      44/50      10.1G      1.474     0.5713     0.8691        105       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.5s

      44/50      10.1G      1.474     0.5705     0.8687        111       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.2s<10.3s

      44/50      10.1G      1.477     0.5714     0.8691        136       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.4s<10.1s

      44/50      10.1G      1.479     0.5723     0.8691        118       1024: 45% ━━━━━─────── 56/124 6.9it/s 8.5s<9.9s

      44/50      10.1G       1.48     0.5724     0.8685        126       1024: 46% ━━━━━╸────── 57/124 6.9it/s 8.7s<9.8s

      44/50      10.1G      1.478     0.5734     0.8693        111       1024: 47% ━━━━━╸────── 58/124 6.9it/s 8.8s<9.6s

      44/50      10.1G      1.483     0.5749     0.8701        136       1024: 48% ━━━━━╸────── 59/124 6.5it/s 9.0s<9.9s

      44/50      10.1G      1.483     0.5749     0.8699        115       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.1s<9.8s

      44/50      10.1G      1.485      0.576     0.8695        123       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.3s<9.5s

      44/50      10.1G      1.482     0.5756     0.8691        110       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.4s<9.3s

      44/50      10.1G      1.481      0.576     0.8693        114       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.6s<9.0s

      44/50      10.1G      1.482     0.5764     0.8689        115       1024: 52% ━━━━━━────── 64/124 6.8it/s 9.7s<8.9s

      44/50      10.1G       1.48     0.5763     0.8688        116       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.9s<8.7s

      44/50      10.1G      1.486     0.5775     0.8683        111       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.0s<8.5s

      44/50      10.1G      1.493     0.5816     0.8692        125       1024: 54% ━━━━━━────── 67/124 6.4it/s 10.2s<8.9s

      44/50      10.1G      1.494      0.582     0.8696        112       1024: 55% ━━━━━━╸───── 68/124 6.5it/s 10.3s<8.7s

      44/50      10.1G      1.492     0.5811     0.8697        129       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.5s<8.3s

      44/50      10.1G      1.491       0.58     0.8697        134       1024: 56% ━━━━━━╸───── 70/124 6.6it/s 10.6s<8.2s

      44/50      10.1G      1.491      0.579     0.8693        114       1024: 57% ━━━━━━╸───── 71/124 6.6it/s 10.8s<8.1s

      44/50      10.1G      1.489      0.579     0.8686        103       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 10.9s<7.8s

      44/50      10.1G      1.488     0.5783     0.8681        110       1024: 59% ━━━━━━━───── 73/124 6.6it/s 11.1s<7.7s

      44/50      10.1G      1.491     0.5792     0.8692        115       1024: 60% ━━━━━━━───── 74/124 6.7it/s 11.2s<7.5s

      44/50      10.1G      1.496     0.5809     0.8705         99       1024: 60% ━━━━━━━───── 75/124 6.4it/s 11.4s<7.6s

      44/50      10.1G      1.495     0.5799       0.87        119       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.6s<7.4s

      44/50      10.1G      1.495     0.5801     0.8699        105       1024: 62% ━━━━━━━───── 77/124 6.5it/s 11.7s<7.2s

      44/50      10.1G      1.495     0.5801     0.8698        120       1024: 63% ━━━━━━━╸──── 78/124 6.6it/s 11.9s<7.0s

      44/50      10.1G      1.495     0.5801     0.8695        111       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 12.0s<6.7s

      44/50      10.1G      1.493     0.5795     0.8694        114       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.1s<6.5s

      44/50      10.1G      1.492     0.5786     0.8685        117       1024: 65% ━━━━━━━╸──── 81/124 6.8it/s 12.3s<6.3s

      44/50      10.1G      1.492     0.5793     0.8685        124       1024: 66% ━━━━━━━╸──── 82/124 6.8it/s 12.4s<6.2s

      44/50      10.1G      1.492     0.5793     0.8698        115       1024: 67% ━━━━━━━━──── 83/124 6.5it/s 12.6s<6.3s

      44/50      10.1G      1.489     0.5784     0.8687        101       1024: 68% ━━━━━━━━──── 84/124 6.6it/s 12.8s<6.1s

      44/50      10.1G      1.487     0.5779     0.8685        114       1024: 69% ━━━━━━━━──── 85/124 6.7it/s 12.9s<5.8s

      44/50      10.1G      1.488      0.578     0.8684        111       1024: 69% ━━━━━━━━──── 86/124 6.7it/s 13.0s<5.6s

      44/50      10.1G      1.486     0.5781     0.8682         93       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.2s<5.5s

      44/50      10.1G      1.484     0.5774     0.8677        111       1024: 71% ━━━━━━━━╸─── 88/124 6.8it/s 13.3s<5.3s

      44/50      10.1G      1.482     0.5765     0.8669        127       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.2s

      44/50      10.1G      1.483      0.577     0.8673        123       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.6s<5.0s

      44/50      10.1G      1.483     0.5765      0.867        124       1024: 73% ━━━━━━━━╸─── 91/124 6.5it/s 13.8s<5.1s

      44/50      10.1G      1.486     0.5777     0.8674        121       1024: 74% ━━━━━━━━╸─── 92/124 6.6it/s 14.0s<4.8s

      44/50      10.1G      1.485     0.5768     0.8674        109       1024: 75% ━━━━━━━━━─── 93/124 6.7it/s 14.1s<4.6s

      44/50      10.1G      1.486     0.5769     0.8669        115       1024: 76% ━━━━━━━━━─── 94/124 6.7it/s 14.2s<4.5s

      44/50      10.1G      1.485     0.5769     0.8674        120       1024: 77% ━━━━━━━━━─── 95/124 6.8it/s 14.4s<4.3s

      44/50      10.1G      1.486     0.5771     0.8674        117       1024: 77% ━━━━━━━━━─── 96/124 6.8it/s 14.5s<4.1s

      44/50      10.1G      1.485      0.577     0.8668        108       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.7s<4.0s

      44/50      10.1G      1.484     0.5767     0.8668        115       1024: 79% ━━━━━━━━━─── 98/124 6.8it/s 14.8s<3.8s

      44/50      10.1G      1.484     0.5766     0.8668        102       1024: 80% ━━━━━━━━━╸── 99/124 6.5it/s 15.0s<3.8s

      44/50      10.1G      1.485     0.5772     0.8668        108       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.1s<3.6s

      44/50      10.1G      1.485     0.5777     0.8664        103       1024: 81% ━━━━━━━━━╸── 101/124 6.7it/s 15.3s<3.4s

      44/50      10.1G      1.482     0.5765     0.8657        107       1024: 82% ━━━━━━━━━╸── 102/124 6.8it/s 15.4s<3.3s

      44/50      10.1G      1.485     0.5776     0.8656        120       1024: 83% ━━━━━━━━━╸── 103/124 6.8it/s 15.6s<3.1s

      44/50      10.1G      1.483     0.5765     0.8654         93       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.7s<3.0s

      44/50      10.1G      1.482     0.5762     0.8652        104       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.8s

      44/50      10.1G      1.483     0.5773     0.8651        117       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.0s<2.7s

      44/50      10.1G      1.485     0.5786     0.8663        109       1024: 86% ━━━━━━━━━━── 107/124 6.5it/s 16.2s<2.6s

      44/50      10.1G      1.484     0.5782     0.8661        111       1024: 87% ━━━━━━━━━━── 108/124 6.5it/s 16.4s<2.5s

      44/50      10.1G      1.483     0.5777     0.8657        122       1024: 88% ━━━━━━━━━━╸─ 109/124 6.6it/s 16.5s<2.3s

      44/50      10.1G      1.482     0.5771     0.8654        118       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.7s<2.1s

      44/50      10.1G      1.483     0.5774     0.8652        115       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.8s<2.0s

      44/50      10.1G      1.481     0.5771      0.865        108       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 16.9s<1.8s

      44/50      10.1G       1.48     0.5772     0.8648        103       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.1s<1.6s

      44/50      10.1G       1.48     0.5778      0.865         96       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.2s<1.5s

      44/50      10.1G       1.48     0.5773     0.8652        110       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.4s<1.4s

      44/50      10.1G      1.478      0.577     0.8646        100       1024: 94% ━━━━━━━━━━━─ 116/124 6.5it/s 17.6s<1.2s

      44/50      10.1G      1.479     0.5766     0.8651        121       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.7s<1.1s

      44/50      10.1G      1.479     0.5764     0.8651         94       1024: 95% ━━━━━━━━━━━─ 118/124 6.7it/s 17.9s<0.9s

      44/50      10.1G      1.481     0.5774      0.865        104       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.0s<0.8s

      44/50      10.1G      1.482     0.5777      0.865        128       1024: 97% ━━━━━━━━━━━╸ 120/124 6.7it/s 18.2s<0.6s

      44/50      10.1G      1.482     0.5773     0.8655         95       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.3s<0.4s

      44/50      10.1G      1.482     0.5774     0.8652        129       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.4s<0.3s

      44/50      10.1G      1.481     0.5765      0.865        104       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.6s<0.2s

      44/50      10.1G      1.481     0.5765      0.865        104       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.5it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.0it/s 0.6s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.8it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.9it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.3it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.4it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.6it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.5it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.5it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.5it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.4it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.7it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.8it/s 2.4s

                   all        330       4227      0.687        0.6      0.619      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      45/50      10.1G      1.641     0.6481       0.89        121       1024: 0% ──────────── 0/124  0.1s

      45/50      10.1G      1.553     0.6016     0.8915        119       1024: 1% ──────────── 1/124 2.0it/s 0.3s<1:02

      45/50      10.1G      1.505     0.5615     0.8642        107       1024: 2% ──────────── 2/124 3.4it/s 0.4s<36.3s

      45/50      10.1G      1.511     0.5575     0.8674        128       1024: 2% ──────────── 3/124 4.4it/s 0.6s<27.4s

      45/50      10.1G      1.482     0.5528     0.8665        100       1024: 3% ──────────── 4/124 5.1it/s 0.7s<23.3s

      45/50      10.1G      1.455     0.5419     0.8582        113       1024: 4% ──────────── 5/124 5.7it/s 0.9s<21.0s

      45/50      10.1G      1.485     0.5569     0.8657        119       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.8s

      45/50      10.1G      1.487     0.5598     0.8687        102       1024: 6% ╸─────────── 7/124 5.9it/s 1.2s<19.8s

      45/50      10.1G      1.486     0.5705     0.8666        111       1024: 6% ╸─────────── 8/124 6.1it/s 1.4s<19.0s

      45/50      10.1G      1.465     0.5628     0.8674         95       1024: 7% ╸─────────── 9/124 6.2it/s 1.5s<18.5s

      45/50      10.1G      1.468     0.5683     0.8664        109       1024: 8% ╸─────────── 10/124 6.4it/s 1.7s<17.8s

      45/50      10.1G      1.469     0.5678     0.8661        127       1024: 9% ━─────────── 11/124 6.6it/s 1.8s<17.2s

      45/50      10.1G       1.48      0.567     0.8646        110       1024: 10% ━─────────── 12/124 6.6it/s 2.0s<16.9s

      45/50      10.1G      1.478     0.5637     0.8637        115       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.6s

      45/50      10.1G      1.465      0.557     0.8629        120       1024: 11% ━─────────── 14/124 6.7it/s 2.2s<16.5s

      45/50      10.1G      1.461     0.5579      0.864        115       1024: 12% ━─────────── 15/124 6.4it/s 2.4s<17.0s

      45/50      10.1G      1.452     0.5553      0.859        113       1024: 13% ━╸────────── 16/124 6.5it/s 2.6s<16.7s

      45/50      10.1G      1.442     0.5511     0.8567        109       1024: 14% ━╸────────── 17/124 6.6it/s 2.7s<16.2s

      45/50      10.1G      1.433     0.5541     0.8579         99       1024: 15% ━╸────────── 18/124 6.7it/s 2.9s<15.9s

      45/50      10.1G      1.432     0.5528     0.8574        113       1024: 15% ━╸────────── 19/124 6.7it/s 3.0s<15.6s

      45/50      10.1G      1.433     0.5513     0.8571        125       1024: 16% ━╸────────── 20/124 6.8it/s 3.2s<15.3s

      45/50      10.1G      1.436      0.553     0.8576        122       1024: 17% ━━────────── 21/124 6.7it/s 3.3s<15.4s

      45/50      10.1G       1.44     0.5552     0.8576         99       1024: 18% ━━────────── 22/124 6.7it/s 3.5s<15.1s

      45/50      10.1G      1.436     0.5563     0.8585        105       1024: 19% ━━────────── 23/124 6.3it/s 3.6s<15.9s

      45/50      10.1G      1.438     0.5558      0.858        123       1024: 19% ━━────────── 24/124 6.5it/s 3.8s<15.4s

      45/50      10.1G      1.429     0.5522     0.8563        106       1024: 20% ━━────────── 25/124 6.6it/s 3.9s<15.0s

      45/50      10.1G      1.438     0.5565      0.857        142       1024: 21% ━━╸───────── 26/124 6.7it/s 4.1s<14.7s

      45/50      10.1G      1.444     0.5592     0.8592        109       1024: 22% ━━╸───────── 27/124 6.7it/s 4.2s<14.4s

      45/50      10.1G      1.445     0.5595     0.8611        117       1024: 23% ━━╸───────── 28/124 6.7it/s 4.4s<14.3s

      45/50      10.1G      1.446       0.56     0.8603        121       1024: 23% ━━╸───────── 29/124 6.8it/s 4.5s<14.1s

      45/50      10.1G      1.445     0.5607     0.8594        120       1024: 24% ━━╸───────── 30/124 6.8it/s 4.7s<13.8s

      45/50      10.1G      1.446     0.5638     0.8605        105       1024: 25% ━━━───────── 31/124 6.5it/s 4.8s<14.4s

      45/50      10.1G      1.453      0.564     0.8602        100       1024: 26% ━━━───────── 32/124 6.6it/s 5.0s<14.0s

      45/50      10.1G      1.455     0.5655     0.8597        133       1024: 27% ━━━───────── 33/124 6.7it/s 5.1s<13.7s

      45/50      10.1G      1.456     0.5665     0.8595        115       1024: 27% ━━━───────── 34/124 6.7it/s 5.3s<13.4s

      45/50      10.1G      1.454     0.5671     0.8598        115       1024: 28% ━━━───────── 35/124 6.7it/s 5.4s<13.2s

      45/50      10.1G      1.454     0.5671     0.8597        117       1024: 29% ━━━───────── 36/124 6.8it/s 5.6s<13.0s

      45/50      10.1G      1.454     0.5661     0.8583        130       1024: 30% ━━━╸──────── 37/124 6.8it/s 5.7s<12.8s

      45/50      10.1G       1.45     0.5657     0.8573        122       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.9s<12.6s

      45/50      10.1G       1.45     0.5662     0.8597        117       1024: 31% ━━━╸──────── 39/124 6.4it/s 6.0s<13.3s

      45/50      10.1G      1.449     0.5658     0.8585        107       1024: 32% ━━━╸──────── 40/124 6.6it/s 6.2s<12.8s

      45/50      10.1G      1.453      0.569     0.8605        113       1024: 33% ━━━╸──────── 41/124 6.6it/s 6.3s<12.5s

      45/50      10.1G      1.447     0.5662     0.8585        116       1024: 34% ━━━━──────── 42/124 6.7it/s 6.5s<12.2s

      45/50      10.1G      1.444     0.5645     0.8576        118       1024: 35% ━━━━──────── 43/124 6.7it/s 6.6s<12.0s

      45/50      10.1G      1.446     0.5644     0.8581         95       1024: 35% ━━━━──────── 44/124 6.8it/s 6.8s<11.8s

      45/50      10.1G      1.441     0.5625     0.8574        103       1024: 36% ━━━━──────── 45/124 6.8it/s 6.9s<11.6s

      45/50      10.1G      1.437     0.5602     0.8558        120       1024: 37% ━━━━──────── 46/124 6.8it/s 7.1s<11.5s

      45/50      10.1G      1.437     0.5603     0.8557        105       1024: 38% ━━━━╸─────── 47/124 6.5it/s 7.2s<11.9s

      45/50      10.1G      1.435     0.5594     0.8561        123       1024: 39% ━━━━╸─────── 48/124 6.6it/s 7.4s<11.5s

      45/50      10.1G      1.436     0.5597      0.856        108       1024: 40% ━━━━╸─────── 49/124 6.7it/s 7.5s<11.2s

      45/50      10.1G      1.433     0.5582     0.8551        103       1024: 40% ━━━━╸─────── 50/124 6.7it/s 7.7s<11.0s

      45/50      10.1G      1.434     0.5577     0.8547        115       1024: 41% ━━━━╸─────── 51/124 6.8it/s 7.8s<10.8s

      45/50      10.1G      1.434     0.5577     0.8537        108       1024: 42% ━━━━━─────── 52/124 6.8it/s 8.0s<10.6s

      45/50      10.1G       1.44     0.5616     0.8547        109       1024: 43% ━━━━━─────── 53/124 6.8it/s 8.1s<10.4s

      45/50      10.1G      1.442     0.5611     0.8559        107       1024: 44% ━━━━━─────── 54/124 6.8it/s 8.3s<10.3s

      45/50      10.1G      1.439     0.5597     0.8552        115       1024: 44% ━━━━━─────── 55/124 6.5it/s 8.4s<10.6s

      45/50      10.1G      1.439     0.5595     0.8552        100       1024: 45% ━━━━━─────── 56/124 6.6it/s 8.6s<10.3s

      45/50      10.1G      1.442     0.5605     0.8552        124       1024: 46% ━━━━━╸────── 57/124 6.7it/s 8.7s<10.0s

      45/50      10.1G      1.445     0.5619     0.8559        118       1024: 47% ━━━━━╸────── 58/124 6.7it/s 8.9s<9.8s

      45/50      10.1G      1.445     0.5625     0.8558        112       1024: 48% ━━━━━╸────── 59/124 6.8it/s 9.0s<9.6s

      45/50      10.1G      1.445     0.5633     0.8559        116       1024: 48% ━━━━━╸────── 60/124 6.8it/s 9.2s<9.4s

      45/50      10.1G      1.443     0.5629     0.8556        116       1024: 49% ━━━━━╸────── 61/124 6.8it/s 9.3s<9.2s

      45/50      10.1G      1.442     0.5625     0.8544        116       1024: 50% ━━━━━━────── 62/124 6.8it/s 9.5s<9.1s

      45/50      10.1G      1.441     0.5623     0.8534        115       1024: 51% ━━━━━━────── 63/124 6.5it/s 9.6s<9.4s

      45/50      10.1G      1.442     0.5633      0.854        111       1024: 52% ━━━━━━────── 64/124 6.5it/s 9.8s<9.2s

      45/50      10.1G      1.442     0.5642     0.8543        108       1024: 52% ━━━━━━────── 65/124 6.6it/s 9.9s<8.9s

      45/50      10.1G      1.441     0.5647     0.8546        105       1024: 53% ━━━━━━────── 66/124 6.6it/s 10.1s<8.8s

      45/50      10.1G      1.441     0.5639     0.8539        121       1024: 54% ━━━━━━────── 67/124 6.7it/s 10.2s<8.5s

      45/50      10.1G      1.441     0.5634      0.854         93       1024: 55% ━━━━━━╸───── 68/124 6.7it/s 10.4s<8.3s

      45/50      10.1G      1.442     0.5632     0.8543        118       1024: 56% ━━━━━━╸───── 69/124 6.8it/s 10.5s<8.1s

      45/50      10.1G      1.445     0.5643     0.8538        121       1024: 56% ━━━━━━╸───── 70/124 6.8it/s 10.7s<7.9s

      45/50      10.1G      1.443     0.5634     0.8542        115       1024: 57% ━━━━━━╸───── 71/124 6.5it/s 10.8s<8.1s

      45/50      10.1G      1.441     0.5628     0.8538        116       1024: 58% ━━━━━━╸───── 72/124 6.6it/s 11.0s<7.8s

      45/50      10.1G      1.443     0.5631     0.8539        129       1024: 59% ━━━━━━━───── 73/124 6.7it/s 11.1s<7.6s

      45/50      10.1G      1.441     0.5635     0.8545        105       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.3s<7.4s

      45/50      10.1G      1.442     0.5645     0.8548        115       1024: 60% ━━━━━━━───── 75/124 6.8it/s 11.4s<7.2s

      45/50      10.1G      1.442     0.5648     0.8551        115       1024: 61% ━━━━━━━───── 76/124 6.9it/s 11.6s<7.0s

      45/50      10.1G      1.445     0.5648     0.8558        126       1024: 62% ━━━━━━━───── 77/124 6.9it/s 11.7s<6.8s

      45/50      10.1G      1.444     0.5646     0.8563        106       1024: 63% ━━━━━━━╸──── 78/124 6.9it/s 11.8s<6.7s

      45/50      10.1G      1.441      0.564     0.8561        104       1024: 64% ━━━━━━━╸──── 79/124 6.5it/s 12.0s<6.9s

      45/50      10.1G      1.439     0.5627      0.855        108       1024: 65% ━━━━━━━╸──── 80/124 6.7it/s 12.2s<6.6s

      45/50      10.1G      1.439     0.5632     0.8554        130       1024: 65% ━━━━━━━╸──── 81/124 6.6it/s 12.3s<6.5s

      45/50      10.1G      1.442      0.563      0.856        119       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.5s<6.2s

      45/50      10.1G      1.441     0.5631      0.856        106       1024: 67% ━━━━━━━━──── 83/124 6.8it/s 12.6s<6.0s

      45/50      10.1G      1.444     0.5644     0.8563         93       1024: 68% ━━━━━━━━──── 84/124 6.8it/s 12.7s<5.8s

      45/50      10.1G      1.447     0.5649     0.8572         99       1024: 69% ━━━━━━━━──── 85/124 6.9it/s 12.9s<5.7s

      45/50      10.1G      1.442     0.5641     0.8568         98       1024: 69% ━━━━━━━━──── 86/124 6.8it/s 13.0s<5.6s

      45/50      10.1G      1.443     0.5637     0.8573        110       1024: 70% ━━━━━━━━──── 87/124 6.5it/s 13.2s<5.7s

      45/50      10.1G      1.443     0.5642     0.8571        102       1024: 71% ━━━━━━━━╸─── 88/124 6.6it/s 13.4s<5.4s

      45/50      10.1G      1.445     0.5649     0.8569        117       1024: 72% ━━━━━━━━╸─── 89/124 6.7it/s 13.5s<5.2s

      45/50      10.1G      1.446      0.565     0.8565        112       1024: 73% ━━━━━━━━╸─── 90/124 6.8it/s 13.7s<5.0s

      45/50      10.1G      1.448     0.5656     0.8568        108       1024: 73% ━━━━━━━━╸─── 91/124 6.8it/s 13.8s<4.8s

      45/50      10.1G      1.448     0.5653     0.8569        107       1024: 74% ━━━━━━━━╸─── 92/124 6.9it/s 13.9s<4.7s

      45/50      10.1G      1.446     0.5644     0.8564        123       1024: 75% ━━━━━━━━━─── 93/124 6.9it/s 14.1s<4.5s

      45/50      10.1G      1.446      0.564     0.8565        129       1024: 76% ━━━━━━━━━─── 94/124 6.9it/s 14.2s<4.3s

      45/50      10.1G      1.447     0.5641     0.8567        112       1024: 77% ━━━━━━━━━─── 95/124 6.6it/s 14.4s<4.4s

      45/50      10.1G      1.447     0.5641     0.8569        111       1024: 77% ━━━━━━━━━─── 96/124 6.6it/s 14.5s<4.2s

      45/50      10.1G      1.445     0.5633     0.8568         96       1024: 78% ━━━━━━━━━─── 97/124 6.6it/s 14.7s<4.1s

      45/50      10.1G      1.446     0.5631     0.8576        105       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.8s<3.9s

      45/50      10.1G      1.446     0.5632     0.8577        112       1024: 80% ━━━━━━━━━╸── 99/124 6.8it/s 15.0s<3.7s

      45/50      10.1G      1.444     0.5623     0.8574        112       1024: 81% ━━━━━━━━━╸── 100/124 6.8it/s 15.1s<3.5s

      45/50      10.1G      1.445     0.5615     0.8576        120       1024: 81% ━━━━━━━━━╸── 101/124 6.9it/s 15.3s<3.4s

      45/50      10.1G      1.444     0.5608     0.8575        109       1024: 82% ━━━━━━━━━╸── 102/124 6.9it/s 15.4s<3.2s

      45/50      10.1G      1.446     0.5613     0.8575        130       1024: 83% ━━━━━━━━━╸── 103/124 6.6it/s 15.6s<3.2s

      45/50      10.1G      1.447     0.5617     0.8576        114       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.7s<3.0s

      45/50      10.1G      1.446     0.5622     0.8573        124       1024: 85% ━━━━━━━━━━── 105/124 6.8it/s 15.9s<2.8s

      45/50      10.1G      1.449     0.5625     0.8574        115       1024: 85% ━━━━━━━━━━── 106/124 6.8it/s 16.0s<2.6s

      45/50      10.1G      1.449     0.5624     0.8574        115       1024: 86% ━━━━━━━━━━── 107/124 6.9it/s 16.2s<2.5s

      45/50      10.1G      1.447     0.5617      0.857        105       1024: 87% ━━━━━━━━━━── 108/124 6.9it/s 16.3s<2.3s

      45/50      10.1G       1.45     0.5621     0.8578        106       1024: 88% ━━━━━━━━━━╸─ 109/124 6.9it/s 16.4s<2.2s

      45/50      10.1G      1.451     0.5619     0.8578        111       1024: 89% ━━━━━━━━━━╸─ 110/124 6.9it/s 16.6s<2.0s

      45/50      10.1G      1.451     0.5617     0.8578        101       1024: 90% ━━━━━━━━━━╸─ 111/124 6.6it/s 16.8s<2.0s

      45/50      10.1G      1.451     0.5617     0.8577        123       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 16.9s<1.8s

      45/50      10.1G      1.451     0.5618      0.858        115       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.1s<1.6s

      45/50      10.1G      1.454     0.5632     0.8586        141       1024: 92% ━━━━━━━━━━━─ 114/124 6.7it/s 17.2s<1.5s

      45/50      10.1G      1.457     0.5646     0.8591        108       1024: 93% ━━━━━━━━━━━─ 115/124 6.7it/s 17.4s<1.3s

      45/50      10.1G      1.458     0.5649     0.8595        106       1024: 94% ━━━━━━━━━━━─ 116/124 6.8it/s 17.5s<1.2s

      45/50      10.1G      1.458     0.5656     0.8599        116       1024: 94% ━━━━━━━━━━━─ 117/124 6.8it/s 17.6s<1.0s

      45/50      10.1G      1.456      0.565     0.8598        102       1024: 95% ━━━━━━━━━━━─ 118/124 6.9it/s 17.8s<0.9s

      45/50      10.1G      1.455     0.5645     0.8598        106       1024: 96% ━━━━━━━━━━━╸ 119/124 6.6it/s 18.0s<0.8s

      45/50      10.1G      1.457     0.5651     0.8603        109       1024: 97% ━━━━━━━━━━━╸ 120/124 6.6it/s 18.1s<0.6s

      45/50      10.1G      1.459     0.5656     0.8605        140       1024: 98% ━━━━━━━━━━━╸ 121/124 6.7it/s 18.3s<0.4s

      45/50      10.1G      1.459     0.5659     0.8602        148       1024: 98% ━━━━━━━━━━━╸ 122/124 6.7it/s 18.4s<0.3s

      45/50      10.1G      1.459     0.5658     0.8602        101       1024: 99% ━━━━━━━━━━━╸ 123/124 6.8it/s 18.5s<0.1s

      45/50      10.1G      1.459     0.5658     0.8602        101       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.7it/s 0.3s<3.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.6it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 7.2it/s 0.6s<2.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.9it/s 0.7s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 8.1it/s 0.8s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.2it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.3it/s 1.0s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.4it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.5it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.5it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.6it/s 1.5s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.5it/s 1.6s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.6it/s 1.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.6it/s 1.8s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.6it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.6it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.6it/s 2.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.6it/s 2.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.8it/s 2.4s

                   all        330       4227      0.692      0.633       0.63      0.383

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      46/50      10.1G      1.501     0.5263     0.8338        118       1024: 0% ──────────── 0/124  0.1s

      46/50      10.1G      1.411     0.5487     0.8125        126       1024: 1% ──────────── 1/124 2.1it/s 0.3s<58.9s

      46/50      10.1G      1.421     0.5475      0.829         98       1024: 2% ──────────── 2/124 3.5it/s 0.4s<34.4s

      46/50      10.1G      1.485     0.5579     0.8499         94       1024: 2% ──────────── 3/124 4.2it/s 0.6s<28.6s

      46/50      10.1G      1.528     0.5751      0.849        116       1024: 3% ──────────── 4/124 5.0it/s 0.8s<24.2s

      46/50      10.1G      1.512     0.5719      0.851        126       1024: 4% ──────────── 5/124 5.6it/s 0.9s<21.4s

      46/50      10.1G      1.541     0.5868     0.8533        123       1024: 5% ╸─────────── 6/124 6.0it/s 1.0s<19.7s

      46/50      10.1G      1.526     0.5832     0.8508        113       1024: 6% ╸─────────── 7/124 6.2it/s 1.2s<18.7s

      46/50      10.1G      1.499     0.5769     0.8505        121       1024: 6% ╸─────────── 8/124 6.4it/s 1.3s<18.0s

      46/50      10.1G      1.491     0.5712     0.8502        135       1024: 7% ╸─────────── 9/124 6.6it/s 1.5s<17.4s

      46/50      10.1G       1.47     0.5637     0.8458        121       1024: 8% ╸─────────── 10/124 6.7it/s 1.6s<17.1s

      46/50      10.1G      1.457     0.5601     0.8444        106       1024: 9% ━─────────── 11/124 6.4it/s 1.8s<17.6s

      46/50      10.1G      1.473      0.565     0.8493        115       1024: 10% ━─────────── 12/124 6.6it/s 1.9s<17.0s

      46/50      10.1G      1.462     0.5633     0.8491         98       1024: 10% ━─────────── 13/124 6.7it/s 2.1s<16.5s

      46/50      10.1G      1.456     0.5607     0.8487        119       1024: 11% ━─────────── 14/124 6.8it/s 2.2s<16.2s

      46/50      10.1G      1.461     0.5649     0.8489        117       1024: 12% ━─────────── 15/124 6.8it/s 2.4s<16.0s

      46/50      10.1G      1.456     0.5624     0.8466        127       1024: 13% ━╸────────── 16/124 6.9it/s 2.5s<15.7s

      46/50      10.1G       1.45      0.562     0.8484        113       1024: 14% ━╸────────── 17/124 6.9it/s 2.7s<15.5s

      46/50      10.1G      1.445     0.5585     0.8463        116       1024: 15% ━╸────────── 18/124 6.9it/s 2.8s<15.4s

      46/50      10.1G      1.446     0.5604     0.8478        106       1024: 15% ━╸────────── 19/124 6.6it/s 3.0s<16.0s

      46/50      10.1G      1.463     0.5672     0.8535        104       1024: 16% ━╸────────── 20/124 6.7it/s 3.1s<15.5s

      46/50      10.1G      1.459     0.5625     0.8528        109       1024: 17% ━━────────── 21/124 6.8it/s 3.3s<15.2s

      46/50      10.1G      1.457     0.5603     0.8519        129       1024: 18% ━━────────── 22/124 6.8it/s 3.4s<15.0s

      46/50      10.1G      1.464     0.5652     0.8542        114       1024: 19% ━━────────── 23/124 6.8it/s 3.5s<14.8s

      46/50      10.1G      1.473     0.5687     0.8537        101       1024: 19% ━━────────── 24/124 6.9it/s 3.7s<14.6s

      46/50      10.1G       1.47     0.5667     0.8512        105       1024: 20% ━━────────── 25/124 6.8it/s 3.8s<14.5s

      46/50      10.1G      1.469     0.5665     0.8501        122       1024: 21% ━━╸───────── 26/124 6.8it/s 4.0s<14.3s

      46/50      10.1G      1.467     0.5654     0.8502        107       1024: 22% ━━╸───────── 27/124 6.5it/s 4.2s<14.9s

      46/50      10.1G      1.474     0.5669     0.8566        102       1024: 23% ━━╸───────── 28/124 6.6it/s 4.3s<14.4s

      46/50      10.1G      1.469     0.5644     0.8553        124       1024: 23% ━━╸───────── 29/124 6.7it/s 4.4s<14.1s

      46/50      10.1G      1.471     0.5649      0.855        117       1024: 24% ━━╸───────── 30/124 6.8it/s 4.6s<13.9s

      46/50      10.1G      1.469     0.5636     0.8552        121       1024: 25% ━━━───────── 31/124 6.8it/s 4.7s<13.7s

      46/50      10.1G       1.47      0.562     0.8558        108       1024: 26% ━━━───────── 32/124 6.8it/s 4.9s<13.5s

      46/50      10.1G       1.47     0.5617     0.8549        109       1024: 27% ━━━───────── 33/124 6.8it/s 5.0s<13.3s

      46/50      10.1G      1.468     0.5609     0.8554        101       1024: 27% ━━━───────── 34/124 6.8it/s 5.2s<13.1s

      46/50      10.1G      1.462     0.5577     0.8548        119       1024: 28% ━━━───────── 35/124 6.5it/s 5.3s<13.7s

      46/50      10.1G      1.459     0.5557     0.8546        120       1024: 29% ━━━───────── 36/124 6.6it/s 5.5s<13.2s

      46/50      10.1G      1.461     0.5564     0.8553        118       1024: 30% ━━━╸──────── 37/124 6.7it/s 5.6s<13.0s

      46/50      10.1G      1.462      0.558      0.855        117       1024: 31% ━━━╸──────── 38/124 6.8it/s 5.8s<12.7s

      46/50      10.1G      1.466     0.5603     0.8564        119       1024: 31% ━━━╸──────── 39/124 6.8it/s 5.9s<12.5s

      46/50      10.1G      1.464      0.559      0.857        105       1024: 32% ━━━╸──────── 40/124 6.8it/s 6.1s<12.3s

      46/50      10.1G      1.469     0.5606     0.8583        112       1024: 33% ━━━╸──────── 41/124 6.8it/s 6.2s<12.1s

      46/50      10.1G      1.467     0.5596     0.8592         97       1024: 34% ━━━━──────── 42/124 6.8it/s 6.4s<12.0s

      46/50      10.1G      1.464     0.5594     0.8597        110       1024: 35% ━━━━──────── 43/124 6.5it/s 6.5s<12.4s

      46/50      10.1G      1.458     0.5571     0.8589        104       1024: 35% ━━━━──────── 44/124 6.6it/s 6.7s<12.0s

      46/50      10.1G       1.46      0.557     0.8584        115       1024: 36% ━━━━──────── 45/124 6.7it/s 6.8s<11.8s

      46/50      10.1G      1.455     0.5555     0.8567        111       1024: 37% ━━━━──────── 46/124 6.8it/s 7.0s<11.5s

      46/50      10.1G      1.453     0.5541     0.8563        114       1024: 38% ━━━━╸─────── 47/124 6.8it/s 7.1s<11.3s

      46/50      10.1G      1.452     0.5546     0.8563         93       1024: 39% ━━━━╸─────── 48/124 6.8it/s 7.3s<11.2s

      46/50      10.1G      1.448     0.5555     0.8559         86       1024: 40% ━━━━╸─────── 49/124 6.8it/s 7.4s<11.0s

      46/50      10.1G      1.447     0.5552     0.8563         98       1024: 40% ━━━━╸─────── 50/124 6.9it/s 7.6s<10.8s

      46/50      10.1G      1.446     0.5559     0.8576         96       1024: 41% ━━━━╸─────── 51/124 6.5it/s 7.7s<11.2s

      46/50      10.1G      1.456     0.5609     0.8597        114       1024: 42% ━━━━━─────── 52/124 6.7it/s 7.9s<10.8s

      46/50      10.1G      1.455     0.5616     0.8605        107       1024: 43% ━━━━━─────── 53/124 6.7it/s 8.0s<10.6s

      46/50      10.1G      1.453     0.5617     0.8601         92       1024: 44% ━━━━━─────── 54/124 6.7it/s 8.2s<10.5s

      46/50      10.1G      1.451     0.5611     0.8599        107       1024: 44% ━━━━━─────── 55/124 6.8it/s 8.3s<10.2s

      46/50      10.1G       1.45     0.5608      0.859        126       1024: 45% ━━━━━─────── 56/124 6.7it/s 8.5s<10.1s

      46/50      10.1G      1.453     0.5612     0.8597        102       1024: 46% ━━━━━╸────── 57/124 6.8it/s 8.6s<9.9s

      46/50      10.1G      1.452     0.5607     0.8594        105       1024: 47% ━━━━━╸────── 58/124 6.8it/s 8.8s<9.7s

      46/50      10.1G       1.45       0.56     0.8592        116       1024: 48% ━━━━━╸────── 59/124 6.4it/s 8.9s<10.1s

      46/50      10.1G      1.451       0.56     0.8591        103       1024: 48% ━━━━━╸────── 60/124 6.6it/s 9.1s<9.8s

      46/50      10.1G      1.453     0.5605     0.8596        116       1024: 49% ━━━━━╸────── 61/124 6.6it/s 9.2s<9.5s

      46/50      10.1G      1.456     0.5611     0.8599        117       1024: 50% ━━━━━━────── 62/124 6.7it/s 9.4s<9.2s

      46/50      10.1G      1.457     0.5616     0.8601        109       1024: 51% ━━━━━━────── 63/124 6.7it/s 9.5s<9.1s

      46/50      10.1G       1.46     0.5619     0.8599        137       1024: 52% ━━━━━━────── 64/124 6.7it/s 9.7s<8.9s

      46/50      10.1G      1.461     0.5629       0.86        116       1024: 52% ━━━━━━────── 65/124 6.8it/s 9.8s<8.7s

      46/50      10.1G      1.459     0.5619     0.8604        103       1024: 53% ━━━━━━────── 66/124 6.8it/s 10.0s<8.5s

      46/50      10.1G      1.457     0.5614     0.8601        111       1024: 54% ━━━━━━────── 67/124 6.5it/s 10.1s<8.8s

      46/50      10.1G      1.455     0.5609     0.8609        109       1024: 55% ━━━━━━╸───── 68/124 6.6it/s 10.3s<8.5s

      46/50      10.1G      1.455     0.5615     0.8608        123       1024: 56% ━━━━━━╸───── 69/124 6.6it/s 10.4s<8.4s

      46/50      10.1G      1.456     0.5617     0.8609        122       1024: 56% ━━━━━━╸───── 70/124 6.7it/s 10.6s<8.1s

      46/50      10.1G      1.457     0.5619      0.861        110       1024: 57% ━━━━━━╸───── 71/124 6.7it/s 10.7s<7.9s

      46/50      10.1G      1.455     0.5612     0.8605        126       1024: 58% ━━━━━━╸───── 72/124 6.8it/s 10.9s<7.7s

      46/50      10.1G      1.452     0.5596     0.8601        115       1024: 59% ━━━━━━━───── 73/124 6.8it/s 11.0s<7.5s

      46/50      10.1G      1.452     0.5605       0.86        111       1024: 60% ━━━━━━━───── 74/124 6.8it/s 11.2s<7.3s

      46/50      10.1G      1.451     0.5598     0.8601        118       1024: 60% ━━━━━━━───── 75/124 6.5it/s 11.3s<7.5s

      46/50      10.1G      1.448     0.5582     0.8595        101       1024: 61% ━━━━━━━───── 76/124 6.5it/s 11.5s<7.4s

      46/50      10.1G      1.445     0.5571     0.8588        108       1024: 62% ━━━━━━━───── 77/124 6.6it/s 11.6s<7.1s

      46/50      10.1G      1.444     0.5567     0.8584        115       1024: 63% ━━━━━━━╸──── 78/124 6.7it/s 11.8s<6.9s

      46/50      10.1G      1.444     0.5562     0.8586        119       1024: 64% ━━━━━━━╸──── 79/124 6.7it/s 11.9s<6.7s

      46/50      10.1G      1.445     0.5562     0.8593        120       1024: 65% ━━━━━━━╸──── 80/124 6.8it/s 12.1s<6.5s

      46/50      10.1G      1.445     0.5568     0.8597        107       1024: 65% ━━━━━━━╸──── 81/124 6.7it/s 12.2s<6.5s

      46/50      10.1G      1.442     0.5558     0.8597        106       1024: 66% ━━━━━━━╸──── 82/124 6.7it/s 12.4s<6.3s

      46/50      10.1G      1.443     0.5564     0.8601        112       1024: 67% ━━━━━━━━──── 83/124 6.4it/s 12.6s<6.4s

      46/50      10.1G      1.448     0.5581     0.8612         90       1024: 68% ━━━━━━━━──── 84/124 6.5it/s 12.7s<6.2s

      46/50      10.1G       1.45     0.5581     0.8612        126       1024: 69% ━━━━━━━━──── 85/124 6.5it/s 12.9s<6.0s

      46/50      10.1G      1.451      0.559     0.8609        109       1024: 69% ━━━━━━━━──── 86/124 6.6it/s 13.0s<5.8s

      46/50      10.1G      1.452     0.5594     0.8609        110       1024: 70% ━━━━━━━━──── 87/124 6.7it/s 13.1s<5.5s

      46/50      10.1G       1.45     0.5593     0.8602        113       1024: 71% ━━━━━━━━╸─── 88/124 6.7it/s 13.3s<5.4s

      46/50      10.1G       1.45     0.5602     0.8598        112       1024: 72% ━━━━━━━━╸─── 89/124 6.6it/s 13.4s<5.3s

      46/50      10.1G      1.451     0.5597     0.8606        103       1024: 73% ━━━━━━━━╸─── 90/124 6.7it/s 13.6s<5.1s

      46/50      10.1G       1.45     0.5587     0.8606        105       1024: 73% ━━━━━━━━╸─── 91/124 6.4it/s 13.8s<5.2s

      46/50      10.1G      1.449     0.5582     0.8603        110       1024: 74% ━━━━━━━━╸─── 92/124 6.4it/s 13.9s<5.0s

      46/50      10.1G       1.45     0.5584     0.8609         94       1024: 75% ━━━━━━━━━─── 93/124 6.5it/s 14.1s<4.7s

      46/50      10.1G       1.45     0.5593     0.8616        102       1024: 76% ━━━━━━━━━─── 94/124 6.6it/s 14.2s<4.5s

      46/50      10.1G      1.448     0.5586     0.8618        118       1024: 77% ━━━━━━━━━─── 95/124 6.7it/s 14.4s<4.3s

      46/50      10.1G      1.446      0.558     0.8618        113       1024: 77% ━━━━━━━━━─── 96/124 6.7it/s 14.5s<4.2s

      46/50      10.1G      1.446     0.5588     0.8616        110       1024: 78% ━━━━━━━━━─── 97/124 6.8it/s 14.7s<4.0s

      46/50      10.1G       1.45      0.561     0.8621        122       1024: 79% ━━━━━━━━━─── 98/124 6.7it/s 14.8s<3.9s

      46/50      10.1G      1.451     0.5605     0.8626        115       1024: 80% ━━━━━━━━━╸── 99/124 6.4it/s 15.0s<3.9s

      46/50      10.1G      1.451     0.5605     0.8625        119       1024: 81% ━━━━━━━━━╸── 100/124 6.6it/s 15.1s<3.7s

      46/50      10.1G      1.454     0.5613     0.8624        139       1024: 81% ━━━━━━━━━╸── 101/124 6.6it/s 15.3s<3.5s

      46/50      10.1G      1.456      0.562     0.8629        109       1024: 82% ━━━━━━━━━╸── 102/124 6.6it/s 15.4s<3.3s

      46/50      10.1G      1.457     0.5627      0.864        103       1024: 83% ━━━━━━━━━╸── 103/124 6.7it/s 15.6s<3.1s

      46/50      10.1G       1.46     0.5639     0.8647        127       1024: 84% ━━━━━━━━━━── 104/124 6.7it/s 15.7s<3.0s

      46/50      10.1G      1.458     0.5627     0.8642        113       1024: 85% ━━━━━━━━━━── 105/124 6.7it/s 15.9s<2.9s

      46/50      10.1G      1.458     0.5624     0.8643        104       1024: 85% ━━━━━━━━━━── 106/124 6.7it/s 16.0s<2.7s

      46/50      10.1G      1.458     0.5627     0.8642        121       1024: 86% ━━━━━━━━━━── 107/124 6.3it/s 16.2s<2.7s

      46/50      10.1G      1.459     0.5636     0.8646        112       1024: 87% ━━━━━━━━━━── 108/124 6.4it/s 16.4s<2.5s

      46/50      10.1G      1.458     0.5634     0.8644        128       1024: 88% ━━━━━━━━━━╸─ 109/124 6.5it/s 16.5s<2.3s

      46/50      10.1G      1.457     0.5627     0.8642        112       1024: 89% ━━━━━━━━━━╸─ 110/124 6.6it/s 16.6s<2.1s

      46/50      10.1G      1.456     0.5628     0.8646        117       1024: 90% ━━━━━━━━━━╸─ 111/124 6.7it/s 16.8s<1.9s

      46/50      10.1G      1.457     0.5637      0.865        134       1024: 90% ━━━━━━━━━━╸─ 112/124 6.7it/s 16.9s<1.8s

      46/50      10.1G      1.455     0.5631     0.8646        118       1024: 91% ━━━━━━━━━━╸─ 113/124 6.7it/s 17.1s<1.6s

      46/50      10.1G      1.455     0.5629     0.8646        126       1024: 92% ━━━━━━━━━━━─ 114/124 6.8it/s 17.2s<1.5s

      46/50      10.1G      1.456     0.5632     0.8646        118       1024: 93% ━━━━━━━━━━━─ 115/124 6.5it/s 17.4s<1.4s

      46/50      10.1G      1.455     0.5636     0.8647        110       1024: 94% ━━━━━━━━━━━─ 116/124 6.6it/s 17.6s<1.2s

      46/50      10.1G      1.456     0.5636     0.8646        121       1024: 94% ━━━━━━━━━━━─ 117/124 6.6it/s 17.7s<1.1s

      46/50      10.1G      1.458     0.5646     0.8653        118       1024: 95% ━━━━━━━━━━━─ 118/124 6.6it/s 17.9s<0.9s

      46/50      10.1G       1.46     0.5651     0.8649        119       1024: 96% ━━━━━━━━━━━╸ 119/124 6.7it/s 18.0s<0.7s

      46/50      10.1G       1.46     0.5654     0.8647        117       1024: 97% ━━━━━━━━━━━╸ 120/124 6.8it/s 18.1s<0.6s

      46/50      10.1G      1.459     0.5654     0.8647        103       1024: 98% ━━━━━━━━━━━╸ 121/124 6.8it/s 18.3s<0.4s

      46/50      10.1G      1.461     0.5662     0.8657        117       1024: 98% ━━━━━━━━━━━╸ 122/124 6.8it/s 18.4s<0.3s

      46/50      10.1G       1.46     0.5659      0.866        105       1024: 99% ━━━━━━━━━━━╸ 123/124 6.5it/s 18.6s<0.2s

      46/50      10.1G       1.46     0.5659      0.866        105       1024: 100% ━━━━━━━━━━━━ 124/124 6.7it/s 18.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.7it/s 0.1s<7.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 4.3it/s 0.2s<4.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 5.6it/s 0.3s<3.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 6.4it/s 0.5s<2.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 6.8it/s 0.6s<2.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 7.6it/s 0.7s<2.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 7.8it/s 0.8s<1.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 8.0it/s 0.9s<1.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 8.2it/s 1.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 8.3it/s 1.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 8.3it/s 1.3s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 8.4it/s 1.4s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.4it/s 1.5s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 8.3it/s 1.7s<0.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.3it/s 1.8s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.4it/s 1.9s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.4it/s 2.0s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.4it/s 2.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.3it/s 2.3s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.4it/s 2.4s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 8.5it/s 2.5s

                   all        330       4227      0.691      0.622      0.626      0.381

EarlyStopping: Training stopped early as no improvement observed in last 25 epochs. Best results observed at epoch 21, best model saved as best.pt.
To update EarlyStopping(patience=25) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

46 epochs completed in 0.287 hours.

Optimizer stripped from /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/weights/last.pt, 40.6MB

Optimizer stripped from /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/weights/best.pt, 40.6MB

Validating /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/weights/best.pt...

Ultralytics 8.4.48 🚀 Python-3.10.12 torch-2.11.0+cu130 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)

YOLO11m summary (fused): 126 layers, 20,033,116 parameters, 0 gradients, 67.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 2.5it/s 0.1s<8.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 3.9it/s 0.3s<4.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 4.9it/s 0.4s<3.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 5.7it/s 0.5s<3.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 4.1it/s 2.5s<3.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 5.3it/s 2.6s<2.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 6.0it/s 2.7s<2.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 6.8it/s 2.8s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 7.2it/s 3.0s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 7.5it/s 3.1s<1.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 7.8it/s 3.2s<1.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 7.9it/s 3.3s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 8.0it/s 3.4s<1.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 7.8it/s 3.6s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 8.2it/s 3.7s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 8.1it/s 3.8s<0.6s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 8.2it/s 3.9s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 8.2it/s 4.1s<0.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 8.2it/s 4.2s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 8.1it/s 4.3s<0.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 4.8it/s 4.4s

                   all        330       4227      0.658      0.618      0.636      0.388

               premium        330       2884      0.796      0.809      0.846       0.54

                single        307        942      0.771      0.791      0.831      0.565

             undersize        161        248      0.593      0.613      0.568      0.297

              abnormal        103        153      0.472      0.261      0.298      0.149

Speed: 0.2ms preprocess, 3.9ms inference, 0.0ms loss, 6.5ms postprocess per image

Results saved to /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep

Model ready: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/weights/best.pt
Ultralytics 8.4.48 🚀 Python-3.10.12 torch-2.11.0+cu130 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)

YOLO11m summary (fused): 126 layers, 20,033,116 parameters, 0 gradients, 67.7 GFLOPs

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3708.8±1761.9 MB/s, size: 161.3 KB)

val: Scanning /tmp/yolo_follicle_dataset_enhanced/labels/val.cache... 330 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 330/330 72.8Mit/s 0.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 5% ╸─────────── 1/21 1.7s/it 0.5s<34.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 10% ━─────────── 2/21 1.4s/it 1.4s<25.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 14% ━╸────────── 3/21 1.2s/it 2.4s<22.0s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 19% ━━────────── 4/21 1.0s/it 3.2s<17.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 24% ━━╸───────── 5/21 2.7it/s 3.3s<5.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 29% ━━━───────── 6/21 3.9it/s 3.5s<3.8s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 33% ━━━━──────── 7/21 4.5it/s 3.7s<3.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 38% ━━━━╸─────── 8/21 5.2it/s 3.8s<2.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 43% ━━━━━─────── 9/21 5.6it/s 4.0s<2.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 48% ━━━━━╸────── 10/21 5.7it/s 4.1s<1.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 52% ━━━━━━────── 11/21 6.0it/s 4.3s<1.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 57% ━━━━━━╸───── 12/21 6.3it/s 4.4s<1.4s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 62% ━━━━━━━───── 13/21 6.4it/s 4.6s<1.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 67% ━━━━━━━━──── 14/21 6.6it/s 4.7s<1.1s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 71% ━━━━━━━━╸─── 15/21 6.6it/s 4.9s<0.9s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 76% ━━━━━━━━━─── 16/21 6.7it/s 5.0s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 81% ━━━━━━━━━╸── 17/21 6.1it/s 5.2s<0.7s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 86% ━━━━━━━━━━── 18/21 6.3it/s 5.4s<0.5s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 90% ━━━━━━━━━━╸─ 19/21 5.8it/s 5.6s<0.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 95% ━━━━━━━━━━━─ 20/21 6.1it/s 5.7s<0.2s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 21/21 3.6it/s 5.8s

                   all        330       4227       0.66      0.617      0.636      0.387

               premium        330       2884      0.797      0.808      0.847      0.539

                single        307        942      0.775      0.792      0.832      0.566

             undersize        161        248      0.591      0.605      0.567      0.299

              abnormal        103        153      0.478      0.261      0.297      0.147

Speed: 1.7ms preprocess, 5.6ms inference, 0.0ms loss, 3.9ms postprocess per image

Results saved to /home/ubuntu/hair-follicle-density-estimation-209b/MS4/runs/detect/val-2

,experiment,run_name,imgsz,conf_for_mAP,nms_iou,max_det,precision,recall,mAP50,mAP50_95
0,enhanced_balanced,yolo_sweep_winner_enhanced_50ep,1024,0.001,0.7,1000,0.660331,0.616525,0.635586,0.387466

Saved metrics to: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/yolo_sweep_winner_enhanced_50ep/enhanced_balanced_validation_summary.csv

## Compare built-in YOLO validation metrics

In [16]:
# Compare baseline and enhanced experiments
validation_comparison_df = pd.concat(
    [baseline_summary_df, enhanced_summary_df],
    ignore_index=True,
)
display(validation_comparison_df)

comparison_path = os.path.join(common_cfg.drive_dir, 'baseline_vs_enhanced_validation_comparison.csv')
os.makedirs(common_cfg.drive_dir, exist_ok=True)
validation_comparison_df.to_csv(comparison_path, index=False)
print('Saved comparison to:', comparison_path)

,experiment,run_name,imgsz,conf_for_mAP,nms_iou,max_det,precision,recall,mAP50,mAP50_95
0,baseline,yolo_sweep_winner_baseline_50ep,1024,0.001,0.7,1000,0.667715,0.627749,0.653825,0.396445
1,enhanced_balanced,yolo_sweep_winner_enhanced_50ep,1024,0.001,0.7,1000,0.660331,0.616525,0.635586,0.387466

Saved comparison to: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/baseline_vs_enhanced_validation_comparison.csv

## Hungarian matching evaluation

This gives as task specific performance of the model. mAP measure the genral peformance of the detection piple end to end. We care about performnace specfic to the follicel detection.

We do post prediction processing using Hungarrian matching to get match one-to-one between prediction and ground truth. Then evalute confusion metrix on the matched predition and ground truth.

In [17]:
def load_gt_from_yolo_label(image_path: str, label_path: str):
    image = Image.open(image_path).convert("RGB")
    W, H = image.size
    boxes = []
    labels = []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue
                labels.append(int(float(parts[0])))
                boxes.append(yolo_to_xyxy(list(map(float, parts[1:])), W, H))
    return np.array(boxes, dtype=np.float32), np.array(labels, dtype=np.int64)


def predict_yolo_xyxy(model, image_path: str, conf=0.001, imgsz=1024, nms_iou=0.70, max_det=1000):
    result = model.predict(
        image_path,
        conf=conf,
        imgsz=imgsz,
        iou=nms_iou,
        max_det=max_det,
        verbose=False,
    )[0]
    if result.boxes is None or len(result.boxes) == 0:
        return (
            np.zeros((0, 4), dtype=np.float32),
            np.zeros((0,), dtype=np.int64),
            np.zeros((0,), dtype=np.float32),
        )
    boxes = result.boxes.xyxy.cpu().numpy().astype(np.float32)
    labels = result.boxes.cls.cpu().numpy().astype(np.int64)
    scores = result.boxes.conf.cpu().numpy().astype(np.float32)
    return boxes, labels, scores


def hungarian_match(pred_boxes, gt_boxes, iou_threshold=0.5):
    """Return matched prediction indices and GT indices using max-IoU Hungarian assignment."""
    if len(pred_boxes) == 0 or len(gt_boxes) == 0:
        return []
    pb = torch.tensor(pred_boxes, dtype=torch.float32)
    gb = torch.tensor(gt_boxes, dtype=torch.float32)
    ious = box_iou(pb, gb).numpy()
    pred_idx, gt_idx = linear_sum_assignment(-ious)
    matches = []
    for p, g in zip(pred_idx, gt_idx):
        if ious[p, g] >= iou_threshold:
            matches.append((p, g, float(ious[p, g])))
    return matches


def evaluate_yolo_hungarian(
    model,
    cfg: Config,
    stems: List[str],
    id2label: Dict[int, str],
    experiment_name: str,
    pred_conf=0.25,
    nms_iou=0.70,
    match_iou_threshold=0.50,
):
    image_dir = os.path.join(cfg.yolo_root, "images", "val")
    label_dir = os.path.join(cfg.yolo_root, "labels", "val")

    total_predictions = 0
    total_gt = 0
    total_matches = 0
    correct_matches = 0
    sum_matched_iou = 0.0
    y_true, y_pred = [], []

    for stem in tqdm(stems, desc=f"Hungarian eval: {experiment_name}"):
        image_path = find_image_path(image_dir, stem)
        label_path = os.path.join(label_dir, stem + ".txt")
        if image_path is None:
            continue

        gt_boxes, gt_labels = load_gt_from_yolo_label(image_path, label_path)
        pred_boxes, pred_labels, pred_scores = predict_yolo_xyxy(
            model,
            image_path,
            conf=pred_conf,
            imgsz=cfg.image_size,
            nms_iou=nms_iou,
            max_det=cfg.max_det,
        )

        total_predictions += len(pred_boxes)
        total_gt += len(gt_boxes)

        matches = hungarian_match(pred_boxes, gt_boxes, iou_threshold=match_iou_threshold)
        total_matches += len(matches)

        for p, g, iou in matches:
            sum_matched_iou += iou
            gt_label = int(gt_labels[g])
            pred_label = int(pred_labels[p])
            y_true.append(gt_label)
            y_pred.append(pred_label)
            if pred_label == gt_label:
                correct_matches += 1

    label_ids = sorted(id2label.keys())
    label_names = [id2label[i] for i in label_ids]
    cm = confusion_matrix(y_true, y_pred, labels=label_ids)
    cm_df = pd.DataFrame(cm, index=[f"true_{n}" for n in label_names], columns=[f"pred_{n}" for n in label_names])

    unmatched_predictions = total_predictions - total_matches
    unmatched_gt = total_gt - total_matches
    wrong_class_matches = total_matches - correct_matches

    tp = correct_matches
    fp = unmatched_predictions + wrong_class_matches
    fn = unmatched_gt + wrong_class_matches

    class_aware_precision = tp / max(tp + fp, 1)
    class_aware_recall = tp / max(tp + fn, 1)
    class_aware_f1 = 2 * class_aware_precision * class_aware_recall / max(class_aware_precision + class_aware_recall, 1e-8)

    localization_precision = total_matches / max(total_predictions, 1)
    localization_recall = total_matches / max(total_gt, 1)
    localization_f1 = 2 * localization_precision * localization_recall / max(localization_precision + localization_recall, 1e-8)

    metrics = {
        "experiment": experiment_name,
        "pred_conf": pred_conf,
        "nms_iou": nms_iou,
        "match_iou_threshold": match_iou_threshold,
        "total_predictions": total_predictions,
        "total_gt": total_gt,
        "total_matches": total_matches,
        "correct_matches": correct_matches,
        "wrong_class_matches": wrong_class_matches,
        "unmatched_predictions": unmatched_predictions,
        "unmatched_gt": unmatched_gt,
        "mean_iou_matched": sum_matched_iou / max(total_matches, 1),
        "matched_accuracy": accuracy_score(y_true, y_pred) if y_true else 0.0,
        "matched_f1_macro": f1_score(y_true, y_pred, labels=label_ids, average="macro", zero_division=0) if y_true else 0.0,
        "matched_f1_micro": f1_score(y_true, y_pred, labels=label_ids, average="micro", zero_division=0) if y_true else 0.0,
        "class_aware_precision": class_aware_precision,
        "class_aware_recall": class_aware_recall,
        "class_aware_f1": class_aware_f1,
        "localization_precision": localization_precision,
        "localization_recall": localization_recall,
        "localization_f1": localization_f1,
        "tp": tp,
        "fp": fp,
        "fn": fn,
    }

    print(f"===== YOLO Hungarian Evaluation: {experiment_name} =====")
    print(json.dumps(metrics, indent=2))
    display(cm_df)
    return metrics, cm_df

## Hungarian evaluation for both models and compare

In [18]:
baseline_hungarian_metrics, baseline_cm_df = evaluate_yolo_hungarian(
    baseline_model,
    baseline_cfg,
    val_files,
    id2label,
    experiment_name='baseline',
    pred_conf=0.25,
    nms_iou=baseline_cfg.val_iou_threshold,
    match_iou_threshold=0.50,
)

enhanced_hungarian_metrics, enhanced_cm_df = evaluate_yolo_hungarian(
    enhanced_model,
    enhanced_cfg,
    val_files,
    id2label,
    experiment_name='enhanced_balanced',
    pred_conf=0.25,
    nms_iou=enhanced_cfg.val_iou_threshold,
    match_iou_threshold=0.50,
)

hungarian_comparison_df = pd.DataFrame([baseline_hungarian_metrics, enhanced_hungarian_metrics])
display(hungarian_comparison_df)

hungarian_comparison_path = os.path.join(common_cfg.drive_dir, 'baseline_vs_enhanced_hungarian_comparison.csv')
hungarian_comparison_df.to_csv(hungarian_comparison_path, index=False)
print('Saved Hungarian comparison to:', hungarian_comparison_path)

Hungarian eval: baseline:   0%|          | 0/330 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline =====
{
  "experiment": "baseline",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 4597,
  "total_gt": 4227,
  "total_matches": 3523,
  "correct_matches": 3223,
  "wrong_class_matches": 300,
  "unmatched_predictions": 1074,
  "unmatched_gt": 704,
  "mean_iou_matched": 0.8187778716462261,
  "matched_accuracy": 0.9148453022991768,
  "matched_f1_macro": 0.849339085564311,
  "matched_f1_micro": 0.9148453022991768,
  "class_aware_precision": 0.7011094191864259,
  "class_aware_recall": 0.7624792997397681,
  "class_aware_f1": 0.7305077062556663,
  "localization_precision": 0.7663693713291277,
  "localization_recall": 0.8334516205346582,
  "localization_f1": 0.7985040797824116,
  "tp": 3223,
  "fp": 1374,
  "fn": 1004
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium            2246          131              29              3
true_single               79          755              14              1
true_undersize             9            4             163             10
true_abnormal              4            5              11             59

Hungarian eval: enhanced_balanced:   0%|          | 0/330 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced_balanced =====
{
  "experiment": "enhanced_balanced",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 4814,
  "total_gt": 4227,
  "total_matches": 3540,
  "correct_matches": 3267,
  "wrong_class_matches": 273,
  "unmatched_predictions": 1274,
  "unmatched_gt": 687,
  "mean_iou_matched": 0.8180572212247526,
  "matched_accuracy": 0.9228813559322034,
  "matched_f1_macro": 0.837005594184501,
  "matched_f1_micro": 0.9228813559322034,
  "class_aware_precision": 0.6786456169505609,
  "class_aware_recall": 0.772888573456352,
  "class_aware_f1": 0.7227076650812962,
  "localization_precision": 0.7353552139592854,
  "localization_recall": 0.837473385379702,
  "localization_f1": 0.7830992146886406,
  "tp": 3267,
  "fp": 1547,
  "fn": 960
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium            2345           88              19              1
true_single              102          730              10              0
true_undersize            15            4             150              6
true_abnormal              8            6              14             42

,experiment,pred_conf,nms_iou,match_iou_threshold,total_predictions,total_gt,total_matches,correct_matches,wrong_class_matches,unmatched_predictions,...,matched_f1_micro,class_aware_precision,class_aware_recall,class_aware_f1,localization_precision,localization_recall,localization_f1,tp,fp,fn
0,baseline,0.25,0.7,0.5,4597,4227,3523,3223,300,1074,...,0.914845,0.701109,0.762479,0.730508,0.766369,0.833452,0.798504,3223,1374,1004
1,enhanced_balanced,0.25,0.7,0.5,4814,4227,3540,3267,273,1274,...,0.922881,0.678646,0.772889,0.722708,0.735355,0.837473,0.783099,3267,1547,960

Saved Hungarian comparison to: /home/ubuntu/hair-follicle-density-estimation-209b/MS4/checkpoints/yolo_sweep_winner_runs/baseline_vs_enhanced_hungarian_comparison.csv

## Per-epoch Hungarian evaluation across all saved checkpoints

We saved every epoch's checkpoint (`save_period=1`). Now we run Hungarian matching evaluation on each one and tabulate mean IoU, class-aware precision/recall/F1, and matched accuracy per epoch. This lets us pick the best epoch on any criterion (e.g., max mean IoU, max F1, etc.) rather than just Ultralytics' default fitness.

In [19]:
import glob

def per_epoch_hungarian_eval(run_dir, cfg, experiment_label, eval_stems_subset):
    """Run Hungarian eval on every saved epoch checkpoint of a single experiment."""
    weights_dir = os.path.join(run_dir, 'weights')
    epoch_files = sorted(
        glob.glob(os.path.join(weights_dir, 'epoch*.pt')),
        key=lambda p: int(os.path.basename(p).replace('epoch', '').replace('.pt', ''))
    )
    best_pt = os.path.join(weights_dir, 'best.pt')
    last_pt = os.path.join(weights_dir, 'last.pt')
    all_checkpoints = epoch_files + ([best_pt] if os.path.exists(best_pt) else []) + ([last_pt] if os.path.exists(last_pt) else [])
    print(f'\n=== {experiment_label}: {len(all_checkpoints)} checkpoints found ===\n')
    
    rows = []
    for ckpt_path in all_checkpoints:
        epoch_label = os.path.basename(ckpt_path).replace('.pt', '')
        print(f'-- evaluating {experiment_label}/{epoch_label}')
        m = YOLO(ckpt_path)
        metrics, _ = evaluate_yolo_hungarian(
            m, cfg, eval_stems_subset, id2label,
            experiment_name=f'{experiment_label}/{epoch_label}',
            pred_conf=0.25, nms_iou=0.70, match_iou_threshold=0.50,
        )
        row = {'experiment': experiment_label, 'checkpoint': epoch_label}
        row.update(metrics)
        rows.append(row)
    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(run_dir, 'per_epoch_hungarian.csv'), index=False)
    return df

# Use 50 val images for speed (full eval would 6x this time)
eval_subset = val_files[:50]
print(f'Per-epoch eval will use {len(eval_subset)} val images per checkpoint\n')

baseline_per_epoch_df = per_epoch_hungarian_eval(baseline_run_dir, baseline_cfg, 'baseline', eval_subset)
enhanced_per_epoch_df = per_epoch_hungarian_eval(enhanced_run_dir, enhanced_cfg, 'enhanced', eval_subset)

combined_per_epoch_df = pd.concat([baseline_per_epoch_df, enhanced_per_epoch_df], ignore_index=True)
combined_per_epoch_df.to_csv(os.path.join(common_cfg.drive_dir, 'per_epoch_hungarian_combined.csv'), index=False)
display(combined_per_epoch_df)

Per-epoch eval will use 50 val images per checkpoint


=== baseline: 33 checkpoints found ===

-- evaluating baseline/epoch0

Hungarian eval: baseline/epoch0:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch0 =====
{
  "experiment": "baseline/epoch0",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 762,
  "total_gt": 760,
  "total_matches": 502,
  "correct_matches": 390,
  "wrong_class_matches": 112,
  "unmatched_predictions": 260,
  "unmatched_gt": 258,
  "mean_iou_matched": 0.7689858930281909,
  "matched_accuracy": 0.7768924302788844,
  "matched_f1_macro": 0.6181490684742955,
  "matched_f1_micro": 0.7768924302788844,
  "class_aware_precision": 0.5118110236220472,
  "class_aware_recall": 0.5131578947368421,
  "class_aware_f1": 0.5124835742444154,
  "localization_precision": 0.6587926509186351,
  "localization_recall": 0.6605263157894737,
  "localization_f1": 0.6596583442838371,
  "tp": 390,
  "fp": 372,
  "fn": 370
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             296           61               4              1
true_single               28           73               3              0
true_undersize             0            0              16              4
true_abnormal              1            1               9              5

-- evaluating baseline/epoch1

Hungarian eval: baseline/epoch1:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch1 =====
{
  "experiment": "baseline/epoch1",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 910,
  "total_gt": 760,
  "total_matches": 556,
  "correct_matches": 470,
  "wrong_class_matches": 86,
  "unmatched_predictions": 354,
  "unmatched_gt": 204,
  "mean_iou_matched": 0.7678872985805539,
  "matched_accuracy": 0.8453237410071942,
  "matched_f1_macro": 0.6380844041652536,
  "matched_f1_micro": 0.8453237410071942,
  "class_aware_precision": 0.5164835164835165,
  "class_aware_recall": 0.618421052631579,
  "class_aware_f1": 0.562874251497006,
  "localization_precision": 0.610989010989011,
  "localization_recall": 0.7315789473684211,
  "localization_f1": 0.665868263473054,
  "tp": 470,
  "fp": 440,
  "fn": 290
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             381           24               2              0
true_single               43           75               0              0
true_undersize             4            2              12              0
true_abnormal              5            4               2              2

-- evaluating baseline/epoch2

Hungarian eval: baseline/epoch2:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch2 =====
{
  "experiment": "baseline/epoch2",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 676,
  "total_gt": 760,
  "total_matches": 507,
  "correct_matches": 422,
  "wrong_class_matches": 85,
  "unmatched_predictions": 169,
  "unmatched_gt": 253,
  "mean_iou_matched": 0.7726519595706721,
  "matched_accuracy": 0.8323471400394478,
  "matched_f1_macro": 0.5823114549387405,
  "matched_f1_micro": 0.8323471400394478,
  "class_aware_precision": 0.6242603550295858,
  "class_aware_recall": 0.5552631578947368,
  "class_aware_f1": 0.5877437325905291,
  "localization_precision": 0.75,
  "localization_recall": 0.6671052631578948,
  "localization_f1": 0.7061281337047353,
  "tp": 422,
  "fp": 254,
  "fn": 338
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             334           33               6              0
true_single               29           72               2              0
true_undersize             2            1              15              0
true_abnormal              1            2               9              1

-- evaluating baseline/epoch3

Hungarian eval: baseline/epoch3:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch3 =====
{
  "experiment": "baseline/epoch3",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 727,
  "total_gt": 760,
  "total_matches": 531,
  "correct_matches": 465,
  "wrong_class_matches": 66,
  "unmatched_predictions": 196,
  "unmatched_gt": 229,
  "mean_iou_matched": 0.7698501475337759,
  "matched_accuracy": 0.8757062146892656,
  "matched_f1_macro": 0.7512568551047336,
  "matched_f1_micro": 0.8757062146892656,
  "class_aware_precision": 0.6396148555708391,
  "class_aware_recall": 0.6118421052631579,
  "class_aware_f1": 0.6254203093476799,
  "localization_precision": 0.7303988995873453,
  "localization_recall": 0.6986842105263158,
  "localization_f1": 0.7141896435776732,
  "tp": 465,
  "fp": 262,
  "fn": 295
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             356           23               4              1
true_single               22           83               1              0
true_undersize             3            1              16              3
true_abnormal              3            2               3             10

-- evaluating baseline/epoch4

Hungarian eval: baseline/epoch4:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch4 =====
{
  "experiment": "baseline/epoch4",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 794,
  "total_gt": 760,
  "total_matches": 559,
  "correct_matches": 488,
  "wrong_class_matches": 71,
  "unmatched_predictions": 235,
  "unmatched_gt": 201,
  "mean_iou_matched": 0.7641020241278442,
  "matched_accuracy": 0.8729874776386404,
  "matched_f1_macro": 0.6887608536425287,
  "matched_f1_micro": 0.8729874776386404,
  "class_aware_precision": 0.6146095717884131,
  "class_aware_recall": 0.6421052631578947,
  "class_aware_f1": 0.6280566280566281,
  "localization_precision": 0.7040302267002518,
  "localization_recall": 0.7355263157894737,
  "localization_f1": 0.7194337194337194,
  "tp": 488,
  "fp": 306,
  "fn": 272
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             368           25               3              0
true_single               23           91               1              0
true_undersize             3            2              26              0
true_abnormal              4            2               8              3

-- evaluating baseline/epoch5

Hungarian eval: baseline/epoch5:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch5 =====
{
  "experiment": "baseline/epoch5",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 783,
  "total_gt": 760,
  "total_matches": 559,
  "correct_matches": 485,
  "wrong_class_matches": 74,
  "unmatched_predictions": 224,
  "unmatched_gt": 201,
  "mean_iou_matched": 0.7754224981306277,
  "matched_accuracy": 0.8676207513416816,
  "matched_f1_macro": 0.7084055779507613,
  "matched_f1_micro": 0.8676207513416816,
  "class_aware_precision": 0.6194125159642401,
  "class_aware_recall": 0.6381578947368421,
  "class_aware_f1": 0.6286454957874271,
  "localization_precision": 0.7139208173690932,
  "localization_recall": 0.7355263157894737,
  "localization_f1": 0.7245625405055087,
  "tp": 485,
  "fp": 298,
  "fn": 275
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             396           11               2              1
true_single               40           67               2              0
true_undersize             4            3              13              2
true_abnormal              4            1               4              9

-- evaluating baseline/epoch6

Hungarian eval: baseline/epoch6:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch6 =====
{
  "experiment": "baseline/epoch6",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 789,
  "total_gt": 760,
  "total_matches": 539,
  "correct_matches": 480,
  "wrong_class_matches": 59,
  "unmatched_predictions": 250,
  "unmatched_gt": 221,
  "mean_iou_matched": 0.7778853363805003,
  "matched_accuracy": 0.8905380333951762,
  "matched_f1_macro": 0.7845753397612172,
  "matched_f1_micro": 0.8905380333951762,
  "class_aware_precision": 0.6083650190114068,
  "class_aware_recall": 0.631578947368421,
  "class_aware_f1": 0.6197546804389928,
  "localization_precision": 0.6831432192648923,
  "localization_recall": 0.7092105263157895,
  "localization_f1": 0.6959328599096192,
  "tp": 480,
  "fp": 309,
  "fn": 280
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             348           33               2              0
true_single                9          104               1              0
true_undersize             1            1              18              2
true_abnormal              1            5               4             10

-- evaluating baseline/epoch7

Hungarian eval: baseline/epoch7:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch7 =====
{
  "experiment": "baseline/epoch7",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 655,
  "total_gt": 760,
  "total_matches": 530,
  "correct_matches": 466,
  "wrong_class_matches": 64,
  "unmatched_predictions": 125,
  "unmatched_gt": 230,
  "mean_iou_matched": 0.7754616781225744,
  "matched_accuracy": 0.879245283018868,
  "matched_f1_macro": 0.7841745609185833,
  "matched_f1_micro": 0.879245283018868,
  "class_aware_precision": 0.7114503816793893,
  "class_aware_recall": 0.6131578947368421,
  "class_aware_f1": 0.6586572438162545,
  "localization_precision": 0.8091603053435115,
  "localization_recall": 0.6973684210526315,
  "localization_f1": 0.7491166077738515,
  "tp": 466,
  "fp": 189,
  "fn": 294
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             343           30               6              1
true_single               16           94               2              0
true_undersize             1            0              18              0
true_abnormal              2            0               6             11

-- evaluating baseline/epoch8

Hungarian eval: baseline/epoch8:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch8 =====
{
  "experiment": "baseline/epoch8",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 753,
  "total_gt": 760,
  "total_matches": 539,
  "correct_matches": 481,
  "wrong_class_matches": 58,
  "unmatched_predictions": 214,
  "unmatched_gt": 221,
  "mean_iou_matched": 0.7740403231309385,
  "matched_accuracy": 0.8923933209647495,
  "matched_f1_macro": 0.8301556646696359,
  "matched_f1_micro": 0.8923933209647495,
  "class_aware_precision": 0.6387782204515272,
  "class_aware_recall": 0.6328947368421053,
  "class_aware_f1": 0.635822868473232,
  "localization_precision": 0.7158034528552457,
  "localization_recall": 0.7092105263157895,
  "localization_f1": 0.7124917382683411,
  "tp": 481,
  "fp": 272,
  "fn": 279
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             342           32               2              0
true_single               12          107               0              0
true_undersize             3            1              19              1
true_abnormal              2            3               2             13

-- evaluating baseline/epoch9

Hungarian eval: baseline/epoch9:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch9 =====
{
  "experiment": "baseline/epoch9",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 807,
  "total_gt": 760,
  "total_matches": 573,
  "correct_matches": 514,
  "wrong_class_matches": 59,
  "unmatched_predictions": 234,
  "unmatched_gt": 187,
  "mean_iou_matched": 0.7769594241395255,
  "matched_accuracy": 0.8970331588132635,
  "matched_f1_macro": 0.7783673542863891,
  "matched_f1_micro": 0.8970331588132635,
  "class_aware_precision": 0.6369268897149938,
  "class_aware_recall": 0.6763157894736842,
  "class_aware_f1": 0.6560306317804722,
  "localization_precision": 0.7100371747211895,
  "localization_recall": 0.7539473684210526,
  "localization_f1": 0.7313337587747286,
  "tp": 514,
  "fp": 293,
  "fn": 246
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             390           17               1              1
true_single               21           97               1              0
true_undersize             6            3              14              3
true_abnormal              1            3               2             13

-- evaluating baseline/epoch10

Hungarian eval: baseline/epoch10:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch10 =====
{
  "experiment": "baseline/epoch10",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 820,
  "total_gt": 760,
  "total_matches": 562,
  "correct_matches": 506,
  "wrong_class_matches": 56,
  "unmatched_predictions": 258,
  "unmatched_gt": 198,
  "mean_iou_matched": 0.7727663848960102,
  "matched_accuracy": 0.900355871886121,
  "matched_f1_macro": 0.8016340220978619,
  "matched_f1_micro": 0.900355871886121,
  "class_aware_precision": 0.6170731707317073,
  "class_aware_recall": 0.6657894736842105,
  "class_aware_f1": 0.640506329113924,
  "localization_precision": 0.6853658536585366,
  "localization_recall": 0.7394736842105263,
  "localization_f1": 0.711392405063291,
  "tp": 506,
  "fp": 314,
  "fn": 254
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             380           18               0              0
true_single               23           98               1              0
true_undersize             4            0              18              1
true_abnormal              3            2               4             10

-- evaluating baseline/epoch11

Hungarian eval: baseline/epoch11:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch11 =====
{
  "experiment": "baseline/epoch11",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 792,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 508,
  "wrong_class_matches": 68,
  "unmatched_predictions": 216,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.7772011474395791,
  "matched_accuracy": 0.8819444444444444,
  "matched_f1_macro": 0.7910538441708901,
  "matched_f1_micro": 0.8819444444444444,
  "class_aware_precision": 0.6414141414141414,
  "class_aware_recall": 0.6684210526315789,
  "class_aware_f1": 0.654639175257732,
  "localization_precision": 0.7272727272727273,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7422680412371135,
  "tp": 508,
  "fp": 284,
  "fn": 252
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             391           17               4              1
true_single               30           85               1              0
true_undersize             8            1              20              2
true_abnormal              1            1               2             12

-- evaluating baseline/epoch12

Hungarian eval: baseline/epoch12:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch12 =====
{
  "experiment": "baseline/epoch12",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 769,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 509,
  "wrong_class_matches": 68,
  "unmatched_predictions": 192,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7727666064399574,
  "matched_accuracy": 0.8821490467937608,
  "matched_f1_macro": 0.779204876907155,
  "matched_f1_micro": 0.8821490467937608,
  "class_aware_precision": 0.6618985695708712,
  "class_aware_recall": 0.6697368421052632,
  "class_aware_f1": 0.6657946370176586,
  "localization_precision": 0.7503250975292588,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.7547416612164813,
  "tp": 509,
  "fp": 260,
  "fn": 251
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             370           32               5              0
true_single               15          109               0              0
true_undersize             5            1              17              2
true_abnormal              1            2               5             13

-- evaluating baseline/epoch13

Hungarian eval: baseline/epoch13:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch13 =====
{
  "experiment": "baseline/epoch13",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 789,
  "total_gt": 760,
  "total_matches": 570,
  "correct_matches": 504,
  "wrong_class_matches": 66,
  "unmatched_predictions": 219,
  "unmatched_gt": 190,
  "mean_iou_matched": 0.7744139770666758,
  "matched_accuracy": 0.8842105263157894,
  "matched_f1_macro": 0.8096339823235558,
  "matched_f1_micro": 0.8842105263157894,
  "class_aware_precision": 0.6387832699619772,
  "class_aware_recall": 0.6631578947368421,
  "class_aware_f1": 0.6507424144609425,
  "localization_precision": 0.7224334600760456,
  "localization_recall": 0.75,
  "localization_f1": 0.7359586830213041,
  "tp": 504,
  "fp": 285,
  "fn": 256
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             392           16               3              0
true_single               35           79               0              0
true_undersize             4            1              18              2
true_abnormal              2            1               2             15

-- evaluating baseline/epoch14

Hungarian eval: baseline/epoch14:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch14 =====
{
  "experiment": "baseline/epoch14",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 691,
  "total_gt": 760,
  "total_matches": 525,
  "correct_matches": 463,
  "wrong_class_matches": 62,
  "unmatched_predictions": 166,
  "unmatched_gt": 235,
  "mean_iou_matched": 0.7859299770991007,
  "matched_accuracy": 0.8819047619047619,
  "matched_f1_macro": 0.7711204399273334,
  "matched_f1_micro": 0.8819047619047619,
  "class_aware_precision": 0.6700434153400868,
  "class_aware_recall": 0.6092105263157894,
  "class_aware_f1": 0.6381805651274983,
  "localization_precision": 0.7597684515195369,
  "localization_recall": 0.6907894736842105,
  "localization_f1": 0.7236388697450035,
  "tp": 463,
  "fp": 228,
  "fn": 297
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             340           26               7              1
true_single               14           91               2              1
true_undersize             2            0              21              2
true_abnormal              0            0               7             11

-- evaluating baseline/epoch15

Hungarian eval: baseline/epoch15:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch15 =====
{
  "experiment": "baseline/epoch15",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 697,
  "total_gt": 760,
  "total_matches": 553,
  "correct_matches": 503,
  "wrong_class_matches": 50,
  "unmatched_predictions": 144,
  "unmatched_gt": 207,
  "mean_iou_matched": 0.7819935183628558,
  "matched_accuracy": 0.9095840867992767,
  "matched_f1_macro": 0.8478711534426971,
  "matched_f1_micro": 0.9095840867992767,
  "class_aware_precision": 0.7216642754662841,
  "class_aware_recall": 0.6618421052631579,
  "class_aware_f1": 0.6904598490048044,
  "localization_precision": 0.793400286944046,
  "localization_recall": 0.7276315789473684,
  "localization_f1": 0.7590940288263556,
  "tp": 503,
  "fp": 194,
  "fn": 257
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           17               3              0
true_single               21           91               1              0
true_undersize             3            0              19              2
true_abnormal              1            0               2             14

-- evaluating baseline/epoch16

Hungarian eval: baseline/epoch16:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch16 =====
{
  "experiment": "baseline/epoch16",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 763,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 504,
  "wrong_class_matches": 72,
  "unmatched_predictions": 187,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.7802647050056193,
  "matched_accuracy": 0.875,
  "matched_f1_macro": 0.8037304162740915,
  "matched_f1_micro": 0.875,
  "class_aware_precision": 0.6605504587155964,
  "class_aware_recall": 0.6631578947368421,
  "class_aware_f1": 0.6618516086671045,
  "localization_precision": 0.7549148099606815,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7564018384766906,
  "tp": 504,
  "fp": 259,
  "fn": 256
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             370           39               0              1
true_single               17          101               2              0
true_undersize             4            2              18              2
true_abnormal              1            1               3             15

-- evaluating baseline/epoch17

Hungarian eval: baseline/epoch17:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch17 =====
{
  "experiment": "baseline/epoch17",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 716,
  "total_gt": 760,
  "total_matches": 541,
  "correct_matches": 485,
  "wrong_class_matches": 56,
  "unmatched_predictions": 175,
  "unmatched_gt": 219,
  "mean_iou_matched": 0.7739870790633168,
  "matched_accuracy": 0.8964879852125693,
  "matched_f1_macro": 0.8194986328773028,
  "matched_f1_micro": 0.8964879852125693,
  "class_aware_precision": 0.6773743016759777,
  "class_aware_recall": 0.6381578947368421,
  "class_aware_f1": 0.6571815718157181,
  "localization_precision": 0.755586592178771,
  "localization_recall": 0.7118421052631579,
  "localization_f1": 0.7330623306233063,
  "tp": 485,
  "fp": 231,
  "fn": 275
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             350           30               3              0
true_single               10          101               2              0
true_undersize             2            1              20              3
true_abnormal              1            1               3             14

-- evaluating baseline/epoch18

Hungarian eval: baseline/epoch18:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch18 =====
{
  "experiment": "baseline/epoch18",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 730,
  "total_gt": 760,
  "total_matches": 561,
  "correct_matches": 506,
  "wrong_class_matches": 55,
  "unmatched_predictions": 169,
  "unmatched_gt": 199,
  "mean_iou_matched": 0.7807283294179648,
  "matched_accuracy": 0.9019607843137255,
  "matched_f1_macro": 0.8404284535558176,
  "matched_f1_micro": 0.9019607843137255,
  "class_aware_precision": 0.6931506849315069,
  "class_aware_recall": 0.6657894736842105,
  "class_aware_f1": 0.6791946308724831,
  "localization_precision": 0.7684931506849315,
  "localization_recall": 0.7381578947368421,
  "localization_f1": 0.753020134228188,
  "tp": 506,
  "fp": 224,
  "fn": 254
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           16               2              0
true_single               24           92               2              0
true_undersize             5            1              20              2
true_abnormal              2            0               1             15

-- evaluating baseline/epoch19

Hungarian eval: baseline/epoch19:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch19 =====
{
  "experiment": "baseline/epoch19",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 712,
  "total_gt": 760,
  "total_matches": 551,
  "correct_matches": 479,
  "wrong_class_matches": 72,
  "unmatched_predictions": 161,
  "unmatched_gt": 209,
  "mean_iou_matched": 0.7856271490860331,
  "matched_accuracy": 0.8693284936479129,
  "matched_f1_macro": 0.8132416389777158,
  "matched_f1_micro": 0.8693284936479129,
  "class_aware_precision": 0.672752808988764,
  "class_aware_recall": 0.6302631578947369,
  "class_aware_f1": 0.6508152173913043,
  "localization_precision": 0.773876404494382,
  "localization_recall": 0.725,
  "localization_f1": 0.748641304347826,
  "tp": 479,
  "fp": 233,
  "fn": 281
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             336           43               4              1
true_single               11          105               2              0
true_undersize             4            1              21              3
true_abnormal              1            0               2             17

-- evaluating baseline/epoch20

Hungarian eval: baseline/epoch20:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch20 =====
{
  "experiment": "baseline/epoch20",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 737,
  "total_gt": 760,
  "total_matches": 555,
  "correct_matches": 506,
  "wrong_class_matches": 49,
  "unmatched_predictions": 182,
  "unmatched_gt": 205,
  "mean_iou_matched": 0.7854179775392687,
  "matched_accuracy": 0.9117117117117117,
  "matched_f1_macro": 0.8394866385372715,
  "matched_f1_micro": 0.9117117117117117,
  "class_aware_precision": 0.6865671641791045,
  "class_aware_recall": 0.6657894736842105,
  "class_aware_f1": 0.6760187040748162,
  "localization_precision": 0.7530529172320217,
  "localization_recall": 0.7302631578947368,
  "localization_f1": 0.7414829659318638,
  "tp": 506,
  "fp": 231,
  "fn": 254
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             374           16               5              0
true_single               18           95               0              0
true_undersize             3            0              23              1
true_abnormal              0            1               5             14

-- evaluating baseline/epoch21

Hungarian eval: baseline/epoch21:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch21 =====
{
  "experiment": "baseline/epoch21",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 703,
  "total_gt": 760,
  "total_matches": 548,
  "correct_matches": 495,
  "wrong_class_matches": 53,
  "unmatched_predictions": 155,
  "unmatched_gt": 212,
  "mean_iou_matched": 0.7856103251450253,
  "matched_accuracy": 0.9032846715328468,
  "matched_f1_macro": 0.8212273181197751,
  "matched_f1_micro": 0.9032846715328468,
  "class_aware_precision": 0.7041251778093883,
  "class_aware_recall": 0.6513157894736842,
  "class_aware_f1": 0.6766917293233082,
  "localization_precision": 0.7795163584637269,
  "localization_recall": 0.7210526315789474,
  "localization_f1": 0.7491455912508543,
  "tp": 495,
  "fp": 208,
  "fn": 265
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             363           22               4              0
true_single               15           99               2              0
true_undersize             3            0              16              4
true_abnormal              0            1               2             17

-- evaluating baseline/epoch22

Hungarian eval: baseline/epoch22:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch22 =====
{
  "experiment": "baseline/epoch22",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 804,
  "total_gt": 760,
  "total_matches": 584,
  "correct_matches": 531,
  "wrong_class_matches": 53,
  "unmatched_predictions": 220,
  "unmatched_gt": 176,
  "mean_iou_matched": 0.7801634976512766,
  "matched_accuracy": 0.9092465753424658,
  "matched_f1_macro": 0.8239204603064073,
  "matched_f1_micro": 0.9092465753424658,
  "class_aware_precision": 0.6604477611940298,
  "class_aware_recall": 0.6986842105263158,
  "class_aware_f1": 0.6790281329923273,
  "localization_precision": 0.7263681592039801,
  "localization_recall": 0.7684210526315789,
  "localization_f1": 0.7468030690537084,
  "tp": 531,
  "fp": 273,
  "fn": 229
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             398           17               1              0
true_single               20          100               1              1
true_undersize             6            0              15              4
true_abnormal              1            1               1             18

-- evaluating baseline/epoch23

Hungarian eval: baseline/epoch23:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch23 =====
{
  "experiment": "baseline/epoch23",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 709,
  "total_gt": 760,
  "total_matches": 553,
  "correct_matches": 501,
  "wrong_class_matches": 52,
  "unmatched_predictions": 156,
  "unmatched_gt": 207,
  "mean_iou_matched": 0.7798482758442704,
  "matched_accuracy": 0.9059674502712477,
  "matched_f1_macro": 0.843422808568339,
  "matched_f1_micro": 0.9059674502712477,
  "class_aware_precision": 0.7066290550070522,
  "class_aware_recall": 0.6592105263157895,
  "class_aware_f1": 0.6820966643975493,
  "localization_precision": 0.7799717912552891,
  "localization_recall": 0.7276315789473684,
  "localization_f1": 0.7528931245745406,
  "tp": 501,
  "fp": 208,
  "fn": 259
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             369           22               4              1
true_single               16           96               0              1
true_undersize             3            0              19              3
true_abnormal              0            1               1             17

-- evaluating baseline/epoch24

Hungarian eval: baseline/epoch24:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch24 =====
{
  "experiment": "baseline/epoch24",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 747,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 526,
  "wrong_class_matches": 51,
  "unmatched_predictions": 170,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7760763036109752,
  "matched_accuracy": 0.9116117850953206,
  "matched_f1_macro": 0.8458488127505048,
  "matched_f1_micro": 0.9116117850953206,
  "class_aware_precision": 0.7041499330655957,
  "class_aware_recall": 0.6921052631578948,
  "class_aware_f1": 0.6980756469807565,
  "localization_precision": 0.7724230254350736,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.7657597876575979,
  "tp": 526,
  "fp": 221,
  "fn": 234
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             381           22               4              1
true_single               11          100               2              1
true_undersize             2            1              27              3
true_abnormal              1            1               2             18

-- evaluating baseline/epoch25

Hungarian eval: baseline/epoch25:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch25 =====
{
  "experiment": "baseline/epoch25",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 778,
  "total_gt": 760,
  "total_matches": 566,
  "correct_matches": 513,
  "wrong_class_matches": 53,
  "unmatched_predictions": 212,
  "unmatched_gt": 194,
  "mean_iou_matched": 0.7819678943485758,
  "matched_accuracy": 0.9063604240282686,
  "matched_f1_macro": 0.8498043213246658,
  "matched_f1_micro": 0.9063604240282686,
  "class_aware_precision": 0.6593830334190232,
  "class_aware_recall": 0.675,
  "class_aware_f1": 0.6671001300390118,
  "localization_precision": 0.7275064267352185,
  "localization_recall": 0.7447368421052631,
  "localization_f1": 0.7360208062418726,
  "tp": 513,
  "fp": 265,
  "fn": 247
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             373           25               4              1
true_single               13          100               2              0
true_undersize             2            1              23              3
true_abnormal              0            1               1             17

-- evaluating baseline/epoch26

Hungarian eval: baseline/epoch26:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch26 =====
{
  "experiment": "baseline/epoch26",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 771,
  "total_gt": 760,
  "total_matches": 560,
  "correct_matches": 501,
  "wrong_class_matches": 59,
  "unmatched_predictions": 211,
  "unmatched_gt": 200,
  "mean_iou_matched": 0.7811241087104593,
  "matched_accuracy": 0.8946428571428572,
  "matched_f1_macro": 0.8252968578735843,
  "matched_f1_micro": 0.8946428571428572,
  "class_aware_precision": 0.6498054474708171,
  "class_aware_recall": 0.6592105263157895,
  "class_aware_f1": 0.6544741998693665,
  "localization_precision": 0.7263294422827496,
  "localization_recall": 0.7368421052631579,
  "localization_f1": 0.7315480078380143,
  "tp": 501,
  "fp": 270,
  "fn": 259
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             366           24               6              0
true_single               17           97               2              0
true_undersize             3            1              21              4
true_abnormal              0            0               2             17

-- evaluating baseline/epoch27

Hungarian eval: baseline/epoch27:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch27 =====
{
  "experiment": "baseline/epoch27",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 773,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 528,
  "wrong_class_matches": 49,
  "unmatched_predictions": 196,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7881704637041538,
  "matched_accuracy": 0.9150779896013865,
  "matched_f1_macro": 0.8269961133178925,
  "matched_f1_micro": 0.9150779896013865,
  "class_aware_precision": 0.6830530401034929,
  "class_aware_recall": 0.6947368421052632,
  "class_aware_f1": 0.6888454011741683,
  "localization_precision": 0.7464424320827943,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.7527723418134378,
  "tp": 528,
  "fp": 245,
  "fn": 232
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             400            9               2              0
true_single               22           92               1              0
true_undersize             5            2              20              4
true_abnormal              1            1               2             16

-- evaluating baseline/epoch28

Hungarian eval: baseline/epoch28:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch28 =====
{
  "experiment": "baseline/epoch28",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 740,
  "total_gt": 760,
  "total_matches": 570,
  "correct_matches": 510,
  "wrong_class_matches": 60,
  "unmatched_predictions": 170,
  "unmatched_gt": 190,
  "mean_iou_matched": 0.7820809257657905,
  "matched_accuracy": 0.8947368421052632,
  "matched_f1_macro": 0.8038559275596591,
  "matched_f1_micro": 0.8947368421052632,
  "class_aware_precision": 0.6891891891891891,
  "class_aware_recall": 0.6710526315789473,
  "class_aware_f1": 0.68,
  "localization_precision": 0.7702702702702703,
  "localization_recall": 0.75,
  "localization_f1": 0.7600000000000001,
  "tp": 510,
  "fp": 230,
  "fn": 250
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             382           20               7              0
true_single               18           93               1              0
true_undersize             5            1              20              3
true_abnormal              2            0               3             15

-- evaluating baseline/epoch29

Hungarian eval: baseline/epoch29:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch29 =====
{
  "experiment": "baseline/epoch29",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 768,
  "total_gt": 760,
  "total_matches": 571,
  "correct_matches": 519,
  "wrong_class_matches": 52,
  "unmatched_predictions": 197,
  "unmatched_gt": 189,
  "mean_iou_matched": 0.7851447203113402,
  "matched_accuracy": 0.9089316987740805,
  "matched_f1_macro": 0.8335192906357083,
  "matched_f1_micro": 0.9089316987740805,
  "class_aware_precision": 0.67578125,
  "class_aware_recall": 0.6828947368421052,
  "class_aware_f1": 0.6793193717277487,
  "localization_precision": 0.7434895833333334,
  "localization_recall": 0.7513157894736842,
  "localization_f1": 0.7473821989528795,
  "tp": 519,
  "fp": 249,
  "fn": 241
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             382           20               4              0
true_single               14          100               2              0
true_undersize             5            0              21              3
true_abnormal              1            1               2             16

-- evaluating baseline/epoch30

Hungarian eval: baseline/epoch30:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/epoch30 =====
{
  "experiment": "baseline/epoch30",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 778,
  "total_gt": 760,
  "total_matches": 587,
  "correct_matches": 530,
  "wrong_class_matches": 57,
  "unmatched_predictions": 191,
  "unmatched_gt": 173,
  "mean_iou_matched": 0.7800862154521975,
  "matched_accuracy": 0.9028960817717206,
  "matched_f1_macro": 0.8249809619041286,
  "matched_f1_micro": 0.9028960817717206,
  "class_aware_precision": 0.6812339331619537,
  "class_aware_recall": 0.6973684210526315,
  "class_aware_f1": 0.6892067620286086,
  "localization_precision": 0.7544987146529563,
  "localization_recall": 0.7723684210526316,
  "localization_f1": 0.7633289986996099,
  "tp": 530,
  "fp": 248,
  "fn": 230
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             398           18               4              0
true_single               20           94               2              0
true_undersize             4            2              22              3
true_abnormal              1            1               2             16

-- evaluating baseline/best

Hungarian eval: baseline/best:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/best =====
{
  "experiment": "baseline/best",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 747,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 526,
  "wrong_class_matches": 51,
  "unmatched_predictions": 170,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7760763036109752,
  "matched_accuracy": 0.9116117850953206,
  "matched_f1_macro": 0.8458488127505048,
  "matched_f1_micro": 0.9116117850953206,
  "class_aware_precision": 0.7041499330655957,
  "class_aware_recall": 0.6921052631578948,
  "class_aware_f1": 0.6980756469807565,
  "localization_precision": 0.7724230254350736,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.7657597876575979,
  "tp": 526,
  "fp": 221,
  "fn": 234
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             381           22               4              1
true_single               11          100               2              1
true_undersize             2            1              27              3
true_abnormal              1            1               2             18

-- evaluating baseline/last

Hungarian eval: baseline/last:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: baseline/last =====
{
  "experiment": "baseline/last",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 778,
  "total_gt": 760,
  "total_matches": 587,
  "correct_matches": 530,
  "wrong_class_matches": 57,
  "unmatched_predictions": 191,
  "unmatched_gt": 173,
  "mean_iou_matched": 0.7800862154521975,
  "matched_accuracy": 0.9028960817717206,
  "matched_f1_macro": 0.8249809619041286,
  "matched_f1_micro": 0.9028960817717206,
  "class_aware_precision": 0.6812339331619537,
  "class_aware_recall": 0.6973684210526315,
  "class_aware_f1": 0.6892067620286086,
  "localization_precision": 0.7544987146529563,
  "localization_recall": 0.7723684210526316,
  "localization_f1": 0.7633289986996099,
  "tp": 530,
  "fp": 248,
  "fn": 230
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             398           18               4              0
true_single               20           94               2              0
true_undersize             4            2              22              3
true_abnormal              1            1               2             16

=== enhanced: 48 checkpoints found ===

-- evaluating enhanced/epoch0

Hungarian eval: enhanced/epoch0:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch0 =====
{
  "experiment": "enhanced/epoch0",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 616,
  "total_gt": 760,
  "total_matches": 435,
  "correct_matches": 352,
  "wrong_class_matches": 83,
  "unmatched_predictions": 181,
  "unmatched_gt": 325,
  "mean_iou_matched": 0.7773063766545263,
  "matched_accuracy": 0.8091954022988506,
  "matched_f1_macro": 0.581525194766949,
  "matched_f1_micro": 0.8091954022988506,
  "class_aware_precision": 0.5714285714285714,
  "class_aware_recall": 0.4631578947368421,
  "class_aware_f1": 0.5116279069767442,
  "localization_precision": 0.7061688311688312,
  "localization_recall": 0.5723684210526315,
  "localization_f1": 0.632267441860465,
  "tp": 352,
  "fp": 264,
  "fn": 408
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             298           28               0              0
true_single               41           47               0              0
true_undersize             3            1               4              0
true_abnormal              3            3               4              3

-- evaluating enhanced/epoch1

Hungarian eval: enhanced/epoch1:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch1 =====
{
  "experiment": "enhanced/epoch1",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 1176,
  "total_gt": 760,
  "total_matches": 580,
  "correct_matches": 471,
  "wrong_class_matches": 109,
  "unmatched_predictions": 596,
  "unmatched_gt": 180,
  "mean_iou_matched": 0.7622647652338291,
  "matched_accuracy": 0.8120689655172414,
  "matched_f1_macro": 0.592544767225176,
  "matched_f1_micro": 0.8120689655172414,
  "class_aware_precision": 0.4005102040816326,
  "class_aware_recall": 0.6197368421052631,
  "class_aware_f1": 0.48657024793388426,
  "localization_precision": 0.4931972789115646,
  "localization_recall": 0.7631578947368421,
  "localization_f1": 0.5991735537190082,
  "tp": 471,
  "fp": 705,
  "fn": 289
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             345           60              11              0
true_single               19          102               3              0
true_undersize             4            1              23              0
true_abnormal              2            1               8              1

-- evaluating enhanced/epoch2

Hungarian eval: enhanced/epoch2:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch2 =====
{
  "experiment": "enhanced/epoch2",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 734,
  "total_gt": 760,
  "total_matches": 524,
  "correct_matches": 445,
  "wrong_class_matches": 79,
  "unmatched_predictions": 210,
  "unmatched_gt": 236,
  "mean_iou_matched": 0.7707675211984693,
  "matched_accuracy": 0.8492366412213741,
  "matched_f1_macro": 0.6879198148594701,
  "matched_f1_micro": 0.8492366412213741,
  "class_aware_precision": 0.6062670299727521,
  "class_aware_recall": 0.5855263157894737,
  "class_aware_f1": 0.5957161981258368,
  "localization_precision": 0.7138964577656676,
  "localization_recall": 0.6894736842105263,
  "localization_f1": 0.7014725568942437,
  "tp": 445,
  "fp": 289,
  "fn": 315
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             357           20               3              1
true_single               39           66               1              0
true_undersize             2            2              17              1
true_abnormal              4            1               5              5

-- evaluating enhanced/epoch3

Hungarian eval: enhanced/epoch3:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch3 =====
{
  "experiment": "enhanced/epoch3",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 718,
  "total_gt": 760,
  "total_matches": 512,
  "correct_matches": 454,
  "wrong_class_matches": 58,
  "unmatched_predictions": 206,
  "unmatched_gt": 248,
  "mean_iou_matched": 0.7727727501187474,
  "matched_accuracy": 0.88671875,
  "matched_f1_macro": 0.7665645834070823,
  "matched_f1_micro": 0.88671875,
  "class_aware_precision": 0.6323119777158774,
  "class_aware_recall": 0.5973684210526315,
  "class_aware_f1": 0.6143437077131257,
  "localization_precision": 0.713091922005571,
  "localization_recall": 0.6736842105263158,
  "localization_f1": 0.692828146143437,
  "tp": 454,
  "fp": 264,
  "fn": 306
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             345           22               1              1
true_single               19           81               1              1
true_undersize             3            1              21              0
true_abnormal              2            2               5              7

-- evaluating enhanced/epoch4

Hungarian eval: enhanced/epoch4:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch4 =====
{
  "experiment": "enhanced/epoch4",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 893,
  "total_gt": 760,
  "total_matches": 564,
  "correct_matches": 506,
  "wrong_class_matches": 58,
  "unmatched_predictions": 329,
  "unmatched_gt": 196,
  "mean_iou_matched": 0.7710082975896537,
  "matched_accuracy": 0.8971631205673759,
  "matched_f1_macro": 0.769215398510228,
  "matched_f1_micro": 0.8971631205673759,
  "class_aware_precision": 0.5666293393057111,
  "class_aware_recall": 0.6657894736842105,
  "class_aware_f1": 0.6122202056866304,
  "localization_precision": 0.631578947368421,
  "localization_recall": 0.7421052631578947,
  "localization_f1": 0.6823956442831215,
  "tp": 506,
  "fp": 387,
  "fn": 254
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             384           16               4              0
true_single               22           94               3              0
true_undersize             3            0              20              0
true_abnormal              2            1               7              8

-- evaluating enhanced/epoch5

Hungarian eval: enhanced/epoch5:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch5 =====
{
  "experiment": "enhanced/epoch5",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 782,
  "total_gt": 760,
  "total_matches": 565,
  "correct_matches": 497,
  "wrong_class_matches": 68,
  "unmatched_predictions": 217,
  "unmatched_gt": 195,
  "mean_iou_matched": 0.7721388439161587,
  "matched_accuracy": 0.879646017699115,
  "matched_f1_macro": 0.7705877976087636,
  "matched_f1_micro": 0.879646017699115,
  "class_aware_precision": 0.6355498721227621,
  "class_aware_recall": 0.6539473684210526,
  "class_aware_f1": 0.6446173800259403,
  "localization_precision": 0.7225063938618926,
  "localization_recall": 0.743421052631579,
  "localization_f1": 0.7328145265888457,
  "tp": 497,
  "fp": 285,
  "fn": 263
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             375           21               3              0
true_single               29           91               1              0
true_undersize             0            2              19              5
true_abnormal              0            3               4             12

-- evaluating enhanced/epoch6

Hungarian eval: enhanced/epoch6:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch6 =====
{
  "experiment": "enhanced/epoch6",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 820,
  "total_gt": 760,
  "total_matches": 549,
  "correct_matches": 495,
  "wrong_class_matches": 54,
  "unmatched_predictions": 271,
  "unmatched_gt": 211,
  "mean_iou_matched": 0.7742825414313644,
  "matched_accuracy": 0.9016393442622951,
  "matched_f1_macro": 0.8091283373135039,
  "matched_f1_micro": 0.9016393442622951,
  "class_aware_precision": 0.6036585365853658,
  "class_aware_recall": 0.6513157894736842,
  "class_aware_f1": 0.6265822784810127,
  "localization_precision": 0.6695121951219513,
  "localization_recall": 0.7223684210526315,
  "localization_f1": 0.6949367088607594,
  "tp": 495,
  "fp": 325,
  "fn": 265
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             369           21               2              0
true_single               18           97               1              0
true_undersize             2            2              20              0
true_abnormal              3            1               4              9

-- evaluating enhanced/epoch7

Hungarian eval: enhanced/epoch7:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch7 =====
{
  "experiment": "enhanced/epoch7",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 702,
  "total_gt": 760,
  "total_matches": 536,
  "correct_matches": 482,
  "wrong_class_matches": 54,
  "unmatched_predictions": 166,
  "unmatched_gt": 224,
  "mean_iou_matched": 0.7759257788533596,
  "matched_accuracy": 0.8992537313432836,
  "matched_f1_macro": 0.7896783900801487,
  "matched_f1_micro": 0.8992537313432836,
  "class_aware_precision": 0.6866096866096866,
  "class_aware_recall": 0.6342105263157894,
  "class_aware_f1": 0.6593707250341997,
  "localization_precision": 0.7635327635327636,
  "localization_recall": 0.7052631578947368,
  "localization_f1": 0.7332421340629275,
  "tp": 482,
  "fp": 220,
  "fn": 278
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             367           14               3              0
true_single               23           89               2              0
true_undersize             2            3              16              1
true_abnormal              0            1               5             10

-- evaluating enhanced/epoch8

Hungarian eval: enhanced/epoch8:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch8 =====
{
  "experiment": "enhanced/epoch8",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 772,
  "total_gt": 760,
  "total_matches": 560,
  "correct_matches": 489,
  "wrong_class_matches": 71,
  "unmatched_predictions": 212,
  "unmatched_gt": 200,
  "mean_iou_matched": 0.7739059132124696,
  "matched_accuracy": 0.8732142857142857,
  "matched_f1_macro": 0.759365520411545,
  "matched_f1_micro": 0.8732142857142857,
  "class_aware_precision": 0.633419689119171,
  "class_aware_recall": 0.6434210526315789,
  "class_aware_f1": 0.6383812010443864,
  "localization_precision": 0.7253886010362695,
  "localization_recall": 0.7368421052631579,
  "localization_f1": 0.7310704960835509,
  "tp": 489,
  "fp": 283,
  "fn": 271
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             366           28               3              0
true_single               20           90               2              0
true_undersize             4            1              21              4
true_abnormal              2            2               5             12

-- evaluating enhanced/epoch9

Hungarian eval: enhanced/epoch9:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch9 =====
{
  "experiment": "enhanced/epoch9",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 893,
  "total_gt": 760,
  "total_matches": 586,
  "correct_matches": 523,
  "wrong_class_matches": 63,
  "unmatched_predictions": 307,
  "unmatched_gt": 174,
  "mean_iou_matched": 0.7713435038975074,
  "matched_accuracy": 0.8924914675767918,
  "matched_f1_macro": 0.8350505006048411,
  "matched_f1_micro": 0.8924914675767918,
  "class_aware_precision": 0.5856662933930571,
  "class_aware_recall": 0.6881578947368421,
  "class_aware_f1": 0.632788868723533,
  "localization_precision": 0.6562150055991042,
  "localization_recall": 0.7710526315789473,
  "localization_f1": 0.7090139140955838,
  "tp": 523,
  "fp": 370,
  "fn": 237
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             376           28               4              0
true_single               18          106               2              0
true_undersize             3            2              26              0
true_abnormal              1            0               5             15

-- evaluating enhanced/epoch10

Hungarian eval: enhanced/epoch10:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch10 =====
{
  "experiment": "enhanced/epoch10",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 808,
  "total_gt": 760,
  "total_matches": 568,
  "correct_matches": 511,
  "wrong_class_matches": 57,
  "unmatched_predictions": 240,
  "unmatched_gt": 192,
  "mean_iou_matched": 0.7692766948275163,
  "matched_accuracy": 0.8996478873239436,
  "matched_f1_macro": 0.8001916395741697,
  "matched_f1_micro": 0.8996478873239436,
  "class_aware_precision": 0.6324257425742574,
  "class_aware_recall": 0.6723684210526316,
  "class_aware_f1": 0.6517857142857143,
  "localization_precision": 0.7029702970297029,
  "localization_recall": 0.7473684210526316,
  "localization_f1": 0.7244897959183674,
  "tp": 511,
  "fp": 297,
  "fn": 249
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             391           14               3              0
true_single               26           90               1              0
true_undersize             4            1              20              1
true_abnormal              1            2               4             10

-- evaluating enhanced/epoch11

Hungarian eval: enhanced/epoch11:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch11 =====
{
  "experiment": "enhanced/epoch11",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 805,
  "total_gt": 760,
  "total_matches": 570,
  "correct_matches": 522,
  "wrong_class_matches": 48,
  "unmatched_predictions": 235,
  "unmatched_gt": 190,
  "mean_iou_matched": 0.7756181800574588,
  "matched_accuracy": 0.9157894736842105,
  "matched_f1_macro": 0.8139163359524006,
  "matched_f1_micro": 0.9157894736842105,
  "class_aware_precision": 0.6484472049689441,
  "class_aware_recall": 0.6868421052631579,
  "class_aware_f1": 0.6670926517571885,
  "localization_precision": 0.7080745341614907,
  "localization_recall": 0.75,
  "localization_f1": 0.7284345047923322,
  "tp": 522,
  "fp": 283,
  "fn": 238
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             400           12               1              0
true_single               21           92               1              0
true_undersize             3            1              18              3
true_abnormal              2            0               4             12

-- evaluating enhanced/epoch12

Hungarian eval: enhanced/epoch12:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch12 =====
{
  "experiment": "enhanced/epoch12",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 808,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 518,
  "wrong_class_matches": 59,
  "unmatched_predictions": 231,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7778925683923983,
  "matched_accuracy": 0.8977469670710572,
  "matched_f1_macro": 0.8415024483576201,
  "matched_f1_micro": 0.8977469670710572,
  "class_aware_precision": 0.6410891089108911,
  "class_aware_recall": 0.6815789473684211,
  "class_aware_f1": 0.6607142857142858,
  "localization_precision": 0.7141089108910891,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.735969387755102,
  "tp": 518,
  "fp": 290,
  "fn": 242
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             375           28               5              0
true_single               14          104               1              0
true_undersize             3            2              25              0
true_abnormal              1            3               2             14

-- evaluating enhanced/epoch13

Hungarian eval: enhanced/epoch13:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch13 =====
{
  "experiment": "enhanced/epoch13",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 783,
  "total_gt": 760,
  "total_matches": 584,
  "correct_matches": 529,
  "wrong_class_matches": 55,
  "unmatched_predictions": 199,
  "unmatched_gt": 176,
  "mean_iou_matched": 0.7651114040245749,
  "matched_accuracy": 0.9058219178082192,
  "matched_f1_macro": 0.8353151324814447,
  "matched_f1_micro": 0.9058219178082192,
  "class_aware_precision": 0.6756066411238825,
  "class_aware_recall": 0.6960526315789474,
  "class_aware_f1": 0.6856772521062864,
  "localization_precision": 0.7458492975734355,
  "localization_recall": 0.7684210526315789,
  "localization_f1": 0.7569669475048607,
  "tp": 529,
  "fp": 254,
  "fn": 231
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             401           13               1              0
true_single               27           91               2              0
true_undersize             4            2              23              1
true_abnormal              1            0               4             14

-- evaluating enhanced/epoch14

Hungarian eval: enhanced/epoch14:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch14 =====
{
  "experiment": "enhanced/epoch14",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 741,
  "total_gt": 760,
  "total_matches": 561,
  "correct_matches": 498,
  "wrong_class_matches": 63,
  "unmatched_predictions": 180,
  "unmatched_gt": 199,
  "mean_iou_matched": 0.7771759713184813,
  "matched_accuracy": 0.8877005347593583,
  "matched_f1_macro": 0.7951745593039633,
  "matched_f1_micro": 0.8877005347593583,
  "class_aware_precision": 0.6720647773279352,
  "class_aware_recall": 0.6552631578947369,
  "class_aware_f1": 0.6635576282478348,
  "localization_precision": 0.757085020242915,
  "localization_recall": 0.7381578947368421,
  "localization_f1": 0.7475016655562959,
  "tp": 498,
  "fp": 243,
  "fn": 262
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             357           23              13              0
true_single               15          102               1              1
true_undersize             1            0              25              4
true_abnormal              0            0               5             14

-- evaluating enhanced/epoch15

Hungarian eval: enhanced/epoch15:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch15 =====
{
  "experiment": "enhanced/epoch15",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 691,
  "total_gt": 760,
  "total_matches": 548,
  "correct_matches": 503,
  "wrong_class_matches": 45,
  "unmatched_predictions": 143,
  "unmatched_gt": 212,
  "mean_iou_matched": 0.7775930500161039,
  "matched_accuracy": 0.9178832116788321,
  "matched_f1_macro": 0.8312166568583472,
  "matched_f1_micro": 0.9178832116788321,
  "class_aware_precision": 0.7279305354558611,
  "class_aware_recall": 0.6618421052631579,
  "class_aware_f1": 0.693314955203308,
  "localization_precision": 0.7930535455861071,
  "localization_recall": 0.7210526315789474,
  "localization_f1": 0.7553411440385941,
  "tp": 503,
  "fp": 188,
  "fn": 257
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             373           12               5              0
true_single               18           98               1              0
true_undersize             1            0              18              3
true_abnormal              1            1               3             14

-- evaluating enhanced/epoch16

Hungarian eval: enhanced/epoch16:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch16 =====
{
  "experiment": "enhanced/epoch16",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 787,
  "total_gt": 760,
  "total_matches": 573,
  "correct_matches": 504,
  "wrong_class_matches": 69,
  "unmatched_predictions": 214,
  "unmatched_gt": 187,
  "mean_iou_matched": 0.7755694896970952,
  "matched_accuracy": 0.8795811518324608,
  "matched_f1_macro": 0.824157356474035,
  "matched_f1_micro": 0.8795811518324608,
  "class_aware_precision": 0.6404066073697586,
  "class_aware_recall": 0.6631578947368421,
  "class_aware_f1": 0.6515837104072398,
  "localization_precision": 0.7280813214739518,
  "localization_recall": 0.7539473684210526,
  "localization_f1": 0.7407886231415642,
  "tp": 504,
  "fp": 283,
  "fn": 256
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             366           38               4              0
true_single               17          104               0              0
true_undersize             3            1              20              1
true_abnormal              0            2               3             14

-- evaluating enhanced/epoch17

Hungarian eval: enhanced/epoch17:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch17 =====
{
  "experiment": "enhanced/epoch17",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 766,
  "total_gt": 760,
  "total_matches": 565,
  "correct_matches": 504,
  "wrong_class_matches": 61,
  "unmatched_predictions": 201,
  "unmatched_gt": 195,
  "mean_iou_matched": 0.7731487177114571,
  "matched_accuracy": 0.8920353982300885,
  "matched_f1_macro": 0.807131609039689,
  "matched_f1_micro": 0.8920353982300885,
  "class_aware_precision": 0.6579634464751958,
  "class_aware_recall": 0.6631578947368421,
  "class_aware_f1": 0.6605504587155963,
  "localization_precision": 0.737597911227154,
  "localization_recall": 0.743421052631579,
  "localization_f1": 0.7404980340760158,
  "tp": 504,
  "fp": 262,
  "fn": 256
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             368           28               3              1
true_single               14          101               1              0
true_undersize             4            2              21              3
true_abnormal              0            2               3             14

-- evaluating enhanced/epoch18

Hungarian eval: enhanced/epoch18:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch18 =====
{
  "experiment": "enhanced/epoch18",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 767,
  "total_gt": 760,
  "total_matches": 560,
  "correct_matches": 513,
  "wrong_class_matches": 47,
  "unmatched_predictions": 207,
  "unmatched_gt": 200,
  "mean_iou_matched": 0.7718204802700451,
  "matched_accuracy": 0.9160714285714285,
  "matched_f1_macro": 0.8424037969316835,
  "matched_f1_micro": 0.9160714285714285,
  "class_aware_precision": 0.6688396349413298,
  "class_aware_recall": 0.675,
  "class_aware_f1": 0.6719056974459726,
  "localization_precision": 0.7301173402868318,
  "localization_recall": 0.7368421052631579,
  "localization_f1": 0.7334643091028159,
  "tp": 513,
  "fp": 254,
  "fn": 247
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             390           13               1              0
true_single               20           86               1              0
true_undersize             4            1              23              2
true_abnormal              0            2               3             14

-- evaluating enhanced/epoch19

Hungarian eval: enhanced/epoch19:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch19 =====
{
  "experiment": "enhanced/epoch19",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 781,
  "total_gt": 760,
  "total_matches": 578,
  "correct_matches": 510,
  "wrong_class_matches": 68,
  "unmatched_predictions": 203,
  "unmatched_gt": 182,
  "mean_iou_matched": 0.7788347805041342,
  "matched_accuracy": 0.8823529411764706,
  "matched_f1_macro": 0.8266958054863126,
  "matched_f1_micro": 0.8823529411764706,
  "class_aware_precision": 0.6530089628681178,
  "class_aware_recall": 0.6710526315789473,
  "class_aware_f1": 0.661907852044127,
  "localization_precision": 0.7400768245838668,
  "localization_recall": 0.7605263157894737,
  "localization_f1": 0.7501622323166774,
  "tp": 510,
  "fp": 271,
  "fn": 250
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             361           41               2              0
true_single               10          110               2              0
true_undersize             5            2              23              1
true_abnormal              0            1               4             16

-- evaluating enhanced/epoch20

Hungarian eval: enhanced/epoch20:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch20 =====
{
  "experiment": "enhanced/epoch20",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 781,
  "total_gt": 760,
  "total_matches": 567,
  "correct_matches": 512,
  "wrong_class_matches": 55,
  "unmatched_predictions": 214,
  "unmatched_gt": 193,
  "mean_iou_matched": 0.7799894725624636,
  "matched_accuracy": 0.9029982363315696,
  "matched_f1_macro": 0.8153139614180535,
  "matched_f1_micro": 0.9029982363315696,
  "class_aware_precision": 0.6555697823303457,
  "class_aware_recall": 0.6736842105263158,
  "class_aware_f1": 0.6645035691109669,
  "localization_precision": 0.7259923175416133,
  "localization_recall": 0.7460526315789474,
  "localization_f1": 0.7358857884490592,
  "tp": 512,
  "fp": 269,
  "fn": 248
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           24               3              0
true_single               14           99               1              0
true_undersize             4            1              21              1
true_abnormal              0            1               6             13

-- evaluating enhanced/epoch21

Hungarian eval: enhanced/epoch21:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch21 =====
{
  "experiment": "enhanced/epoch21",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 642,
  "total_gt": 760,
  "total_matches": 533,
  "correct_matches": 481,
  "wrong_class_matches": 52,
  "unmatched_predictions": 109,
  "unmatched_gt": 227,
  "mean_iou_matched": 0.7809921963800857,
  "matched_accuracy": 0.9024390243902439,
  "matched_f1_macro": 0.8430452493611524,
  "matched_f1_micro": 0.9024390243902439,
  "class_aware_precision": 0.7492211838006231,
  "class_aware_recall": 0.6328947368421053,
  "class_aware_f1": 0.6861626248216832,
  "localization_precision": 0.8302180685358256,
  "localization_recall": 0.7013157894736842,
  "localization_f1": 0.7603423680456491,
  "tp": 481,
  "fp": 161,
  "fn": 279
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             350           28               3              0
true_single               13           98               0              0
true_undersize             1            1              20              1
true_abnormal              0            1               4             13

-- evaluating enhanced/epoch22

Hungarian eval: enhanced/epoch22:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch22 =====
{
  "experiment": "enhanced/epoch22",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 794,
  "total_gt": 760,
  "total_matches": 583,
  "correct_matches": 536,
  "wrong_class_matches": 47,
  "unmatched_predictions": 211,
  "unmatched_gt": 177,
  "mean_iou_matched": 0.7806393638074296,
  "matched_accuracy": 0.9193825042881647,
  "matched_f1_macro": 0.8563033342723453,
  "matched_f1_micro": 0.9193825042881647,
  "class_aware_precision": 0.6750629722921915,
  "class_aware_recall": 0.7052631578947368,
  "class_aware_f1": 0.6898326898326899,
  "localization_precision": 0.7342569269521411,
  "localization_recall": 0.7671052631578947,
  "localization_f1": 0.7503217503217503,
  "tp": 536,
  "fp": 258,
  "fn": 224
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             394           16               3              0
true_single               17          102               0              1
true_undersize             2            2              23              2
true_abnormal              1            0               3             17

-- evaluating enhanced/epoch23

Hungarian eval: enhanced/epoch23:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch23 =====
{
  "experiment": "enhanced/epoch23",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 746,
  "total_gt": 760,
  "total_matches": 555,
  "correct_matches": 507,
  "wrong_class_matches": 48,
  "unmatched_predictions": 191,
  "unmatched_gt": 205,
  "mean_iou_matched": 0.7803682256389308,
  "matched_accuracy": 0.9135135135135135,
  "matched_f1_macro": 0.8546028897346337,
  "matched_f1_micro": 0.9135135135135135,
  "class_aware_precision": 0.6796246648793566,
  "class_aware_recall": 0.6671052631578948,
  "class_aware_f1": 0.6733067729083666,
  "localization_precision": 0.7439678284182306,
  "localization_recall": 0.7302631578947368,
  "localization_f1": 0.7370517928286853,
  "tp": 507,
  "fp": 239,
  "fn": 253
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             378           19               3              0
true_single               16           92               1              0
true_undersize             3            1              20              1
true_abnormal              0            1               3             17

-- evaluating enhanced/epoch24

Hungarian eval: enhanced/epoch24:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch24 =====
{
  "experiment": "enhanced/epoch24",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 739,
  "total_gt": 760,
  "total_matches": 567,
  "correct_matches": 510,
  "wrong_class_matches": 57,
  "unmatched_predictions": 172,
  "unmatched_gt": 193,
  "mean_iou_matched": 0.780032480099424,
  "matched_accuracy": 0.8994708994708994,
  "matched_f1_macro": 0.8273314256007878,
  "matched_f1_micro": 0.8994708994708994,
  "class_aware_precision": 0.6901217861975643,
  "class_aware_recall": 0.6710526315789473,
  "class_aware_f1": 0.6804536357571714,
  "localization_precision": 0.7672530446549392,
  "localization_recall": 0.7460526315789474,
  "localization_f1": 0.7565043362241495,
  "tp": 510,
  "fp": 229,
  "fn": 250
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             372           27               3              1
true_single               15          100               0              0
true_undersize             1            2              22              3
true_abnormal              0            1               4             16

-- evaluating enhanced/epoch25

Hungarian eval: enhanced/epoch25:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch25 =====
{
  "experiment": "enhanced/epoch25",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 729,
  "total_gt": 760,
  "total_matches": 560,
  "correct_matches": 513,
  "wrong_class_matches": 47,
  "unmatched_predictions": 169,
  "unmatched_gt": 200,
  "mean_iou_matched": 0.7797991388610431,
  "matched_accuracy": 0.9160714285714285,
  "matched_f1_macro": 0.841022789051289,
  "matched_f1_micro": 0.9160714285714285,
  "class_aware_precision": 0.7037037037037037,
  "class_aware_recall": 0.675,
  "class_aware_f1": 0.6890530557421088,
  "localization_precision": 0.7681755829903978,
  "localization_recall": 0.7368421052631579,
  "localization_f1": 0.7521826729348556,
  "tp": 513,
  "fp": 216,
  "fn": 247
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             373           19               5              0
true_single               12          103               2              0
true_undersize             1            1              22              3
true_abnormal              0            1               3             15

-- evaluating enhanced/epoch26

Hungarian eval: enhanced/epoch26:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch26 =====
{
  "experiment": "enhanced/epoch26",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 825,
  "total_gt": 760,
  "total_matches": 580,
  "correct_matches": 531,
  "wrong_class_matches": 49,
  "unmatched_predictions": 245,
  "unmatched_gt": 180,
  "mean_iou_matched": 0.7806974347295432,
  "matched_accuracy": 0.9155172413793103,
  "matched_f1_macro": 0.8421343015159649,
  "matched_f1_micro": 0.9155172413793103,
  "class_aware_precision": 0.6436363636363637,
  "class_aware_recall": 0.6986842105263158,
  "class_aware_f1": 0.670031545741325,
  "localization_precision": 0.703030303030303,
  "localization_recall": 0.7631578947368421,
  "localization_f1": 0.7318611987381703,
  "tp": 531,
  "fp": 294,
  "fn": 229
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             400           10               4              0
true_single               21           91               2              0
true_undersize             4            2              23              2
true_abnormal              0            1               3             17

-- evaluating enhanced/epoch27

Hungarian eval: enhanced/epoch27:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch27 =====
{
  "experiment": "enhanced/epoch27",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 791,
  "total_gt": 760,
  "total_matches": 578,
  "correct_matches": 531,
  "wrong_class_matches": 47,
  "unmatched_predictions": 213,
  "unmatched_gt": 182,
  "mean_iou_matched": 0.781445798370665,
  "matched_accuracy": 0.9186851211072664,
  "matched_f1_macro": 0.8233032501124606,
  "matched_f1_micro": 0.9186851211072664,
  "class_aware_precision": 0.6713021491782554,
  "class_aware_recall": 0.6986842105263158,
  "class_aware_f1": 0.6847195357833655,
  "localization_precision": 0.7307206068268015,
  "localization_recall": 0.7605263157894737,
  "localization_f1": 0.7453255963894261,
  "tp": 531,
  "fp": 260,
  "fn": 229
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             398           10               4              0
true_single               20          100               1              0
true_undersize             2            2              18              3
true_abnormal              0            1               4             15

-- evaluating enhanced/epoch28

Hungarian eval: enhanced/epoch28:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch28 =====
{
  "experiment": "enhanced/epoch28",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 786,
  "total_gt": 760,
  "total_matches": 577,
  "correct_matches": 524,
  "wrong_class_matches": 53,
  "unmatched_predictions": 209,
  "unmatched_gt": 183,
  "mean_iou_matched": 0.7776992488361933,
  "matched_accuracy": 0.9081455805892548,
  "matched_f1_macro": 0.8383945814909358,
  "matched_f1_micro": 0.9081455805892548,
  "class_aware_precision": 0.6666666666666666,
  "class_aware_recall": 0.6894736842105263,
  "class_aware_f1": 0.6778783958602845,
  "localization_precision": 0.7340966921119593,
  "localization_recall": 0.7592105263157894,
  "localization_f1": 0.7464424320827943,
  "tp": 524,
  "fp": 262,
  "fn": 236
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             390           17               7              0
true_single               18           95               1              0
true_undersize             4            0              23              2
true_abnormal              0            1               3             16

-- evaluating enhanced/epoch29

Hungarian eval: enhanced/epoch29:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch29 =====
{
  "experiment": "enhanced/epoch29",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 772,
  "total_gt": 760,
  "total_matches": 570,
  "correct_matches": 522,
  "wrong_class_matches": 48,
  "unmatched_predictions": 202,
  "unmatched_gt": 190,
  "mean_iou_matched": 0.7821018999083,
  "matched_accuracy": 0.9157894736842105,
  "matched_f1_macro": 0.8613617773085465,
  "matched_f1_micro": 0.9157894736842105,
  "class_aware_precision": 0.6761658031088082,
  "class_aware_recall": 0.6868421052631579,
  "class_aware_f1": 0.6814621409921671,
  "localization_precision": 0.7383419689119171,
  "localization_recall": 0.75,
  "localization_f1": 0.7441253263707571,
  "tp": 522,
  "fp": 250,
  "fn": 238
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           21               2              1
true_single               15          104               2              0
true_undersize             1            1              25              1
true_abnormal              0            1               3             14

-- evaluating enhanced/epoch30

Hungarian eval: enhanced/epoch30:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch30 =====
{
  "experiment": "enhanced/epoch30",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 732,
  "total_gt": 760,
  "total_matches": 566,
  "correct_matches": 514,
  "wrong_class_matches": 52,
  "unmatched_predictions": 166,
  "unmatched_gt": 194,
  "mean_iou_matched": 0.7836325424509419,
  "matched_accuracy": 0.9081272084805654,
  "matched_f1_macro": 0.828930431243287,
  "matched_f1_micro": 0.9081272084805654,
  "class_aware_precision": 0.7021857923497268,
  "class_aware_recall": 0.6763157894736842,
  "class_aware_f1": 0.6890080428954424,
  "localization_precision": 0.773224043715847,
  "localization_recall": 0.7447368421052631,
  "localization_f1": 0.7587131367292225,
  "tp": 514,
  "fp": 218,
  "fn": 246
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           19               2              1
true_single               18          101               0              0
true_undersize             3            2              18              4
true_abnormal              0            1               2             16

-- evaluating enhanced/epoch31

Hungarian eval: enhanced/epoch31:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch31 =====
{
  "experiment": "enhanced/epoch31",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 765,
  "total_gt": 760,
  "total_matches": 574,
  "correct_matches": 526,
  "wrong_class_matches": 48,
  "unmatched_predictions": 191,
  "unmatched_gt": 186,
  "mean_iou_matched": 0.7793697305672675,
  "matched_accuracy": 0.9163763066202091,
  "matched_f1_macro": 0.8350077417694406,
  "matched_f1_micro": 0.9163763066202091,
  "class_aware_precision": 0.6875816993464052,
  "class_aware_recall": 0.6921052631578948,
  "class_aware_f1": 0.6898360655737705,
  "localization_precision": 0.7503267973856209,
  "localization_recall": 0.7552631578947369,
  "localization_f1": 0.7527868852459018,
  "tp": 526,
  "fp": 239,
  "fn": 234
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             391           13               3              0
true_single               18           96               2              0
true_undersize             2            2              23              3
true_abnormal              0            1               4             16

-- evaluating enhanced/epoch32

Hungarian eval: enhanced/epoch32:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch32 =====
{
  "experiment": "enhanced/epoch32",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 712,
  "total_gt": 760,
  "total_matches": 555,
  "correct_matches": 504,
  "wrong_class_matches": 51,
  "unmatched_predictions": 157,
  "unmatched_gt": 205,
  "mean_iou_matched": 0.7841139300449474,
  "matched_accuracy": 0.9081081081081082,
  "matched_f1_macro": 0.8595088707532172,
  "matched_f1_micro": 0.9081081081081082,
  "class_aware_precision": 0.7078651685393258,
  "class_aware_recall": 0.6631578947368421,
  "class_aware_f1": 0.6847826086956521,
  "localization_precision": 0.7794943820224719,
  "localization_recall": 0.7302631578947368,
  "localization_f1": 0.7540760869565217,
  "tp": 504,
  "fp": 208,
  "fn": 256
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             366           23               1              0
true_single               16           96               1              0
true_undersize             3            1              24              3
true_abnormal              1            0               2             18

-- evaluating enhanced/epoch33

Hungarian eval: enhanced/epoch33:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch33 =====
{
  "experiment": "enhanced/epoch33",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 748,
  "total_gt": 760,
  "total_matches": 563,
  "correct_matches": 513,
  "wrong_class_matches": 50,
  "unmatched_predictions": 185,
  "unmatched_gt": 197,
  "mean_iou_matched": 0.783340903412597,
  "matched_accuracy": 0.911190053285968,
  "matched_f1_macro": 0.8319894120192294,
  "matched_f1_micro": 0.911190053285968,
  "class_aware_precision": 0.6858288770053476,
  "class_aware_recall": 0.675,
  "class_aware_f1": 0.6803713527851459,
  "localization_precision": 0.7526737967914439,
  "localization_recall": 0.7407894736842106,
  "localization_f1": 0.746684350132626,
  "tp": 513,
  "fp": 235,
  "fn": 247
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             386           13               3              0
true_single               19           92               2              0
true_undersize             5            2              19              2
true_abnormal              1            1               2             16

-- evaluating enhanced/epoch34

Hungarian eval: enhanced/epoch34:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch34 =====
{
  "experiment": "enhanced/epoch34",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 780,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 526,
  "wrong_class_matches": 50,
  "unmatched_predictions": 204,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.7818975498278936,
  "matched_accuracy": 0.9131944444444444,
  "matched_f1_macro": 0.842155413615987,
  "matched_f1_micro": 0.9131944444444444,
  "class_aware_precision": 0.6743589743589744,
  "class_aware_recall": 0.6921052631578948,
  "class_aware_f1": 0.6831168831168832,
  "localization_precision": 0.7384615384615385,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7480519480519481,
  "tp": 526,
  "fp": 254,
  "fn": 234
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             383           19               4              0
true_single               14          103               2              0
true_undersize             3            1              24              3
true_abnormal              0            1               3             16

-- evaluating enhanced/epoch35

Hungarian eval: enhanced/epoch35:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch35 =====
{
  "experiment": "enhanced/epoch35",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 789,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 527,
  "wrong_class_matches": 49,
  "unmatched_predictions": 213,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.778874083318644,
  "matched_accuracy": 0.9149305555555556,
  "matched_f1_macro": 0.8488195876014084,
  "matched_f1_micro": 0.9149305555555556,
  "class_aware_precision": 0.6679340937896071,
  "class_aware_recall": 0.6934210526315789,
  "class_aware_f1": 0.6804389928986444,
  "localization_precision": 0.7300380228136882,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7437056165267915,
  "tp": 527,
  "fp": 262,
  "fn": 233
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             388           18               4              0
true_single               16          101               0              0
true_undersize             4            1              20              3
true_abnormal              0            1               2             18

-- evaluating enhanced/epoch36

Hungarian eval: enhanced/epoch36:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch36 =====
{
  "experiment": "enhanced/epoch36",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 783,
  "total_gt": 760,
  "total_matches": 585,
  "correct_matches": 529,
  "wrong_class_matches": 56,
  "unmatched_predictions": 198,
  "unmatched_gt": 175,
  "mean_iou_matched": 0.782082514375703,
  "matched_accuracy": 0.9042735042735043,
  "matched_f1_macro": 0.8455476531683168,
  "matched_f1_micro": 0.9042735042735043,
  "class_aware_precision": 0.6756066411238825,
  "class_aware_recall": 0.6960526315789474,
  "class_aware_f1": 0.6856772521062864,
  "localization_precision": 0.7471264367816092,
  "localization_recall": 0.7697368421052632,
  "localization_f1": 0.7582631237848347,
  "tp": 529,
  "fp": 254,
  "fn": 231
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             385           24               3              0
true_single               18          103               0              0
true_undersize             3            1              23              4
true_abnormal              0            1               2             18

-- evaluating enhanced/epoch37

Hungarian eval: enhanced/epoch37:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch37 =====
{
  "experiment": "enhanced/epoch37",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 766,
  "total_gt": 760,
  "total_matches": 589,
  "correct_matches": 535,
  "wrong_class_matches": 54,
  "unmatched_predictions": 177,
  "unmatched_gt": 171,
  "mean_iou_matched": 0.7828226067214344,
  "matched_accuracy": 0.9083191850594228,
  "matched_f1_macro": 0.8381199983800323,
  "matched_f1_micro": 0.9083191850594228,
  "class_aware_precision": 0.6984334203655352,
  "class_aware_recall": 0.7039473684210527,
  "class_aware_f1": 0.7011795543905635,
  "localization_precision": 0.7689295039164491,
  "localization_recall": 0.775,
  "localization_f1": 0.7719528178243775,
  "tp": 535,
  "fp": 231,
  "fn": 225
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             385           23               3              0
true_single               15          110               1              0
true_undersize             3            1              23              4
true_abnormal              0            1               3             17

-- evaluating enhanced/epoch38

Hungarian eval: enhanced/epoch38:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch38 =====
{
  "experiment": "enhanced/epoch38",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 746,
  "total_gt": 760,
  "total_matches": 573,
  "correct_matches": 527,
  "wrong_class_matches": 46,
  "unmatched_predictions": 173,
  "unmatched_gt": 187,
  "mean_iou_matched": 0.780874213831171,
  "matched_accuracy": 0.9197207678883071,
  "matched_f1_macro": 0.8624476428759809,
  "matched_f1_micro": 0.9197207678883071,
  "class_aware_precision": 0.7064343163538874,
  "class_aware_recall": 0.6934210526315789,
  "class_aware_f1": 0.699867197875166,
  "localization_precision": 0.7680965147453083,
  "localization_recall": 0.7539473684210526,
  "localization_f1": 0.7609561752988047,
  "tp": 527,
  "fp": 219,
  "fn": 233
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             385           16               1              0
true_single               16          100               1              0
true_undersize             5            1              23              3
true_abnormal              1            0               2             19

-- evaluating enhanced/epoch39

Hungarian eval: enhanced/epoch39:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch39 =====
{
  "experiment": "enhanced/epoch39",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 791,
  "total_gt": 760,
  "total_matches": 580,
  "correct_matches": 529,
  "wrong_class_matches": 51,
  "unmatched_predictions": 211,
  "unmatched_gt": 180,
  "mean_iou_matched": 0.7839508099802609,
  "matched_accuracy": 0.9120689655172414,
  "matched_f1_macro": 0.8447755688132593,
  "matched_f1_micro": 0.9120689655172414,
  "class_aware_precision": 0.6687737041719343,
  "class_aware_recall": 0.6960526315789474,
  "class_aware_f1": 0.68214055448098,
  "localization_precision": 0.7332490518331226,
  "localization_recall": 0.7631578947368421,
  "localization_f1": 0.7479045776918117,
  "tp": 529,
  "fp": 262,
  "fn": 231
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             389           20               2              1
true_single               15          100               2              0
true_undersize             3            2              22              3
true_abnormal              0            1               2             18

-- evaluating enhanced/epoch40

Hungarian eval: enhanced/epoch40:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch40 =====
{
  "experiment": "enhanced/epoch40",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 805,
  "total_gt": 760,
  "total_matches": 594,
  "correct_matches": 541,
  "wrong_class_matches": 53,
  "unmatched_predictions": 211,
  "unmatched_gt": 166,
  "mean_iou_matched": 0.7794196700006222,
  "matched_accuracy": 0.9107744107744108,
  "matched_f1_macro": 0.8465309696085598,
  "matched_f1_micro": 0.9107744107744108,
  "class_aware_precision": 0.6720496894409937,
  "class_aware_recall": 0.7118421052631579,
  "class_aware_f1": 0.691373801916933,
  "localization_precision": 0.737888198757764,
  "localization_recall": 0.781578947368421,
  "localization_f1": 0.7591054313099042,
  "tp": 541,
  "fp": 264,
  "fn": 219
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             394           21               2              0
true_single               17          106               1              0
true_undersize             4            1              21              4
true_abnormal              0            1               2             20

-- evaluating enhanced/epoch41

Hungarian eval: enhanced/epoch41:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch41 =====
{
  "experiment": "enhanced/epoch41",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 788,
  "total_gt": 760,
  "total_matches": 574,
  "correct_matches": 524,
  "wrong_class_matches": 50,
  "unmatched_predictions": 214,
  "unmatched_gt": 186,
  "mean_iou_matched": 0.7830396717226048,
  "matched_accuracy": 0.9128919860627178,
  "matched_f1_macro": 0.8580321476176436,
  "matched_f1_micro": 0.9128919860627178,
  "class_aware_precision": 0.6649746192893401,
  "class_aware_recall": 0.6894736842105263,
  "class_aware_f1": 0.6770025839793282,
  "localization_precision": 0.7284263959390863,
  "localization_recall": 0.7552631578947369,
  "localization_f1": 0.7416020671834624,
  "tp": 524,
  "fp": 264,
  "fn": 236
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             390           17               2              0
true_single               19           93               0              0
true_undersize             5            2              23              2
true_abnormal              0            1               2             18

-- evaluating enhanced/epoch42

Hungarian eval: enhanced/epoch42:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch42 =====
{
  "experiment": "enhanced/epoch42",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 792,
  "total_gt": 760,
  "total_matches": 590,
  "correct_matches": 538,
  "wrong_class_matches": 52,
  "unmatched_predictions": 202,
  "unmatched_gt": 170,
  "mean_iou_matched": 0.7803696860701351,
  "matched_accuracy": 0.911864406779661,
  "matched_f1_macro": 0.821667734347804,
  "matched_f1_micro": 0.911864406779661,
  "class_aware_precision": 0.6792929292929293,
  "class_aware_recall": 0.7078947368421052,
  "class_aware_f1": 0.6932989690721649,
  "localization_precision": 0.7449494949494949,
  "localization_recall": 0.7763157894736842,
  "localization_f1": 0.7603092783505155,
  "tp": 538,
  "fp": 254,
  "fn": 222
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             395           18               3              0
true_single               14          104               0              0
true_undersize             5            2              22              5
true_abnormal              0            2               3             17

-- evaluating enhanced/epoch43

Hungarian eval: enhanced/epoch43:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch43 =====
{
  "experiment": "enhanced/epoch43",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 791,
  "total_gt": 760,
  "total_matches": 583,
  "correct_matches": 531,
  "wrong_class_matches": 52,
  "unmatched_predictions": 208,
  "unmatched_gt": 177,
  "mean_iou_matched": 0.7838108490507149,
  "matched_accuracy": 0.9108061749571184,
  "matched_f1_macro": 0.8394651253558534,
  "matched_f1_micro": 0.9108061749571184,
  "class_aware_precision": 0.6713021491782554,
  "class_aware_recall": 0.6986842105263158,
  "class_aware_f1": 0.6847195357833655,
  "localization_precision": 0.7370417193426043,
  "localization_recall": 0.7671052631578947,
  "localization_f1": 0.75177304964539,
  "tp": 531,
  "fp": 260,
  "fn": 229
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             395           14               4              0
true_single               20           98               1              0
true_undersize             5            2              22              2
true_abnormal              0            2               2             16

-- evaluating enhanced/epoch44

Hungarian eval: enhanced/epoch44:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch44 =====
{
  "experiment": "enhanced/epoch44",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 767,
  "total_gt": 760,
  "total_matches": 585,
  "correct_matches": 533,
  "wrong_class_matches": 52,
  "unmatched_predictions": 182,
  "unmatched_gt": 175,
  "mean_iou_matched": 0.7837187956541013,
  "matched_accuracy": 0.9111111111111111,
  "matched_f1_macro": 0.8305340270182819,
  "matched_f1_micro": 0.9111111111111111,
  "class_aware_precision": 0.6949152542372882,
  "class_aware_recall": 0.7013157894736842,
  "class_aware_f1": 0.6981008513425017,
  "localization_precision": 0.7627118644067796,
  "localization_recall": 0.7697368421052632,
  "localization_f1": 0.7662082514734775,
  "tp": 533,
  "fp": 234,
  "fn": 227
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             393           16               3              0
true_single               18          101               1              0
true_undersize             4            2              21              5
true_abnormal              0            1               2             18

-- evaluating enhanced/epoch45

Hungarian eval: enhanced/epoch45:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/epoch45 =====
{
  "experiment": "enhanced/epoch45",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 789,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 522,
  "wrong_class_matches": 54,
  "unmatched_predictions": 213,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.7866552226866285,
  "matched_accuracy": 0.90625,
  "matched_f1_macro": 0.8369295362710268,
  "matched_f1_micro": 0.90625,
  "class_aware_precision": 0.6615969581749049,
  "class_aware_recall": 0.6868421052631579,
  "class_aware_f1": 0.6739832149774049,
  "localization_precision": 0.7300380228136882,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7437056165267915,
  "tp": 522,
  "fp": 267,
  "fn": 238
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             386           19               3              0
true_single               19           98               1              0
true_undersize             4            1              21              3
true_abnormal              0            2               2             17

-- evaluating enhanced/best

Hungarian eval: enhanced/best:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/best =====
{
  "experiment": "enhanced/best",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 781,
  "total_gt": 760,
  "total_matches": 567,
  "correct_matches": 512,
  "wrong_class_matches": 55,
  "unmatched_predictions": 214,
  "unmatched_gt": 193,
  "mean_iou_matched": 0.7799894725624636,
  "matched_accuracy": 0.9029982363315696,
  "matched_f1_macro": 0.8153139614180535,
  "matched_f1_micro": 0.9029982363315696,
  "class_aware_precision": 0.6555697823303457,
  "class_aware_recall": 0.6736842105263158,
  "class_aware_f1": 0.6645035691109669,
  "localization_precision": 0.7259923175416133,
  "localization_recall": 0.7460526315789474,
  "localization_f1": 0.7358857884490592,
  "tp": 512,
  "fp": 269,
  "fn": 248
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             379           24               3              0
true_single               14           99               1              0
true_undersize             4            1              21              1
true_abnormal              0            1               6             13

-- evaluating enhanced/last

Hungarian eval: enhanced/last:   0%|          | 0/50 [00:00<?, ?it/s]

===== YOLO Hungarian Evaluation: enhanced/last =====
{
  "experiment": "enhanced/last",
  "pred_conf": 0.25,
  "nms_iou": 0.7,
  "match_iou_threshold": 0.5,
  "total_predictions": 789,
  "total_gt": 760,
  "total_matches": 576,
  "correct_matches": 522,
  "wrong_class_matches": 54,
  "unmatched_predictions": 213,
  "unmatched_gt": 184,
  "mean_iou_matched": 0.7866552226866285,
  "matched_accuracy": 0.90625,
  "matched_f1_macro": 0.8369295362710268,
  "matched_f1_micro": 0.90625,
  "class_aware_precision": 0.6615969581749049,
  "class_aware_recall": 0.6868421052631579,
  "class_aware_f1": 0.6739832149774049,
  "localization_precision": 0.7300380228136882,
  "localization_recall": 0.7578947368421053,
  "localization_f1": 0.7437056165267915,
  "tp": 522,
  "fp": 267,
  "fn": 238
}

                pred_premium  pred_single  pred_undersize  pred_abnormal
true_premium             386           19               3              0
true_single               19           98               1              0
true_undersize             4            1              21              3
true_abnormal              0            2               2             17

,experiment,checkpoint,pred_conf,nms_iou,match_iou_threshold,total_predictions,total_gt,total_matches,correct_matches,wrong_class_matches,...,matched_f1_micro,class_aware_precision,class_aware_recall,class_aware_f1,localization_precision,localization_recall,localization_f1,tp,fp,fn
0,baseline/epoch0,epoch0,0.25,0.7,0.5,762,760,502,390,112,...,0.776892,0.511811,0.513158,0.512484,0.658793,0.660526,0.659658,390,372,370
1,baseline/epoch1,epoch1,0.25,0.7,0.5,910,760,556,470,86,...,0.845324,0.516484,0.618421,0.562874,0.610989,0.731579,0.665868,470,440,290
2,baseline/epoch2,epoch2,0.25,0.7,0.5,676,760,507,422,85,...,0.832347,0.624260,0.555263,0.587744,0.750000,0.667105,0.706128,422,254,338
3,baseline/epoch3,epoch3,0.25,0.7,0.5,727,760,531,465,66,...,0.875706,0.639615,0.611842,0.625420,0.730399,0.698684,0.714190,465,262,295
4,baseline/epoch4,epoch4,0.25,0.7,0.5,794,760,559,488,71,...,0.872987,0.614610,0.642105,0.628057,0.704030,0.735526,0.719434,488,306,272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,enhanced/epoch43,epoch43,0.25,0.7,0.5,791,760,583,531,52,...,0.910806,0.671302,0.698684,0.684720,0.737042,0.767105,0.751773,531,260,229
77,enhanced/epoch44,epoch44,0.25,0.7,0.5,767,760,585,533,52,...,0.911111,0.694915,0.701316,0.698101,0.762712,0.769737,0.766208,533,234,227
78,enhanced/epoch45,epoch45,0.25,0.7,0.5,789,760,576,522,54,...,0.906250,0.661597,0.686842,0.673983,0.730038,0.757895,0.743706,522,267,238
79,enhanced/best,best,0.25,0.7,0.5,781,760,567,512,55,...,0.902998,0.655570,0.673684,0.664504,0.725992,0.746053,0.735886,512,269,248
80,enhanced/last,last,0.25,0.7,0.5,789,760,576,522,54,...,0.906250,0.661597,0.686842,0.673983,0.730038,0.757895,0.743706,522,267,238

In [20]:
# Find best epoch by each metric, per experiment
for experiment_name, df in [('baseline', baseline_per_epoch_df), ('enhanced', enhanced_per_epoch_df)]:
    print(f'\n=== Best checkpoint by metric: {experiment_name} ===\n')
    metric_cols = [c for c in df.columns if c not in ('experiment', 'checkpoint') and df[c].dtype in ('float64', 'int64')]
    for col in metric_cols:
        if 'loss' in col.lower():
            idx = df[col].idxmin(); direction = 'min'
        else:
            idx = df[col].idxmax(); direction = 'max'
        print(f'  {col} ({direction}): {df.loc[idx, "checkpoint"]} = {df.loc[idx, col]:.4f}')

# Plot trajectory of mean IoU for both experiments
for experiment_name, df in [('baseline', baseline_per_epoch_df), ('enhanced', enhanced_per_epoch_df)]:
    epoch_df = df[df['checkpoint'].str.startswith('epoch')].copy()
    if len(epoch_df) == 0: continue
    epoch_df['epoch'] = epoch_df['checkpoint'].str.replace('epoch', '').astype(int)
    epoch_df = epoch_df.sort_values('epoch')
    plot_metrics = [c for c in ['mean_matched_iou', 'matched_accuracy', 'precision', 'recall', 'f1'] if c in epoch_df.columns]
    if plot_metrics:
        n = len(plot_metrics)
        fig, axes = plt.subplots(1, n, figsize=(4 * n, 4))
        if n == 1: axes = [axes]
        for ax, m in zip(axes, plot_metrics):
            ax.plot(epoch_df['epoch'], epoch_df[m], marker='o')
            ax.set_xlabel('epoch'); ax.set_ylabel(m); ax.set_title(f'{experiment_name}: {m}'); ax.grid(alpha=0.3)
        plt.tight_layout(); plt.show()

=== Best checkpoint by metric: baseline ===

  pred_conf (max): epoch0 = 0.2500
  nms_iou (max): epoch0 = 0.7000
  match_iou_threshold (max): epoch0 = 0.5000
  total_predictions (max): epoch1 = 910.0000
  total_gt (max): epoch0 = 760.0000
  total_matches (max): epoch30 = 587.0000
  correct_matches (max): epoch22 = 531.0000
  wrong_class_matches (max): epoch0 = 112.0000
  unmatched_predictions (max): epoch1 = 354.0000
  unmatched_gt (max): epoch0 = 258.0000
  mean_iou_matched (max): epoch27 = 0.7882
  matched_accuracy (max): epoch27 = 0.9151
  matched_f1_macro (max): epoch25 = 0.8498
  matched_f1_micro (max): epoch27 = 0.9151
  class_aware_precision (max): epoch15 = 0.7217
  class_aware_recall (max): epoch22 = 0.6987
  class_aware_f1 (max): epoch24 = 0.6981
  localization_precision (max): epoch7 = 0.8092
  localization_recall (max): epoch30 = 0.7724
  localization_f1 (max): epoch24 = 0.7658
  tp (max): epoch22 = 531.0000
  fp (max): epoch1 = 440.0000
  fn (max): epoch0 = 370.0000

=== Best checkpoint by metric: enhanced ===

  pred_conf (max): epoch0 = 0.2500
  nms_iou (max): epoch0 = 0.7000
  match_iou_threshold (max): epoch0 = 0.5000
  total_predictions (max): epoch1 = 1176.0000
  total_gt (max): epoch0 = 760.0000
  total_matches (max): epoch40 = 594.0000
  correct_matches (max): epoch40 = 541.0000
  wrong_class_matches (max): epoch1 = 109.0000
  unmatched_predictions (max): epoch1 = 596.0000
  unmatched_gt (max): epoch0 = 325.0000
  mean_iou_matched (max): epoch45 = 0.7867
  matched_accuracy (max): epoch38 = 0.9197
  matched_f1_macro (max): epoch38 = 0.8624
  matched_f1_micro (max): epoch38 = 0.9197
  class_aware_precision (max): epoch21 = 0.7492
  class_aware_recall (max): epoch40 = 0.7118
  class_aware_f1 (max): epoch37 = 0.7012
  localization_precision (max): epoch21 = 0.8302
  localization_recall (max): epoch40 = 0.7816
  localization_f1 (max): epoch37 = 0.7720
  tp (max): epoch40 = 541.0000
  fp (max): epoch1 = 705.0000
  fn (max): epoch0 = 408.0000

#Prediction preview for both models

In [21]:
def show_prediction_preview(model, cfg, n=4, pred_conf_for_display=0.25):
    val_img_paths = list(Path(cfg.yolo_root, 'images/val').glob('*.jpg'))[:n]
    for img_path in val_img_paths:
        results = model.predict(
            str(img_path), imgsz=cfg.image_size,
            conf=pred_conf_for_display, iou=cfg.val_iou_threshold,
            max_det=cfg.max_det, verbose=False,
        )
        annotated = cv2.cvtColor(results[0].plot(), cv2.COLOR_BGR2RGB)
        plt.figure(figsize=(7, 7)); plt.imshow(annotated)
        plt.title(f'{cfg.run_name}: {img_path.name}'); plt.axis('off'); plt.show()

print('=== Baseline predictions ==='); show_prediction_preview(baseline_model, baseline_cfg, n=4)
print('\n=== Enhanced predictions ==='); show_prediction_preview(enhanced_model, enhanced_cfg, n=4)

=== Baseline predictions ===

=== Enhanced predictions ===